### ISSUE TITLE
[change request] checkboxes for charts

### ISSUE THREAD

**Issue by ille** [anshooarora/extentreports#10]
Can we get checkboxes for the charts(testview, stepview) so we can deselect f.i. the info steps?

**Comment by anshooarora** [comment]
Its possible, and what you will see is a small control at the top-right corner of the chart's div that will allow you to select the statuses to be shown in the chart.  It will be a 3 step process:

1. Click the control that brings up a selection of the status you want to see (will contain all statuses)
2. Select the ones you want displayed
3. Click "Save"

**Comment by anshooarora** [comment]
ille

This will be part of the next release.  You can see the latest sample here:  http://relevantcodes.com/Tools/ExtentReports2/Extent.html.  The 2nd chart object provides the ability to filter.

* You can keep the ticket open until the release and close if it works as expected.

**Comment by ille** [comment]
ok, looks fine

**Comment by anshooarora** [comment]
Closing issue based on the above comment by ille.
