### ISSUE TITLE
Report is not pulling images on trying to use relative path.

### ISSUE THREAD

**Issue by vishwathma** [anshooarora/extentreports#100]
Version : 2.10
Somehow report is not pulling images on using relative path. Am storing the reports & screenshots in separate folders under the working directory(project). The path to the screenshots is "./screenshots/1444907774034.jpg"(destFileLoctn). I don't see anything wrong with the path. Also am not using File.separator.
To capture screenshot am using the below code:
public static String captureScreenshot(WebDriver driver) throws WebDriverException, MalformedURLException {
    	File src= ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
    	String destFileLoctn = "./screenshots/"+System.currentTimeMillis()+".jpg";
    	try {
    		FileUtils.copyFile(src, new File(destFileLoctn));
    		} catch (IOException e) {
    			System.out.println(e.getMessage());
    			}
    	System.out.println(destFileLoctn);
        return destFileLoctn;
    	}

Fyi, I have gone through all the info & the tickets associated w.r.t the relative path. Somehow none of the info helped me. Till now, I had been using absolute path & it was working absolutely fine. Also, this code will be ported to MAC as well. Please let me know if this(file separator) works perfectly on MAC.

**Comment by anshooarora** [comment]
Given the following structure:

Parent
   - Report
       - extent.HTML
   - Screenshots
       - filename.png

../screenshots/filename.png

**Comment by vishwathma** [comment]
On Windows OS, this is my obserbation:
The reports location should be in the format: 
./reports/extent.html

w.r.t screenshots, the screenshots should be saved using the format ./screenshots/filename.png
while returning the path to the test.addScreenCapture("Path to the image"), an extra "." is to be concatenated along the filepath & then should be sent to test.addScreenCapture().

**Comment by anshooarora** [comment]
Yes.  I have not been able to test this, but are you saying that the supplied paths are changed by Extent?  As per the design, you can provide any relative path and it will stay intact in the report..

**Comment by anshooarora** [comment]
Closing issue as there was no response.

**Comment by rajikuchana** [comment]
> This is working fine.
> 
> On Windows OS, this is my obserbation:
> The reports location should be in the format:
> ./reports/extent.html
> 
> w.r.t screenshots, the screenshots should be saved using the format ./screenshots/filename.png. If we try to save using the format ../screenshots/filename.png directly, the screenshots are not saved. But while returning the path to the test.addScreenCapture("Path to the image"), an extra "." has to be concatenated along the filepath & then should be sent to test.addScreenCapture() to see the screenshot in the reports.

Hi Vishwa,

Can u please provide complete code.

**Comment by rajikuchana** [comment]
> Yes. I have not been able to test this, but are you saying that the supplied paths are changed by Extent? As per the design, you can provide any relative path and it will stay intact in the report..

Hi Anshoo,

Can u please provide complete code,my reports are still not showing Images in case send in email
