### ISSUE TITLE
Test names are repeated in the report and log lines from previous test get logged in subsequent tests

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports#102]
I am testing ExtentReports to see if it can replace ReportNG in my WebDriver project which has ~1600 tests at this point. For the test, I have a testng.xml suite file containing 2 tests (in 2 separate classes) that are configured to run via Maven in parallel using the Failsafe plugin. The project follows the page object model framework with separate page and test classes. The page classes are backed by a BasePage class and the test classes by BaseTest class.

When I have thread-count set to 1(single-threaded), the report shows the log steps and test status as expected. But when I run it multi-threaded, I see the second test have the same name as the first test. Moreover, log lines from the first test show up in the second test results. I have looked at the examples on the site and in your testngexamples directory in GitHub, but haven't been able to find a solution. Is this a known issue, a limitation or am I doing something wrong?

Here is the report: 
<img width="1428" alt="screen shot 2015-10-19 at 8 25 19 pm" src="https://cloud.githubusercontent.com/assets/10567800/10597037/9d8d8944-769f-11e5-821c-d901087e4a7d.png">

Ideally, I'd like to avoid a massive refactor of the entire project, by replacing the current logging pattern in the project, with a new one.

**Here's the suite file:**
```xml
<suite name="WebDriver Tests" parallel="classes" thread-count="5">
    <test name = "Classes with a single test method - can be used for quick test" 
             allow-return-values="true">
		<groups>
			<run>
				<exclude name="SlowRunning" />
			</run>
		</groups>
		<classes>
			<class name = "com.axiom.turbo.webdriver.tests.SuccessTestClass" />
			<class name = "com.axiom.turbo.webdriver.tests.FailTestClass" />
		</classes>
	</test>
</suite>
```

**I have a BaseTest class. Here's a snippet of code relevant to ExtentReports.**
```java
@ContextConfiguration(locations = "classpath:base-test.xml")
public abstract class BaseTest extends AbstractTestNGSpringContextTests implements InitializingBean {
    public static ExtentReports extent;
    public static ExtentTest test;

    @BeforeSuite
    public void extentSetup(ITestContext context) {
        ExtentManager.setOutputDirectory(context);
        extent = ExtentManager.getInstance();
    }


    @BeforeMethod
    public void startExtent(Method method) {
        test = ExtentManager.getInstance().startTest(method.getName());
    }

    protected String getStackTrace(Throwable t) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        t.printStackTrace(pw);
        return sw.toString();
    }

    @AfterMethod
    public void endExtent(ITestResult result) {

        test.getTest().setStartedTime(getTime(result.getStartMillis()));
        test.getTest().setEndedTime(getTime(result.getEndMillis()));

        for (String group : result.getMethod().getGroups()) {
            test.assignCategory(group);
        }

        if (result.getStatus() == 1) {
            test.log(LogStatus.PASS, "Test Passed");
        } else if (result.getStatus() == 2) {
            test.log(LogStatus.FAIL, getStackTrace(result.getThrowable()));
        } else if (result.getStatus() == 3) {
            test.log(LogStatus.SKIP, "Test Skipped");
        }

        ExtentManager.getInstance().endTest(test);
        ExtentManager.getInstance().flush();
    }

    @AfterSuite
    public void generateReport() {
        ExtentManager.getInstance().close();
    }

    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();
    }
}
```
**I have a ExtentManager class:**
```java
public class ExtentManager {
    private static ExtentReports extent;
    private static ITestContext context;

    public synchronized static ExtentReports getInstance() {
        if (extent == null) {
            File outputDirectory = new File(context.getOutputDirectory());
            File resultDirectory = new File(outputDirectory.getParentFile(), "html");
            extent = new ExtentReports(resultDirectory + File.separator +  "Report.html", true);
            Reporter.log("Extent Report directory: " + resultDirectory, true);
        }

        return extent;
    }

    public static void setOutputDirectory(ITestContext context) {
        ExtentManager.context = context;
    }
```
**I have a TestLogger class with various static logger methods.** To test ExtentReports, I have added 1 line to the existing log method.
```java
public class TestLogger extends BaseTest {

    public static void log(final String message) {
          Reporter.log(message + "<br>", true);
          test.log(LogStatus.INFO, message + "<br>");
    }
}
```
**Here are my 2 test classes:**

SuccessTestClass.java:
```java
public class SuccessTestClass extends BaseTest {
    @Test
    public void successMethod() {
        // Assertion will be always true.
        TestLogger.log("Log line looks good!");
        Assert.assertTrue(true);
    }
}
```
FailTestClass.java:
```java
public class FailTestClass extends BaseTest {

    @Test(groups = {Groups.KNOWN_ISSUES})
    public void failMethod() {
        // Assertion will be always false.
        TestLogger.log("Log line looks good! Test fails");
        Assert.assertTrue(false);
    }
}
```

**Comment by anshooarora** [comment]
Had a quick look:  in TestLogger class, you seem to be using the same test instance from BaseTest for all logging..

Also see here: https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ParallelClass1.java and here: https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ParallelClass1.java

**Comment by anshooarora** [comment]
Also, since you are using TestNG, would you consider using the listener as shown <a href='https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ExtentReporterNG.java'>here</a>.  Original post:  http://relevantcodes.com/testng-listener-using-extentreports/

**Comment by testphreak** [comment]
Hi Anshoo, yes the post above regarding using an ExtentReport listener for TestNG was what drew me into exploring ExtentReports as an alternative to ReportNG a few days back. While the listener works well for reporting just the status, what would be great is to combine logging and test status into one single report, the way ReportNG does it. This will make it easy for existing WebDriver/TestNG projects using either the native TestNG listener or the ReportNG listener to transition to ExtentReports for reporting without making a lot of changes across the project. If it was a new project I was developing from scratch, I could have used the ExtentReports logging pattern you have established.

That being said, I took a further look into the examples you linked in your comment above. I got ExtentReports to work in parallel with the SuccessTestClass and FailTestClass after creating a new instance of ExtentTest for each class and duplicating the @AfterMethod for each class. I also had to modify the log method above in my example to include an ExtentTest parameter. 

Some problems I see, if I want to integrate ExtentReports across the entire project are:

* With the page object model framework we built our project on, there's only 1 @AfterMethod in the BaseTest with all test classes extending this BaseTest (see below). With ExtentReports I would need to duplicate the @AfterMethod I have above to about 200 test classes, so I can pass the specific ExtentTest instance correctly to the @AfterMethod.
```java
@AfterMethod(alwaysRun = true)
    public void afterMethodWebDriverTest(final Method method) {
if (webDriver != null) {
            try {
                webDriver.quit();
            } catch (Exception e) {
                // Driver maybe already closed. Ignore.
            }
        }
}
```
As you can see, I am not passing in ITestResult as both logging of steps and status (pass/fail/skip) is handled by the ReportNG listener I have specified in the pom.

* We have more than 500 classes (pages, utility and test classes combined). I will need to create an instance of ExtentTest in each of those classes, then create a specific constructor to pass the ExtentTest instance from the test method to the page class.

While the existing ExtentReports is good (I like the layout and dashboard), it would be great if perhaps in a future version of ExtentReports, the dependency of creating a ExtentTest instance with every class and having to pass it around to every class is removed. Either that or if ExtentReport Listener for TestNG can support logging test steps as well like ReportNG, that would be awesome.

**Comment by anshooarora** [comment]
It is possible to do this with a utility method that keeps track of the threads creating tests.  It will called in the AfterMethod and safely end each test for the thread using a:

```
Map(threadId, ExtentTest)
```

I will share a sample soon.

**Comment by anshooarora** [comment]
You can use the below to run the same tests.  I have marked <code>//new</code> where there are changes.

Here it is:

```java
public abstract class BaseTest {
    public static ExtentReports extent;

    @BeforeSuite
    public void extentSetup(ITestContext context) {
        ExtentManager.setOutputDirectory(context);
        extent = ExtentManager.getInstance();
    }

    @BeforeMethod
    public void startExtent(Method method) {
        ExtentTestManager.startTest(method.getName()); // new
    }

    protected String getStackTrace(Throwable t) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        t.printStackTrace(pw);
        return sw.toString();
    }
    
    @AfterMethod
    public void afterEachTestMethod(ITestResult result) {
        ExtentTestManager.getTest().getTest().setStartedTime(getTime(result.getStartMillis()));  // new
        ExtentTestManager.getTest().getTest().setEndedTime(getTime(result.getEndMillis()));  // new

        for (String group : result.getMethod().getGroups()) {
            ExtentTestManager.getTest().assignCategory(group);  // new
        }

        if (result.getStatus() == 1) {
            ExtentTestManager.getTest().log(LogStatus.PASS, "Test Passed");  // new
        } else if (result.getStatus() == 2) {
            ExtentTestManager.getTest().log(LogStatus.FAIL, getStackTrace(result.getThrowable()));  // new
        } else if (result.getStatus() == 3) {
            ExtentTestManager.getTest().log(LogStatus.SKIP, "Test Skipped");  // new
        }

        ExtentTestManager.endTest();  // new

        extent.flush();
    }

    @AfterSuite
    public void generateReport() {
        extent.close();
    }

    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();
    }
}
```

```java
public class ExtentTestManager {  // new
    static Map<Integer, ExtentTest> extentTestMap = new HashMap<Integer, ExtentTest>();
    private static ExtentReports extent = ExtentManager.getInstance();
    
    public static synchronized ExtentTest getTest() {
        return extentTestMap.get((int) (long) (Thread.currentThread().getId()));
    }
    
    public static synchronized void endTest() {
        extent.endTest(extentTestMap.get((int) (long) (Thread.currentThread().getId())));
    }
    
    public static synchronized ExtentTest startTest(String testName) {
        return startTest(testName, "");
    }
    
    public static synchronized ExtentTest startTest(String testName, String desc) {
        ExtentTest test = extent.startTest(testName, desc);
        extentTestMap.put((int) (long) (Thread.currentThread().getId()), test);
        
        return test;
    }
}
```

```java
public class TestLogger extends BaseTest {
    public static void log(final String message) {
          Reporter.log(message + "<br>", true);
          ExtentTestManager.getTest().log(LogStatus.INFO, message + "<br>");  // new
    }
}
```

**Comment by testphreak** [comment]
Anshoo, thanks for coming up with the ExtentTestManager class! That indeed solved some of the issues I had earlier with integrating ExtentReports with my WebDriver project. And I think this will help a lot of other projects out there looking for an alternative reporting solution. While I've run it with 5 threads, a typical suite with our project runs 100 threads in parallel (class). I'll try to give you a definitive answer by end of this week after verifying the solution scales. 

Also, I ran into a couple of issues with the Listener class as I was testing ExtentReports more: 

* A few of our test classes do not extend BaseTest. Those tests exclusively use the report listener. These tests started failing because the context is set in the BaseTest (@BeforeSuite). I was able to get around the problem and make ExtentReports listener work by adding a null check for context in the ExtentManager and a getTest() null check in the log wrapper method. I am okay with not logging steps and reporting just the status for these test classes.
```java
public synchronized static ExtentReports getInstance() {
        if (extent == null) {
            if (context != null) {
                File outputDirectory = new File(context.getOutputDirectory());
                File resultDirectory = new File(outputDirectory.getParentFile(), "html");
                extent = new ExtentReports(resultDirectory + File.separator +  "Report.html", true);
                Reporter.log("Extent Report directory: " + resultDirectory, true);
            }
        }
        return extent;
    }
```
```java
public static void log(final String message) {
        Reporter.log(message + "<br>", true);
        if (ExtentTestManager.getTest() != null) {
            ExtentTestManager.getTest().log(LogStatus.INFO, message + "<br>");
        }
    }
 ```
* But, I am unable to use the ExtentReport Listener in combination with setting up extent instance in the BaseTest. That is due to the fact that we create an "extent" instance in the Listener class and the ExtentManager class. Since we set the context in BaseTest, I haven't been able to figure out a way to run tests using the ExtentReports listener, since context is always null for test classes not extending BaseTest. Is there a way I can do an ExtentManager.getInstance() in the listener class and get the context? I need the context (and not hard code the path) since when we run via Maven, the report goes into the failsafe-reports directory whereas when running individually, it goes into the test-output folder.

So, instead of what you have right now in the listener class:
```java
public class ExtentReporterNG implements IReporter {
    private ExtentReports extent;
 
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = new ExtentReports(outputDirectory + File.separator + "Extent.html", true);
.......
.......
.......
```
I tried doing:
```java
public class ExtentReporterNG implements IReporter {
    private ExtentReports extent;
 
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = ExtentManager.getInstance();
......
......
......
```
which hasn't worked for me, since I get a NPE because context is null.

I am essentially trying to combine the results from non-BaseTest extending classes and BaseTest extending classes into one report using the ExtentManager and Extent Listener. It would be great if we can do this with Extent.

**Comment by testphreak** [comment]
Sorry for the delay in getting back to you, but I got busy with a release last week. I made a few changes to your solution above and was able to integrate the library with our project. It scales well with a 100 threads in parallel and did not notice any performance issues during the run. 

With your changes however, I was no longer able to use ExtentReports purely as a listener, which is fine. I just modified tests that were not extending BaseTest to extend BaseTest. One minor thing I'd like to share is that when I opened the result file with 1600 tests, it was slow in loading and the layout looked messed up (on a fast office connection). But after about 30 seconds, it completed loading with the proper layout.

The report looks good! Importantly I was able to integrate it without making massive changes to the WebDriver project. Thanks again with coming up with ExtentReports. If I see anything that can be improved upon or fixed, I'll share it here.

**Comment by anshooarora** [comment]
Thanks for the update.  I haven't been able to work on extent as often as I would like due to other obligations. 

I am glad that it works.  I will see if we can improve the performance, but 30 seconds is still quite long for the report to load.  How large is your HTML file?

**Comment by testphreak** [comment]
I understand, what you've done looks pretty neat already. 

The result html file is about 900 MB. It looks like it's initially trying to load the dashboard page and then it eventually disappears once the load is complete.

**Comment by anshooarora** [comment]
900 MB is huge,  you are lucky that the report event opened :)

I am working on a feature that will allow creating multiple reports for run sessions and linking each so you can access different (smaller) files.  Each report will be accessible from the left-sidenav.

**Comment by testphreak** [comment]
ExtentReports is surely getting stress tested with my project :). The report loading slowly isn't a major pain point right now. I'd rather keep things simple by having a single report with all tests, the way it is right now. Please make sure we have the option to choose if we want to create multiple reports or not.

**Comment by ansonliao** [comment]
So cool, the coding in BaseTest and extentreport factoring.
Hi Testphreak, could you share the whole project to me? (@testphreak)

**Comment by testphreak** [comment]
Ansonliao, my implementation is not a whole lot different from what Anshoo has already shared here and in the documentation. I can help answer any specific questions if there are any. @anshooarora, closing story.
