### ISSUE TITLE
Is there a beta build of 2.11 around?

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#105]
When I clone, I don't see the 2.11 updates.

Is there a build of 2.11 beta around?

Thanks,

Chris

**Comment by anshooarora** [comment]
Here it is:  https://github.com/anshooarora/extentreports/commit/cb87de1b2244f29e1b187feb93accd0f7b9f48ed

But, currently, only a few minor changes.  Wouldn't recommend to use it over 2.10 (yet)..

**Comment by cktech529** [comment]
Thanks Anshoo

**Comment by anshooarora** [comment]
The next release will be 2.40.0 as there is a version issue on maven search causing confusion.  On maven search, 2.03.1 is being shown as 2.31 so users are downloading the old version.
