### ISSUE TITLE
Override testcase status with RetryListener

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#111]
Hi Anshoo,

I am using RetryListener in my framework to run failed test case three times and it is getting reported in the report as three test cases , i want to override test case status every time it runs but don't want to report as new test case ,could you please provide me any workaround if possible.

Thanks

**Comment by anshooarora** [comment]
You can hide the previous tests using js or if you prefer doing it from Java side, using Jsoup.

**Comment by jawlitkp** [comment]
Hi Anshoo,

Could you please provide me js code for this ?

Thanks 
Jawlit

**Comment by anshooarora** [comment]
Closing as this is a duplicate issue: see #106 for design discussion for this feature.
