### ISSUE TITLE
extent trends for .NET, + version 2.1

### ISSUE THREAD

**Issue by karthikbhatnagar** [anshooarora/extentreports#112]
Hi Anshoo
Are you planning to release the 2 products for .Net also?

**Comment by anshooarora** [comment]
Yes.  Trends will be used as-is, there won't be a separate impl for .NET.

**Comment by karthikbhatnagar** [comment]
OK.  I am unable to use for .net 2.02 though. It says my report is not valid extent file.

**Comment by anshooarora** [comment]
Yes, that is expected because ExtentMerge will only combine reports that are v2.10+.

**Comment by anshooarora** [comment]
The beta is out now.
