### ISSUE TITLE
When we use normal testng.xml it works for Extent Reports but when i run it through command line it does not work.

### ISSUE THREAD

**Issue by HarshalSaindane** [anshooarora/extentreports#113]
When we use normal testng.xml it works for Extent Reports but when i run it through command line it does not work properly, script runs but does not finish it, using firefox version 31, selenium 2.44 for webdriver.

**Comment by anshooarora** [comment]
What is the error?

**Comment by HarshalSaindane** [comment]
actually it does not give any error, when i try to run through command prompt it almost stuck at the end of the script, i am running testng.xml through command prompt, other classes runs through command prompt properly, but when i try to run Extend Report class it does not respond.

**Comment by HarshalSaindane** [comment]
this happens on firefox, when i tried for Chrome it fails only without any error, is it any problem of version of selenium or firefox? please help.

**Comment by HarshalSaindane** [comment]
Below is the sample class which runs through testng.xml but does not give respond/result through command prompt, sample url added here which does not existspublic class classNewTest

{
	
	@Test
	public void Hello() 
	{   
		String BRtitle;
		ExtentTest logger;
		ExtentReports extent = new ExtentReports("E:\\QA\\Testing\\.metadata\\WeDriverTest\\SeleniumTestPro\\Reports\\reportstest.html.", true);						
		logger=extent.startTest("Execution Started");
		WebDriver driver = new FirefoxDriver();		
	        String baseUrl = "http://testsite.test.com/login.aspx";
		String user="automation";
		String password="automation";
		driver.get(baseUrl);
		driver.manage().window().maximize();
		logger.log(LogStatus.INFO, "Browser Runnig");
		WebElement userid= driver.findElement(By.xpath("//input[@id='m_txtLogin']"));
		userid.clear();
		userid.sendKeys(user);
		WebElement pswd=driver.findElement(By.xpath("//input[@id='m_txtPassword']"));
		pswd.clear();	
		pswd.sendKeys(password);
		WebElement loginbtn = driver.findElement(By.xpath("//input[@id='m_wibLogin_input']"));
		loginbtn.click();
		logger.log(LogStatus.INFO, "Dashboard is going to open");
		WebDriverWait wait = new WebDriverWait(driver, 30);
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//ul[@id='key-indices']/li[5]")));
		driver.findElement(By.xpath("//ul[@id='key-indices']/li[5]")).sendKeys("Text box is visible now");
		System.out.print("Dashboard open sucessfully/n");
		BRtitle= driver.getTitle();
		System.out.println("BRTitle: "+BRtitle);               
		logger.log(LogStatus.PASS, "Dashboard Displayed");		
		extent.endTest(logger);		
		extent.flush();		
		extent.close();		
		driver.quit();		
					
		
	}
	
 }.

**Comment by anshooarora** [comment]
Were you able to resolve this issue?  What was the cause?

**Comment by HarshalSaindane** [comment]
jar file location i was using from command line was in another locations, so yes it was configurations issue, Thanks Anshoo.
