### ISSUE TITLE
Feature request: change filter By Status when click on particular status in Dashboard

### ISSUE THREAD

**Issue by ilitkevich** [anshooarora/extentreports#114]
Hi Anshoo,

I think it would be a nice tweak when click on particular status in Dashboard will change filter By Status. It will spare one click each time when you need to analyse different types of failure. And if you need to analyze a lot of reports it become quite handy.

![2015-10-27_15-25-36](https://cloud.githubusercontent.com/assets/15159015/10770196/5c71746c-7cc0-11e5-9184-bc817e101149.png)

**Comment by anshooarora** [comment]
Thanks,  this will be a good feature to incorporate.  I will share a sample with this soon.

**Comment by anshooarora** [comment]
Please try with this sample:  http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html

Currently, dashboard is the main view, but it might change to the original test-view in the release unless there is more support dashboard as the main view..

**Comment by ilitkevich** [comment]
Thanks for quick response.

You got my main idea right, but I don't exactly understand why you redraw 'Tests View' chart all the time. Could you keep it stable please. Also, amount of Total tests and amount of tests in test view don't match.

![2015-10-29_10-04-18](https://cloud.githubusercontent.com/assets/15159015/10821777/7ee7d44e-7e2a-11e5-8667-3830f368d0b8.png)

Speaking about view, my personal preference are next: 
![2015-10-29_9-55-05](https://cloud.githubusercontent.com/assets/15159015/10821813/b862db1a-7e2a-11e5-9462-4d6c4f7bc47b.png)

**Comment by karthikbhatnagar** [comment]
Redraw provides latest counts from filter. Who use child tests require this feature.
Anshoo: please don't remove. Can you provide setting to enable or disable redraw instead?

**Comment by anshooarora** [comment]
Yes, this feature will not be removed but I will provide option to not update the graphs each time there is an update.

**Comment by ilitkevich** [comment]
Great, thanks.

**Comment by anshooarora** [comment]
This is available in 2.40b with the option to enable it.  The config file can be configured to run any script against the report.

**Comment by anshooarora** [comment]
Closing as this feature was included in 2.40.
