### ISSUE TITLE
Unable to use 2.10v of EntentReports

### ISSUE THREAD

**Issue by purnimashanti** [anshooarora/extentreports#115]
Everytime I add 2.10 verison of this report, I get an error. I use Maven project, so I added the dependency in my pom.xml file.
The error I get is "The method init(String, boolean) is undefined for the type ExtentReports".
But when I change the version to 1.41, it's fine.

**Comment by anshooarora** [comment]
Version 1.41 and 2.0+ are completely different, and the entire API changes between the two.  Here are version 2.0+ docs:  http://extentreports.relevantcodes.com/java/version2/docs.html.

With version 2.10, you can also utilize the TestNG listener:  http://relevantcodes.com/testng-listener-using-extentreports/

**Comment by purnimashanti** [comment]
I have successfully integrated the 2.10 version of ExtentReports and it's working fine, Thanks,

**Comment by shilpabhapkar** [comment]
Getting error at this:
ExtentReports extent= new ExtentReports(fileName,true);
while executing commant "ant run" from cmd promt.

**Comment by ashishjsharda** [comment]
Got the code working for version 3.0.1:


package com.webdriver.ltree.core;

import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.xml.XmlSuite;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.configuration.ChartLocation;
import com.aventstack.extentreports.reporter.configuration.Theme;
//import com.relevantcodes.extentreports.ExtentReports;

/**
 * @author asharda
 *
 */
public class ExtentTestNGIReporterListener implements IReporter {
    
    private static final String OUTPUT_FOLDER = "test-output/";
    private static final String FILE_NAME = "Extent.html";
    
    private ExtentReports extent;

   
    
    private void init() {
        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(OUTPUT_FOLDER + FILE_NAME);
        htmlReporter.config().setDocumentTitle("ExtentReports - Created by TestNG Listener");
        htmlReporter.config().setReportName("ExtentReports - Created by TestNG Listener");
        htmlReporter.config().setTestViewChartLocation(ChartLocation.BOTTOM);
        htmlReporter.config().setTheme(Theme.STANDARD);
        extent = new ExtentReports();
        extent.attachReporter(htmlReporter);
        extent.setReportUsesManualConfiguration(true);
    }
    
    private void buildTestNodes(IResultMap tests, Status status) {
        ExtentTest test;
        
        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
                 test=extent.createTest(result.getMethod().getMethodName());
                
                for (String group : result.getMethod().getGroups())
                    test.assignCategory(group);

                if (result.getThrowable() != null) {
                    test.log(status, result.getThrowable());
                }
                else {
                    test.log(status, "Test " + status.toString().toLowerCase() + "ed");
                }
                
                test.getModel().setStartTime(getTime(result.getStartMillis()));
                test.getModel().setEndTime(getTime(result.getEndMillis()));
            }
        }
    }
    
    private Date getTime(long millis) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(millis);
        return calendar.getTime();      
    }

	public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
		// TODO Auto-generated method stub
		init();
		 for (ISuite suite : suites) {
			 Map<String, ISuiteResult> result = suite.getResults();
	            
	            
	            for (ISuiteResult r : result.values()) {
	                ITestContext context = r.getTestContext();
	                
	                buildTestNodes(context.getFailedTests(), Status.FAIL);
	                buildTestNodes(context.getSkippedTests(), Status.SKIP);
	                buildTestNodes(context.getPassedTests(), Status.PASS);
	                
	            }
	        }
	        
	        for (String s : Reporter.getOutput()) {
	            extent.setTestRunnerOutput(s);
	        }
	        
	        extent.flush();
		
	}

	
}

Maven Dependencies used:
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.0.1</version>
	</dependency>
	
	<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>2.41.1</version>
	</dependency>
