### ISSUE TITLE
add a method to clean the screenshots when we run the tests. 

### ISSUE THREAD

**Issue by purnimashanti** [anshooarora/extentreports#138]
pls add a feature to clean the screenshots. every time the previous screenshots gets saved in the folder and it's becomes a big file.

**Comment by karthikbhatnagar** [comment]
This can be done in your startup. Report should not be responsible for cleaning folders

**Comment by purnimashanti** [comment]
I asked about how to clean the previous screenshots taken, not the folder.

**Comment by karthikbhatnagar** [comment]
What does it mean by "cleaning screenshots? Screenshots will not increase file size..

**Comment by purnimashanti** [comment]
I got the solution for this..thanks a lot.
