### ISSUE TITLE
How to use absolute path for screencast without the file:/// ?

### ISSUE THREAD

**Issue by shaynl** [anshooarora/extentreports#14]
Hi Anshoo,
Thanks for this great library!
Can I use an absolute path for screencast without the file:/// ?
When this added, the Image will not show in the report.

**Comment by anshooarora** [comment]
shaynl - Please provide the version and a sample of the absolute path you would like to use.

**Comment by shaynl** [comment]
I'm using version 2.01.
I save my reports to Google drive in the folder "AutomationReports". Inside that folder I save my screenshot in the folder "screenshots" so the absolute path i'm using is is: screenshots/screenshot.jpg

In the report html the output now is:
 <img class="report-img" data-featherlight="file:///screenshots/screenshot.jpg" src="file:///screenshots/screenshot.jpg">

The output i'm looking for is:
<img class="report-img" data-featherlight="screenshots/screenshot.jpg" src="screenshots/screenshot.jpg">

**Comment by anshooarora** [comment]
You can just using the following path:

```
./screenshots/screenshot.jpg
```

**Comment by anshooarora** [comment]
So you can use the below path like this:

```
extent.log(LogStatus.INFO, "Snapshot below: " + test.addScreenCapture("./screenshots/screenshot.jpg"));
```
or you can use the path you want by replacing "file:///" from the HTML:

```
String path = test.addScreenCapture("screenshots/screenshot.jpg").replace("file:///", "");
extent.log(LogStatus.INFO, "Snapshot below: " + path);
```

**Comment by shaynl** [comment]
Thanks!
