### ISSUE TITLE
Wrong Start time in dashboard

### ISSUE THREAD

**Issue by guneetgarg** [anshooarora/extentreports#144]
thanks for awesome reporting library

there is a issue when i use extent with testNg Listener 
then in dashboard when i see start time it shows me my last test case start time instead of my first test case execution time

**Comment by anshooarora** [comment]
This will be fixed in the upcoming release.

**Comment by anshooarora** [comment]
2.40b is out with this fix.

**Comment by guneetgarg** [comment]
Great, thanks.

**Comment by guneetgarg** [comment]
Issue still exist when am using TestNG Listener

**Comment by guneetgarg** [comment]
Time issue has got resolved in extentreports-java-v2.40.1-beta1
But when using extent with jenkin and performing post action again dashboard shows wrong time

**Comment by anshooarora** [comment]
What do you mean by "performing post action" in Jenkins?

**Comment by guneetgarg** [comment]
like sending email or some other action through jenkin
