### ISSUE TITLE
Folks are confused on passed tests

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#146]
Very minor, but folks are confused with the following color choice indicating selection...

On the passed test, the left most selection indicator is red (indicating failure in some minds..)

![image](https://cloud.githubusercontent.com/assets/6800679/10918250/b3760404-8232-11e5-9874-2e8bd97c112f.png)

**Comment by anshooarora** [comment]
This will be changing with the upcoming release to have the same color as the status..

**Comment by cktech529** [comment]
Thanks :)

**Comment by anshooarora** [comment]
2.40b is out now with this addition.

**Comment by anshooarora** [comment]
Corrected in 2.40.
