### ISSUE TITLE
Report html file path, have to be a absolute path

### ISSUE THREAD

**Issue by ansonliao** [anshooarora/extentreports#148]
My extentreport version in maven is 2.10.

My init extentreport code is below:
```java
ExtentReports reporter;
ExtentTest test;
reporter = new ExtentReports("test.html", true);
```
and above code will be error as the report file path is related path, not absolute path.

if change the code to:
```java
reporter = new ExtentReports("/app/test.html", true);
```
will be PASSED.

so is it possible that the report path support related path?
such as in Maven project, related to maven project's root directory, for example, I would like to put the report to maven project directory --> 'Reports" folder, so the code can be:
```java
reporter = new ExtentReports("Reports/test.html", true);
```

Thanks.

**Comment by anshooarora** [comment]
Can you test the following:

```java
reporter = new ExtentReports("./app/test.html", true);
reporter = new ExtentReports(".Reports/test.html", true);
```

Just append a "dot" before your path and try again?

**Comment by testphreak** [comment]
Or you could use ITestContext (context.getOutputDirectory()) if you use TestNG with Maven.

**Comment by ansonliao** [comment]
Thanks for two guys, I will try it later.

**Comment by ansonliao** [comment]
@testphreak 
thanks testphreak, I use ITestContext() method to get the path.
and I suggest that, extentreport can use related path.
