### ISSUE TITLE
Is it possible to group methods by test name? 

### ISSUE THREAD

**Issue by shaynl** [anshooarora/extentreports#15]
Hi Anshoo,

I'm running my tests with TestNG xml that contains few tests. each test contains few methods.
ExtentReports ver: 2.01
@BeforeSuite i'm calling: report = ReportManager.getInstance();
@BeforeMethod i'm calling: test = report.startTest(method.getName());
@AfterMethod i'm calling: report.endTest(test);
@AfterSuite I'm calling: report.flush();

In the result report I see all the methods that run in one big list. 
How to group them by test name in one report file?
For example:
Test 1
-----------
Method 1
Method 2
Method 3

Test 2
-----------
Method 1
Method 2
Method 3

**Comment by anshooarora** [comment]
Can you please send me a sample code?  You can remove all the business logic, just need the ExtentReports events so I can replicate this and create nodes for each method:

```
public class Issue15 {
    private ExtentReports extent;
    
    @BeforeSuite
    public void beforeSuite() {
        extent = ReportManager.getInstance();
    }
    
    @BeforeTest
    public void beforeTest() {}
    
    @AfterTest
    public void afterTest() {}
    
    @BeforeMethod
    public void beforeMethod() {}
    
    @AfterMethod
    public void afterMethod() {}
    
    @AfterSuite
    public void afterSuite() {
        extent.flush();
    }
}
```

**Comment by shaynl** [comment]
This is my code. I just moved report.flush() to @AfterMethod so I can check
the report when it's running.

@BeforeSuite (alwaysRun = true)
    public void setUp()
    {
        AppiumServer.stop();
        AppiumServer.start();
report = ReportManager.getInstance();
    }

    @BeforeTest (alwaysRun = true)
    public void startTest ( )
    }
        if(driver==null)
        {
            CommonUtils.loadConfigProp("IPhone5c.properties");
            CommonUtils.setCapabilities();
            driver = CommonUtils.getDriver();
        }

        if (!driver.isAppInstalled("app.name"))
        }
            driver.installApp("app.ipa");
        }
    }

    @BeforeMethod (alwaysRun = true)
    public void startTestReport(Method method)
    {
        test = report.startTest(method.getName());
    }

    @AfterMethod (alwaysRun = true)
    public void endTestReport()
    {
        report.endTest(test);
        report.flush();
    }

    @AfterTest (alwaysRun = true)
    public void removeApp()
    {
        driver.removeApp("app.name");
        driver.quit();
    }

    @AfterSuite (alwaysRun = true)
    public void tearDown()
    }
        AppiumServer.stop();
    }

**Comment by anshooarora** [comment]
This is similar to an earlier ticket correct:  https://github.com/anshooarora/extentreports/issues/5?

Instead of each method showing up as a test, you want them to show up as nodes in a single test?

If yes, still working on this one.  Its quite complicated, so not sure of an ETA but it will surely be added.

**Comment by shaynl** [comment]
it's not quite similar...
I want to see each method with @Test as a small test (with all the steps
like it's today) and the  <test name="Test1"> in TestNG xml more as a group
of small tests.
It's like in TestNG deflate report.

**Comment by anshooarora** [comment]
Something like below?

![img](https://cloud.githubusercontent.com/assets/4107384/8553060/5e1b1b64-24a6-11e5-811a-60b2cc823590.png)

**Comment by shaynl** [comment]
Yes. when Test 1 & Test 2 are methods and Test Group is the test name in
TestNG xml: <test name="Test Group"> (can be more then one test group in a
file).

**Comment by anshooarora** [comment]
Hi - please see the upcoming sample:

http://relevantcodes.com/Tools/ExtentReports2/Extent203.html

The test "Embeds Media" contains 2 child tests.  Does this look good?  Please share any ideas if you think this functionality can be improved.

**Comment by shaynl** [comment]
Looks good! Thanks :)

**Comment by antonguba1** [comment]
@anshooarora could you please share a link for code that built such beautiful report http://relevantcodes.com/Tools/ExtentReports2/Extent203.html
