### ISSUE TITLE
Can we have a category page with failures grouped by exception?

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports#150]
I'd like to be able to see a sorted list of failures by exception with highest occurring exception first. This will make it easy to analyze failures in reports and identify why certain tests may be failing. It would also help automation engineers to first target their fix towards exceptions that majority of the test failures are running into.

Something like this:
org.openqa.selenium.NoSuchElementException - 24.
org.openqa.selenium.ElementNotVisibleException - 12
.
.
.
etc.

Then clicking on the 24 for example, would show the 24 tests that failed with the exception

**Comment by anshooarora** [comment]
This can be a great feature.  However..  How should the exceptions be parsed from logs?

**Comment by testphreak** [comment]
Maybe I am oversimplifying, but could we do it by collecting all ITestResult's getThrowable().getMessage() in a map, then sorting it? This has been done before. Not sure if you've explored the test tracking tool called [Cuanto](https://github.com/ttop/cuanto) before. It does this in a pretty neat way like in the example below. Each row is clickable, which then filters the results to show only failures related to the exception.

![screen shot 2015-11-09 at 3 54 33 pm](https://cloud.githubusercontent.com/assets/10567800/11050408/74a8e2b0-86fa-11e5-8190-5030ce329a68.png)

**Comment by anshooarora** [comment]
This would be a good addition to Extent but as a testng extension.  I am not sure if this is also possible with Junit (I don't use that much) but would be nice to have a similar junit extension too.

**Comment by testphreak** [comment]
This post talks about how it's done with JUnit: https://thomassundberg.wordpress.com/2012/07/08/performing-an-action-when-a-test-fails/

I agree though it may not be as straightforward like with TestNG.

**Comment by anshooarora** [comment]
From #160:

Is it posible to add new section for defects ,so basically from left navigation bar user can navigate to defects section and under defects section should list of all issues for failed test cases but more in to defect format and defect dash board at top,i know this could be lot of work but if you can make it it would be great feature.

1. defect number
2. Priority based on (fail,warning,fatal)
3. screenshot
4. Error message
5. testsuite name 
6. testcase name

**Comment by anshooarora** [comment]
Will be released in next beta.

**Comment by anshooarora** [comment]
quick example:

![exceptions-view](https://cloud.githubusercontent.com/assets/4107384/12096658/7bcaf6f6-b2dc-11e5-91e3-2ad82718e66c.png)

**Comment by testphreak** [comment]
Thanks for the screen shot. Great work. Looks good to me. A few things to think about:
1. Do we need a Status column? We already know these tests failed, so there may not be much value for that column.
2. Please add a count next to each exception in the left container, so we don't need to manually count the number of tests that failed with this specific exception in the right container in the event of the run having a lot of failures.
3. Exception column in the right container is likely going to have the same exception message repeated, unless you are doing an additional filtering for each exception, so that each exception will then have different messages based on a specific test. By that I mean, will InterruptedException with messages "Sleep failed" and another test with another InterruptedException with message "Wait failed" both show up in the right container against InterruptedException?

**Comment by anshooarora** [comment]
1.  Removed
2.  Will add this
3. I kept this so you can see the entire exception here, longer exceptions with their inner messages will be displayed in entirety

I will release the current build today (beta-3) so you will be able to test.

I wanted to keep the behavior generic so all test frameworks can take advantage of it, so all you have to do is, use either of these signatures and log a `throwable`:

```
log(LogStatus logStatus, Throwable t);
log(LogStatus logStatus, String stepName, Throwable t);
```

This will automatically create the exceptions view from the template.  [Code](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/view/Extent.ftl#L497).

**Comment by testphreak** [comment]
Sounds good. Thanks!

**Comment by karthikbhatnagar** [comment]
Anshoo is this feature available to .Net also?

**Comment by palanics** [comment]
Hi I have used the latest extentreport java version 2.41.1. I am getting incorrect number of exceptions count. Say I have two tests failed with "NullPointerException" and other two tests with "IllegalArgumentException". so totally here are 4 exceptions.

But the count is shown as 2 (1 for two tests and 1 for other two tests) for both the exceptions, so here the  exception count is shown wrong.

Please see the attached screenshot.
![excep1](https://cloud.githubusercontent.com/assets/2254007/16651329/da9a7d62-4460-11e6-8d6d-8d6ec38e5436.png)
![excep2](https://cloud.githubusercontent.com/assets/2254007/16651333/e0c75a34-4460-11e6-960a-0658ce057ca7.png)

**Comment by nivithaCisco** [comment]
i am not getting the bug tab
