### ISSUE TITLE
On the category page after clicking on a specific row it would be nice to click either the pass label or fail label and filter to show only passed or only failed in the details section

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports#153]
This is a nice to have, but would be nice to drill down to only passed tests or failed tests by clicking on the pass: <Number> or fail: <Number>.

**Comment by anshooarora** [comment]
This is one of the planned features for 2.40.

**Comment by testphreak** [comment]
Nice! Thanks! Please feel free to close this one now or change has been tested with 2.40.

**Comment by testphreak** [comment]
It would be good, if you can sort the categories in the category page based on most failures first. I am not sure in which order they're sorted in right now.

**Comment by anshooarora** [comment]
Randomly sorted. 

We are very close to 2.40 release so will include this in the next.

**Comment by anshooarora** [comment]
This feature is available in 2.40 and next release (minor) will have all categories alphabetically sorted.

**Comment by anshooarora** [comment]
Categories will be sorted alphabetically starting next release.  0783b59dc4902b1012d2758bcbb09a3edef2f98f

**Comment by testphreak** [comment]
Nice, thanks Anshoo!
