### ISSUE TITLE
extentMerge can't run

### ISSUE THREAD

**Issue by ansonliao** [anshooarora/extentreports#155]
Hi Sir, 
I pull down extentreport source code from GitHub and try to generate extentmerge.jar.
my Maven command is:
````shell
mvn package
````
and got extentmerge-0.10.jar.

Then I try to merge two extentreport html files with extentmerge.jar
```Shell
java -jar extentmerge-0.10.jar -html "1.html" -html "2.html" -out "merge.html"
```
bug got message:
```
no main manifest attribute, in extentmerge.jar
```

and no action on merging.

also I can't find extentmerge download link in extentreport official site.

please advise.

**Comment by anshooarora** [comment]
Can you download extentmerge.jar from here:  http://relevantcodes.com/extentreports-for-selenium/ and try again?

**Comment by ansonliao** [comment]
Hello Anshooarora,
Thanks for your reply, found the download place and works.
