### ISSUE TITLE
Extent Merge using database

### ISSUE THREAD

**Issue by Yaazie** [anshooarora/extentreports#156]
Hi 
I am trying to test the extent merge using the extent.db but i am getting some exception errors. 
![2015-11-12_14h38_57](https://cloud.githubusercontent.com/assets/10814618/11118527/374235cc-894b-11e5-9446-27ae9e73fb5e.png)

Also I have a report with an embedded image. The image is not able to zoom in. You can only right click and view the image.

**Comment by anshooarora** [comment]
Can you try the following:

```
java -jar extentmerge.jar -db ./extent.db -out extent.html
```

**Comment by Yaazie** [comment]
Okay thanks. It works. Is it suppose to separate each step and put them under a different heading?

**Comment by anshooarora** [comment]
Step? Do you mean report?

**Comment by anshooarora** [comment]
Closing issue as there was no response.
