### ISSUE TITLE
Ability to print exception under report not only string message

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#157]
Hi Anshoo,

Could you please provide overload of log methods which can accept Exception class ? at this point i have to print e.getmessage() and this message is not printing java class lines inside my report so by seeing error message i am not able to figure out at what line exception occurred.

Thanks

**Comment by anshooarora** [comment]
Will provide an overloaded log for this in the next version.

**Comment by jawlitkp** [comment]
Thanks Anshoo

**Comment by anshooarora** [comment]
Here are the new method signatures that will be available:

```java
test.log(logStatus, stepName, Throwable);
test.log(logStatus, Throwable);
```

**Comment by anshooarora** [comment]
Beta version released today.  Both signatures part of test.  Closing ticket.
