### ISSUE TITLE
Run .NET 2.40-beta-1 get exception for creating html report

### ISSUE THREAD

**Issue by azary10** [anshooarora/extentreports#158]
Hey,
Your project is great work
Unfortunately run latest version for dot.net  with exception to create html report
When call EndTest(test) method

" An unhandled exception of type 'System.NullReferenceException' occurred in CompiledRazorTemplates.Dynamic.RazorEngine_dec960bd850642309276c12402455bad.dll "
 
Thank you

**Comment by anshooarora** [comment]
Can you share the steps to reproduce? 

Did you add Razor and RazorEngine as references?

**Comment by azary10** [comment]
Yes,it added
Exception happens here :

public virtual void AddTest()
        {
            _extentSource = Engine.Razor.RunCompile(View.Extent.Source, "extent",                   typeof(Model.Report), _report);
        }

**Comment by anshooarora** [comment]
Can you share the code for me to reproduce? Your .NET version?

**Comment by azary10** [comment]
Yes .NET version.

I just download your project from hithub
And referenced from my project



 private ExtentReports extent = new ExtentReports(@"C:/output-folder/report.html");
private ExtentTest report = extent.StartTest(TestContext.TestName + " - " + DateTime.Now.ToString("yyyy.MM.dd.hh.ss"), TestContext.TestName);

report.Log(LogStatus.Info, "Created new Lead email:" + user.Email + "  Check into CRM");
                    report.Log(LogStatus.Pass,  report.AddScreenCapture(SharedActions.TakeScreenShotAction(_browser.GetWebDriver(), TestContext, SharedActions.CreateTestFolder(TestContext))));

           extent.EndTest(report);//here exception
            extent.Flush();
            extent.Close();

**Comment by azary10** [comment]
anshooarora
I can download Version 2.02?

**Comment by anshooarora** [comment]
Yes, from:

extentreports.relevantcodes.com or http://relevantcodes.com/extentreports-for-selenium/

**Comment by azary10** [comment]
Thank you. 

With my issue can you help?

**Comment by anshooarora** [comment]
Please try with beta-2, download link:  http://relevantcodes.com/extentreports-for-selenium/

**Comment by azary10** [comment]
This is extended dll file?
If the version has a child ability for test?
Thank you.
14 нояб. 2015 г. 3:53 пользователь "Anshoo Arora" <notifications@github.com>
написал:

**Comment by anshooarora** [comment]
Yes, this version will have the ability to add child tests upto 1 level deep.

**Comment by anshooarora** [comment]
Can you try with 2.40? Stable version released today.

**Comment by anshooarora** [comment]
Closing as this issue is fixed in 2.40.
