### ISSUE TITLE
New Feature : Section for defects

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#160]
Hi Anshoo,

Is it posible to add new section for defects ,so basically from left navigation bar user can navigate to defects section and under defects section should list of all issues for failed test cases but more in to defect format and defect dash board at top,i know this could be lot of work but if you can make it it would be great feature.

1. defect number
2. Priority based on (fail,warning,fatal)
3. screenshot
4. Error message
5. testsuite name 
6. testcase name

**Comment by anshooarora** [comment]
Jawlit, let's use the following ticket to track this feature.

#150
