### ISSUE TITLE
Timestamp of log actions while using ExtentReports in the listener

### ISSUE THREAD

**Issue by MegaUkrainian** [anshooarora/extentreports#161]
Dear Anshoo Arora,

Firstly, I'd like to thank you for your work and nice reports framework.

When I use ExtentReports (v2.10) in testNG listener, all the timestamps of logging actions are written at the end of all tests  during the report generation. As a result, all the steps which I retrieve from TestNG reporter (Reporter.getOutput(result)) have useless timestamps in the Report (see the attachment)

Is there a way of hiding the timestamp for log actions? I think it would be enough to check the start, end, duration time of the test. 
I highly appreciate other suggestions on solving my issue, if any.

Thank you in advance.
![selection_040](https://cloud.githubusercontent.com/assets/13480390/11178059/dca88b2e-8c52-11e5-8343-e996d6f4b770.jpg)

**Comment by anshooarora** [comment]
Simply use `config` and insert the following css:

```
#test-details-wrapper th:nth-child(2), td.timestamp {
    display: none
}
```

More info here:  http://extentreports.relevantcodes.com/java/version2/docs.html#using-custom-css

Note:  This method of configuration is going to change in version 2.40.0 and will be replaced by an xml file.

**Comment by MegaUkrainian** [comment]
Hi,

Thanks, resolved.
