### ISSUE TITLE
Not able to generate reports when tests running parallel with TestNG

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports#162]
@anshooarora @virenv 

Need some help, i'm triggering my tests in parallel using the ExecutorService and i'm not able to get any results in the ExtentReports

@Test
	public void testReports() {
		// TODO Auto-generated method stub
		List<Class> testCases = new ArrayList<Class>();
		testCases.add(Sample2Test.class);
		testCases.add(SampleTest.class);
		
		ExecutorService executorService = Executors.newFixedThreadPool(2);
		for (final Class testFile : testCases) {
			executorService.submit(new Runnable() {
				public void run() {
					System.out.println("Running test file: " + testFile.getName());
					testRunnerTestNg(testFile);

				}
			});
		}
		executorService.shutdown();
		try {
			executorService.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		// baseTest.convertXmlToJSon();
		System.out.println("ending");
	}
	public static void testRunnerTestNg(Class arg) {
		TestNG test = new TestNG();
		test.setTestClasses(new Class[] { arg });
		test.run();
	}

**Comment by saikrishna321** [comment]
SampleTest
```
package com.test.sample;

import org.testng.AssertJUnit;
import org.testng.annotations.Test;

import com.test.basetest.BaseTest;

public class SampleTest extends BaseTest {

	
	@Test
	public void testApp(){
		testReporter.assignCategory("Smoke");
		AssertJUnit.assertTrue(false);
	}
	
	@Test
	public void testApp1(){
		AssertJUnit.assertTrue(true);
	}
	
	@Test
	public void testApp2(){
		AssertJUnit.assertTrue(false);
	}
	
	
	@Test
	public void testApp3(){
		AssertJUnit.assertTrue(true);
	}
}

```

BaseTest

```
package com.test.basetest;

import java.lang.reflect.Method;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import org.openqa.selenium.WebDriver;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeMethod;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.test.factory.ComplexReportFactory;


public class BaseTest extends TestListenerAdapter {

	WebDriver driver;
	public ExtentTest testReporter;
	private String filenameOfReport = System.getProperty("user.dir") + "/index.html";

	@BeforeMethod
	public void beforeMethod(Method caller) {
		ComplexReportFactory.getTest(caller.getName(), "This is a simple test from complex factory");
	}

	@AfterMethod
	public void afterMethod(Method caller) {
		ComplexReportFactory.closeTest(caller.getName());

	}

	/*
	 * After suite will be responsible to close the report properly at the end
	 * You an have another afterSuite as well in the derived class and this one
	 * will be called in the end making it the last method to be called in test exe
	 */
	@AfterSuite
	public void afterSuite() {
		ComplexReportFactory.closeReport();
	}
    
	@Override
	public void onTestSuccess(ITestResult tr) {
		System.out.println(((ITestResult) tr).getMethod().getMethodName() + "--Test method success\n");
//		ExtentReports extent = createReport();
//		ExtentTest test = extent.startTest(tr.getMethod().getMethodName(), "-");
		testReporter = ComplexReportFactory.getTest();
		testReporter.log(LogStatus.PASS, "-");
		//flushReports(extent, test);
	}

	@Override
	public void onTestFailure(ITestResult tr) {
		System.out.println(tr.getMethod().getMethodName() + "--Test method failed\n");
		//ExtentReports extent = createReport();
		//ExtentTest test = extent.startTest(tr.getMethod().getMethodName(), "Test failed, click here for further details");
		//ExtentTest testReporter = ComplexReportFactory.getTest();
		// step log
		testReporter =  ComplexReportFactory.getTest();
		testReporter.log(LogStatus.FAIL, "Failure trace Selenium: " + tr.toString());
		testReporter.log(LogStatus.INFO, "Snapshot below: " + testReporter.addScreenCapture("/Users/saikrisv/Downloads/addtext_com_MjA1MjUxNDkyODA.png"));
		//flushReports(extent, test);
	
	}

	private ExtentReports createReport() {
		ExtentReports extent = new ExtentReports(filenameOfReport, false);
		extent.config().reportName("My first extentReport report");
		extent.config().reportHeadline("See my awesome passed tests!");
		return extent;
	}

	private void flushReports(ExtentReports extent, ExtentTest test) {
		// ending test
		extent.endTest(test);
		// writing everything to document
		extent.flush();
	}

	private String getDateTime() {
		Date date = Calendar.getInstance().getTime();

		// Display a date in day, month, year format
		DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy_HH_mm_ss");
		String today = formatter.format(date);
		return today;
	}
}

```

**Comment by saikrishna321** [comment]
@anshooarora u need to take look @ this issue as well https://github.com/virenv/ParallelTestNg/issues/1

**Comment by anshooarora** [comment]
Few issues in your code. Will share a solution tomorrow morning, but have a look here:

#102

ExtentTestManager class.

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/extent_reports this is the sample example. Please take a look @ Runner1.java thats how i programmatically and get the issue which i pointed to viren and Check Runner.java for the reports not getting generating ...

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/extent_reports this is the sample example. Please take a look @ Runner1.java thats how i programmatically and get the issue which i pointed to viren and Check Runner.java for the reports not getting generating ...

**Comment by anshooarora** [comment]
Here is a working sample:

http://relevantcodes.com/Tools/ExtentReports2/issues/test.zip

**Comment by saikrishna321** [comment]
@anshooarora Awesome.. i look at it and it worked :+1: How can i log the error stack as well in the report ?

And do u think we have a gitter.im for this repo will help communication easy

**Comment by saikrishna321** [comment]
@anshooarora i dont see the entire stack trace error on the report i use the below code

ExtentTestManager.getTest().log(LogStatus.FAIL, result.getThrowable().getMessage().toString());

expected: but was: this is all i see in the report when it fails .. 

This is the assert statement
AssertJUnit.assertEquals("sai", "sa");

**Comment by anshooarora** [comment]
You can get stacktrace from Throwable or if you use 2.40b, you can pass Throwable to log and it will print the entire stacktrace.

**Comment by anshooarora** [comment]
This is added in v2.40 - released today.

**Comment by saikrishna321** [comment]
@anshooarora thanks a lot .. an other concern 


From the above zip which u shared, i also want to assign category.

For Example:: I need to know the tests that ran on thread 1 , thread 2 and so on ... 


	@BeforeMethod
	public void beforeMethod(Method caller) throws Exception {
	    testopenBroswer();
	    System.out.println(device_udid);
		ExtentTestManager.startTest(caller.getName(), "This is a simple test.").assignCategory("Mobile_Test");
	}

Instead of Mobile_Test i need to assign the device_udid which is different .. l= can you help me on this ?
