### ISSUE TITLE
Test Report result is getting replaced by the next parameter run of the same class!!!! 

### ISSUE THREAD

**Issue by TanujAutomata** [anshooarora/extentreports#163]
HI Anshoo,
Hope u r doing good!!!

When executing a same class using different parameters, Test report is getting overlapped again and again and only showing the result for the last class run only
Extent report being used:2.04 Java 

PFA the testngxml data!!!
There class 'QuickActionsSection' is executed using different parameter in a single run.....

[Test.txt](https://github.com/anshooarora/extentreports/files/36749/Test.txt)

Regards,
Tanuj

**Comment by anshooarora** [comment]
Are you creating a new instance of Extent each time?  That would overwrite the previous file.  Try with: `replaceExisting = false`.

**Comment by TanujAutomata** [comment]
Yeah Anshoo.. I am creating a new instance of Extent each time.
I have set replaceExisting = false...will check and let u know.
Thanks for the help!!!!

Anshoo: Is it possible to print the report without calling flush or endtest method after each test??

**Comment by anshooarora** [comment]
No.  But you can add both in your `@AfterMethod` just once and it should take care of it.
