### ISSUE TITLE
Too long rendering of the Filter By Status/Category fields

### ISSUE THREAD

**Issue by MegaUkrainian** [anshooarora/extentreports#164]
Hi Anshoo Arora,

I have found performance issue with Filter By Status/Category fields. Please take a look.

HW: 4 cores CPU, 12 GB RAM
Browsers: Chrome 46.0, Firefox 42.0
Extent Reports v2.10
Generated Report contains 35 categories, 278 tests and 6122 steps
Total size of the report is near 3 MB

When I try to filter tests by failed status it takes 4-5 sec all the time (see attachements)
I think 300 tests are not so big number and 5 secs delay is quite long. 

As I understand you use external jquery library for this purpose. May be you see a way of optimizing filtering technique. 
Please share your thoughts. 

![selection_046](https://cloud.githubusercontent.com/assets/13480390/11236166/00a7d6e0-8de0-11e5-848d-f92f570ad930.jpg)
![selection_047](https://cloud.githubusercontent.com/assets/13480390/11236168/05f80b10-8de0-11e5-92cb-4e20c77f9d2a.jpg)
Screencast: https://drive.google.com/file/d/0B-ZrK7UNzoiQZDNvWk02UFNaZG8/view?usp=sharing

**Comment by anshooarora** [comment]
The upcoming version has several performance improvements (starting 2.40-beta-2).  Please try with that and see if this performs better?

**Comment by MegaUkrainian** [comment]
Could you please add the latest version to maven repo? I am trying to avoid changes on our CI servers

**Comment by anshooarora** [comment]
I haven't had a chance to do this, but the release version will be available on the repo.

**Comment by anshooarora** [comment]
Can you try with 2.40?  <a href='http://search.maven.org/#artifactdetails|com.relevantcodes|extentreports|2.40|jar'>Link</a>.  

It has lots of performance improvements. I tested with 300 tests and it took about 1 second.

**Comment by MegaUkrainian** [comment]
Thank you. I will try later and post the results.

**Comment by anshooarora** [comment]
Did you find the response times to be better for filters with 2.40?

**Comment by MegaUkrainian** [comment]
Hi, I was busy with other tasks. I am going to check 2.40 on the next week.

**Comment by MegaUkrainian** [comment]
Here is the results on 2.40:
209 step(s) passed, 140 step(s) failed, 5797 others
Duration of filtering: 1.8sec - 2.4sec

![capture](https://cloud.githubusercontent.com/assets/13480390/11909598/6be14490-a5f1-11e5-9c0d-ace37c50ec33.JPG)

Yes, it's better, but I think ~1-1.5 sec should be appropriate duration.

**Comment by anshooarora** [comment]
Can you also try the same after disabling the charts refresh?  Its the 5th enabled control..  If that is the culprit, I can make it asynchronous so it does not interfere with the filters.

**Comment by MegaUkrainian** [comment]
![report](https://cloud.githubusercontent.com/assets/13480390/11909785/20dcd394-a5f4-11e5-8bfc-628f50185679.JPG)
Seems charts refresh is not the root of the issue.

Some additional info: PC where I am looking the report has less perfomance than I provide at the initial post. However, I have a feeling that it wold be the quite the same with my first HW (performance was quite equal on 2.10 on both PC)

Also, this is the Offline report and I have few errors in console
--------
HTML_Report/extentreports/font/roboto/Roboto-Regular.woff2  << missing font
HTML_Report/extentreports/font/roboto/Roboto-Bold.woff2  << missing font
Uncaught ReferenceError: holds is not definedinvoke @ inject.js:134 << ?
--------

One more thing, that might help: Filtering time depends on the total number of filtered tests. If there are less failed tests (filer by Failed status) the executing time, will be less too.

If there is no obvious issues with JS filters, how about adding smthg like cache. It's not a nig deal to wait for 2 sec =) but if you are trying to work with the same report for a long time it becomes noticable.

**Comment by anshooarora** [comment]
Made a few more perf improvements.

The jar will be uploaded to downloads soon, and you can use the maven dependency to test as well:

```
<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>2.40.1-SNAPSHOT</version>
</dependency>
```

**Comment by MegaUkrainian** [comment]
Thanks, I'll check as soon as the new version is available in the repository.
