### ISSUE TITLE
Is Extent reports support IE.

### ISSUE THREAD

**Issue by Deerasameera** [anshooarora/extentreports#165]
Hi,
I am new to this extent reports. My question is, when i open the extent report in IE, My report details are not displaying but in IE i have seen more options than Chrome & Firefox.
will you please explain regarding this.
And i need details document of Extent reports.

Thanks & Regards
Deerasameera.Ch

**Comment by anshooarora** [comment]
See here for supported browsers and docs: http://extentreports.relevantcodes.com/#browsers-supported
