### ISSUE TITLE
Customization ExptentReports Name

### ISSUE THREAD

**Issue by guneetgarg** [anshooarora/extentreports#166]
Hi anshoo

Can we customize this to something like Dashboard Menu

![rename](https://cloud.githubusercontent.com/assets/3676026/11267566/0e37a8ce-8ed2-11e5-83cb-cef569d38dd6.png)

**Comment by anshooarora** [comment]
Yes, with js only.

But.. starting 2.40.0-beta-2:  even if you customize another supplementary script will run and overwrite the value to Extent.

**Comment by guneetgarg** [comment]
ok thanks

**Comment by anshooarora** [comment]
Closing as changing logo is only possible by altering the source.
