### ISSUE TITLE
RESULT FILE

### ISSUE THREAD

**Issue by balaramc** [anshooarora/extentreports#167]
Hi 

I just got a small problem, i deleted result.html (extentreport) from my project and after running the code i cant see the new results.html file. Is there any solution to this problem.if it was sorted it was great help to me Mr.Anshooarora

**Comment by anshooarora** [comment]
Check trash-bin?  If its not there, re-run the test and it should be saved in the location Extent initialized.

**Comment by balaramc** [comment]
Thanx for fast reply, but still i cant get that output result file.(when i am runnng the program, folder was creating but .html file was not getting in that folder)

**Comment by anshooarora** [comment]
Can you share a test case?

**Comment by anshooarora** [comment]
Closing issue as there was no response.
