### ISSUE TITLE
extent reports for ruby

### ISSUE THREAD

**Issue by anilreddy** [anshooarora/extentreports#168]
Hi @anshooarora,

Could you please add extent reports for ruby. I could like to help you on that.

Thanks,
Anil

**Comment by anshooarora** [comment]
I do have plans to create impl for Python/Ruby but due to bandwidth issues, both projects are idle.  Just supporting Java/.NET takes up nearly all capacity.  Feel free to start on Ruby if you want and I will merge your pull requests.  You can use Java/.NET code for reference.

**Comment by anilreddy** [comment]
@anshooarora sure Thanks..!!

**Comment by anshooarora** [comment]
I have begun bringing the template over to ruby with liquid.  I will share the source soon, the rest is just creating the controllers + model.  Feel free to contribute.

**Comment by anilreddy** [comment]
cool..!!

**Comment by anshooarora** [comment]
Here you go:  89fb8d6ce5d7c8725e67a4365ef549dfa8670f5c

Please feel free to contribute and spread a word so we can be greater contributions.

You can test the library using the following code:

```ruby
# main extent instance
extent = RelevantCodes::ExtentReports.new('extent_ruby.html')

# extent-test
extent_test = extent.start_test('First', 'description string').assign_category('Extent').assign_author('Anshoo')

# logs
extent_test.log(:pass, 'step', 'details')
extent.end_test(extent_test)

# flush to write everything to html file
extent.flush

```
