### ISSUE TITLE
v240 Beta: Getting error while generating report in Network offline mode

### ISSUE THREAD

**Issue by varunanilgupta** [anshooarora/extentreports#170]
Here is code that I am running:

package com.citi.vms.report;

import java.io.File;
import java.util.List;

import org.apache.log4j.Level;

import com.core.Constants;
import com.core.Log;
import com.testinfo.Steps;
import com.testinfo.TestResults;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import com.relevantcodes.extentreports.NetworkMode;

public class Reporter {
	ExtentReports htmlReport;
	ExtentTest htmlTestCase;

	

	 */
	public void generateReport(String reportLoc,String reportTitle,String reportHeadLine) throws Exception {

		Log.logMessage(Level.INFO,
				"Inside generateReport function. File Location is passed as "
						+ reportLoc);

		try {

			htmlReport = new ExtentReports(reportLoc, true,NetworkMode.OFFLINE);		   
		    htmlReport.loadConfig(new File("C:\\Framework\\extent-config.xml"));
			for (int k = 0; k < Constants.testcaseList.size(); k++) {
				String testCaseName = Constants.testcaseList.get(k);
				Log.logMessage(Level.DEBUG,
						"Extracting information for the testcase "
								+ testCaseName);

				List<Steps> testCaseSteps = Constants.testInfoMap.get(testCaseName);
				List<TestResults> totalNoOfExec = testCaseSteps.get(0)
						.getStepResults();

				int size = 1;
				for (int execCounter = 0; execCounter < totalNoOfExec.size(); execCounter++) {

					String testcaseCounter = "";
					if (totalNoOfExec.size() >= size) {
						testcaseCounter = testCaseName + " " + size;
						Log.logMessage(Level.DEBUG,
								"Adding testcase information with name "
										+ testcaseCounter);
						htmlTestCase = htmlReport.startTest(testcaseCounter); //Starting a new testcase
					}
					
					for (int i = 0; i < testCaseSteps.size(); i++) 
					{						
						List<TestResults> step = testCaseSteps.get(i)
								.getStepResults();
						if (execCounter < step.size()) {
							TestResults testResultObj = step.get(execCounter);							
							if (htmlTestCase != null) 
							{								
					
								Log.logMessage(Level.DEBUG,"Adding information for the Step to the report "+ testResultObj.getStepName());
								
								if(testResultObj.getStepResult().equals("true"))
								{
										htmlTestCase.log(LogStatus.PASS, testResultObj.getStepName()+"\n"+"<span><pre>"+ testResultObj.getStepResultDetails()+ "</pre></span>");
								}
								else if(testResultObj.getStepResult().equals("false"))
								{
									htmlTestCase.log(LogStatus.FAIL, testResultObj.getStepName()+"\n"+"<span><pre>"+ testResultObj.getStepResultDetails()+ "</pre></span>");											
								}
								else
								{
									htmlTestCase.log(LogStatus.SKIP, testResultObj.getStepName()+"\n"+"<span><pre>"+ testResultObj.getStepResultDetails()+ "</pre></span>");
								}
							}

						}
					}
					htmlReport.endTest(htmlTestCase); //Closing test case
					size++;
					Log.logMessage(Level.DEBUG,
							"Successfully added testcase information for "
									+ testcaseCounter);
					// }
				}
			}
			htmlReport.flush();			
			Log.logMessage(Level.INFO,"Successfully able to generate the report at location "+reportLoc);
			
		} catch (Exception e) {
			Log.logMessage(Level.ERROR,"Issue occurend while generating report "+e);
			throw new Exception ("Issue occurend while generating report "+e);
		}
	}	
}

Here is the error that I am getting:
Nov 20, 2015 2:03:03 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/C:/Framework/Framework_lib/extentreports-java-v2.40.0-beta-2/extentreports-2.40.0-beta2/extentreports-java-2.40.0-beta-2.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
[main] ERROR   - Issue occurend while generating report java.lang.NullPointerException
Exception in thread "main" java.lang.Exception: Issue occurend during execution 
 java.lang.Exception: Issue occurend while generating report java.lang.NullPointerException
	at com.core.Driver.main(Driver.java:97)

**Comment by anshooarora** [comment]
The issue with offline report is finally fixed.  

Beta-3 available for download.

**Comment by anshooarora** [comment]
Have you tried this with 2.40?  Can you test and report back if you are still having issues?

**Comment by anshooarora** [comment]
I am closing this ticket as this bug is fixed in 2.40.  Please reopen if you still encounter this issue.

**Comment by varunanilgupta** [comment]
I have tested the fix and it is working fine.
