### ISSUE TITLE
Would be nice to have the class name under the test method name in the test-steps div

### ISSUE THREAD

**Issue by testphreak** [anshooarora/extentreports#172]
On the landing page, once we select a method, it would be nice if the class name is added right below the method name in the test-steps div (right section). This would be a nice little feature to have if there are multiple test methods with the same name under different classes. Then it helps find out the class for which the method failed.

<img width="1428" alt="screen shot 2015-10-19 at 8 25 19 pm classname" src="https://cloud.githubusercontent.com/assets/10567800/11387483/d4fd8c56-92df-11e5-8dd6-6c83f2495017.png">

**Comment by MegaUkrainian** [comment]
Hi,

I use Test Categories for distinguishing the methods under the different Test classes:
http://extentreports.relevantcodes.com/java/version2/docs.html#assign-category

**Comment by testphreak** [comment]
Thanks, but that doesn't help within the framework of my project. 

@anshooarora this is possible in TestNG using ITestResult's result.getTestClass().getName()

**Comment by anshooarora** [comment]
This can be an ER.  I can release this soon, but filtering won't be immediately available based on this field.  I will have to rewrite the way filtering is performed as we are adding more items to filter tests against.

**Comment by testphreak** [comment]
I am not sure I followed your comment, but perhaps you thought my suggestion was something more sophisticated. To explain better I added a screenshot above. I am not asking for any fancy filtering here (though that would be nice :smiley: ). All I want is a plain text class name at the top where the test method is printed out.

**Comment by anshooarora** [comment]
With v2.40.0, you can add the class name when starting your test.

```java
private static String getLabel(String text) {
    return "<span class='label outline info'>" + text + "</span>";
}

test = extent.startTest("Extent " + getLabel("com.relevantcodes"));
```

I will make it a bit more elegant in the next release but you will now be able to insert any HTML in the test-name field.

**Comment by testphreak** [comment]
@anshooarora I'd like to test that, but I've run into an issue. I updated project to v2.40 and added the loadConfig line as described in the docs. Ran a test. For some reason, I don't see anything on the page when I load the report.

```java
public synchronized static ExtentReports getInstance() {
        if (extent == null) {
            if (context != null) {
                File outputDirectory = new File(context.getOutputDirectory());
                File resultDirectory = new File(outputDirectory.getParentFile(), "html");
                extent = new ExtentReports(resultDirectory + File.separator +  "index.html", true);
                File configFile = new File("src/test/resources/extent-config.xml");
                extent.loadConfig(configFile);
                Reporter.log("Extent Report directory: " + resultDirectory, true);
            }
        }
        return extent;
    }
```

Output:

```
Dec 01, 2015 1:08:08 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/Users/testphreak/.m2/repository/com/relevantcodes/extentreports/2.40/extentreports-2.40.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
Dec 01, 2015 1:08:08 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from src/test/resources/extent-config.xml
.
.
.
```
Am I missing something? Why is configuration getting invoked twice as per the output above? The report is generated correctly if I don't add my own config file. The config file itself is the same as your example except for project specific text changes.

**Comment by anshooarora** [comment]
Hmm, try loading the config file one of the 2 ways as shown here:  http://extentreports.relevantcodes.com/java/version2/docs.html#configuration

```java
// loadConfig(Class clazz, String fileName);
// clazz: com.relevantcodes.extentreports.ExtentReports
// packagePath of clazz: com/relevantcodes/extentreports
// final path: com/relevantcodes/extentreports/extent-config.xml
loadConfig(ExtentReports.class, "extent-config.xml");


// loadConfig(Class clazz, String basePackagePath, String fileName;
// clazz: com.relevantcodes.extentreports.ExtentReports
// 	packagePath of clazz: com/relevantcodes/extentreports
// basePackagePath: "resources"
// final path: com/relevantcodes/extentreports/resources/extent-config.xml
loadConfig(ExtentReports.class, "resources", "extent-config.xml");
```

So if you are running your test from `src/test`, use the following command:

```
loadConfig(YourTest.class, "resources", "extent-config.xml");
```

With the method signature you are using, I will have to see what's happening there.

**Comment by testphreak** [comment]
My project directory structure is:
![screen shot 2015-12-01 at 12 23 37 pm](https://cloud.githubusercontent.com/assets/10567800/11513185/aa1cacaa-9826-11e5-82c9-06d908d2da9b.png)

I tried providing the absolute path, but that is generating the same blank report as well (no error, test runs fine).

```
Dec 01, 2015 12:03:52 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/Users/testphreak/.m2/repository/com/relevantcodes/extentreports/2.40/extentreports-2.40.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
Dec 01, 2015 12:06:53 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from /Users/testphreak/git/turbo/test/webdriver/src/test/resources/extent-config.xml
``` 

Code for the output above:

```
final String currentDirectory = System.getProperty("user.dir");
File configFile = new File(currentDirectory + "/src/test/resources/extent-config.xml");
extent.loadConfig(configFile);
```

When I use the 3rd loadConfig option, it expects the config xml file to be in the resources directory under the root directory (webdriver), which isn't good, because it breaks the Maven folder hierarchy, where all resource files are expected to be in the resources directory (as shown in screen shot). So when I try something like this:

```
String greatGrandParent = ExtentReporter.class.getResource("../../../../").toString();
extent.loadConfig(ExtentReporter.class, greatGrandParent + "resources", "extent-config.xml");
```

I get the following output:

```
Dec 01, 2015 12:48:23 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/Users/testphreak/.m2/repository/com/relevantcodes/extentreports/2.40/extentreports-2.40.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
Dec 01, 2015 12:51:29 PM com.relevantcodes.extentreports.ExtentReports loadConfig
WARNING: Unable to perform report configuration. The package or file com/citrix/turbo/webdriver/file:/Users/testphreak/git/turbo/test/webdriver/target/test-classes/resources/extent-config.xml was not found.
```

Is there any way we can use relative paths with loadConfig like I tried originally? It's the most straight-forward option.

**Comment by anshooarora** [comment]
Woops.  Your usage is correct.  The config file wasn't updated in the docs with the release.

Here is the correct one:  http://extentreports.relevantcodes.com/java/version2/docs.html#configuration

```
<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
		<!-- document encoding -->
		<encoding>UTF-8</encoding>
		
        <!-- title of the document -->
        <documentTitle>Custom</documentTitle>
        
        <!-- report name - displayed at top-nav -->
        <reportName>Automation Report</reportName>
        
        <!-- report headline - displayed at top-nav, after reportHeadline -->
        <reportHeadline></reportHeadline>
        
        <!-- custom javascript -->
        <scripts>
            <![CDATA[
                $(document).ready(function() {
                    $('#enableDashboard').click();
                });
            ]]>
        </scripts>
        
        <!-- custom styles -->
        <styles>
            <![CDATA[
                
            ]]>
        </styles>
    </configuration>
</extentreports>
```

**Comment by testphreak** [comment]
Works correctly now with the right configuration file! Also, the solution to add class name to every test works well. One thing I noticed was with 2.40 all lines in a stack trace are wrapping together. To fix that I replaced line separators with br tags.

```java
/**
     * Returns stacktrace to display on web page
     * @param t of type Throwable
     * @return stacktrace
     */
    protected String getStackTrace(Throwable t) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        t.printStackTrace(pw);
        String stackTrace = sw.toString();
        return stackTrace.replace(System.getProperty("line.separator"), "<br/>\n");
    }
```
Also, long test method names wrap to a new line. Thanks for the fixes Anshoo!

P.S. I kept thinking the word "configurating" from the initial log message that gets printed with 2.40 "INFO: *Configurating* report from" is a typo and should have been "configuring". Then I looked it up and in  fact [there is a debate](http://forum.wordreference.com/threads/whats-the-difference-between-configure-and-configurate.2788829/) about if the word exists :grinning:!

**Comment by anshooarora** [comment]
Are all lines wrapping together when you use this method as well?

```
test.log(LogStatus, Exception e);
```

Configuration.. Hmm does sound weird. It should be configuring.  Will correct the typo

**Comment by testphreak** [comment]
Thanks for pointing me to this new log method signature. No, with this new method, I don't see the wrapping. Now, I don't need the custom getStackTrace method and it looks better formatted on the report.

**Comment by testphreak** [comment]
Just in case if anybody else is interested in doing this with a parallel implementation using TestNG. While the second parameter is meant to be used for test descriptions, it's been re-purposed to print test class names.

```java
@BeforeMethod(alwaysRun = true)
public void startExtent(Method method) {
        ExtentReporter.startTest(method.getName(), ExtentReporter.getLabel(method.getDeclaringClass().getName()));
 }
```

**Comment by testphreak** [comment]
@anshooarora please feel free to close this issue, unless you want to use this one to track the more elegant solution you were planning with the next release.

**Comment by anshooarora** [comment]
We can close this since the method you've used (passing the className in description) is quite good.  I will point other users to this in case they are looking for a similar solution.
