### ISSUE TITLE
How to merge report if test cases are running on different machines

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#173]
Hi Anshoo,

I am getting lots of troubles while running test on remote machines using selenium grid and i am thinking to take different approach ,I want to make copy of code on each machines and run as local on all machines but I want to generate only one report ,could you please suggest me work around for this one 

Thanks 
Jawlit

**Comment by testphreak** [comment]
I run my tests using Selenium Grid and there's nothing special you need to do generate a single report. This issue likely has nothing to do with ExtentReports. You would face the same problems integrating your project with any other reporting framework. Try ReportNG or the one which comes with TestNG out of the box.

Also, when submitting an issue, you are likely to get more help by providing the steps/code snippet to reproduce the bug along with any stack trace from the log. "Getting lots of troubles" is ambiguous and not very helpful. 

A more appropriate forum for this question would be https://groups.google.com/forum/#!forum/selenium-users

**Comment by jawlitkp** [comment]
Hello,

My question is not related to selenium functionality ,i just want to know if i am running test on different machine without using grid than how would i report all test cases to only one html file.

**Comment by anshooarora** [comment]
The report is for a session only.  If you want to write from multiple machines to a single file, I would recommend writing to the database instead.  You can merge the reports from the database into one by date using ExtentMerge.

**Comment by jawlitkp** [comment]
Thanks Anshoo,

How about if i use shared or network drive to create report.html and tell all machines to write report to report.html which is on shared drive and accessible from all machines.
