### ISSUE TITLE
BUG: Category filter is not working properly

### ISSUE THREAD

**Issue by petuk** [anshooarora/extentreports#174]
version: extentreports-2.40.0-beta-final
IE11

- I've added the package name and class name for all test as a Category
-> all test contains the same package name category and different class name category
- select filter with package name
-> no tests are selected (NOT OK)
- select filter with test name
-> test is selected (OK)

The category(package, class name) are shown in the test box in a blue circle.

**Comment by petuk** [comment]
Additional info: If the category looks like this: com.company.classname.etc (contains "." character) the filter by category is not working. If I removed the dot character -> works like a charm

**Comment by anshooarora** [comment]
I am able to reproduce this, very strange as its a text search.  Will release fixed filter soon.

**Comment by anshooarora** [comment]
Fixed in 2.40.
