### ISSUE TITLE
BUG: Test name link is not working

### ISSUE THREAD

**Issue by petuk** [anshooarora/extentreports#175]
version: extentreports-2.40.0-beta-final
IE11

1. select Categories tab in the test report
2. click one of the test and then select the first test
-> In this case if click the test name, nothing happens (should be jump in the test steps)

Note: if you skip the 2. steps and just simply click the first test, it works

**Comment by anshooarora** [comment]
I am able to reproduce, will release a fix

**Comment by anshooarora** [comment]
This is fixed in v2.40 - released today.
