### ISSUE TITLE
Nice-to-Have: Categories box is too small

### ISSUE THREAD

**Issue by petuk** [anshooarora/extentreports#176]
version: extentreports-2.40.0-beta-final
IE11

- Click on Analysis tab
- Check the Categories part 

Result: As I added the package name as a category, the place is too small for that (it is wrapped in 3 lines). It would be better if the width of the categories box would be the same as Steps View box.

**Comment by petuk** [comment]
changing with the style, it works:

Original:
<div class='category-summary-view'>
<div class='col l2 m6 s12'>

Changed:
Original:
<div class='category-summary-view'>
<div class='col l4 m6 s12'>

**Comment by anshooarora** [comment]
Thanks,  I will make this style standard in the upcoming.

**Comment by anshooarora** [comment]
This is fixed in v2.40.
