### ISSUE TITLE
html report issue not displaying the full Assert Error

### ISSUE THREAD

**Issue by KyletheWolff** [anshooarora/extentreports#177]
This is the error I have in eclipse when the report is finished the <true> and <false> do not display. Please fix for better reporting

java.lang.AssertionError: Should return true if all of the elements are accounted for
Expected: is <true>
     but: was <false>

**Comment by anshooarora** [comment]
What version are you using?

**Comment by KyletheWolff** [comment]
2.10

**Comment by anshooarora** [comment]
In the next version you willbbe able to pass in the exception and the entire stack trace will be printed.

**Comment by KyletheWolff** [comment]
When willl this be?

**Comment by anshooarora** [comment]
v2.40.0 released today.

Link:  http://extentreports.relevantcodes.com/java/version2/docs.html#create-step-logs
