### ISSUE TITLE
Screenshot not working for Perfecto Drivers

### ISSUE THREAD

**Issue by RichieGulati** [anshooarora/extentreports#178]
Hi Anshoo,

I am using Perfecto and Selenium. Drivers used for execution are domdriver, visualdriver and nativedriver. As per the screenshot code, I am using mobiledriver but it is not able to take the screenshot. Can you let me know which driver should I use to take screenshot in Perfecto Mobile.

public static String CaptureScreen(MobileDriver driver, String ImagesPath)
    {
    	ImagesPath="C:/Softwares/Regression/Regression_Framework/Reports/Extent_Reports/Screenshots"+System.currentTimeMillis();
        TakesScreenshot oScn = (TakesScreenshot) driver;
        File oScnShot = oScn.getScreenshotAs(OutputType.FILE);
     File oDest = new File(ImagesPath+".jpg");
     try {
          FileUtils.copyFile(oScnShot, oDest);
     } catch (IOException e) {System.out.println(e.getMessage());}
     return ImagesPath+".jpg";
            }
}

**Comment by anshooarora** [comment]
Richie,  This question is not related to Extent.  I would suggest posting this on the selenium or perfecto forum.
