### ISSUE TITLE
Embedded Screenshot cannot zoom

### ISSUE THREAD

**Issue by Yaazie** [anshooarora/extentreports#179]
Hi 
When i embed an image and try to click on it to get the fullscreen view. This is what happens. It only happens to embedded images.
![2015-11-26_13h44_46](https://cloud.githubusercontent.com/assets/10814618/11422365/099bf37a-9444-11e5-96a6-1adebcf801f6.png)

What can i do to fix this?

**Comment by anshooarora** [comment]
Hmm, Extent uses the featherlight plugin for its lightbox.  Looks like an issue with the plugin, or could be I am using it incorrectly.  Will investigate.

**Comment by anshooarora** [comment]
duplicate issue #169
