### ISSUE TITLE
Feature Request: Requirements-level BDD

### ISSUE THREAD

**Issue by rjmadhu** [anshooarora/extentreports#18]
It would be great if this API reports Requirements-level BDD for tools such as JBehave, Cucumber…
Reporting not only on how the tests did but also what requirements have been tested and what requirements haven’t.

Let me know your thoughts on this.

Regards
Madhu RJ

**Comment by anshooarora** [comment]
Madhu

It would be very easy to design feature to assign reqs to tests.

Quick question: how would we know what percentage of a requirement is complete?  What other features would have to be implemented to complete this requirement?

Would really like to get more details from you to be able to correctly implement this.

Also, #17 seems similar to this, looks like it would be a good addition.

**Comment by rjmadhu** [comment]
A test coverage report  should list both tested and untested requirements.
BDD reporting tools such as Jbehave, Cucumber have a concept of pending Tests. Pending test is one that has been specified but not yet implemented. 
Example: Acceptance criteria for the user stories.

user story is not complete until all of its automated acceptance tests pass. Similarly, a feature cannot be considered ready to deliver until all of the acceptance criteria for the underlying user stories have been specified and implemented. The requirements with no acceptance criteria must be part of the report. 

Yes #17  has the same requirement.

**Comment by anshooarora** [comment]
Madhu

Thanks foe the explanation.  You should really write on your blog more often, it would be very well received by your readers. 

Do you think I need to read up on bdd before implementing this requirement?  

Basicaily we just need a method that assigns a requirement to a test and specifies what percentage of that requirement is complete, correct?

```
test.assignReq(reqName, percentage complete)
```

**Comment by rjmadhu** [comment]
Hi Anshoo,
Thanks for you suggestion. I will start writing more in my blog soon.
I have been transitioning from one framework to other framework and this
kept be busy to work on your api.
Yes learning about BDD (GWT) will definitely help you more.
I am trying few things on BDD and will try to fit in your API into this
 and let you know what are the limitations with Extent Repots.

Thanks
Madhu RJ

**Comment by anshooarora** [comment]
Version 2.10 (major upgrade) will have initial support for this.

**Comment by rjmadhu** [comment]
Are you going to support jbehave ?

**Comment by anshooarora** [comment]
Yes, but the only challenge is to know how to distinguish between normal tests and scenarios/steps because of Extent's agnostic nature.  Another issue is with pending tests - how will Extent know if a test was skipped because the scenario/step wasn't implemented?

Most of the BDD frameworks are developed without reporting in mind as they implement their own reporting.  So if we can't hook into what they're doing, the user will have to manually do everything which is quite painful.

**Comment by anshooarora** [comment]
Update:  Vimal has written a plugin to support cucumber - a single dependency that will allow creating report with extent.  Link: https://github.com/email2vimalraj/CucumberExtentReporter

**Comment by rjmadhu** [comment]
thanks Anshoo.

**Comment by perwez123** [comment]
Hi Ansho , I tried to run the test of BDD using JVM Cucumber and using the
 https://github.com/email2vimalraj/CucumberExtentReporter , jar file for report. I found there some issue .

1.Unable to write the out put file after taking the screen shot . It throw the error .

Can you provide some example of attaching the screen shot in the report .



Logs :+1: 
SEVERE: Stream closed
java.io.IOException: Unable to write source: Stream closed.
	at com.relevantcodes.extentreports.Report.flush(Report.java:155)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:490)
	at main.java.com.cucumber.listener.ExtentCucumberFormatter.eof(ExtentCucumberFormatter.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy12.eof(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.eof(JUnitReporter.java:198)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:71)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

2.

**Comment by perwez123** [comment]
Can you provide some example of BDD with Hooks and screen shot and How to Customize the report as we do it for extent report . ??

**Comment by email2vimalraj** [comment]
@perwez123: Kindly have a look here for the example: https://github.com/email2vimalraj/CucumberExtentReporter/blob/master/src/test/java/com/cucumber/stepdefinitions/selenium/Google.java#L36

The unit test in CucumberExtentReport works fine by attaching the screenshot. You might have to look at the code on how you generate the screenshot. Let me know how it goes.

**Comment by perwez123** [comment]
Hi ,

Still I am facing the issue , Screen shot is captured but it is unable to
write the file . I have attached the error below .

I am using the extent report version is : 2.40
and the jar file provided by you .

I am using the hook class where i have implemented the Before and After
annotation . I have attached the piece of code i am running . Please have
look and let me know if something wrong from my end . Please find the four
attached file .







Apr 11, 2016 8:02:33 PM com.relevantcodes.extentreports.Report flush
SEVERE: Stream closed
java.io.IOException: Unable to write source: Stream closed.
    at com.relevantcodes.extentreports.Report.flush(Report.java:155)
    at
com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:490)
    at
main.java.com.cucumber.listener.ExtentCucumberFormatter.eof(ExtentCucumberFormatter.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cucumber.runtime.Utils$1.call(Utils.java:37)
    at cucumber.runtime.Timeout.timeout(Timeout.java:13)
    at cucumber.runtime.Utils.invoke(Utils.java:31)
    at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
    at com.sun.proxy.$Proxy12.eof(Unknown Source)
    at cucumber.runtime.junit.JUnitReporter.eof(JUnitReporter.java:198)
    at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:71)
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

On Mon, Apr 11, 2016 at 7:27 PM, VimalRaj Selvam <notifications@github.com>
wrote:

> @perwez123 <https://github.com/perwez123>: Kindly have a look here for
> the example:
> https://github.com/email2vimalraj/CucumberExtentReporter/blob/master/src/test/java/com/cucumber/stepdefinitions/selenium/Google.java#L36
>
> The unit test in CucumberExtentReport works fine by attaching the
> screenshot. You might have to look at the code on how you generate the
> screenshot. Let me know how it goes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/18#issuecomment-208355652>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

package main.java.com.cucumber.listener;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import cucumber.runtime.CucumberException;
import cucumber.runtime.io.URLOutputStream;
import gherkin.formatter.Formatter;
import gherkin.formatter.Reporter;
import gherkin.formatter.model.*;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URL;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

/**
 * Cucumber custom format listener which generates ExtentsReport html file
 */
public class ExtentCucumberFormatter implements Reporter, Formatter {

    private ExtentReports extent;
    private ExtentTest featureTest;
    private ExtentTest scenarioTest;
    private LinkedList<Step> testSteps;
    private File htmlReportDir;

    private static final Map<String, String> MIME_TYPES_EXTENSIONS = new HashMap() {
        {
            this.put("image/bmp", "bmp");
            this.put("image/gif", "gif");
            this.put("image/jpeg", "jpg");
            this.put("image/png", "png");
            this.put("image/svg+xml", "svg");
            this.put("video/ogg", "ogg");
        }
    };

    public ExtentCucumberFormatter(File filePath) {

        if (!filePath.getPath().equals("")) {
            String reportPath = filePath.getPath();
            this.htmlReportDir = new File(reportPath);
            this.extent = new ExtentReports(reportPath);
        } else {
            String reportDir = "output/Run_" + System.currentTimeMillis();
            this.htmlReportDir = new File(reportDir);
            this.extent = new ExtentReports(reportDir + "/report.html");
        }

        this.testSteps = new LinkedList<Step>();
    }

    public void before(Match match, Result result) {

    }

    public void result(Result result) {
        if ("passed".equals(result.getStatus())) {
            scenarioTest.log(LogStatus.PASS, testSteps.poll().getName(), "PASSED");
        } else if ("failed".equals(result.getStatus())) {
            scenarioTest.log(LogStatus.FAIL, testSteps.poll().getName(), result.getErrorMessage());
        } else if ("skipped".equals(result.getStatus())) {
            scenarioTest.log(LogStatus.SKIP, testSteps.poll().getName(), "SKIPPED");
        } else if ("undefined".equals(result.getStatus())) {
            scenarioTest.log(LogStatus.UNKNOWN, testSteps.poll().getName(), "UNDEFINED");
        }
    }

    public void after(Match match, Result result) {

    }

    public void match(Match match) {

    }

    public void embedding(String s, byte[] bytes) {
        String extension = (String)MIME_TYPES_EXTENSIONS.get(s);
        String fileName = "screenshot-" + System.currentTimeMillis() + "." + extension;
        this.writeBytesAndClose(bytes, this.reportFileOutputStream(fileName));
        scenarioTest.log(LogStatus.INFO, scenarioTest.addScreenCapture(fileName));
        
        
    }

    public void write(String s) {
        extent.close();
    }

    public void syntaxError(String s, String s1, List<String> list, String s2, Integer integer) {

    }

    public void uri(String s) {

    }

    public void feature(Feature feature) {
        featureTest = extent.startTest("Feature: " + feature.getName());
    }

    public void scenarioOutline(ScenarioOutline scenarioOutline) {

    }

    public void examples(Examples examples) {

    }

    public void startOfScenarioLifeCycle(Scenario scenario) {
        scenarioTest = extent.startTest("Scenario: " + scenario.getName());

        for (Tag tag : scenario.getTags()) {
            scenarioTest.assignCategory(tag.getName());
        }
    }

    public void background(Background background) {

    }

    public void scenario(Scenario scenario) {

    }

    public void step(Step step) {
        testSteps.add(step);
    }

    public void endOfScenarioLifeCycle(Scenario scenario) {
        extent.endTest(scenarioTest);
        featureTest.appendChild(scenarioTest);
    }

    public void done() {

    }

    public void close() {

    }

    public void eof() {
        extent.endTest(featureTest);
        extent.flush();
    }

    private OutputStream reportFileOutputStream(String fileName) {
        try {
            return new URLOutputStream(new URL(this.htmlReportDir.toURI().toURL(), fileName));
        } catch (IOException var3) {
            throw new CucumberException(var3);
        }
    }

    private void writeBytesAndClose(byte[] buf, OutputStream out) {
        try {
            out.write(buf);
        } catch (IOException var4) {
            throw new CucumberException("Unable to write to report file item: ", var4);
        }
    }

}

package com.test;
import org.testng.Assert;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
public class StepsDef {
	
	@Given("^I am on Google home page$")
    public void test1(){
		
	}
	@Then("^I verify the title is$")
	public void then(){
		Assert.assertTrue(false);
		
	}
}

package com.test;

import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
@RunWith(Cucumber.class)
@CucumberOptions(features = {"src/test/resources/features/selenium"},
                    plugin = {"main.java.com.cucumber.listener.ExtentCucumberFormatter:test/cucmbber.html"})
public class TestRunner {

	 

}

package com.test;

import java.net.MalformedURLException;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import cucumber.api.Scenario;
import cucumber.api.java.After;
import cucumber.api.java.Before;

public class Hooks{
    public static WebDriver driver;

    
    @Before()
    /**
     * Delete all cookies at the start of each scenario to avoid
     * shared state between tests
     */
    public void openBrowser() throws MalformedURLException {
    	System.out.println("Called openBrowser");
    	driver = new FirefoxDriver();
    	driver.manage().deleteAllCookies();
    	driver.get("https://www.google.co.in/?gfe_rd=cr&ei=tLQLV8P0JcqBoAPhqYG4BA");
    	driver.manage().window().maximize();
    }

     
    @After()
    /**
     * Embed a screenshot in test report if test is marked as failed
     */
    public void embedScreenshot(Scenario scenario) {
     
        if(scenario.isFailed()) {
        try {
        	 scenario.write("Current Page URL is " + driver.getCurrentUrl());
//            byte[] screenshot = getScreenshotAs(OutputType.BYTES);
            byte[] screenshot = ((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES);
            scenario.embed(screenshot, "image/png");
        } catch (WebDriverException somePlatformsDontSupportScreenshots) {
            System.err.println(somePlatformsDontSupportScreenshots.getMessage());
        }
        
        }
        driver.quit();
        
    }
    
}

**Comment by anshooarora** [comment]
@perwez123 - can you open a new issue for this?  it will be easier to track.
