### ISSUE TITLE
Issue with Extent Screenshot code for Perfecto

### ISSUE THREAD

**Issue by RichieGulati** [anshooarora/extentreports#180]
Hi Team,

I am trying to take screenshot in perfecto mobile. i am not able to take it using the code used for taking screenshot in extentmanager.java class. Please let me know if I need to use some other driver to capture screenshot?

 public static String CaptureScreen(WebDriver driver, String ImagesPath)
    {
    	ImagesPath="C:/Softwares/Regression/Regression_Framework/Reports/Extent_Reports/Screenshots"+System.currentTimeMillis();
        TakesScreenshot oScn = (TakesScreenshot) driver;
        File oScnShot = oScn.getScreenshotAs(OutputType.FILE);
     File oDest = new File(ImagesPath+".jpg");
     try {
          FileUtils.copyFile(oScnShot, oDest);
     } catch (IOException e) {System.out.println(e.getMessage());}
     return ImagesPath+".jpg";
            }
}

**Comment by anshooarora** [comment]
Closing ticket as this is not an extent-reports question.
