### ISSUE TITLE
Attached screenshot in extent report and sending the report through mail,but screenshot is not visible . I am using latest V2.10 version.On my machine i can see screenshot is attached in the report.

### ISSUE THREAD

**Issue by shrinivasvedula** [anshooarora/extentreports#181]
Attached screenshot in extent report and sending the report through mail,but screenshot is not visible . I am using latest V2.10 version.On my machine i can see screenshot is attached in the report.

**Comment by anshooarora** [comment]
The screenshot attach links the snapshot path which must be available from recipient's machine otherwise it will not be displayed.
