### ISSUE TITLE
HTML file is not getting created on execution.

### ISSUE THREAD

**Issue by anichat26** [anshooarora/extentreports#182]
Hi Abshoo,

       First of all I would like to thank you for your efforts on extent report. Its a great reporting structure for selenium what I saw in the website. But while creating it in my demo project, no HTML file is getting created. Please help!!! the code snippet is provided below. No errror is being displayed. Folder entitled 'demo' is created, but the html file is not getting created. I am using extent reports 2.10

String reportFile="d:\\demo\\demo.html";
extent = new ExtentReports(reportFile, true);
test = extent.startTest("Website Found?");
String website= "https://www.google.co.in/
wd.manage().window().maximize();
wd.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
wd.get(website);

**Comment by MegaUkrainian** [comment]
Hi,

Have you added these statements at the end?
======
// ending test
extent.endTest(test);

// writing everything to document
extent.flush();
======

**Comment by anichat26** [comment]
No. But after adding the statement, It was executed successfully. Thanks
for the support

On Mon, Nov 30, 2015 at 6:42 PM, MegaUkrainian <notifications@github.com>
wrote:

> Hi,
> Have you added these statements at the end?
>
> // ending test
> extent.endTest(test);
>
> // writing everything to document
> extent.flush();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/182#issuecomment-160623570>
> .
>



-- 



*Thanks and Regards,Anirban Chatterjee*

**Comment by rkmatrix** [comment]
I'm using extent report 3.0.6.
Every time I want to generate a new html log file.
But html file is not getting created wen I give a new file path. But if I use the existing file the reports are getting flushed. 
Should I pass an existing html to the reports ??

**Comment by anshooarora** [comment]
@rkmatrix - can you please open a new ticket?

**Comment by saurabh2018** [comment]
Was there any ticket raised for the above reported issue. I am facing the same . Please suggest 

Thanks
Saurabh

**Comment by mouni-ravela** [comment]
Hello anshooarora,

**i am not able to generate extent html report:**

**please go through my code:**

package Extentreport;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class NewTest {
	
	ExtentReports report;
	ExtentTest logger; 
	WebDriver driver;
	
  @Test
  public void verifypagetitle() {
	  
	  {
		report=new ExtentReports("C:\\advancereport.html");
		   
		logger=report.startTest("verifypagetitle");
		   
	  System.setProperty("webdriver.gecko.driver", "C:\\Geco\\geckodriver.exe");	
		
	   driver = new FirefoxDriver ();
	   
	   logger.log(LogStatus.INFO, "Browser started ");

	  driver.get("https://www.google.co.in/");
	
	  logger.log(LogStatus.INFO, "Application is up and running");
	  
	  String title = driver.getTitle();
	  
	  Assert.assertTrue(title.contains("Google"));
	  
	  logger.log(LogStatus.PASS, "Title verified");
	  
	 System.out.println("Test case passed");
	  
	  
  }
	  
	  report.endTest(logger);
		 
		 report.flush();
		 
		 driver.get("C:\\advancereport.html");
	  
	  
}
}

Please let me know the issue.
