### ISSUE TITLE
Using Maven in eclipse it is giving me the error missing artifactId 

### ISSUE THREAD

**Issue by KyletheWolff** [anshooarora/extentreports#183]
<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>2.40</version>
</dependency>

**Comment by anshooarora** [comment]
I just finished uploading to nexus, can you please try again?

**Comment by KyletheWolff** [comment]
Still happening

**Comment by anshooarora** [comment]
Hmm, unable to reproduce.  Below is my output:

```
C:\Users\Anshoo\Documents\workspace\MyJarTest>mvn dependency:copy-dependencies
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MyJarTest 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default-cli) @ MyJarTest ---
[INFO] Copying sqlite-jdbc-3.8.11.1.jar to C:\Users\Anshoo\Documents\workspace\MyJarTest\target\dependency\sqlite-jdbc-3.8.11.1.jar
[INFO] Copying freemarker-2.3.23.jar to C:\Users\Anshoo\Documents\workspace\MyJarTest\target\dependency\freemarker-2.3.23.jar
[INFO] Copying jsoup-1.8.3.jar to C:\Users\Anshoo\Documents\workspace\MyJarTest\target\dependency\jsoup-1.8.3.jar
[INFO] Copying extentreports-2.40.jar to C:\Users\Anshoo\Documents\workspace\MyJarTest\target\dependency\extentreports-2.40.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.538 s
[INFO] Finished at: 2015-11-30T14:24:04-06:00
[INFO] Final Memory: 13M/155M
[INFO] ------------------------------------------------------------------------
```

```
<dependencies>
    <dependency>
        <groupId>com.relevantcodes</groupId>
        <artifactId>extentreports</artifactId>
        <version>2.40</version>
    </dependency>
</dependencies>
```

**Comment by KyletheWolff** [comment]
Missing artifact com.relevantcodes:extentreports:jar:2.40

**Comment by anshooarora** [comment]
Can you share your pom.xml?

**Comment by KyletheWolff** [comment]
```
<dependency>
        <groupId>com.relevantcodes</groupId>
        <artifactId>extentreports</artifactId>
       	<version>2.40</version>
</dependency>

**Comment by anshooarora** [comment]
can you try this:

http://stackoverflow.com/questions/6111408/maven2-missing-artifact-but-jars-are-in-place

**Comment by KyletheWolff** [comment]
When I go back to 

```
<dependency>
        	<groupId>com.relevantcodes</groupId>
        	<artifactId>extentreports</artifactId>
       		<version>2.10</version>
</dependency>
```
Everything works

**Comment by KyletheWolff** [comment]
Not sure why its not working

**Comment by anshooarora** [comment]
Can you open cmd and do a `mvn dependency:copy-dependencies` from your project path?  Same error?

**Comment by KyletheWolff** [comment]
mvn dependency:copy-dependencies
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building AndroidTestSuite 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.relevantcodes:extentreports:jar:2.40 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.754 s
[INFO] Finished at: 2015-11-30T16:24:11-05:00
[INFO] Final Memory: 8M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project AndroidTestSuite: Could not resolve dependencies for project com.AndroidAutomation:AndroidTestSuite:jar:0.0.1-SNAPSHOT: Failure to find com.relevantcodes:extentreports:jar:2.40 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
qas-mac-mini:AndroidTestSuite QA$

**Comment by anshooarora** [comment]
The artifact is available here also:  http://search.maven.org/#artifactdetails|com.relevantcodes|extentreports|2.40|jar

You can download from this link directly or extentreports.relevantcodes.com.

**Comment by anshooarora** [comment]
Did you find a way to resolve this issue?
