### ISSUE TITLE
Html issues

### ISSUE THREAD

**Issue by KyletheWolff** [anshooarora/extentreports#185]
The reporting is still not displaying the complete trace I want. Also, in 2.10 I could build the html fail message the way I wanted it to show up on the report. 

Currently 2.40: 
` Method Name: createAccount_specialCharPasswordValidation Detail message: java.lang.AssertionError: Should return true if a special character is inputed Expected: is but: was Line Number: 95
`

What I want:
```
Method Name: createAccount_specialCharPasswordValidation
Detail message: java.lang.AssertionError: Should return true if a special character is inputed
Expected: is <true>
     but: was <false>
Line Number: 95
```

The expected: is <true> but: was <false> is from an assertThat assertion.

**Comment by anshooarora** [comment]
Looks like the tags `<` and `>` are getting parsed out.  For now, you can replace `<` with `&lt;` and `>` with `&gt;`.  Are you using TestNG?

I do not have any issues with formatting though, here is the uploaded sample: http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html (see 'Test Shows Pre Block'). 

You can still create your fail message the same way you did in 2.10 as all HTML tags are supported in logs.

**Comment by KyletheWolff** [comment]
They way I was doing it was like so

`
extentTest.log(LogStatus.FAIL, getErrorMessage(description, e));
`


```
private String getErrorMessage(Description description, Throwable e){
		errorMessage = new StringBuilder();
		errorMessage.append("Method Name: ");
		errorMessage.append(description.getMethodName());
		errorMessage.append("\t");
		errorMessage.append("Detail message: ");
		errorMessage.append(e);
		errorMessage.append("\t"); 
		errorMessage.append("Line Number: ");
		errorMessage.append(e.getStackTrace()[2].getLineNumber());
	
		return errorMessage.toString();
	}
```

**Comment by KyletheWolff** [comment]
I am using JUnit

**Comment by anshooarora** [comment]
The above formatting that you shared was with the following method signature:

```
extentTest.log(LogStatus.FAIL, e);
``` 
?

**Comment by KyletheWolff** [comment]
Yes then for the e I call that method. 

Previously it worked perfect.

**Comment by KyletheWolff** [comment]
extenTest.log(LogStatus.FAIL, String Details) is what I used

**Comment by anshooarora** [comment]
Test without calling that method.  Directly pass in the exception like this:

```
extentTest.log(LogStatus.FAIL, e);
```

if you want to use the above approach, replace `\t` with `\n` in getErrorMessage.  Also parse out `<` with `&lt;` and `>` with `&gt;` and try again?

**Comment by KyletheWolff** [comment]
Already tried \n does not work anymore. I will try to parse out here in a second

**Comment by anshooarora** [comment]
Hmm,  `<br />` should work as its HTML.

**Comment by KyletheWolff** [comment]
<br> worked well and I just replaced the <true> <false> with the actual string.

**Comment by anshooarora** [comment]
Had no luck using the direct method by passing in the exception?

```
extentTest.log(LogStatus.FAIL, e);
```

This would have been the easiest..

**Comment by KyletheWolff** [comment]
Im trying to make it more readable for other people. That is the reason why I am trying to manipulate it.

**Comment by anshooarora** [comment]
Closing as solution was found.
