### ISSUE TITLE
Extent reports for cucumber with grid

### ISSUE THREAD

**Issue by mkarthik87** [anshooarora/extentreports#186]
Hi,
I have a requirement where I have to integrate grid with cucumber. The default.cucumber report doesn't generate the complete report. It only captures the last execution.so I was thinking if there is a possibility of integrating extent reports with cucumber and grid.

**Comment by anshooarora** [comment]
You can configure Extent to work with Grid.

There are some users working with Extent + Cucumber, but I don't know how it is being used.  I haven't worked with Cucumber in a while - if it now provides an interface to extend and listen to events, it will be much easier.
