### ISSUE TITLE
Test description doesn't consider the br characters

### ISSUE THREAD

**Issue by petuk** [anshooarora/extentreports#188]
Version: 2.40
Browser: IE

ExtentTest test = extent.startTest("Test Name", testDesc);

- if the testDesc description contains <br> characters for new line, only the last test displays properly the test description the others removed the <br> and the description is shown only in one line.

**Comment by anshooarora** [comment]
Are you using `\n` or `<br />` for new line?

**Comment by petuk** [comment]
<'br />"

(sorry I added in the original comment, but it is disappeared due to format)

**Comment by anshooarora** [comment]
`<br />` works for me.

See the attached report below, I have used the following code:

```
test = extent.startTest("Extent", "A very basic step with a few <br />logs.");
test.log(LogStatus.PASS, "StepName", "Step <br />Info");
```

![br](https://cloud.githubusercontent.com/assets/4107384/11564700/2a03a4e4-99a0-11e5-8535-c047ee606b16.png) * rename file to .html

**Comment by petuk** [comment]
We are using this code:
extent = new ExtentReports("junitreport\\tmp\\" + "SeleniumReport.html", false);
extent.loadConfig(new File("src\\extent-config.xml"));
test = extent.startTest(fileName, testDesc);
dirName = dirName.replace(File.separatorChar,'.');
String className = fileName.substring(0, fileName.indexOf('_'));
test.assignCategory(dirName, className);

What is strange:
- it worked before in version 2.10
- before StartTest method writes to system output the testDesc contains the br chars
- the standard junit report shows properly the br chars

**Comment by anshooarora** [comment]
What is testDesc value?

You can wrap your code like this:  https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by petuk** [comment]
- We are running multiple test and only the last test displays properly (with br) the test description.
- we appended the test report with the new test
- if the tests contains the same testdesc, in this case also the last testdesc are displayed properly

This is the testDesc value:
```
Ok ksjdf lskdjf lskjf lksjf lskdfj lksjfdl ksjflkj sdljkf. lskjd fklsjdfl jsdflkj.
 LKjlkjsdflk jl.<br />
 During the test it: <br />
 - Searches for a dummy blabla <br />
17:24:37: Daniel EOETTEVENYI/URSS/HU: This test is a blabla test and will fail. <br />
 During the test: <br />
 - Failasd!f sdf sdff sdf sdfsd fsd fsdf
 sdf sdfe sdf sdf sdf <br />
 - Okkkk
```

**Comment by anshooarora** [comment]
I would need a test case to reproduce this as I am unable to.  I tried using linebreak in test-desc, logs etc. and it works.

**Comment by petuk** [comment]
we try to debug the code and we found this issue:
- we use the ExtentReports with append mode (replaceExisting = False)
- set desc1 in StartTest method
- set desc2 in StartTest method

when we set desc2 before calling the test.setDescription method with desc1 parameter. In this case the br character is removed from the string. That's why always the last desc contains the br character, because the setDescription is not called before.

So please test with the append mode or check with extentmerge function where also removed the br characters.
