### ISSUE TITLE
New Feature Request: Override "Warning" status to "Pass" throught out report and display indication

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#19]
Hi Anshoo,

Requesting you for following 
1. Should be able to override "Warning" status to "Pass" (chart,summary,details) but display indicator so warning status can be use for soft errors but overall test case status should be pass.
2. Would be nice if all numbers are in colors based on status 

Note: code you have provided is not overriding Chart status.

Attached screenshot.

Thanks 
Jawlit

**Comment by anshooarora** [comment]
Jawlit,  complete override is possible 2.02 onwards.  Simply use the new code:

```
extent.config().insertJs("$('.test.warning').each(function() { $(this).addClass('pass').removeClass('warning'); }); $('.test-status.warning').each(function() { $(this).addClass('pass').removeClass('warning').text('pass'); });$('.tests-quick-view .status.warning').each(function() { $(this).addClass('pass').removeClass('warning').text('PASS'); }); testSetChart(); ");
```

It should help you override the chart as well.. please let me know if it works.

**Comment by jawlitkp** [comment]
You are the best ,Working like a charm.

Adding indication is doable in next release ? I show indicator in sample report but it is not getting displayd

**Comment by anshooarora** [comment]
Great!

Btw, which indicator?

**Comment by anshooarora** [comment]
Not being able to see this indicator is a good thing. :)  It will only display if your test was not ended safely.  

There is a new method <code>close()</code> that you can call as the very last one, in your <code>AfterSuite</code>.  Once <code>close</code> is called, no further events will be possible so recommended to only use at the very end.  This method will find and dispose all tests that were ended abruptly and put the indicator next to them:

More info here:  http://extentreports.relevantcodes.com/2x/docs.html#close-extent

**Comment by jawlitkp** [comment]
Red small icon in my above comment

**Comment by jawlitkp** [comment]
So if there is any warning ,test case status should pass but small warning icon should ne display next to test case name

**Comment by anshooarora** [comment]
Actually.. no.  I received a lot of feedback where users are not developing their scripts in a stable manner.  This was causing their test being dropped, or it reporting an invalid status.  

So this method serves as a last resort in case something went wrong during execution.  It will still show the test with whatever info you provided preventing it from being dropped.

Sample code and scenario:

```
ExtentReports extent = new ExtentReports("file-path", true);
ExtentTest test = extent.startTest("Test");
test.log(LogStatus.ERROR, "ERROR");
// lets assume some error occured, user's code did not endTest correctly
// extent.endTest(test); was not called

// AfterSuite calls this:
extent.close();
```

If you see the report, there will be this indicator showing.

**Comment by jawlitkp** [comment]
Thanks Anshoo , I was trying to see if there is any way you can set up indication in warning color (yellow) that even thought test cases is passed there is is warning inside , same as you are setting up red indication for above issue , sorry for confusion

**Comment by anshooarora** [comment]
Ah,  I see,  sorry I misunderstood.  There is currently no way to add a warning because when you call <code>endTest</code> all warnings will automatically be reset.  

Although,  if you think this is a useful feature, we can add to the next release.

**Comment by jawlitkp** [comment]
Sure please , it will give hight level idea on what test case needs analysis for warnings.

Thanks much

**Comment by anshooarora** [comment]
Jawlit

This feature is now available.  You can add a warning to any test using:

```
test.getTest().internalWarning = "Warning";
```

**Comment by jawlitkp** [comment]
Just tested and it is working as i was expecting ,Thanks a lot Anshoo.

**Comment by anshooarora** [comment]
Can this issue be closed?

**Comment by jawlitkp** [comment]
Yes we can close this one, thanks

**Comment by RakiMohan** [comment]
Hi Anshoo,
 
Here for an extent test i have test steps with different status but the status of the last step is 'Pass' so I want to override the extent Test status to Pass. Is this possible?

![image](https://user-images.githubusercontent.com/20772735/44077778-b8d53572-9f72-11e8-9f04-57f34dc3f043.png)

Thank you for your support in advance.
-Rakesh
