### ISSUE TITLE
Test steps not shown correctly for category in  version 2.10

### ISSUE THREAD

**Issue by Madhavsri** [anshooarora/extentreports#191]
When categories are created total test shown in category is correct but the test steps is always shown as the total steps

**Comment by karthikbhatnagar** [comment]
Which view?

**Comment by Madhavsri** [comment]
In the test details when we do a filter based on category with dashboard enabled.
Then in the dash board the total test steps are always same for all categories selected
which is the Total test steps of all the Test cases run

**Comment by anshooarora** [comment]
This is by design.  I will add this as an ER in the next release.
