### ISSUE TITLE
com.relevantcodes.extentreports.Configuration <init> INFO: Configurating report from file:

### ISSUE THREAD

**Issue by SimpleNoob** [anshooarora/extentreports#192]
Hi, 

I have set up the extent reports 2.40 when I ran it first time it was okay. Second time it started to throw this error on the eclispe IDE .It seems that the test starts browser opens, load and then after that browser closes down and then error is generated. 
Am I missing something? Can you please take a look.
Thanks a lot in advance.

Log error from eclipse IDE from console.

About to begin executing RABase.BeforeClass
C://Users//Ak//Desktop//Eclispe_environment//Maven_Project//administrationReports//Adminitration.html

Dec 04, 2015 7:17:32 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/C:/Users/Downloads/extentreports-java-v2.40/extentreports-2.40.0/extentreports-java-2.40.0.jar!/com/relevantcodes/extentreports/resources/extent-config.xml

*************************************************
My Class:
*************************************************

public static class ExtentManager {
		 
		public static ExtentReports Instance()
		       {
		 
			ExtentReports report;
		 	
		 String Path = TestConstants.ExtentReportspath;
		 System.out.println(Path);
		 
		 report = new ExtentReports(Path, true ,DisplayOrder.NEWEST_FIRST);
		 report.loadConfig(new File("C:\\Users\\Downloads\\extentreports-java-v2.40\\extentreports-2.40.0\\extent-config.xml"));
		 
		 return report;
		    }
	}

****************************************************
My before class method where it is getting started defined in base class
********************************************************
      @BeforeClass
		 public void BeforeClass()
		{
		 
			report = ExtentManager.Instance();
		    
		    
		 }

*************************************************
Extra info.

package utility;

public interface TestConstants {
	  
public static final String ExtentReportspath = "C://Users//Ak//Desktop//Eclispe_environment//Maven_Project//administrationReports//Adminitration.html";

**Comment by karthikbhatnagar** [comment]
Where is the error?   that is standard log message with info status.

**Comment by SimpleNoob** [comment]
Hi, sorry for late reply. I missed out few things I was able to configure but whenever I run the case I face two issues given below.

- The report is not loading fully on firefox some content is missing.
- Whenever I run the report its not updated - its set to after method given below.


		@AfterMethod
		public void tearDown(ITestResult result) throws Exception
		{
		if(result.getStatus()==ITestResult.FAILURE)
		{

		String scrFile = Utils.takeScreenshot(driver,result.getName());
		String image= logger.addScreenCapture(scrFile);
		logger.log(LogStatus.FAIL, "Failure trace Selenium:" + result.getName(), image);

		}

		report.endTest(logger);
		report.flush();

**Comment by SimpleNoob** [comment]
Just an update the second issue i was able to fix now one remaining.

The report is not loading fully on firefox some content is missing.

Thank you so much.

**Comment by Madhavsri** [comment]
Hi SimpleNoob how did you fixed your first configuration issue where you were getting info message in the log.

**Comment by anshooarora** [comment]
The log is to inform that the standard config.xml was used.

What content is missing?  Does it work fine without using the config file?

**Comment by SimpleNoob** [comment]
Hey Madavsri/Anshooarora,

@Madavsri
-Yes I was able to fix the first configuration I simply removed the jar file,clean the project and then downloaded again by using maven it worked fine.
@Anshooarora
- I also tried to use by doing configuration outside of my Instance
method in the ExtentManager class. That worked well.

Thank you so much guys!
