### ISSUE TITLE
[question] - Is there a way we can log  the test execution time for respective categories ?

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports#193]
Let's say my tests are running on multiple threads ( Thread 1 and Thread 2 ) i would want to know the time the tests cases on Thread 1 have taken to execute and same with Thread 2 

Is there any way @anshooarora  and @virenv ?

**Comment by virenv** [comment]
@saikrishna321 Your ExtenTest object can give you this information

ExtentTest::getTest() will return you a test Object. On the test object we have getFormattedDateTime

so eventually it becomes
ExtentTest::getTest(). getFormattedDateTime()

**Comment by anshooarora** [comment]
@saikrishna321  -  can this ticket be closed?

**Comment by saikrishna321** [comment]
:+1:
