### ISSUE TITLE
Leveraging existing extentreports api to generate live report

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#194]
Hi Ansho,

Currently I am working on to generate live report for my company framework and basically i am writing test case current status to data base using testng listener methods ,is there any way i can utilize extent report api to generate report out of data base data.

Thanks

**Comment by anshooarora** [comment]
Are you using the db-reporter?  If yes, you can simply use ExtentMerge and it will create a report for you.

**Comment by jawlitkp** [comment]
what db-reporter are you talking ? does extentreport api has db-reporter ?,i have wrote my code to report in to db

**Comment by anshooarora** [comment]
See <a href='http://extentreports.relevantcodes.com/java/version2/docs.html#custom-reporter'>here</a>, usage:

```
extent.startReporter(ReporterType.DB, "/folder/extent.db");
```

**Comment by jawlitkp** [comment]
Okay thanks ,i will take a look,i am not sure if it'd write all results at end to db or during run time, my requirement is to log test case status after each test case completed so when ever i pull data from db i should have current status of all test cases, i have more than 500 test cases and i have to check execution status frequently during run time

**Comment by anshooarora** [comment]
You can just use `flush()` after each test for this, no?

**Comment by jawlitkp** [comment]
i never thought of it as of now ,i will start working on live reporting soon and try flush() method ,i will update you on soon.

Thanks for help
