### ISSUE TITLE
Can I still use config in code when moving to ver 2.40?

### ISSUE THREAD

**Issue by shaynl** [anshooarora/extentreports#195]
Hi Anshoo,
Now i'm using ver 2.10 and I need a dynamic config as follow: 
report.config()
                    .documentTitle(TestBase.testName)
                    .reportName(TestBase.suiteName)
                    .reportHeadline(TestBase.testName);

How to do the same in 2.40?

**Comment by anshooarora** [comment]
The only way 2.40 onward is with the config.xml.  `config()` is deprecated and will not utilize the above settings..

**Comment by anshooarora** [comment]
The only way is to dynamically update the xml file with your settings before loading it.  Note: you can load the config file any number of times.
