### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#198]
Hi, i am a new user in .Net and I want to know how to install ExtentReports 2.4 in my Visual Studio because I only appears as version 2.0.2 in Nuget Manager.

Thanks you!

PD: Sorry for my english.

**Comment by anshooarora** [comment]
I will soon make v2.40 available on nuget.  For now, you can download the package from extentreports.relevantcodes.com and manually add references to your project.

**Comment by MaxiTalenti** [comment]
Ok, thanks!

One more question, i have to import RazorEngine.dll, System.Web.Razor.dll and RelevantCode.ExtentReports.dll? And extent-config.html?.

Sorry for my low level of programming and english.
Thanks you!

**Comment by anshooarora** [comment]
Yes, all 3 DLLs.  No need to import extent-config.xml.  That is required if you want to perform any config against the report.  For more info, see here: <a href='http://extentreports.relevantcodes.com/net/docs.html#configuration'>link</a>.

**Comment by MaxiTalenti** [comment]
Thanks!!
