### ISSUE TITLE
Tests View is showing wrong graph

### ISSUE THREAD

**Issue by cybkishor** [anshooarora/extentreports#199]
Tests View is showing wrong graph , if you click on the pass , graph will turn to pass but never comes back to old value even if i remove filter from tests.
![image](https://cloud.githubusercontent.com/assets/4117481/11729578/fef9c0dc-9fb5-11e5-8cab-981559310872.png)

Original Graph:
![image](https://cloud.githubusercontent.com/assets/4117481/11729661/56056552-9fb6-11e5-8c54-a14cd935236c.png)

**Comment by anshooarora** [comment]
The graphs will toggle if the refresh functionality is enabled.

With filters:
![with-filters](https://cloud.githubusercontent.com/assets/4107384/11729829/f1e0b950-9f56-11e5-848c-3c3ecbc77bb8.png)


See change in graph, upon clear:
![clear-filters](https://cloud.githubusercontent.com/assets/4107384/11729787/b3ed879a-9f56-11e5-8b35-781957253460.png)

**Comment by cybkishor** [comment]
i tried , still it is not refreshing back

**Comment by anshooarora** [comment]
Are you doing this from dashboard view?  If yes, this was discovered in another ticket and will be fixed in the next release.

**Comment by anshooarora** [comment]
#223 - same issue.
