### ISSUE TITLE
How to initiate when using multiple suite files?

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#2]
testng.xml contains:
suite name="All Browsers" parallel="tests" thread-count="10"
  suite-files
    suite-file path="StoragePoolsWidgetAutomationTest.xml"
    suite-file path="SystemCapacityWidgetAutomationTest.xml"
  /suite-files
/suite

Each file initiates my test class (which extends a base class)

BeforeSuite is called 2 times in this situation.
BeforeClass is called 4 times since there are 2 browser <test> entries in each "suite-file" mentioned above.

[selenium:testng] About to begin executing Suite StoragePoolsWidgetAutomationTest @ 10:32:42:421
[selenium:testng] About to begin executing Suite SystemCapacityWidgetAutomationTest @ 10:32:42:421
[selenium:testng] About to begin executing Suite StoragePoolsWidgetAutomationTest @ 10:32:42:421
[selenium:testng] About to begin executing Suite SystemCapacityWidgetAutomationTest @ 10:32:42:421
[selenium:testng] Before Suite...
[selenium:testng] Before Suite...
[selenium:testng] Start executing test Chrome-WINDOWS-7 @ 10:32:42:433
[selenium:testng] Start executing test Chrome-WINDOWS-7 @ 10:32:42:433
[selenium:testng] Start executing test Firefox-WINDOWS-7 @ 10:32:42:434
[selenium:testng] Start executing test Firefox-WINDOWS-7 @ 10:32:42:434
[selenium:testng] Before Class...
[selenium:testng] Before Class...
[selenium:testng] Before Class...
[selenium:testng] Before Class...

Thoughts?

Thanks!

Chris

**Comment by relevantcodes** [comment]
Chris

So if I understood correctly, you want to use multiple processes/threads to write to a single file correct? 

Currently, only a single test can write to a file and concurrency is not supported.  I believe you can use this way to write to multiple files.. I haven't tried though.

It is a planned feature for 2.0 as there have been other request as well which will allow multiple concurrent tests to build a single report file.

Cheers 

Anshoo

**Comment by cktech529** [comment]
Thanks for the quick reply.

Yeah, I was hoping to run everything in parallel (suite contains say 20 suite files of 2-3 tests per file etc.) and have a SINGLE test-report.html dumped.

I thought about doing it 1 file per session, but then it's not really a report :)

Chris

**Comment by relevantcodes** [comment]
No ETA as of now, sorry.  I have started the initial code but not sure how long it will take to become stable.  Would surely need a beta tester though when its ready.  Thanks for the support.  Cheers.

**Comment by anshooarora** [comment]
Chris

Extent 2.0 alpha is now here.  It will support parallel execution support.   Sample here:  file:///C:/Users/Anshoo/Documents/workspace/Extentv2.html#!

I can share the library with you if you're willing to test.

**Comment by anshooarora** [comment]
Chris, I am closing this issue as support for parallel execution has been added in version 2.

**Comment by cktech529** [comment]
Just saw this,

Thanks!

I shall test it.

Chris
