### ISSUE TITLE
ExtentReports.log(...) not available in 2.x

### ISSUE THREAD

**Issue by texag93** [anshooarora/extentreports#20]
The doc show how to insert a screenshot by calling
extent.log(LogStatus.INFO, "Snapshot below: " + test.addScreenCapture("screenshot-path"));

However, that method is not available in ExtentReports in version 2.x.
http://extentreports.relevantcodes.com/2x/docs.html#insert-screenshots

This product looks awesome. I hope to use it soon!

Cheers,
Mike

**Comment by anshooarora** [comment]
Mike,  

If you are using version 2.0+, the method is available for ExtentTest instead of ExtentReports object.

![screencapture](https://cloud.githubusercontent.com/assets/4107384/8708103/a2c3b03c-2aff-11e5-91b3-3fec8c380a56.png)

Can you please check once again?

**Comment by anshooarora** [comment]
And you caught a bug in the documentation. :)

I've just corrected it.  The correct syntax should be:

```
test.log(LogStatus.INFO, test.addScreenCapture("screenshot-path"));
```

**Comment by texag93** [comment]
Thanks for the quick reply!
