### ISSUE TITLE
Error in Icon Status - ExtentMerge

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#200]
Hi, my problem is:

https://www.dropbox.com/s/2lvtivk5f8suhz9/Captura.PNG?dl=0

When in mi ExtentReports is:

https://www.dropbox.com/s/bryg0p78h0uyjf5/Captura2.PNG?dl=0

Te icon Status does not appear when in ExtentReports works ok.

Thanks you!

**Comment by anshooarora** [comment]
There have been some changes in Extent, but ExtentMerge has not been updated to work with those.  I will soon release a fix for this.

**Comment by anshooarora** [comment]
fix for this will be part of the next release.

**Comment by MaxiTalenti** [comment]
Thanks you! When published the new version?

**Comment by anshooarora** [comment]
I am closing this as ExtentMerge is deprecated.  ExtentX is the replacement and will be available soon.
