### ISSUE TITLE
replaceExisting in ExtentReports 2.4 [.NET]

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#201]
Hi, this option (replaceExisting) was removed? Because i need to add a test to another in the same file in different times, with 2.4 which replaces me the file.There solution to this? How could it?

Thanks you!.

**Comment by anshooarora** [comment]
This feature was removed because I am still working to find a stable way to read the existing file by parsing out all HTML.  There aren't many good libraries available in .NET do this sort of thing.  Let me know if you come across a good HTML parser, I would be glad to include this as an ER.

**Comment by MaxiTalenti** [comment]
This would serve you?

https://htmlagilitypack.codeplex.com

**Comment by karthikbhatnagar** [comment]
+1

**Comment by anshooarora** [comment]
Will test with this package and if it parses well, will include this ER in the next release.

**Comment by anshooarora** [comment]
Feel free to contribute towards this effort.  I will merge all pull requests.

**Comment by anshooarora** [comment]
You can download the latest .NET build from [here](http://extentreports.relevantcodes.com).  Nuget prerelease version ready: https://www.nuget.org/packages/ExtentReports/2.40.1-beta1.

**Comment by MaxiTalenti** [comment]
Thank you! I'll try and I'll testing. Regards.

**Comment by anshooarora** [comment]
Closing as this feature is included in 2.40.1-beta1.  If you find any issues with this functionality, please open a new defect.
