### ISSUE TITLE
Filter Categories [2.4] [.NET]

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#202]
Hi, The option of filtering does not work on test details and categories, in test details not display nothing, in categories, only displlay the thest in categorie 'others' when the categories test is different.

Sorry for my english.
Thanks you!

**Comment by anshooarora** [comment]
I just tested this and filters work for both status and categories in the Test view.  Am I missing something?

**Comment by MaxiTalenti** [comment]
In all these categories, clicking does not work.

https://www.dropbox.com/sh/7hzkr0pywclogyc/AAALxu0jiwwIXrdkqZw00PSma?dl=0

**Comment by karthikbhatnagar** [comment]
Hey MaxiTalenti

It works for me also. Can you show us steps to reproduce?

Anshoo: can we have option to add our class as category?

**Comment by anshooarora** [comment]
Are you still experiencing this issue?  I am unable to reproduce it.  Can you share a sample that I can use with the code you used?

**Comment by MaxiTalenti** [comment]
Monday I sent the html file

**Comment by MaxiTalenti** [comment]
This is the HTML
                                        <!DOCTYPE html>
                    <html>
                        <head>
                            
                            <meta http-equiv='content-type' content='text/html; charset=UTF-8;' /> 
                            <meta name='description' content='ExtentReports (by Anshoo Arora) is a reporting library for automation testing for .NET and Java. It creates detailed and beautiful HTML reports for modern browsers. ExtentReports shows test and step summary along with dashboards, system and environment details for quick analysis of your tests.' />
                            <meta name='robots' content='noodp, noydir' />
                            <meta name='viewport' content='width=device-width, initial-scale=1' />
                            <title>
Pruebas Karen                            </title>
                            <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css' type='text/css'>
                            <link href='https://cdn.rawgit.com/noelboss/featherlight/1.3.4/release/featherlight.min.css' type='text/css' rel='stylesheet' />
                            <link href='http://cdn.rawgit.com/anshooarora/extentreports/c52c8b4c4cf7853d658daeb1cb09207ed5a667c6/cdn/extent.css' type='text/css' rel='stylesheet' />

                            <style>
                            </style>
                        </head>
                        <body class='extent'>  
                            <nav>
                                <ul id='slide-out' class='side-nav fixed'>
                                    <li class='logo'>
                                        <a class='logo-content' href='http://extentreports.relevantcodes.com'><span>ExtentReports</span></a>
                                        <a class='menu-toggle right'><i class='mdi-navigation-menu'></i></a>
                                    </li> 
                                    <li class='analysis waves-effect active'><a href='#!' class='test-view'><i class='mdi-action-dashboard'></i>Test Details</a></li>
                                    <li class='analysis waves-effect'><a href='#!' class='categories-view'><i class='mdi-maps-local-offer'></i>Categories</a></li>
                                    <li class='analysis waves-effect'><a href='#!' class='dashboard-view'><i class='mdi-action-track-changes'></i></i>Analysis</a></li>
                                    <li class='analysis waves-effect'><a href='#!' class='testrunner-logs-view'><i class='mdi-action-assignment'></i>TestRunner Logs</a></li>
                                </ul>
                                <a href='#' data-activates='slide-out' class='button-collapse'><i class='mdi-navigation-menu'></i></a>
                                <span class='report-name'>Emision poliza</span> <span class='report-headline'></span>
                                <ul class='right hide-on-med-and-down nav-right'>
                                    <li class='theme-selector' alt='Click to toggle dark theme. To enable by default, use js configuration $(".theme-selector").click();' title='Click to toggle dark theme. To enable by default, use js configuration $(".theme-selector").click();'>
                                        <i class='mdi-hardware-desktop-windows'></i>
                                    </li>
                                    <li>
                                        <span class='suite-started-time'>2015-12-14 15:23:05</span>
                                    </li>
                                    <li>
                                        <span>v2.40.0</span>
                                    </li>
                                </ul>
                            </nav>
                            <div class='container'>
                                <div id='dashboard-view' class='row'>
                                    <div class='time-totals'>
                                        <div class='col l2 m4 s6'>
                                            <div class='card suite-total-tests'> 
                                                <span class='panel-name'>Total Tests</span> 
                                                <span class='total-tests'> <span class='panel-lead'></span> </span> 
                                            </div> 
                                        </div>
                                        <div class='col l2 m4 s6'>
                                            <div class='card suite-total-steps'> 
                                                <span class='panel-name'>Total Steps</span> 
                                                <span class='total-steps'> <span class='panel-lead'></span> </span> 
                                            </div> 
                                        </div>
                                        <div class='col l4 m4 s12'>
                                            <div class='card suite-total-steps'> 
                                                <span class='panel-name'>Total Time Taken</span> 
                                                <span class='suite-total-time-taken panel-lead'>0h 0m 52s+18ms</span> 
                                            </div> 
                                        </div>
                                        <div class='col l2 m6 s6 suite-start-time'>
                                            <div class='card green-accent'> 
                                                <span class='panel-name'>Start</span> 
                                                <span class='panel-lead suite-started-time'>2015-12-14 15:23:05</span> 
                                            </div> 
                                        </div>
                                        <div class='col l2 m6 s6 suite-end-time'>
                                            <div class='card pink-accent'> 
                                                <span class='panel-name'>End</span> 
                                                <span class='panel-lead suite-ended-time'>2015-12-14 15:23:57</span> 
                                            </div> 
                                        </div>
                                    </div>
                                    <div class='charts'>
                                        <div class='col s12 m6 l4 fh'> 
                                            <div class='card-panel'> 
                                                <div>
                                                    <span class='panel-name'>Tests View</span>
                                                </div> 
                                                <div class='panel-setting modal-trigger test-count-setting right'>
                                                    <a href='#test-count-setting'><i class='mdi-navigation-more-vert text-md'></i></a>
                                                </div> 
                                                <div class='chart-box'>
                                                    <canvas class='text-centered' id='test-analysis'></canvas>
                                                </div> 
                                                <div>
                                                    <span class='weight-light'><span class='t-pass-count weight-normal'></span> test(s) passed</span>
                                                </div> 
                                                <div>
                                                    <span class='weight-light'><span class='t-fail-count weight-normal'></span> test(s) failed, <span class='t-others-count weight-normal'></span> others</span>
                                                </div> 
                                            </div> 
                                        </div> 
                                        <div class='col s12 m6 l4 fh'> 
                                            <div class='card-panel'> 
                                                <div>
                                                    <span class='panel-name'>Steps View</span>
                                                </div> 
                                                <div class='panel-setting modal-trigger step-status-filter right'>
                                                    <a href='#step-status-filter'><i class='mdi-navigation-more-vert text-md'></i></a>
                                                </div> 
                                                <div class='chart-box'>
                                                    <canvas class='text-centered' id='step-analysis'></canvas>
                                                </div> 
                                                <div>
                                                    <span class='weight-light'><span class='s-pass-count weight-normal'></span> step(s) passed</span>
                                                </div> 
                                                <div>
                                                    <span class='weight-light'><span class='s-fail-count weight-normal'></span> step(s) failed, <span class='s-others-count weight-normal'></span> others</span>
                                                </div> 
                                            </div> 
                                        </div>
                                        <div class='col s12 m12 l4 fh'> 
                                            <div class='card-panel'> 
                                                <span class='panel-name'>Pass Percentage</span> 
                                                <span class='pass-percentage panel-lead'></span> 
                                                <div class='progress light-blue lighten-3'> 
                                                    <div class='determinate light-blue'></div> 
                                                </div> 
                                            </div> 
                                        </div>
                                    </div>
                                    <div class='system-view'>
                                        <div class='col l4 m12 s12'>
                                            <div class='card-panel'>
                                                <span class='label info right'>Environment</span>
                                                <table>
                                                    <thead>
                                                        <tr>
                                                            <th>Param</th>
                                                            <th>Value</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                            <tr>
                                                                <td>User Name</td>
                                                                <td>mtalenti</td>
                                                            </tr>
                                                            <tr>
                                                                <td>Machine Name</td>
                                                                <td>PS0049</td>
                                                            </tr>
                                                            <tr>
                                                                <td>Domain</td>
                                                                <td>SANCORSEG</td>
                                                            </tr>
                                                            <tr>
                                                                <td>OS</td>
                                                                <td>Win32NT 6.1.7601.65536</td>
                                                            </tr>
                                                            <tr>
                                                                <td>Selenium Version</td>
                                                                <td>2.4.2</td>
                                                            </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='category-summary-view'>
                                        <div class='col l4 m6 s12'>
                                            <div class='card-panel'>
                                                <span class='label info right'>Categories</span>
                                                <table>
                                                    <thead>
                                                        <tr>
                                                            <th>Name</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                                <tr>
                                                                    <td>Pruebas Karen</td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Mozilla Firefox</td>
                                                                </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id='test-view' class='row'>
                                    <div class='col s5'>
                                        <div class='card-panel heading'>
                                            <h5>Tests</h5>
                                        </div>
                                        <div class='card-panel filters'>
                                            <div>
                                                <a data-activates='tests-toggle' data-constrainwidth='true' data-beloworigin='true' data-hover='true' href='#' class='dropdown-button button'><i class='mdi-action-subject icon'></i></a>
                                                <ul id='tests-toggle' class='dropdown-content'>
                                                    <li class='pass'><a href='#!'>Pass</a></li>
                                                    <li class='fail'><a href='#!'>Fail</a></li>
                                                                                                                                                            <li class='skip'><a href='#!'>Skip</a></li>
                                                    <li class='divider'></li>
                                                    <li class='clear'><a href='#!'>Clear Filters</a></li>
                                                </ul>
                                            </div>                                            
                                            <div>
                                                <a data-activates='category-toggle' data-constrainwidth='false' data-beloworigin='true' data-hover='true' href='#' class='category-toggle dropdown-button button'><i class='mdi-image-style icon'></i></a>
                                                <ul id='category-toggle' class='dropdown-content'>
                                                    <li class='divider'></li>
                                                            <li class='Pruebas Karen'><a href='#!'>Pruebas Karen</a></li>
                                                            <li class='Mozilla Firefox'><a href='#!'>Mozilla Firefox</a></li>
                                                    <li class='clear'><a href='#!'>Clear Filters</a></li>
                                                </ul>
                                            </div>
                                            <div>
                                                <a id='clear-filters' alt='Clear Filters' title='Clear Filters'><i class='mdi-navigation-close icon'></i></a>
                                            </div>
                                            <div>&nbsp;&middot;&nbsp;</div>
                                            <div>
                                                <a id='enableDashboard' alt='Enable Dashboard' title='Enable Dashboard'><i class='mdi-action-track-changes icon'></i></a>
                                            </div> 
                                            <div>
                                                <a id='refreshCharts' alt='Refresh Charts on Filter' title='Refresh Charts on Filter' class='enabled'><i class='mdi-navigation-refresh icon'></i></i></a>
                                            </div>
                                            <div>&nbsp;&middot;</div>
                                            <div class='search' alt='Search tests' title='Search tests'>
                                                <div class='input-field left'>
                                                    <input id='searchTests' type='text' class='validate' placeholder='Search tests...'>
                                                </div>
                                                <i class='mdi-action-search icon'></i>
                                            </div>
                                        </div>

                                        <div class='card-panel no-padding-h no-padding-v vh100'>
                                            <div class='wrapper'>
                                                <ul id='test-collection' class='test-collection'>
                                                        <li class='collection-item test displayed active fail ' extentid='74aa0d89-23ca-4a91-afc3-4372b662557d'>
                                                            <div class='test-head'>
                                                                <span class='test-name'>Emision poliza </span>
                                                                <span class='test-status right label capitalize outline fail'>fail</span>
                                                                <span class='category-assigned hide  pruebas karen mozilla firefox'></span>
                                                            </div>
                                                            <div class='test-body'>
                                                                <div class='test-info'>
                                                                    <span title='Test started time' class='test-started-time label green lighten-2 text-white'>2015-12-14 15:23:06</span>
                                                                    <span title='Test ended time' class='test-ended-time label red lighten-2 text-white'>2015-12-14 15:23:49</span>
                                                                    <span title='Time taken to finish' class='test-time-taken label blue-grey lighten-3 text-white'>0h 0m 43s+313ms</span>
                                                                </div>
                                                                <div class='test-desc'>Caso de prueba para una emisión de póliza</div>
                                                                <div class='test-attributes'>
                                                                        <div class='categories'>
                                                                            <span class='category'>Pruebas Karen</span>
                                                                            <span class='category'>Mozilla Firefox</span>
                                                                        </div>
                                                                                                                                            <div class='authors'>
                                                                            <span class='author'>SANCORSEG\mtalenti</span>
                                                                        </div>
                                                                </div>
                                                                <div class='test-steps'>
                                                                        <table class='bordered table-results'>
                                                                            <thead>
                                                                                <tr>
                                                                                    <th>Status</th>
                                                                                    <th>Timestamp</th>
                                                                                    <th>Details</th>
                                                                                </tr>
                                                                            </thead>
                                                                            <tbody>
                                                                                    <tr>
                                                                                        <td class='status pass'><i class='mdi-action-check-circle'></i></td><td class='timestamp'>15:23:10</td>                                                                                        <td class='step-details'>Acceso a URL</td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td class='status pass'><i class='mdi-action-check-circle'></i></td><td class='timestamp'>15:23:12</td>                                                                                        <td class='step-details'>Click</td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td class='status pass'><i class='mdi-action-check-circle'></i></td><td class='timestamp'>15:23:13</td>                                                                                        <td class='step-details'>Click</td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td class='status pass'><i class='mdi-action-check-circle'></i></td><td class='timestamp'>15:23:14</td>                                                                                        <td class='step-details'>Click</td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td class='status pass'><i class='mdi-action-check-circle'></i></td><td class='timestamp'>15:23:15</td>                                                                                        <td class='step-details'>Click</td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td class='status pass'><i class='mdi-action-check-circle'></i></td><td class='timestamp'>15:23:19</td>                                                                                        <td class='step-details'>...</td>
                                                                                    </tr>
                                                                                    <tr>
                                                                                        <td class='status fail'><i class='mdi-navigation-cancel'></i></td><td class='timestamp'>15:23:49</td>                                                                                        <td class='step-details'>Click ...<img class='report-img' data-featherlight='file:///...' src='file://path' /></td>
                                                                                    </tr>
                                                                            </tbody>
                                                                        </table>
                                                                                                                                    </div>
                                                            </div>
                                                        </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div id='test-details-wrapper' class='col s7'>
                                        <div class='card-panel vh100 details-view pin'>
                                            <h5 class='details-name'></h5>
                                            <div class='details-container'>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id='categories-view' class='row hide'>
                                    <div class='col s5'>
                                        <div class='card-panel heading'>
                                            <h5>Categories</h5>
                                        </div>
                                        <div class='card-panel filters'>
                                            <div class='search' alt='Search tests' title='Search tests'>
                                                <div class='input-field left'>
                                                    <input id='searchTests' type='text' class='validate' placeholder='Search tests...'>
                                                </div>
                                                <i class='mdi-action-search icon'></i>
                                            </div>
                                        </div>
                                        <div class='card-panel no-padding-h no-padding-v vh100'>
                                            <div class='wrapper'>
                                                <ul id='cat-collection' class='cat-collection'>
                                                            <li class='category-item displayed pruebas karen'>
				                                                <div class='cat-head'>
					                                                <span class='category-name'>Pruebas Karen</span>
				                                                </div>
				                                                <div class='category-status-counts'>
                                                                    					                                                    <span class='fail label dot'>Fail: 1</span>
                                                                    				                                                </div>
				                                                <div class='cat-body'>
					                                                <div class='category-status-counts'>
						                                                <div class='button-group'>
                                                                            <a href='#!' class='pass label filter'>Pass <span class='icon'>0</span></a>
                                                                            <a href='#!' class='fail label filter'>Fail <span class='icon'>1</span></a>
                                                                            <a href='#!' class='other label filter'>Others <span class='icon'>0</span></a>
                                                                        </div>
					                                                </div>
					                                                <div class='cat-tests'>
						                                                <table class='bordered'>
							                                                <thead>
								                                                <tr>
									                                                <th>Run Date</th>
									                                                <th>Test Name</th>
									                                                <th>Status</th>
								                                                </tr>
							                                                </thead>
                                                                            <tbody>
                                                                                    <tr>
                                                                                        <td>2015-12-14 15:23:06</td>
                                                                                        <td><span class='category-link linked' extentid='74aa0d89-23ca-4a91-afc3-4372b662557d'>Emision poliza</span></td>
                                                                                        <td><div class='status label outline capitalize fail'>Fail</div></td>
                                                                                    </tr>
                                                                            </tbody>
						                                                </table>
					                                                </div>
				                                                </div>
			                                                </li>
                                                            <li class='category-item displayed mozilla firefox'>
				                                                <div class='cat-head'>
					                                                <span class='category-name'>Mozilla Firefox</span>
				                                                </div>
				                                                <div class='category-status-counts'>
                                                                    					                                                    <span class='fail label dot'>Fail: 1</span>
                                                                    				                                                </div>
				                                                <div class='cat-body'>
					                                                <div class='category-status-counts'>
						                                                <div class='button-group'>
                                                                            <a href='#!' class='pass label filter'>Pass <span class='icon'>0</span></a>
                                                                            <a href='#!' class='fail label filter'>Fail <span class='icon'>1</span></a>
                                                                            <a href='#!' class='other label filter'>Others <span class='icon'>0</span></a>
                                                                        </div>
					                                                </div>
					                                                <div class='cat-tests'>
						                                                <table class='bordered'>
							                                                <thead>
								                                                <tr>
									                                                <th>Run Date</th>
									                                                <th>Test Name</th>
									                                                <th>Status</th>
								                                                </tr>
							                                                </thead>
                                                                            <tbody>
                                                                                    <tr>
                                                                                        <td>2015-12-14 15:23:06</td>
                                                                                        <td><span class='category-link linked' extentid='74aa0d89-23ca-4a91-afc3-4372b662557d'>Emision poliza</span></td>
                                                                                        <td><div class='status label outline capitalize fail'>Fail</div></td>
                                                                                    </tr>
                                                                            </tbody>
						                                                </table>
					                                                </div>
				                                                </div>
			                                                </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div id='cat-details-wrapper' class='col s7'>
                                        <div class='card-panel vh100 details-view pin'>
                                            <h5 class='cat-name'></h5>
                                            <div class='cat-container'>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id='testrunner-logs-view' class='row hide'>
                                    <div class='col s12'>
                                        <div class='card-panel'>
                                            <h5>TestRunner Logs</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id='test-count-setting' class='modal bottom-sheet'> 
                                <div class='modal-content'> 
                                    <h5>Configure Tests Count Setting</h5> 
                                    <input name='test-count-setting' type='radio' id='parentWithoutNodes' class='with-gap'> 
                                    <label for='parentWithoutNodes'>Parent Tests Only (Does not include child nodes in counts)</label> 
                                    <br> 
                                    <input name='test-count-setting' type='radio' id='parentWithoutNodesAndNodes' class='with-gap'> 
                                    <label for='parentWithoutNodesAndNodes'>Parent Tests Without Child Tests + Child Tests</label> 
                                    <br> 
                                    <input name='test-count-setting' type='radio' id='childNodes' class='with-gap'> 
                                    <label for='childNodes'>Child Tests Only</label> 
                                </div> 
                                <div class='modal-footer'> 
                                    <a href='#!' class='modal-action modal-close waves-effect waves-green btn'>Save</a> 
                                </div> 
                            </div> 
                            <div id='step-status-filter' class='modal bottom-sheet'> 
                                <div class='modal-content'> 
                                    <h5>Select status</h5> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-pass'> 
                                    <label for='step-dashboard-filter-pass'>Pass</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-fail'> 
                                    <label for='step-dashboard-filter-fail'>Fail</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-fatal'> 
                                    <label for='step-dashboard-filter-fatal'>Fatal</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-error'> 
                                    <label for='step-dashboard-filter-error'>Error</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-warning'> 
                                    <label for='step-dashboard-filter-warning'>Warning</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-skip'> 
                                    <label for='step-dashboard-filter-skip'>Skipped</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-info'> 
                                    <label for='step-dashboard-filter-info'>Info</label> 
                                    <br> 
                                    <input checked class='filled-in' type='checkbox' id='step-dashboard-filter-unknown'> 
                                    <label for='step-dashboard-filter-unknown'>Unknown</label> 
                                </div> 
                                <div class='modal-footer'> 
                                    <a href='#!' class='modal-action modal-close waves-effect waves-green btn'>Save</a> 
                                </div> 
                            </div>
                            <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'></script> 
                            <script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/js/materialize.min.js'></script>
                            <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>
                            <script src='https://cdn.rawgit.com/noelboss/featherlight/1.3.4/release/featherlight.min.js' type='text/javascript' charset='utf-8'></script>
                            <script src='http://cdn.rawgit.com/anshooarora/extentreports/005d99e2f2716f6d749c77c65b57ca3c632c35a8/cdn/extent.js' type='text/javascript'></script>

                            <script>$(document).ready(function() { $('.logo span').html('ExtentReports'); });</script>
                            <script>
                $(document).ready(function() {
                });
            </script>
                            
                        </body>
                    </html>

**Comment by MaxiTalenti** [comment]
I could find the error:

If i write:

test.AssignCategory("Category1");
test.AssignCategory("Category2");

category filtering works well

But if i write:

String Var = "Category1";

test.AssignCategory(Var);

Category filter does not work.

I step html example, change it from .txt to .html and watch it

[Reporte.txt](https://github.com/anshooarora/extentreports/files/68484/Reporte.txt)

**Comment by anshooarora** [comment]
That helped me reproduce.  The issue is due to spaces - use the following categories and it will work - i will fix it in the next release.

`
PruebasKaren
GoogleChrome
`
