### ISSUE TITLE
Broken image screenshot on report

### ISSUE THREAD

**Issue by karenpetrie** [anshooarora/extentreports#203]
When the report is generated, the screenshot image is broken and doesn't display the image.
Also, when the screenshot is saved, it is saving as a file but the image format is not being assigned.
I've tried different image formats and have also tried changing the location to save the file to "./testimage"

ITakesScreenshot screenshotDriver = driver as ITakesScreenshot;
                Screenshot screenshot = screenshotDriver.GetScreenshot();
                screenshot.SaveAsFile("C:\\Users\\XXX\\Documents\\Selenium\\Screenshots\\testimage", ImageFormat.Jpeg);

                test.Log(LogStatus.Info, "Snapshot below: " + test.AddScreenCapture("C:\\Users\\XXX\\Documents\\Selenium\\Screenshots\\testimage.jpg"));

**Comment by anshooarora** [comment]
Does the image display correctly viewed manually?  Its only shows broken in the report file?

**Comment by karenpetrie** [comment]
No, the image format doesn't get assigned. The type is just 'file' which means the report shows it as broken

**Comment by anshooarora** [comment]
So this would be a Selenium/capture-functionality issue?

**Comment by karenpetrie** [comment]
Managed to sort this, thanks
