### ISSUE TITLE
extent-config.xml is not loading

### ISSUE THREAD

**Issue by cybkishor** [anshooarora/extentreports#204]
INFO: Configurating report from file:/C:/Users/knaik/Desktop/Audit/extentreports-java-v2.40/extentreports-2.40.0/extentreports-java-2.40.0.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
Dec 12, 2015 4:29:41 AM com.relevantcodes.extentreports.ExtentReports loadConfig
WARNING: Unable to perform report configuration. The package or file com\relevantcodes\extentreports\resources\D:\New_Framework\NewSeleniumDemo\extent-config.xml was not found.

**Comment by cybkishor** [comment]
public class ReportTest {	
	ExtentReports report;
	ExtentTest extentre;
	WebDriver driver;
	
@BeforeSuite
public void beforeSuite()
{
	report = new ExtentReports("D:\\ExtentReport\\Report.html", true );	
	report.loadConfig(ExtentReports.class, "resources","D:\\New_Framework\\NewSeleniumDemo\\extent-config.xml");
	driver = new FirefoxDriver();
}

**Comment by anshooarora** [comment]
Just do:

```
report.loadConfig(new File("D:\New_Framework\NewSeleniumDemo\extent-config.xml");
```

The one you are using is a relative loader and your usage is incorrect.

**Comment by cybkishor** [comment]
it worked , thanks.
