### ISSUE TITLE
Style sheets link change to https

### ISSUE THREAD

**Issue by subratkumarmandal** [anshooarora/extentreports#205]
Hi ,

Can the link 
'http://cdn.rawgit.com/anshooarora/extentreports/c52c8b4c4cf7853d658daeb1cb09207ed5a667c6/cdn/extent.css' type='text/css' rel='stylesheet' can be made access through https as our company have recently blocked all http calls through the environment when reports are hosted hence the report generated in malformed.

Let me know if I can change it to access through https instead of http ?

Thanks

**Comment by anshooarora** [comment]
It is possible using js.  See here:  http://stackoverflow.com/questions/11833759/add-stylesheet-to-head-using-javascript-in-body

You can embed your js under `scripts` tag of config file. See <a href='http://extentreports.relevantcodes.com/java/version2/docs.html#configuration'>here</a>.

**Comment by subratkumarmandal** [comment]
Since our server only allows https request to be served i get following error : mixed content the page at was loaded over https but requested an insecure stylesheet hence can you make href='http://cdn.rawgit.com/anshooarora/extentreports/c52c8b4c4cf7853d658daeb1cb09207ed5a667c6/cdn/extent.css' type='text/css' rel='stylesheet' />  call in html head being served from https instead of http and one more call <script src='http://cdn.rawgit.com/anshooarora/extentreports/005d99e2f2716f6d749c77c65b57ca3c632c35a8/cdn/extent.js' type='text/javascript'></script> into https.

**Comment by anshooarora** [comment]
You can try this by placing it in the `script` tag of config and loading the config file using `loadConfig`:

```
$('script').each(function() {
  if (this.src.indexOf('http:') >= 0) {
    this.src = this.src.replace('http', 'https');
  }
});
```

If this doesn't work, you will have to wait until the next version or rebuilding the template file and compiling the jar manually.

**Comment by subratkumarmandal** [comment]
Neither of above solution worked hence we have reverted back to 2.10(where all calls to css and scripts are https) please let me know when will be the next upgraded version released so that we use latest version of Extent reports.

**Comment by anshooarora** [comment]
You can try with the latest version.  All resources are `https` by default.

Direct download: [here](http://extentreports.relevantcodes.com/)

```
<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>2.40.1-SNAPSHOT</version>
</dependency>
```
