### ISSUE TITLE
How to store reports in DB

### ISSUE THREAD

**Issue by cybkishor** [anshooarora/extentreports#207]
// optional - to store all results in a database
        extent.startReporter(ReporterType.DB, "extent.db");

What is extent.db here ..can some one give example

**Comment by anshooarora** [comment]
You can use a database if you want to centralize multiple runs into a single db.  Example:

```
extent.startReporter(ReporterType.DB, "C:/extent.db");
```

Note:  it is recommended that you use a single db for your runs, even though you are creating different HTML files.  You can use the db to merge your reports using ExtentMerge.
