### ISSUE TITLE
How to add image (Logo) to the extent Report - 2.4

### ISSUE THREAD

**Issue by cybkishor** [anshooarora/extentreports#209]
How to add image (Logo) to the extent Report - 2.4

**Comment by cybkishor** [comment]
i wanted to add the company logo to the report, please guide me.

**Comment by cybkishor** [comment]
Please suggest

**Comment by anshooarora** [comment]
You can use `js` in your config file to load the image and use `styles` to make it fit inside the headline area.

**Comment by cybkishor** [comment]
Still i am not able to see the image , can you please pass the sample code
here , i have a demo tomorrow ..

On Tue, Dec 15, 2015 at 9:36 PM, Anshoo Arora <notifications@github.com>
wrote:

> You can use js in your config file to load the image and use styles to
> make it fit inside the headline area.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/209#issuecomment-164809490>
> .
>



-- 
Regards,
Kishorkumar Naik

**Comment by cybkishor** [comment]
i can see this

(#54) New feature request - User should have the option to add the Product
Logo into extent report

Please suggest how to do this.

On Wed, Dec 16, 2015 at 4:16 AM, Kishor Naik <cybkishor@gmail.com> wrote:

> Still i am not able to see the image , can you please pass the sample code
> here , i have a demo tomorrow ..
>
> On Tue, Dec 15, 2015 at 9:36 PM, Anshoo Arora <notifications@github.com>
> wrote:
>
>> You can use js in your config file to load the image and use styles to
>> make it fit inside the headline area.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/anshooarora/extentreports/issues/209#issuecomment-164809490>
>> .
>>
>
>
>
> --
> Regards,
> Kishorkumar Naik
>



-- 
Regards,
Kishorkumar Naik

**Comment by cybkishor** [comment]
String css = ".report-name { padding-left: 10px; } .report-name > img { float: left;height: 90%;margin-left: 30px;margin-top: 2px;width: auto; }";

extent.config()
    .reportName("<img src='pathToImg.png' />")
    .insertCustomStyles(css);

this does not work in 2.4

**Comment by anshooarora** [comment]
That is for the older versions.. but with 2.40, you can use the css string and paste it (without quotes) under the `styles` tag of configuration file.  In the `reportName' tag, add path of your image:

```

<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
        <!-- document encoding -->
        <encoding>UTF-8</encoding>
        
        <!-- title of the document -->
        <documentTitle>Custom</documentTitle>
        
        <!-- report name - displayed at top-nav -->
        <reportName>
            <![CDATA[
                <img src='your-image-path' />
            ]]>
        </reportName>
        
        <!-- report headline - displayed at top-nav, after reportHeadline -->
        <reportHeadline></reportHeadline>
        
        <!-- custom javascript -->
        <scripts>
            <![CDATA[
                $(document).ready(function() {

                });
            ]]>
        </scripts>
        
        <!-- custom styles -->
        <styles>
            <![CDATA[
                .report-name { padding-left: 10px; } .report-name > img { float: left;height: 90%;margin-left: 30px;margin-top: 2px;width: auto; }
            ]]>
        </styles>
    </configuration>
</extentreports>
```

**Comment by Novatu** [comment]
Hi anshoo ,

i used your above js code but still i couldnt see my logo in report .

please find the below xml file 


<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
    	
    	
    	<theme>standard</theme>
    
		
		
		<encoding>UTF-8</encoding>
		
		
		
		<protocol>https</protocol>
		
        
        <documentTitle>RAFT_Report 2.0</documentTitle>
        
        
        <reportName>
		
		<![CDATA[
                <img src='E:\Project\jar\Image for sites\New folder\RAFT-1.png' />
            ]]>
		</reportName>
        
        
        <reportHeadline>Talent Recruit</reportHeadline>
        
        
        
        <dateFormat>yyyy-MM-dd</dateFormat>
        
        
        
        <timeFormat>HH:mm:ss</timeFormat>
        
        
        <scripts>
            <![CDATA[
                $(document).ready(function() {
                $("body").addClass("dark");
                });
            ]]>
        </scripts>
        
        
        <styles>
            <![CDATA[
             .report-name { padding-left: 10px; } .report-name > img { float: left;height: 90%;margin-left: 30px;margin-top: 2px;width: auto; } 
            ]]>
        </styles>
    </configuration>
</extentreports>

**Comment by Novatu** [comment]
And also i want to make the black Background as a default for my report .
 
I used the above code but its not reflecting in output.

Could you please help me in these both issues.

**Comment by savvyaxnjxn** [comment]
@Novatu - I also like the 'dark' background as my default.  I use an extent.xml config file as described here:

#524 and #541 

Other report config options are available if you search around or follow those links much as you appear to have already used in your own posted example although I don't have anything to help you with concerning your logo at this time - good luck!

**Comment by RDNShakya** [comment]
Hello Anshoo,

How can  I add a logo (an image) to extend report version 3.0.2 ???

Thank you!

**Comment by anshooarora** [comment]
Yes, depending on where you want to place it, you can:

* add the image tag in the relevant configuration (reportName)
* use JS and CSS to add and format the image

**Comment by hemmarkit14** [comment]
Hi Anshoo,

I am not able to add company logo , have added js and image tag

Please find the below xml file

<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
  <configuration>
    
    
    <theme>dark</theme>
  
    
    
    <encoding>UTF-8</encoding>
    
    
    
    <protocol>https</protocol>
    
    
    <documentTitle>Sample CATS ExtentReports </documentTitle>
    
    
    <reportName>
		<image id="image-zoom">
			<![CDATA[	
			<img src='C:\CATS\logo.png'/>
			]]>
		</image>
		
    </reportName>
    
    
    <reportHeadline>CATS TEST AUTOMATION</reportHeadline>
    
    
    
    <dateFormat>yyyy-MM-dd</dateFormat>
    
    
    
    <timeFormat>HH:mm:ss</timeFormat>
    
    
    <scripts>
      <![CDATA[
        $(document).ready(function() {
          $("#image-zoom").src("src",src);
		  $("#image-zoom").append("src",src);
        });
      ]]>
    </scripts>
    
    
    <styles>
       <![CDATA[
                .report-name { padding-left: 120px; } .report-name > img { float: left;height: 90%;margin-left: 120px;margin-top: 2px;width: auto; }
            ]]>
    </styles>
  </configuration>
</extentreports>

Please tell what else need's to be done

**Comment by dsathishupm** [comment]
HI ALL, here the code to hide and showing some text instead of ExtendReport link,


add ur config file..

 <scripts> <![CDATA[ $(document).ready(function() { $(".logo-content").hide(); $(".logo-container").html("SATHISH" ); }); ]]> </scripts>

**Comment by nirmalapsn214** [comment]
Hi Satish,
The above response is quite interesting. Thank you! I have a requirement where the dashboard alone should be copy pasted into email body or attached to email and save the entire report along with screenshots to a network shared folder and provide that link in the email body. 

I don't find a way to hide the log part or generate dashboard and logs separately. Could you please throw some light if you have any relevant info?
