### ISSUE TITLE
Question about adding screen captures and screen casts

### ISSUE THREAD

**Issue by texag93** [anshooarora/extentreports#21]
I initially thought the [test.addScreenCapture(...)](http://extentreports.relevantcodes.com/2x/docs.html#insert-screenshots) method would take the screen shot and add it to the report. However, it looks like it simply adds the path of the screen shot to the report. Taking the screen shot must be done programmatically. Is the code below the right approach? If so, what would be a good approach for using the [test.addScreencast(...)](http://extentreports.relevantcodes.com/2x/docs.html#insert-screencast)?

    test.log(LogStatus.INFO, "Snapshot below: " + test.addScreenCapture(takeScreenshot("./beforeLogin")));

    protected String takeScreenshot(String name) {
        String path = "./screenshots/" + name + ".png";
        try {
            File screenshotFile = ((TakesScreenshot) getDriver()).getScreenshotAs(OutputType.FILE);
            FileUtils.copyFile(screenshotFile, new File(path));
        } catch (Exception e) {
            LOG.log(Level.SEVERE, e.getMessage(), e);
        }
        return path;
    }

**Comment by anshooarora** [comment]
From:  http://extentreports.relevantcodes.com/2x/docs.html#insert-screenshots

```This method returns the HTML with <img> tag which can be used anywhere in the log details. Calling addScreenCapture will also add the image to the ImageCollectionView from where you can see all images used by your tests.```

It will return the HTML that you can place anywhere in your report while calling log().  Once this method is called, the path of the image is added to the ImagesCollections:

![media](https://cloud.githubusercontent.com/assets/4107384/8727475/8bccb436-2ba5-11e5-90fc-941e85107578.png)

Your code should be (I have removed the ./ in beforeLogin):

```
test.log(LogStatus.INFO, "Snapshot below: " + test.addScreenCapture(takeScreenshot("beforeLogin")));
```

**Comment by chaluvarajups** [comment]
Can we create an hyperlink for  image..?

**Comment by chaluvarajups** [comment]
Also, blank screen is displaying to me,have I missed something..?

**Comment by poojagadekar89** [comment]
Anyone got solution?
