### ISSUE TITLE
error  Loading template for "Extent.ft

### ISSUE THREAD

**Issue by williamrussellajb** [anshooarora/extentreports#210]
I have written a framework and  added ExtentReport as a listener for Selenium logs. 
This error randomly shows up, Im not sure where it's coming from. 

2015-12-15 11:22:13 DEBUG cache:45 - Loading template for "Extent.ftl"("en_US", UTF-8, parsed) from "jar:file:/C:/Users/jyothi_p/.m2/repository/com/relevantcodes/extentreports/2.40/extentreports-2.40.jar!/com/relevantcodes/extentreports/view/Extent.ftl"
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorI

**Comment by anshooarora** [comment]
I haven't seen this one before, but this one may be coming from the templating engine (Freemarker) which seems to be loading the template file from cache.  Does it stop execution?  Any other errors?

**Comment by williamrussellajb** [comment]
I guess it's just debug messages.

DEBUG [main] (_Log4jLoggerFactory.java:45) - Couldn't find template in cache for "Extent.ftl"("en_US", UTF-8, parsed); will try to load it.
DEBUG [main] (_Log4jLoggerFactory.java:45) - TemplateLoader.findTemplateSource("Extent_en_US.ftl"): Not found
DEBUG [main] (_Log4jLoggerFactory.java:45) - TemplateLoader.findTemplateSource("Extent_en.ftl"): Not found
DEBUG [main] (_Log4jLoggerFactory.java:45) - TemplateLoader.findTemplateSource("Extent.ftl"): Found
DEBUG [main] (_Log4jLoggerFactory.java:45) - Loading template for "Extent.ftl"("en_US", UTF-8, parsed) from "jar:file:/Users/name/.m2/repository/com/relevantcodes/extentreports/2.40/extentreports-2.40.jar!/com/relevantcodes/extentreports/view/Extent.ftl"

**Comment by anshooarora** [comment]
Thanks, I believe its because your project is using a supporter logger: log4j/slf4j.

**Comment by williamrussellajb** [comment]
Yes. Thank you very much.

**Comment by manjunathscp** [comment]
Is there any way to suppress this logs?
