### ISSUE TITLE
ExtentMerge missing snapshots

### ISSUE THREAD

**Issue by wonitta** [anshooarora/extentreports#211]
ExtentMerge is not including images in the merged report. See image below
![screenshot2](https://cloud.githubusercontent.com/assets/1801390/11820719/2a5235be-a323-11e5-80f9-2a98279e8ec0.png)

The image was included in the original individual report for that test. See image below:
![screenshot1](https://cloud.githubusercontent.com/assets/1801390/11820744/5078dd4c-a323-11e5-9037-cdfc2fe52db1.png)

**Comment by anshooarora** [comment]
fix for this will be part of the next release.
