### ISSUE TITLE
ExtentMerge dashboard duration is not adding up

### ISSUE THREAD

**Issue by wonitta** [anshooarora/extentreports#212]
The duration summary shown on the dashboard is showing zeros, but these tests lasted more than 60 seconds. See image below
![screenshot1](https://cloud.githubusercontent.com/assets/1801390/11820964/6d6afd3a-a324-11e5-96a4-60ca03523847.png)

**Comment by anshooarora** [comment]
fix for this will be part of the next release.

**Comment by anshooarora** [comment]
Closing this as ExtentMerge is deprecated.  ExtentX is the replacement and will be available soon.
