### ISSUE TITLE
Not able to specify date format in config xml

### ISSUE THREAD

**Issue by contactsimonwilson** [anshooarora/extentreports#215]
The date format is hard coded to the yyyy-MM-dd format. Not all countries use this format so it would be nice to be able to specify what is used in the custom config xml. 
eg <dateFormat>dd-MM-yyyy</dateFormat>

**Comment by anshooarora** [comment]
I am adding this as an enhancement.  Will include in the next release.

**Comment by anshooarora** [comment]
Would you be interested to help me test this feature?  Its going to involve changing a couple of things so I would like to make sure I don't break anything in the process.

**Comment by contactsimonwilson** [comment]
Sure thing. Happy to help with this great tool. Keep up the good work.

**Comment by anshooarora** [comment]
Thanks.

Here is the build:  http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.40.1-alpha1.zip

Changes:  https://github.com/anshooarora/extentreports/commit/f9323d54f6567efe5ed6d67c3afdee595c61dc5c

**Comment by contactsimonwilson** [comment]
Thanks for that. Do you also want me to take a look at the dotnet version?

**Comment by anshooarora** [comment]
Thanks.  Were you originally using the .NET api?  The .NET fix will probably be available later this week.

**Comment by contactsimonwilson** [comment]
Yea, I was. I will gladly help test both when you've made the changes.

**Comment by anshooarora** [comment]
You can download the latest .NET build from [here](http://extentreports.relevantcodes.com).  Working on creating a prerelease package for Nuget.

**Comment by anshooarora** [comment]
Closing as this feature is included in 2.40.1-beta1 + more config options available for 2.40.1-beta2.
