### ISSUE TITLE
Unnecessary scroll on Categories page

### ISSUE THREAD

**Issue by MegaUkrainian** [anshooarora/extentreports#219]
Hello,

Version: 2.40
Chrome 47.0
FF 43.0

![scroll](https://cloud.githubusercontent.com/assets/13480390/11914359/9b57d9d2-a687-11e5-80f3-8ae246fb0567.JPG)

**Comment by anshooarora** [comment]
Thanks, this will be fixed in the next release..  You can also do it using js for now:

```
$('#categories-view .vh100').removeClass('vh100');
```

**Comment by anshooarora** [comment]
Closing as this issue was fixed in 2.40.1.
