### ISSUE TITLE
Specflow integration [2.4] [.NET]

### ISSUE THREAD

**Issue by gBritz** [anshooarora/extentreports#220]
Using https://github.com/timschlechter/SpecResults project to create easily new reports.

**Comment by anshooarora** [comment]
There is already a section for this:  https://github.com/timschlechter/SpecResults#wanted-reporters

The `Report` class provides all methods to create a report using Extent. Also see here the Scenario class which can be accessed to create child nodes: 

https://github.com/timschlechter/SpecResults/blob/master/SpecResults/Model/Scenario.cs

Am I missing something?

**Comment by gBritz** [comment]
No.
I did a test and works well.
I only have doubts on how to organize BDD concepts: feature -> scenarios -> steps into your dashboard.

**Comment by gBritz** [comment]
Another question.
How do you think should be organized repeated scenarios executions into different browsers?

**Comment by anshooarora** [comment]
I would recommend test for each feature + child for each scenario.

```
feature (extent.StartTest)
  - scenario (test.AppendChild)
      - steps (test.Log)
```

**Comment by gBritz** [comment]
Show, thanks your answer.
