### ISSUE TITLE
Question to traduce

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#221]
I spend file should translate into Spanish?

**Comment by anshooarora** [comment]
Hmm? What is traduce?

**Comment by MaxiTalenti** [comment]
Some things that are in English which in a while could be translated.

**Comment by anshooarora** [comment]
What would be the best way to create support for Spanish?  Just manually covert the required text or use a translator API?

**Comment by MaxiTalenti** [comment]
I think there is little to be converted, so manually would be easier, right?

**Comment by anshooarora** [comment]
Can you do the translating and send a pull request as for the language template?

Since you are using .NET, can you convert the following template: https://github.com/anshooarora/extentreports/blob/master/dotnet/RelevantCodes.ExtentReports/RelevantCodes.ExtentReports/View/Extent.cs
