### ISSUE TITLE
Graph in Analysis

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#223]
Hi, when I click on the picture below:

![testextent](https://cloud.githubusercontent.com/assets/7159779/11944697/adad58b4-a826-11e5-8c1f-e58cbdacc674.jpg)

Filter correctly and displays the selected graphics, but no way to erase that filter, just refreshing the page, or by deselecting category "Test details"

![testextent1](https://cloud.githubusercontent.com/assets/7159779/11944711/d1425d10-a826-11e5-9dfd-637ed2d2c80d.jpg)

**Comment by anshooarora** [comment]
You can click the X icon:

![img](https://cloud.githubusercontent.com/assets/4107384/11944845/ce318794-a80e-11e5-9a78-545545d06c10.png)

**Comment by MaxiTalenti** [comment]
I click but the graph does not update, only when i press F5

**Comment by anshooarora** [comment]
Do you have refresh disabled?

Disabled:
![disabled](https://cloud.githubusercontent.com/assets/4107384/11944928/dfae9cf4-a80f-11e5-8493-dbe953841b35.png)


Enabled:
![enabled](https://cloud.githubusercontent.com/assets/4107384/11944931/e22782ac-a80f-11e5-83f1-d02e68416f5e.png)

**Comment by MaxiTalenti** [comment]
No, i have enabled

**Comment by anshooarora** [comment]
Hmm.. Can you upload a sample so I can see what's causing it?

**Comment by MaxiTalenti** [comment]
Yes!

[Reports1.txt](https://github.com/anshooarora/extentreports/files/69163/Reports1.txt)

**Comment by anshooarora** [comment]
I am able to clear filters and refresh graph from your report by clicking the X icon on Firefox/Chrome/IE..

**Comment by MaxiTalenti** [comment]
Now I saw that only works well if you have activated the dashboard in 'Test Details'. But if you have not activated, not working.

**Comment by MaxiTalenti** [comment]
I uploaded this image in 'Analysis', not  in 'Test details'

**Comment by anshooarora** [comment]
I was able to reproduce using your steps.  Will release as fixed beta.

**Comment by anshooarora** [comment]
Issue fixed in d0742321230ad4f9e26636a409308b26fef3761e.
