### ISSUE TITLE
Error on mouse hover to Charts

### ISSUE THREAD

**Issue by MegaUkrainian** [anshooarora/extentreports#226]
Version 2.40 
On mouse hover to Chart we get a JS error. 
Please take a look
![js_error_on_charts](https://cloud.githubusercontent.com/assets/13480390/11951601/e5f5383a-a89a-11e5-9d8a-4a48437ec3f9.jpg)

**Comment by anshooarora** [comment]
This does happen if you are using offline mode and due to an issue with charts.js.  line 26 is minified script of the charting toolkit.  Already an open issue: https://github.com/nnnick/Chart.js/issues/1772

**Comment by Ali-Usmaan** [comment]
Apply this CSS on your doughnut chart and you will not get that error in console
#doughnut{
  pointer-events:none;
}

**Comment by anshooarora** [comment]
Ali, thanks for sharing the solution.

**Comment by anshooarora** [comment]
Closing, Ali's comment above solves.
