### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#228]
Hi,

I'm having a problem when it does not replace the html and add a test on one before, the problem is with characters like á, ñ, etc.

[Rep.txt](https://github.com/anshooarora/extentreports/files/70837/Rep.txt)

**Comment by anshooarora** [comment]
Can you use "iso-8859-1" for encoding and try again?

**Comment by MaxiTalenti** [comment]
How could I do this?

**Comment by MaxiTalenti** [comment]
Thanks you!

**Comment by anshooarora** [comment]
You can add encoding in extent-config.XML.
