### ISSUE TITLE
No Extentreports generated when run test suite from maven command

### ISSUE THREAD

**Issue by ansonliao** [anshooarora/extentreports#229]
Dear Sir,
My extendreports version is 2.10, also I tried extendrepotrs 2.40, but also meet the problem below.
My manage my test case in TestNG in XML, when I run TestNG XML in command run via TestNG command, Extentreports can be generated corrected.

    java org.testng.TestNG TestNG.xml

But, when I run the test suite of TestNG XML via Maven build command, for example

    mvn clean test -DxmlFileName=TestNG.xml

after the test run, no extentreport was generated.

For TestNG.xml, no extentreport listener as I generate extentreport is in testing, not after all test classes run then call the listener.

I would like to know, for this case, how to config the maven in POM.xml to generate extentreport in run testng test suit in mvn command?

**Comment by anshooarora** [comment]
I am not sure exactly how, but see here:  http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html

**Comment by ansonliao** [comment]
Dear Anshooaroa,
I uploaded my demo code to GitHub, please try to download it for reproduce, the link is below.
<https://github.com/ansonliao/extentreportdemo.git>

After import the maven project in Eclipse (please make sure TestNG plugin was installed in Eclipse), 
1. 
please run TestNG test suite XML file 
`TestNG.xml`
in maven project root directory.
In Package Explorer view, right click "TestNG.xml" and select "Run as" --> "TestNG Suite".
After the test completed, you will get extent report in the directory 
`test-output/ExtentReport`

2.
Run TestNG test suite via Maven command in Terminal:
`mvn clean test -DxmlFileName=TestNG.xml`

after the test completed, you will find that the extentreport dirctory is empty.
`test-output/ExtentReport`

**Comment by ansonliao** [comment]
@anshooarora 
any comment?

**Comment by ansonliao** [comment]
@anshooarora 
Hi Anshooarora, I found the problem, please close this issue.

**Comment by anshooarora** [comment]
Thanks for letting me know.

**Comment by taras-git** [comment]
@ansonliao 
hi, could you please explain the issue as I'm facing the same....

**Comment by ansonliao** [comment]
@taras-git 
If you are using sure-fire-plugin, and the output setting is default, after test run, extentreports base dir changed to `target/surefire-reports`.

It means that, extentreport output setting will be override by surefire.

**Comment by madhuri1ch** [comment]
@ansonliao 

can you please tell me how you changed the default output directory so that extent reports are not overidden

**Comment by Dharmendrapawar** [comment]
Hi ansonliao,

Can you please let me know how did you fix the issue of ExtentReport not generating when tests run via Maven using command line.

Many Thanks in advance

**Comment by ansonliao** [comment]
@Dharmendrapawar 
for my case, the report was generated, and I searched the wrong directory to find the extentreport.
