### ISSUE TITLE
New Feature : Customized DB name 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#232]
Hi Anshoo,

Current API always creates extent.db file or write to same file,I want to create diff db file based on time stamps ,could you please add feature where i can override "extent.db" to "customize name.db"

Thanks

**Comment by anshooarora** [comment]
The reason extent.db was set so a single database is used for all runs, otherwise it would become a nightmare to manage multiple files + dbs.  I will add this enhancement for the next release though.

**Comment by anshooarora** [comment]
This feature is included in beta-5, available [here](http://extentreports.relevantcodes.com/).
