### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#236]
Although I write the following line before creating html I can not view the report in Spanish.

**Comment by anshooarora** [comment]
Which line?

**Comment by MaxiTalenti** [comment]
Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("es-ES");

**Comment by anshooarora** [comment]
Are you now able to create the report in the correct culture?

**Comment by anshooarora** [comment]
Closing ticket.  Feel free to open if you continue to encounter.

**Comment by MaxiTalenti** [comment]
Yes, i create the report in the correct culture but i can´t view the report in Spanish.

**Comment by MaxiTalenti** [comment]
Solution for this? I use:

```
            Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("es-ES");
            ExtReports.ExtentR = new ExtentReports(logpath + "\\" + NombreTestT + " " + iBuild.ToString() + ".html", CultureInfo.GetCultureInfo("es-ES"), true, DisplayOrder.OldestFirst);

```
