### ISSUE TITLE
Total time taken

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#238]
Total Time Taken time only shows a single test, not all. Start time and End time too.

**Comment by anshooarora** [comment]
Do you mean a single run, for dashboard?

**Comment by MaxiTalenti** [comment]
When the html file has a lot of test, the Start time and End time only show the time for a only test, not of the total test.

**Comment by anshooarora** [comment]
Do you mean here:

![timetaken](https://cloud.githubusercontent.com/assets/4107384/12037116/8242551c-ae11-11e5-96e4-6eb40f72122e.png)

**Comment by MaxiTalenti** [comment]
Yes, the 3 times there appear.

These times are the single test, not all.

**Comment by anshooarora** [comment]
Are you running the 3 tests sequentially, or using `replaceExisting = false' and running with breaks in between?

If you run the 3 tests at different times, it will only show you the totals for the most recent run session.

**Comment by MaxiTalenti** [comment]
Okey, and because this is so?

**Comment by anshooarora** [comment]
This feature is going to change and display:

1. Total time taken by all tests combined when `ReplaceExisting = false`
2. Total time taken in the current run
