### ISSUE TITLE
Final test results

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#239]
Create the possibility of the final test result manually not depending on steps.

**Comment by anshooarora** [comment]
Ability to override test results?  When would a user require this?

**Comment by MaxiTalenti** [comment]
when some alerts do not determine that the test is not okey for example

**Comment by anshooarora** [comment]
Allowing manipulation of results would not be such a good idea.  The test model drives the final result based on the logs and it can have negative effects when used by ExtentMerge and it can give a false picture of execution and log-level hierarchy.
