### ISSUE TITLE
ExtentReport 2.40 opening always new tabs in browser

### ISSUE THREAD

**Issue by dlitmano** [anshooarora/extentreports#240]
After a successful creation of a report, every link in this report opening a new tab in browser.
Please fix it with the new Version. I am using the java extentreport tool.

**Comment by anshooarora** [comment]
You can refresh the report in an existing tab..

**Comment by dlitmano** [comment]
I think its a mozilla problem, becasue i did not have this problem with chrome. Do you know maybe what config setting did open new tab?

**Comment by anshooarora** [comment]
I believe [this](https://support.mozilla.org/en-US/questions/970999) is the setting to prevent opening multiple tabs..
