### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#242]
IE 11:

![image](https://cloud.githubusercontent.com/assets/6800679/12065859/aec5baba-afac-11e5-939f-cb6eb07844df.png)

Chrome:
 
![image](https://cloud.githubusercontent.com/assets/6800679/12065867/c0a7f2ca-afac-11e5-923e-e4cf05198b87.png)

**Comment by anshooarora** [comment]
Chris - I believe some content is blocked in your IE settings, once you unblock it, should work fine:

![blocked-content](https://cloud.githubusercontent.com/assets/4107384/12081784/902c36ba-b24a-11e5-89b8-a5659ed35209.png)

![unblocked](https://cloud.githubusercontent.com/assets/4107384/12081792/c2eb1922-b24a-11e5-8a98-5f9713db4317.png)
