### ISSUE TITLE
Assembly RelevantCodes.ExtentReports.dll, v2.4.0.0 Issue

### ISSUE THREAD

**Issue by rohitadvani** [anshooarora/extentreports#245]
Hi Anshoo,

I'm using extent reports v2.4.0.0 to generate reports. I want my test reports to be appended to earlier reports. But, in this version, constructor for class ExtentReports doesn't have parameter for "replaceExisting", below is the signature of constructor for this version.

public ExtentReports(string FilePath, DisplayOrder Order = DisplayOrder.OldestFirst);

Can you please help here, if I want to append my test output to previous output, how to do that ?

Regards,
Rohit

**Comment by rohitadvani** [comment]
Please note, I'm working on c# (.Net), not Java. I don't think, this should make any difference with the kind of issue I'm facing.

**Comment by anshooarora** [comment]
The latest [.NET build](https://github.com/anshooarora/extentreports/tree/master/dotnet) has this functionality available, which you can download and compile to use.  This feature was part of d075d2bf112d9050cd69d43104c70a843ed38900.

2.40.1 beta-3 for .NET will be available tomorrow or day after, it will have this functionality available too.

**Comment by anshooarora** [comment]
Closing as this enhancement was part of an earlier commit d075d2b and will be released with .NET 2.40.1-beta-3.

**Comment by rohitadvani** [comment]
Thanks Anshoo. That helped ! Cheers.

**Comment by AlokPrasoon** [comment]
Hi,
I am unable to find relevantcodes.extentreport dll in Visual Studio 2015. Does VS 2015 supports Extent Report? Can you please help!

Thanks,
Alok
