### ISSUE TITLE
I am looking for help to change headings and color in the report

### ISSUE THREAD

**Issue by RaghavendraVenkat** [anshooarora/extentreports#246]
![attachment1](https://cloud.githubusercontent.com/assets/16552683/12108496/b94a8d3a-b39e-11e5-8ed2-c3e17ddd4f81.jpg)
![attachment2](https://cloud.githubusercontent.com/assets/16552683/12108519/f9b8b572-b39e-11e5-890c-c537331f80fd.jpg)

Hi Anshoo,

We are using your report jar for our framework. 

1) We are looking to use our own headings in place of "Categories", "Test view" and other Labels which are pre-defined. 
2) Can you please help us to know how we can change the default headings, position of headings(In the attachment2, you can Mercury Tours below MySampleTest but we want it to be placed above MySampleTest ) and color of start and stop time?

**Comment by anshooarora** [comment]
1. Currently no direct way.  You will have to modify this in the source template and re-compile.  I won't recommend this as you will have to do it for each release.  A workaround is using js (`scripts` node) from [config.xml](http://extentreports.relevantcodes.com/java/version2/docs.html#configuration)

2. Color of start-time/stop-time can be changed from the `styles` node of [config.xml](http://extentreports.relevantcodes.com/java/version2/docs.html#configuration).  To change the position of elements, use js

**Comment by RaghavendraVenkat** [comment]
Hi Anshoo,

Can you please help me on that work around you have suggested..
