### ISSUE TITLE
Tests are sorted by alphabet instead of sequentially - by time they were initiated

### ISSUE THREAD

**Issue by drormik** [anshooarora/extentreports#248]
tests should (in my view) appear in the order in which they were launched. but currently they appear sorted by test name.  the the screenshot attached- the "user namangement" test should be between "browser preparation" test, instead it is listed at the end of the list because of alphabet sorting:

![capture](https://cloud.githubusercontent.com/assets/5310157/12111753/75209d64-b3a0-11e5-99c5-60b8ce253f0b.JPG)

**Comment by anshooarora** [comment]
Are you using Java or .Net?  What version?

**Comment by drormik** [comment]
I'm using Java 1.7
Extent report I see are 2.10.  ->  I'll update per your recommendation
