### ISSUE TITLE
[question] Is it possible to add txt file

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports#249]
@anshooarora is it possible to attach a txt file to the report or link them .

I have set of txt files which has logs, so i need to add them to the reports

**Comment by anshooarora** [comment]
If you are doing it as part of your log, simply add a link:

```java
test.log(logStatus, "<a href='file:///c:/Users/log.txt'>linky</a>");  // absolute path
test.log(logStatus, "<a href='Users/log.txt'>linky</a>");  // relative path
```

**Comment by saikrishna321** [comment]
I have a couple of text files and I would want to add these before flushing rhr report .. Is that possible ?

**Comment by anshooarora** [comment]
To add multiple log files, you will have to somehow pass a list/array/collection and add each link one by one using the above mentioned html.

Just to clarify, you would like to add the links in your test logs, correct?  And you are using the listener not normal logging?

**Comment by saikrishna321** [comment]
@anshooarora thanks a lot for your help, i was able to add the logs as link as u suggested. 

Yes i'm using listeners..  Thanks for writing such a nice reporting tool .


Last one, How can i log certain values to the report ? For Ex: i get all the text available on the list, i want to log all these text values into the report. Which helps me know if all the values are present

**Comment by anshooarora** [comment]
Hmm, if you have a list, you can either create multiple logs in a loop.  Although if the list is huge, I would recommend separating the values in comma:

```
Value1, Value2
```

or creating a table on fly:

<table>
  <tr>
    <td>Value1</td>
  </tr>
  <tr>
    <td>Value2</td>
  </tr>
</table>

You can do this using simple string manipulation of using Jsoup.

**Comment by saikrishna321** [comment]
@anshooarora thanks .. got it worked.. closing the issue
