### ISSUE TITLE
Relative Reference to Screenshot in Report

### ISSUE THREAD

**Issue by dampfnudel** [anshooarora/extentreports#25]
In my opinion there is a problem with the screenshots, which are included in the report (html).

Method addScreenCapture(String imgPath) of ExtentTest returns "file:///screenshots/abc.png" for files which do have a relative path like "screenshots/abc.png".

**Comment by anshooarora** [comment]
Hello

What version are you using, and Java/.NET?

If version 2.+, this functionality is going to be revamped in the next version so the path you have mention will indeed be marked as relative.

**Comment by dampfnudel** [comment]
Thanks for the quick response. I am using 2.02 (Java).

**Comment by anshooarora** [comment]
Sure thing,  the next release is going to carry this fix.

For now, you can simply append a <code>./</code> to your path and it would work:

<pre>
./screenshots/abc.png
</pre>

**Comment by dampfnudel** [comment]
Sure Thanks
