### ISSUE TITLE
Report Not Functional on Linux using Firefox and Chrome

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#250]
The reports seem to work great on Windows and the Mac when using Firefox, Chrome, or Safari, but for some reason, when I load the html file on a Linux Browser like FF or CH, the report doesn't show any pie charts and the left-side tabbing from one screen to another fails to work? Any suggestions? I will attach the HTML file and bitmaps in Zip format 
[TestNGLogs.zip](https://github.com/anshooarora/extentreports/files/79844/TestNGLogs.zip)
as well...

**Comment by anshooarora** [comment]
Is 'work-offline' checked?  Seems that the javascript files are not being loaded correctly.  Can you check in Firebug or Chrome console and see what errors pop up there?

**Comment by carlc986** [comment]
Work-offline is not checked but FF Console shows:

ReferenceError: jQuery is not defined materialize.min.js:6
ReferenceError: jQuery is not defined featherlight.min.js:8
ReferenceError: $ is not defined extent.js:16
ReferenceError: $ is not defined RSA%20Via%20Access%20Console%20Test%20Suite.html:562
ReferenceError: $ is not defined RSA%20Via%20Access%20Console%20Test%20Suite.html:566

**Comment by anshooarora** [comment]
What version are you using?  Looks like the browser is preventing external javascript files being loaded.

**Comment by carlc986** [comment]
Linux Mint with Firefox 36, behind a firewall on a private network. Probably on our side then?

**Comment by anshooarora** [comment]
Most likely.  Can you check the protocol used by the javascript files in the report?  Are they all "https"?

The latest versions allow changing the protocol to be all "https".

**Comment by carlc986** [comment]
the config file has it set to https

**Comment by anshooarora** [comment]
The attached report works on my Windows 7/10 + Ubuntu box.  Most likely an environment issue..

**Comment by carlc986** [comment]
OK, thanks...

**Comment by anshooarora** [comment]
Closing ticket as this is most likely an environment issue.

PS.  I have removed the attachment in your original post.
