### ISSUE TITLE
3D Pie Charts in V2.40.1?

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#251]
Hi,there were 3D Pie Charts in the 1.x version of the ExtentReports, but those seem to be gone now, is there an option to turn them on in the config file or elsewhere? (GridType=Masonry)

**Comment by anshooarora** [comment]
Versions 1 used Google Charts but due to its licensing, the charting library is changed to [Chartjs](http://www.chartjs.org/docs/#doughnut-pie-chart).  3D is not an option in this library.
