### ISSUE TITLE
Query: Adding pass/fail while using extent as listener

### ISSUE THREAD

**Issue by guneetgarg** [anshooarora/extentreports#252]
Am using TestNg  with extent listener

Now in my each test script i want to add <b>test.log(LogStatus.PASS, "Step details");</b>
So is this possible will using listener we can use above code

Plz share the code how we can do this

**Comment by anshooarora** [comment]
Its not possible.  I would recommend using Extent as a logger instead - its not much different.  You can trap exceptions in `@AfterMethod` and also report other statuses.  See [here](http://extentreports.relevantcodes.com/java/version2/docs.html#testng-example) for an example.

    @AfterMethod
    protected void afterMethod(ITestResult result) {
        if (!result.isSuccess()) {
            test.log(LogStatus.FAIL, result.getThrowable());
        }
        
        extent.endTest(test);        
        extent.flush();
    }
