### ISSUE TITLE
Issue with parent child relationship

### ISSUE THREAD

**Issue by rohitadvani** [anshooarora/extentreports#254]
Hi,

I'm facing issue with regard to adding child tests to parent.

My requirement is: I want to have a parent label (for e.g. Login) with expand ('+') icon, when I click on '+' icon, I should be able to all login tests (which would be child tests added to Login label.

I tried to do it using .AppendChild method but couldn't get any help, it didn'y work. Can someone please assist how I can deal with this scenario.

Regards,
Rohit

**Comment by anshooarora** [comment]
Can you share your code?

**Comment by rohitadvani** [comment]
Hi Anshoo.

Please find below sample code that I have running.

// Test Case 1

        [Test]
        public void LoginTest1()
        {
        }

        [Test]
        public void LoginTest2()
        {
        }

        [Test]
        public void LoginTest3()
        {
        }

Now, what I'm looking to achieve is, to "Login" label etc. as top level parent and then above 3 test cases can be added to "Login" parent along with expand ('+') icon. So that, when I click on + I can see all 3 Login test cases.

Currently, all test cases, Login, Payment, Income etc. are shown at same level with no parent child relation.

Please assist.

Regards,
Rohit

**Comment by karthikbhatnagar** [comment]
You can see docs under Adding Child Tests.  You can start parent test in class SetUp or constructor.

**Comment by rohitadvani** [comment]
Hi Karthik,

In my case there is no parent test case as such. All are different independent test cases. That's why I'm looking for something like parent label under which I can have all these as child test cases.

Regards,
Rohit

**Comment by rohitadvani** [comment]
In case if we can't have parent label sort of thing, then can you share any sample code where I can have a parent test which internally calls these child test cases.

Regards,
Rohit

**Comment by karthikbhatnagar** [comment]
I mean you can start a wrapper test in constructor and add all class level child test to it.  You can add child tests in TearDown.

**Comment by anshooarora** [comment]
> I mean you can start a wrapper test in constructor and add all class level child test to it. You can add child tests in TearDown. 

Good suggestion..  You can add the class name test in the constructor and add each test in the TearDown.

```
class ClassName
{
    private ExtentTest test;
    private ExtentTest parent;

    [Test] public void TestName1()
    {
        test = extent.StartTest("TestName1");
    }

    [Test] public void TestName2()
    {
        test = extent.StartTest("TestName2");
    }

    [TearDown] public void TearDown()
    {
        parent.AppendChild(test);
    }

    public ClassName() 
    {
        parent = extent.StartTest("ClassName");
    }
}
```

**Comment by rohitadvani** [comment]
Hi Anshoo,
I'm still problems with this one. I tried the code you suggested. But I didn't get required expected output on the report. Below is the code snippet that i have tried, for your reference please. But I still got the same output as I was getting before this code.

1) Can you please help here, what wrong am I doing ?
2) My requirement is not adding child test cases to parent TEST CASE, but rather adding child cases to parent (Parent is not a test case, it is just a label with expand, collapse icon)
3) Secondly, can you please share some screen shot, based on how it looks like when it works fine based on this tool.

Below is my code snippet.

In my test class LoginPageTest, I have test cases ClearLoginInputFields() and AuthorisedLogin().

namespace Project.Tests
{
    class LoginPageTest : UtilClass
    {
        private ExtentTest parent;

        // Constructor
        public i360LoginPageTest()
        {
            automationReport = new ExtentReports(AutomationReportPath,appendReportToExistingReportOutput);
            parent = automationReport.StartTest(typeof(LoginPageTest).ToString());
        }

       // Test Case starts
        [Test]
        public void ClearLoginInputFields()
        {
                 automationReport = new ExtentReports(AutomationReportPath,appendReportToExistingReportOutput);
            automationReport.AddSystemInfo("Application", "ABC");
            automationReport.AddSystemInfo("Selenium Version", "2.48.0"); 
            clearLoginTest = automationReport.StartTest("Clear Login Fields Test", "Clear Login Fields Test ABC Application");
        }  // Test Case ends

        // Test Case starts
        [Test]
        public void AuthorisedLogin()
        {
                 automationReport = new ExtentReports(AutomationReportPath,appendReportToExistingReportOutput);
            automationReport.AddSystemInfo("Application", "ABC");
            automationReport.AddSystemInfo("Selenium Version", "2.48.0"); 
            authorisedLoginTest= automationReport.StartTest("Authorised Login Test", "Authorised Login Test for ABC Application");
        } // Test Case ends

       // Tear Down Method
       [TestFixtureTearDown]
        public void CleanUp()
        {
            if (driver != null)
            {
                parent.AppendChild(clearLoginTest);
                parent.AppendChild(authorisedLoginTest);
                driver.Quit();
                driver = null;
                Logger.Info(BrowserClosed);
            }
        } // Tear Down method ends
   } // Class ended
}   // Namespace ended

**Comment by anshooarora** [comment]
See my [previous comment](https://github.com/anshooarora/extentreports/issues/254#issuecomment-170702306).  Add a TearDown and append test to parent everytime.
