### ISSUE TITLE
"Analyse" instead of "Test Details" defaultly

### ISSUE THREAD

**Issue by VaibhavRepo** [anshooarora/extentreports#255]
Whenever Report is open it is better to view graphs than data. So how can we open "Analyse" instead of "Test Details" defaultly

**Comment by rohitadvani** [comment]
I have exactly same question, I agree with you Vaibhav and I'm also looking for same. I feel, graphs are better to show first by default.

**Comment by testphreak** [comment]
People have different preferences. Anshoo has made it pretty straight-forward to customize default report behavior as you please with JavaScript using the extent-config.xml configuration file with v2.40.

http://extentreports.relevantcodes.com/java/version2/docs.html#configuration

Just add this to the *scripts* section -
```xml
<![CDATA[
       $(document).ready(function() {
             $('.dashboard-view').click();
       });
]]>
```

If you're still on v2.10, you can do this using the config() method -
```java
extent.config().insertJs("$(document).ready(function() { $('.dashboard-view').click(); });");
```

**Comment by VaibhavRepo** [comment]
thanks a lot
