### ISSUE TITLE
extentreports-net-v2.40.1-beta3 - is broken - GET file:///C:/Users/Anshoo/git/extentreports/cdn/extent.js net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by mittt** [anshooarora/extentreports#256]
Beta-3 is broken:
GET file:///C:/Users/Anshoo/git/extentreports/cdn/extent.js net::ERR_FILE_NOT_FOUND

I guess this shouldn't have ended in the commit:
```
<!--<s cript src='https://cdn.rawgit.com/anshooarora/extentreports/3792d0fdb706caa24ce479cbf0a5996e8c168805/cdn/extent.js' type='text/javascript'></script>--><s cript src='file:///C:/Users/Anshoo/git/extentreports/cdn/extent.js'>
```

**Comment by anshooarora** [comment]
Woops.  I uploaded the correct package `beta-3a` to my ftp.  You can download from [here]http://extentreports.relevantcodes.com/(http://extentreports.relevantcodes.com/).

**Comment by mittt** [comment]
I get an error, with this one:

TearDown failed for test fixture WebTests.Tests.SetUpFixture
System.IO.FileNotFoundException : Could not load file or assembly 'RelevantCodes.ExtentReports.Merged, Version=2.40.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
TearDown : System.IO.FileNotFoundException : Could not load file or assembly 'RelevantCodes.ExtentReports.Merged, Version=2.40.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at WebTests.Tests.SetUpFixtureBase.BaseRunBeforeAnyTests()

**Comment by anshooarora** [comment]
Sorry for that.  Can you try again with `beta-3b`.  There is an issue if I change the name of file, forgot it would break your code.

**Comment by anshooarora** [comment]
Note:  I have packaged the file with all resources, so it would not be requred to load the following assemblies anymore:

System.Web.Razor
RazorEngine
HtmlAgilityPack

**Comment by mittt** [comment]
10x, this one works

**Comment by anshooarora** [comment]
Great!  can this be closed?
