### ISSUE TITLE
Need your help in generating reports using cucumber

### ISSUE THREAD

**Issue by srikrishna-n** [anshooarora/extentreports#258]
Hi Anshoo,

Is there a way where I can generate reports using Cucumber Framework with Java? If so can you let me know the procedure.

Thanks in advance!

Regards,
Srikrishna

**Comment by anshooarora** [comment]
You can, but I won't know which design would be best for your scenario.  You can see the [docs](http://extentreports.relevantcodes.com/java/version2/docs.html) and try.
