### ISSUE TITLE
Possible Nullpointer in log Method

### ISSUE THREAD

**Issue by dampfnudel** [anshooarora/extentreports#26]
Could you please check for Null before you do a trim()? ExtentTest => log(LogStatus logStatus, String stepName, String details)

**Comment by anshooarora** [comment]
Thanks for pointing this out.  I will fix it for the upcoming release.

**Comment by anshooarora** [comment]
Can this issue be closed?  Its fixed in 2.031.

**Comment by dampfnudel** [comment]
Yes, thanks
