### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V

### ISSUE THREAD

**Issue by nikhilmullangi** [anshooarora/extentreports#261]
@anshooarora 

i'm running my test script, when my script started logging the details i'm getting the below error message.

Exception in thread "main" java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:92)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:168)

extent-config.xml

<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
    <configuration>
		
		<encoding>UTF-8</encoding>
		
        
        <documentTitle>ExtentReports 2.0</documentTitle>
        
        
        <reportName>Automation Report</reportName>
        
        
        <reportHeadline> [Headline]</reportHeadline>
        
        
        <scripts>
            <![CDATA[
                $(document).ready(function() {
                    
                });
            ]]>
        </scripts>
        
        
        <styles>
            <![CDATA[
                
            ]]>
        </styles>
    </configuration>
</extentreports>

java Code

public static ExtentReports extent;
public static ExtentTest test;		

extent = new ExtentReports(sreportname, true);
extent.loadConfig(new File("extent-config.xml"));

CommonActions.test.log(LogStatus.INFO, steps.FieldName,"Optional Element Not Found");
CommonActions.test.log(LogStatus.ERROR, steps.FieldName,"Query is returning null value at FeildName");

**Comment by karthikbhatnagar** [comment]
Can you share complete code and version

**Comment by nikhilmullangi** [comment]
Version 2.40.0

public static ExtentReports extent;

public static ExtentTest test;

Reports();

test = extent.startTest(testCases.TestCaseID, testCases.TestCaseDescription);

WebElement targetElement = driver.findElement(By.xpath(steps.FieldDefinition));
targetElement.sendKeys(Keys.ENTER);
test.log(LogStatus.INFO, steps.FieldName,								"Optional element found and Enter Button pressed successfully");
} else {
test.log(LogStatus.INFO, steps.FieldName,"Optional element Not found");
}

[Report.txt](https://github.com/anshooarora/extentreports/files/85367/Report.txt)

**Comment by nikhilmullangi** [comment]
Test instance is created but when it is trying to log im getting issue

Jan 11, 2016 11:14:03 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from file:/D:/OBP_AUTOMATION_NEW/OBPSelenium-New/ExternalJars/extentreports-java-2.40.0.jar!/com/relevantcodes/extentreports/resources/extent-config.xml
Jan 11, 2016 11:14:03 AM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from extent-config.xml

Exception in thread "main" java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V

**Comment by karthikbhatnagar** [comment]
Did you recently use 2.40?  There is some code that is from previous version I think.  Can you do fresh build of project?  Sometimes that helps because I have seen when you update jar it uses the old methods and does not reference latest jar.

**Comment by karthikbhatnagar** [comment]
Let me check with your code gimme 2 mins

**Comment by karthikbhatnagar** [comment]
I tried with same version (eclipse Luna).. No issues.

**Comment by nikhilmullangi** [comment]
actually i tried fresh build of project also. anyways i will check again

**Comment by karthikbhatnagar** [comment]
Sorry can't be much help maybe Anshoo will able to figure out..

**Comment by nikhilmullangi** [comment]
Thanks @karthikbhatnagar

**Comment by nikhilmullangi** [comment]
@anshooarora 
@karthikbhatnagar 

Please find the sample project which i have created and when i'm trying the run getting same error message.

can please try to run the same file and let me know.

Version 2.40.0


Jan 11, 2016 2:44:05 PM com.relevantcodes.extentreports.Configuration <init>
INFO: Configurating report from extent-config.xml
Exception in thread "main" java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:92)
	at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:168)
	at report.main(report.java:26)


[sampleReport.txt](https://github.com/anshooarora/extentreports/files/85479/sampleReport.txt)

**Comment by anshooarora** [comment]
Here is what I get after running your code:

![t261](https://cloud.githubusercontent.com/assets/4107384/12236874/dbf217e0-b830-11e5-834b-526febf376e0.png)

**Comment by nikhilmullangi** [comment]
Thanks @anshooarora 

Donno what's wrong with my system. i getting the same error message which i have mentioned in earlier post.

Can you please let me know what all external jars you have linked with the project

**Comment by agupta89** [comment]
I am also encountering the same error...Please help me to get it resolved.

com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V

**Comment by anshooarora** [comment]
@nikhilmullangi - jars:  freemarker, jsoup and sqlite.  They are included in lib folder if you download from website.  If using maven dependency, they will be automatically added.

Can you create a brand new project and use the latest beta from website or use its snapshot version as shown [here](http://extentreports.relevantcodes.com) under Download section.

**Comment by anshooarora** [comment]
@agupta89 - were you also using version 2.10 earlier?

**Comment by agupta89** [comment]
@anshooarora : 
Yes Anshoo. I have used 2.10 on Jenkins server, nightly builds was running fine till yesterday.

**Comment by anshooarora** [comment]
Most probably a build issue.  Can you do a Project->Clean and try again?

**Comment by nikhilmullangi** [comment]
@anshooarora 

Its Working Now. i have mentioned same folder structure which was mentioned in the snapshot version.

Thanks a ton @anshooarora

**Comment by agupta89** [comment]
Tried several times but all in vain. will replace with updated jar. Hope it will work. Thanks a lot @anshooarora .

**Comment by anshooarora** [comment]
This does seem like a build/environment/IDE issue..  Try with the latest SNAPSHOT, looks like it worked for @nikhilmullangi also.
