### ISSUE TITLE
How to send the screenshots alongwith HTML report via email

### ISSUE THREAD

**Issue by TanujAutomata** [anshooarora/extentreports#262]
Hi Anshoo,

Hope you are doing good.
Is there a way to send the screenshots(in html report) captured in html report to a user who does not have access to the path of the captured screenshots!!!!
Extent report version:2.04(Java)
Regards,
Tanuj

**Comment by karthikbhatnagar** [comment]
I think not possible..

**Comment by anshooarora** [comment]
The path must be accessible to the recipient otherwise images will not be displayed.

**Comment by Balu14** [comment]
Hi Anshoo,

How to make access to send the report with screen shot captured in mail.

Thanks & regards,
Balu
