### ISSUE TITLE
ExtentMerge - Reports i would like to get file name 

### ISSUE THREAD

**Issue by vamshipeddi** [anshooarora/extentreports#263]
Thank you for all the hard work on reporting
I was using ExtentMerge and is it possible that on the left side reports section i would like to see File name instead of data. 
Also in Dashboard insted of DATE	SOURCE	DURATION	TEST COUNT	SUMMARY
I would prefer FileName	SOURCE	DURATION	TEST COUNT	SUMMARY
How can i customize

**Comment by anshooarora** [comment]
Have a look at `Template.ftl` and the Report model for this.  Currently there is no field for the ReportName, but you can add it and update the view using this.
