### ISSUE TITLE
Issue with log sequence in parallel tests

### ISSUE THREAD

**Issue by rkkreddy** [anshooarora/extentreports#264]
I have tests designed to run in parallel using testng and I am using extentreports(ExtentReporterNG) as listener. The tests are generating the extentreports html result file successfully. I have 3 views in the results: Tests view, Dashboard view and TestRunner Logs view. I am very much impressed with the way the results are displayed. But I have an issue with TestRunner Logs view where the logs from different tests are written to the same file and they are written in sequence of the occurrence. Due to this, the steps are not separated based on the tests, instead it is just one big log and there is no way to differentiate which step belongs to which test case. How can I get these logs separated so that each test's logs are written to separate containers?

**Comment by anshooarora** [comment]
You will have to replace this code as it gets output sequentially from the Reporter:

```
for (String s : Reporter.getOutput()) {
    extent.setTestRunnerOutput(s);
}
```

It will be displayed in the same order you send in the logs.  You can also send in html as shown to distinguish between tests:

```
extent.setTestRunnerOutput("<h3>MyTestName</h3>");
extent.setTestRunnerOutput("log");
```

**Comment by rkkreddy** [comment]
Thank you for the solution. With this I am able to pull the logs to the perticular tests in Tests view.
I have one more question: How can I set the status and particularly timestamp for each step. Right now I am setting the status as Info and timestamp is set the same for all the steps as the time when these were pulled into the extent report. Any ideas around this will greatly help me in shaping better reports.

Thanks in advance.

**Comment by anshooarora** [comment]
You can use `Reporter log()` to create these logs correct?  Require more info about your usage.

**Comment by rkkreddy** [comment]
Yes, I am using Reporter.log(). Most of this logging comes from findElement of my CustomWebDriver and sendKeys of CustomWebElement and from page object methods. Attached image shows the log for a step and it's display on extent report.
![seleniumdocs](https://cloud.githubusercontent.com/assets/6282147/12266077/0715451c-b90f-11e5-96fc-94547a9538f9.png)

Instead of writing the steps at the end of the run, is there a way to get an instance of extentreport listener for that test and write the log directly to it while test execution?

Or the other way I thinking is by passing status+timestamp+step description to testng log description and then parsing as you said.

Please suggest.

**Comment by anshooarora** [comment]
Without knowing too much about your design, I would say this is not a very good approach.  Instead, you can create an extension to handle this by replacing all `Reporter.log()` with for example `MasterReporter.log()`:

```
class MasterReporter {
    public void log(String message) {
        Reporter.log(message);
        test.log(status, message);
    }
}
```

You can even use [ExtentTestManager](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/common/ExtentTestManager.java) utility class to manage your tests (supports both single and multi threaded sessions).

[Example1](https://github.com/anshooarora/extentreports/issues/102#issuecomment-149753021)
[Example2](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ParallelMethodsTest.java)

**Comment by saikrishna321** [comment]
@anshooarora is it possible to categorize the logs, i would want to know for which method/class the log depends to..i'm running it on multithreading . Below screen shows all the logs together.

![d9d93b76-bc88-11e5-829f-fae0799d36f4](https://cloud.githubusercontent.com/assets/4045041/12377233/53e36b90-bd3c-11e5-90cc-5e3038d0b738.png)

**Comment by karthikbhatnagar** [comment]
I was adding class/ method name in log, parse them in listener...  And add in map as

Class.method - list<log>

Then sending by class.method

You can use any html tag here to segregate ur logs

**Comment by saikrishna321** [comment]
@karthikbhatnagar how will the report look like then .. can u post a screenshot ?

**Comment by testphreak** [comment]
You can do it using Collections as @karthikbhatnagar suggested or use Reflection.

Assuming you are using Java, you can use [method reflection](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html) to get the class name and method. Use `Thread.currentThread().getId()` to help understand the sequence.

**Comment by shanep2300** [comment]
So I've been playing around with this and I've been wanting to use the logger as log steps for each individual test in an xml suite. I was able to that without a listener but the problem is that ALL the steps show up in the first test. I feel like I'm super close with figuring this out but I can't seem to be able to separate the logs in their respective tests.

With the listener I was able to get the log report, but I don't want it like that. I want for each step to be shown under the respective test. Using log(LogStatus.INFO, "*"); with the listener, seems to break my test. Always getting NullPointerException.

If what I'm asking for can be done with either approach, please lead me to the the right direction. As currently, I'm the closest at getting it working the way I want it to without the listener.

**Comment by anshooarora** [comment]
@shanep2300 

If you are using TestNG, using normal logging, you can use `@AfterMethod`:

```
@AfterMethod
protected void afterMethod(ITestResult result) {
    if (!result.isSuccess()) {
        test.log(LogStatus.FAIL, result.getThrowable());
    }
    
    extent.endTest(test);    
    extent.flush();
}
```

You can also use the following utility classes to manage `extent` and `extentTest` references globally:

* [ExtentManager](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/common/ExtentManager.java)
* [ExtentTestManager](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/common/ExtentTestManager.java)

**Comment by shanep2300** [comment]
@anshooarora Yup, that's what I have in my @AfterMethod, but the steps still shows up in the first test that's executed in the suite. All the other tests just have the pass/fail step. That's it. Maybe adding the global references will fix the issue?

**Comment by anshooarora** [comment]
You will have to share your code, without that its impossible to tell what's happening.  The above utility classes will manage the test instance, so you will always have the correct instance.  It should work if the issue is due to your references aren't managed correctly.

**Comment by shanep2300** [comment]
Of course, no problem. I have a feeling it's something I'm easily overlooking. ExtenteManager and ExtentTestManager you provided have not been changed.

Here is the main test:  
    
    public class EventsManagerTest implements IRetryAnalyzer
    {   
    protected static ExtentReports extent = ExtentManager.getReporter("test-output/ExtentReport/TestReport.html");
    protected static ExtentTest parent, child;	
	
	@BeforeTest
	public static void createParentNode(ITestContext testName)
	{
		parent = ExtentTestManager.startTest(testName.getName(), "");
	}
	
	@BeforeMethod
	@Parameters({"browser", "url", "user", "password"})
	public static void start(Method method, @Optional String browser, @Optional String url, @Optional String user,
		@Optional String password)
	{
		if (browser.equals("${browser}"))
			browser = defaultBrowser;
		if (url.equals("${url}"))
			url = defaultUrl;
		if (user.equals("${user}"))
			user = defaultUser;
		if (password.equals("${password}"))
			password = defaultPassword;

		currentTest = method.getName();
		currentBrowser = browser;
		currentUrl = url;
		currentUser = user;
		currentPassword = password;

		Driver.initialize(browser);

		child = ExtentTestManager.startTest(currentTest, "");
		parent.appendChild(child);

		LoginPage.goTo();
		LoginPage.login(user, password);

		Log.printTestStart();
	}

	@AfterMethod
	public static void close(ITestResult result)
	{
		Driver.Instance.quit();
		
		Log.printTestEnd();

		if (result.getStatus() == ITestResult.SKIP)
		{
			child.log(LogStatus.SKIP, "Error found. Retrying the test...");
		}
		else if (result.getStatus() == ITestResult.FAILURE)
		{
			child.log(LogStatus.FAIL, result.getThrowable());
		}
		else if (result.getStatus() == ITestResult.SUCCESS)
		{
			child.log(LogStatus.PASS, "Test completed successfully");
		}
		
		extent.endTest(child);
		extent.flush();
	}
	
	@AfterTest
	public static void endParentTest()
	{
		extent.endTest(parent);
		extent.flush();
	}

	@AfterSuite
	public static void closeExtentReport()
	{
		extent.close();
	}

Here is a snippet of the log class:

    public class Log
    {
	public static String screenshotDirectory = System.getProperty("user.dir") + "\\test-output\\screenshots\\";
	private static ExtentTest test = ExtentTestManager.getTest();
	
	public static void screenshot()
	{
		File srcFile = ((TakesScreenshot) Driver.Instance).getScreenshotAs(OutputType.FILE);

		String fileName = EventsManagerTest.getCurrentTest() + ".jpg";
		
		String fileDir = screenshotDirectory + fileName;

		try
		{
			FileUtils.copyFile(srcFile, new File(fileDir));
			
			test.log(LogStatus.INFO, "Snapshot below: " + test.addScreenCapture(screenshotDirectory + fileName));
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}

	public static void printAction(String info)
	{
		System.out.println(info + "...");
		
		test.log(LogStatus.INFO, info + "...");
	}

And this is what the report looks under the first test:
![ss_000030](https://cloud.githubusercontent.com/assets/16820289/12491955/d15b1ab6-c04b-11e5-9772-47148ae0017b.jpg)

Under the next tests:
![ss_000031](https://cloud.githubusercontent.com/assets/16820289/12492017/1e31f10c-c04c-11e5-9264-850f100d092d.jpg)

**Comment by karthikbhatnagar** [comment]
You should store all tests in collection and use that collection in listener.  Only end test in listener.  Then it will be possible I think.

**Comment by shanep2300** [comment]
Is there a way to split my questions up into a separate questions thread? I just noticed that my problem has nothing to do with parallel testing. Just trying to get this to work with a single test suite.

**Comment by anshooarora** [comment]
You can open new issues for each

**Comment by dushyantan** [comment]
Hi anshooarora,
   I am unable to see CATEGORIES section in the left pane of Report. Here is the snapshot of the report.
![image](https://cloud.githubusercontent.com/assets/19422757/15472098/0808afb6-2117-11e6-8235-90966ae26fe8.png)
