### ISSUE TITLE
Custom Styles and Report Title

### ISSUE THREAD

**Issue by nikhilmullangi** [anshooarora/extentreports#267]
@anshooarora 

How to change the report title and document title based on the test type (i.e Smoke, Regression etc) 

Currently in extent-config.xml file we are passing the report title and document title

    <documentTitle>ExtentReports 2.0</documentTitle>
        
    
    <reportName>Automation Report</reportName>
        
    
    <reportHeadline></reportHeadline>

if we want to change the same in runtime what exactly we need to do

**Comment by nikhilmullangi** [comment]
How to hide default system properties like Host Name and Username

**Comment by nikhilmullangi** [comment]
@anshooarora 

I'm using the below code but it is not updating the report name

extent.config().reportName("OBP " + sReportType + " Report");

extent.config().reportHeadline("OBP " + sReportType + " Report");

**Comment by anshooarora** [comment]
Its not possible to use `config()` as its deprecated.  The only way is to update the config.xml at runtime and load it.

**Comment by nageshbn1974** [comment]
Hi, I am using extent report 3.0.1 

And I am using following configuration while creating instance. However I do not see these in report. It is still 'ExtentReports. 

htmlReporter.config().setDocumentTitle("SMOKE TESTS");
htmlReporter.config().setReportName("SMOKE TESTS");

**Comment by liznyamu** [comment]
Hi ,
this worked for me...
Properties prop = new Properties();
...
String documentTitle = prop.getProperty("documentTitle", "SMOKE TESTS");
htmlReporter.config().setDocumentTitle(documentTitle);
