### ISSUE TITLE
Question:How to merge multiple db files to create merge report 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#268]
Hi Ansho,

I have to extent.db file in my reporting folder and i want to merge them and create one html report ,could you please how do i do that ?

Thanks 
<img width="178" alt="screnshot" src="https://cloud.githubusercontent.com/assets/9873362/12296145/d47577ba-b9d3-11e5-95c3-16e3ccafdc78.png">

**Comment by anshooarora** [comment]
Using:

```
java -jar extentmerge.jar -db "extent.db" -db "extent.db" -db "extent.db" -out "extent.html"
```

But remember, its always a good idea to use a single database file which contains all of your runs.  Its okay to create multiple files for viewing but databases should not be created for each run.

With a single database, its much easier, you can simply specify the `from` and `to` dates:

```
java -jar extentmerge.jar -db "extent.db" -out "extent.html" -from "2015-10-02 00:00:00" -to "2015-10-05 23:59:59"
```
