### ISSUE TITLE
Enhancement:Printing stack trace in separate lines 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#269]
Hi Ansho,

in the report exception is getting printed in merged lines,could you please change it to print in line by line so it would be easy to ready java line numbers 

Thanks 
<img width="591" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9873362/12297190/fa7dd7d0-b9d9-11e5-9e6a-ba454690ad1e.png">

**Comment by jawlitkp** [comment]
Something like this

<img width="637" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/9873362/12297219/240c160c-b9da-11e5-91e9-6896b91ffd38.png">

**Comment by anshooarora** [comment]
It should show as the 2nd snapshot you shared, see the last test of [this sample](http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html). 

Log your exceptions in the following way using the signatures which also creates an Exceptions view:

```
// log(LogStatus logStatus, Throwable t);
// log(LogStatus logStatus, String stepName, Throwable t);

test.log(LogStatus.FAIL, result.getThrowable());
test.log(LogStatus.FAIL, "stepName", result.getThrowable());
```
