### ISSUE TITLE
Add New Filter "Filter By Browser" in ExtentReport version 2.40

### ISSUE THREAD

**Issue by noorshiblee** [anshooarora/extentreports#270]
Currently,I am using extent report version 2.40. I am running my test on safari and chrome browser. If i run my test cases only in single browser, than report is ok. But if i run the test in both Chrome and Safari browser parallely, than the problem is, all test cases shown twice in the report- one for chrome and another for safari.

Is there any way to add filtering options by browser-if i select chrome browser, only testcases run in chrome will be shown and same for safari or other browsers.

Thanks

**Comment by anshooarora** [comment]
Simply add browser name as category for each test.
