### ISSUE TITLE
UTF-8 does not seem to work

### ISSUE THREAD

**Issue by vincentlabatut** [anshooarora/extentreports#272]
Hi,

I'm loading my own config file 
<extentreports>
    <configuration>
		
		<encoding>UTF-8</encoding>

My report seems to be UFT-8 in the HTML file:
<meta http-equiv='content-type' content='text/html; charset=UTF-8' /> 

The encoding of the file is UTF-8 without BOM.

But inside the file I find badly encoded characters. They come from hard coded logs from my java code (Like the word "touché").  My java sources are saved in utf8 format.

I need to add the following code to convert the file after having closed the report and only then those caracters are well displayed... 

			Path p = Paths.get(myReportPath);
			ByteBuffer bb = ByteBuffer.wrap(Files.readAllBytes(p));
			CharBuffer cb = Charset.forName("windows-1252").decode(bb);
			bb = Charset.forName("UTF-8").encode(cb);
			Files.write(p, bb.array());

I had the same problem with 2.10 and thought upgrading to 2.40 would solve the issue because of the encoding from the config file.

Thanks for your help,
Vincent

**Comment by anshooarora** [comment]
Report was still using HTML4 charset which is why.  It is changed and will be available in next beta so you will not have to use the above code.

**Comment by vincentlabatut** [comment]
Ok, this is great news ! thanks !

**Comment by anshooarora** [comment]
This feature is included in beta-5, available [here](http://extentreports.relevantcodes.com/).
