### ISSUE TITLE
Would like a chance to load my config first

### ISSUE THREAD

**Issue by vincentlabatut** [anshooarora/extentreports#273]
Ok, I know I'm messing a bit, but I'd like to avoid extentreports from loading its "default config file".

I want a way to tell it to load my config file right from the beginning.

I can't avoid it to load the default config file since it is loaded from the ExtentReports constructor. I don't have a chance to load my config first...

By the way, there is this message that indicates the default config is loaded. Don't take it personnally but I find it a bit annoying since it cannot be avoided.

Maybe I'm all wrong and there is way to load our own file without the default one being loaded first ?

Finally, design speaking, why load a default file in the constructor when it is possible to set a default behavior by code ?

**Comment by vincentlabatut** [comment]
upgraded to extentreports-java-2.40.1-beta4 and there is no more message => that's a good point...

so this issue is not a real issue, it's more like a design discussion.

**Comment by anshooarora** [comment]
Some of the config values are mandatory for the report to work correctly, so from a design perspective, these values can go inside:

1. A globals class
2. Inside the template
3. A properties file

I am using `#3` since these values won't be hard coded inside the Java or Template code, and obviously over-written by the user's config.

**Comment by vincentlabatut** [comment]
Understood, once we know that the values are only "values" and that they are not used by the time we load our own config, It no longer shocking me. With the "loading config" message, we truly go the feeling that something noteworthy was happening, and got scared our config could not make it in time.
By the way, thankd for this great piece of code, our reports are very nice looking :)

**Comment by anshooarora** [comment]
I decided to remove the configuration message in 2.40 due the same reasons you've mentioned here.  :)
