### ISSUE TITLE
Missing artifact com.relevantcodes:extentreports:jar:2.40.1-SNAPSHOT

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#274]
I have added the following dependency in pom.xml, I am getting error 'missing artifact'.

<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>2.40.1-SNAPSHOT</version>
</dependency>

**Comment by anshooarora** [comment]
See if adding this [link](https://github.com/anshooarora/extentreports/issues/260#issuecomment-170806529) helps..

**Comment by gsaimadhu** [comment]
I went through the link. I tried the maven project update, Force update of snapshots and releases. But still same issue.

I have NOT tried deleting .m2 folder.

FYI, there is no issue with 2.40 dependency.

**Comment by anshooarora** [comment]
Looks like issue is resolved, ref: #275
