### ISSUE TITLE
Getting file not found exception if report html file is opened while test is in progress

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#277]
Env: 2.40.1 beta-4 

while the test execution is in progress, if we open the extent report to see the current test execution status, then the next test case writing is giving error:

Error:
java.io.FileNotFoundException: D:\tomee\webapps\TestResults\Freemium\2016-01-15_15-41-05\MAA_REST_TestExecutionReport.html (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at com.relevantcodes.extentreports.utils.Writer.write(Writer.java:20)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:184)
	at com.relevantcodes.extentreports.Report.flush(Report.java:282)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:667)

**Comment by anshooarora** [comment]
Where are you opening this file, and where is it saved?  Is an external process is locking this file?  Are you are using multiple Extent instances to write to the same file, in which case share your code.

**Comment by gsaimadhu** [comment]
I am using single extent instance.

The resutl path contains a path name (local machine) with file name.
extent = new ExtentReports(resultPath, true);

Suppose we have 5 test cases. After the execution of first test case, if we open the html report by clicking it then the next test case when trying to write result to the file is giving the file not found exception.

**Comment by karthikbhatnagar** [comment]
Where are you opening file? In browser?  It shouldn't lock as it still always open read only....  Are you saving file in eclipse project?  Someone else was having same issue it is not related to extent reports

**Comment by testphreak** [comment]
If you are trying to view test execution in real time I suggest you write a custom listener. Assuming you are using TestNG here's a basic [example](http://www.tutorialspoint.com/testng/testng_custom_logger.htm).

**Comment by gsaimadhu** [comment]
I am opening file in browser. Running through eclipse. I am saving file in outside of eclipse project.
I am using custom test framework (not testng).

**Comment by anshooarora** [comment]
The browser shouldn't lock the file, but most probably another process is. 

Can you share sample code so I can try to reproduce?

**Comment by gsaimadhu** [comment]
Anshoo, 
Sorry for the late reply. I am getting this issue intermittently. 
No other process holds this file. Browser (chrome) open is not locking most of the times. But  intermitently i see extent report throwing this error.
I am not sure of reproduction steps.

Thanks
Madhu
