### ISSUE TITLE
Regarding message reporting.

### ISSUE THREAD

**Issue by pavankumar9** [anshooarora/extentreports#278]
@anshooarora 

Is there a way where i can customise and show the report under details section as below.

TC_FLIGHTS_001
Testdesc!
Error : Failed due to network issue.

**Comment by anshooarora** [comment]
To clarify, customize the test's description?

**Comment by pavankumar9** [comment]
No basically i would like to show report as including test failure reason.

If you click on details section, it should show something like this:

TC_FLIGHTS_001
Test Desc : This test verifies search function
Failure Reason : Failed due to network issue.

TC_FLIGHTS_002
Test Desc : This test verifies flight select function
Failure Reason : Failed due to locator not found issue.

![extent_report](https://cloud.githubusercontent.com/assets/16286975/12358957/f2d29f04-bbd5-11e5-924e-f00a0aa43ae6.png)

**Comment by anshooarora** [comment]
This is not possible upto the current version.

**Comment by pavankumar9** [comment]
Can this be added as an enhancement in upcoming version?

**Comment by anshooarora** [comment]
The upcoming version is just around the corner (in final beta), but will include this in 2.40.2.

**Comment by anshooarora** [comment]
This was quite easy to implement, available in 2.40.1 acad805.
