### ISSUE TITLE
How to give sufficient column space for test step in the report?

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#279]
![Uploading image.png…]()

How to provide atleast 25 char space for test step name.

**Comment by gsaimadhu** [comment]
![image](https://cloud.githubusercontent.com/assets/8359360/12370757/fa9748a8-bc42-11e5-8d0b-227065de5dd7.png)

**Comment by saikrishna321** [comment]
+1

**Comment by karthikbhatnagar** [comment]
Why not use css to set column size?

**Comment by karthikbhatnagar** [comment]
And add it in styles of extebt-config.xml

**Comment by testphreak** [comment]
Agree with @karthikbhatnagar. ExtentReports allows you to customize the look and feel of the report yourself. Refer [here](http://extentreports.relevantcodes.com/java/version2/docs.html#configuration).

**Comment by saikrishna321** [comment]
@testphreak can u post the sample xml ?

**Comment by testphreak** [comment]
Show us what you've tried so far, so we can understand what's not working for you.

**Comment by anshooarora** [comment]
You can use this css to increase space:

```
th:nth-child(3), td:nth-child(3) {
    max-width: 250px !important;
    min-width: 200px !important;
}
```
