### ISSUE TITLE
Report is not getting updated, i am trying to open the report aftersuite and its not getting refreshed or updated 

### ISSUE THREAD

**Issue by bharathramaswamy** [anshooarora/extentreports#280]
when i am trying to open the report in After suite , reports opens where as its the old report which was for last run and if i press f5 for two times it gets the newer report .

Thanks in advance 
Bharath Ramaswamy

**Comment by testphreak** [comment]
Make sure you are calling flush() in the @AfterMethod and calling close() in the @AfterSuite. Only then open the report. Refer [here](http://extentreports.relevantcodes.com/java/version2/docs.html#close-extent).

**Comment by anshooarora** [comment]
@testphreak is correct, if you want to see the updated report, you must flush after each test ends.  Calling `flush` writes to the html file each time.
