### ISSUE TITLE
LogStatus : 

### ISSUE THREAD

**Issue by mailtokyatham** [anshooarora/extentreports#282]
Logstatus having pass/fail ..etc, Can it be based on the verification(true or flase)?

Either I should give two statements one for pass another for faile.

Based on boolean condition , I would like to log the results.

**Comment by testphreak** [comment]
You could write a listener as this [example](http://relevantcodes.com/testng-listener-using-extentreports/) shows which just logs a pass/fail. Or follow this [example](http://extentreports.relevantcodes.com/java/version2/docs.html#parallel-methods) to both log steps in your test (using Log.INFO) and pass/fail based on Assertions in the @AfterMethod when running tests in parallel.

```java
@AfterMethod(alwaysRun = true)
    public void afterEachTestMethod(ITestResult result) {

        if (result.getStatus() == ITestResult.SUCCESS) {
            ExtentReporter.getTest().log(LogStatus.PASS, "Test Passed");
        } else if (result.getStatus() == ITestResult.FAILURE) {
            ExtentReporter.getTest().log(LogStatus.FAIL, "Test Failed", result.getThrowable());
        } else if (result.getStatus() == ITestResult.SKIP) {
            ExtentReporter.getTest().log(LogStatus.SKIP, "Test Skipped");
        }

        // call the endTest() and flush() methods here.
    }
```
