### ISSUE TITLE
Is it possible to integrate extent reports with Jenkins ?

### ISSUE THREAD

**Issue by praveen-4705** [anshooarora/extentreports#283]
Is it possible to integrate extent reports with Jenkins

**Comment by testphreak** [comment]
You should be able to. You would need to point the Jenkins task running the tests to point to the artifact created by the run i.e. to wherever you're creating the report file. Try it out and let us know.

**Comment by praveen-4705** [comment]
Thanks for the response

I am new to jenkins, It will be useful if you provide the procedure to do that

**Comment by anshooarora** [comment]
Closing this as you have the answer in #290.
