### ISSUE TITLE
Test result are not displaying on the result board  in hierarchy

### ISSUE THREAD

**Issue by puneetjian** [anshooarora/extentreports#284]
Hi ,

How will i used extent report in key word-driven frame work? .

As in framework  there are 3 or more step against each test cases. so will i implement  this in such a way that each  test case content it  test steps in hierarchy way. 

below piece of code return the result for test cases parent0 only. not for parent 1 and parent 2.

    public static void main(String arg[])
    {
    ExtentReports extent=new ExtentReports("./demo.html");
    

   ExtentTest parent=null; 
   
for(int i=0;i<3;i++){
	
 parent = extent.startTest("Parent"+i);

for(int j=i;i<3;i++){

	ExtentTest child1 = extent.startTest("Child 1");
	child1.log(LogStatus.INFO, "Info from method"+j);
	
parent
    .appendChild(child1);
	
}
extent.endTest(parent);
extent.flush();
    
}
    }

Please have a look.

Thank, 
Puneet Jain

**Comment by anshooarora** [comment]
I don't understand the question.  I don't see the code creating parent1 and parent2.

**Comment by puneetjian** [comment]
Thanks anshoo for look into the my problem.

I am trying to develop keyword driven framework for my project.

In which i am taking the input from the excel sheet which contain set of test cases(in the form of keywords)

Against each test their were certain steps.

Test Case         Test step
TC_1                    open browser
TC_1                    Navigate To Url
TC_1                    Close Browser
TC_2                    Open Browser
TC_2                    Navigate To Url
TC_2                     Verify Text
TC_2                     Close Browser
   
what i want  is through extent report that if run the test. Then it wil first execute the test case TC_1 and it contains the steps in hierarchy like:

TC_1
      open browser
      Navigate To Url
      Close Browser

Then it after it execute the testcase TC_2 
    
TC_2
      open browser
      Navigate To Url
      Verify Text
      Close Browser

But I got the result in non-hierarchy way:

TC_1
      open browser
TC_1
      Navigate To Url
TC_1
      Close Browser
TC_2
      open browser
TC_2
       Navigate To Url
TC_2
      Verify Text
TC_2
      Close Browser


public static void main(String arg[])
{

String [][] data;
data=readExcel();
ExtentReports extent=new ExtentReports("./demo.html");
ExtentTest parent=null;

for(int i=0;i<data.lenght;i++){

if(data[i][0]==data[i+1][0])
parent = extent.startTest(data[i][0]);

ExtentTest child1 = extent.startTest(data[i][1]);
child1.log(LogStatus.INFO, "Info from method"+j);
parent
.appendChild(child1);
}

else{
ExtentTest child1 = extent.startTest(data[i][1]);
child1.log(LogStatus.INFO, "Info from method"+j);
parent
.appendChild(child1);
}
extent.endTest(parent);
extent.flush();
}
}


Please have look.

Is extent report  can only be use with Testng only?.


Thanks,
Puneet Jain

**Comment by anshooarora** [comment]
You can use it with any test framework, but the listener is only available to TestNG.  With Junit, use the `@Rule` annotation.

The issue is because you are adding this `parent = extent.startTest(data[i][0]);` in the loop.  You must keep it outside the loop to create the parent node only once.

**Comment by puneetjian** [comment]
Thanks for resolution.
But it  doesn't for me. Because if i declared  parent = extent.startTest(data[i][0]); out side  loop. the test cases name change every time. it will static all the time. and it will the result to me like:

TC_1
    open browser
     Navigate To Url
     Close Browser
    open browser
    Navigate To Url
    Verify Text
     Close Browser

And i want result in this way:

TC_1
     open browser
     Navigate To Url
     Close Browser

Then it after it execute the testcase TC_2

TC_2
     open browser
     Navigate To Url
     Verify Text
     Close Browser


Thanks,
Puneet Jain
QA TEAM
