### ISSUE TITLE
When mailing extent reports to team, screenshots are not available in extent reports as they are geeting saved on my local machine

### ISSUE THREAD

**Issue by Abdulkadirkhan** [anshooarora/extentreports#285]

**Comment by testphreak** [comment]
You have 2 options

1. Zip the entire folder (report file + screenshots) and then email.
2. Use continuous integration tools such as Bamboo, Jenkins, TeamCity etc running on a dedicated server to run the tests for you and automatically email links to reports.

**Comment by anshooarora** [comment]
Please see @testphreak answer.  The images must be available to the team for viewing - Extent creates an html file which does not "embed" this info.
