### ISSUE TITLE
config deprecated in 2.10 ?

### ISSUE THREAD

**Issue by drormik** [anshooarora/extentreports#286]
if i used the command-

        extent.config()
        .documentTitle("User Management Sanity")
        .reportName("login sanity")
        .reportHeadline("");

what should i replace it with ?

**Comment by testphreak** [comment]
If using 2.10 then no. If using 2.40+, then yes.

http://extentreports.relevantcodes.com/java/version2/docs.html#configuration

**Comment by drormik** [comment]
thanks

**Comment by kenston** [comment]
Will we still be able to dynamically set the headline or report name at runtime without writing and loading files?

**Comment by surivikas** [comment]
extent.config()
    .documentTitle("User Management Sanity")
    .reportName("login sanity")
    .reportHeadline("");

what is the alternative for the above code
