### ISSUE TITLE
Need improvements in the view for data driven tests

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#287]
Anshoo,
At the test level, we have a test (with multiple steps). This test can be executed with multiple data (say 2 different types of data).
In the report, i am gettign the Test at LHS. And on RHS, i see the test with multiple steps for data 1 (ie. Andorid in the snapshot attached.) and similarly for data 2 (ie iOS as shown in snapshot).
![datadriventestcase_report](https://cloud.githubusercontent.com/assets/8359360/12414552/2e00d9cc-bebc-11e5-98ed-b2c9d6e199f3.jpg)

In the report, Can we arrange the 2 sub tests (related to data1 and data2) at LHS as a child to the Test tree? And clicking on one of these tests should show the test steps at RHS?

FYI, as mentioned in below snapshot i am using the leaf child level of extent report for logging data to help in troublehsoot..
![loggingtestdatainfofortroubleshooting](https://cloud.githubusercontent.com/assets/8359360/12414697/44597dae-bebd-11e5-83c8-fe325d260712.jpg)

**Comment by anshooarora** [comment]
Any child test will automatically appear on the right-container, there is no way to change this behavior other than modifying the [template](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/view/Extent.ftl).  Another solution would be to not append those test as children, and let them remain at the top-most hierarchy.

**Comment by gsaimadhu** [comment]
Thanks Anshoo.
In the Right container, the child and subchilds are shown in the same color code. is it possible to distinguish?
If i click on the child then only it is displaying start and end time information in white background color. Is it possible to show this info without click.

![image](https://cloud.githubusercontent.com/assets/8359360/12441793/c9719e50-bf70-11e5-888b-5c495c6195f0.png)

**Comment by anshooarora** [comment]
Yes.  If you identify these elements you will notice that the hierarchy:

```
node-1x
node-2x
node-3x ...
```

Simply style this element by adding the css in `styles` of config.xml.
