### ISSUE TITLE
Displaying JSON in proper format

### ISSUE THREAD

**Issue by jsudhi** [anshooarora/extentreports#288]
Hello,

I have API response as JSON string which I want to display in the execution reports. Currently its displaying just like a raw text without formatting. How can I achieve this ?

Thanks
Sudhi

**Comment by anshooarora** [comment]
Simply wrap the json string in `<pre></pre>` tags.

**Comment by jsudhi** [comment]
Hello Anshoo,

I tried with <pre> tags, but it did not help.

Here is my code : 

`ExtentLogger.getInstance().getLogger().log(LogStatus.INFO, "JSON Validation Passed For : " + targetURL
				+ System.lineSeparator() + "<br>" + " Here is the output JSON" + "<pre>" + rs.asString() + "</pre>");`

Screenshot of the report : 

![image](https://cloud.githubusercontent.com/assets/16775642/12427714/c90a41e8-bf06-11e5-87be-3e6ea61cf88b.png)

**Comment by anshooarora** [comment]
What version are you using?

If possible, can you upgrade to the latest?  [Here](http://extentreports.relevantcodes.com/)

**Comment by jsudhi** [comment]
Hello Anshoo,

I am using 2.40 as of now. I tried with latest beta, but it did not work.

Also, along with displaying json properly, I would also like to collapse it. Is it something I can do ?

Thanks
Sudhi

**Comment by anshooarora** [comment]
To add custom features, you will have to write custom javascript and add it in the `scripts` node of config.xml.

I just tested with 2.40 and `pre` tag gets rendered correctly..

You may have to use something like this to preserve the formatting: [link](http://stackoverflow.com/questions/2010990/how-do-you-return-a-json-object-from-a-java-servlet).

**Comment by testphreak** [comment]
@jsudhi not really an ExtentReports related question. There are many ways to pretty print JSON strings most notably with GSON or Jackson's ObjectMapper. Possibly the easiest way to do it (one-liner) is to include this [dependency](https://github.com/jdereg/json-io) in your project and then do this -

```java
ExtentReporter.getTest().log(LogStatus.INFO, "<pre>" + "Formatted JSON: " + JsonWriter.formatJson(responseBody) + "</pre>");
```

**Comment by testphreak** [comment]
The solution I posted above is much better than unformatted output previously. Though one thing I noticed is that while the formatted output is correctly indented for braces and brackets on the **console**, there is **no indentation** when displayed in the browser and the text appears **left-aligned**. I've tried not just with the json-io library I shared above but with google-gson as well.

@anshooarora Not sure if something different needs to be done, but looking around, if we really want to display json strings with the correct indentation in a browser, the report might need to integrate with something like [code-prettify](https://github.com/google/code-prettify). There might be other ways to do this as well.

This is how it appears in the console which is correct

![image](https://cloud.githubusercontent.com/assets/10567800/12500546/08e1adf2-c069-11e5-9b23-604b340607fc.png)

This is how it appears in the report in a browser (no indentation and left aligned)

![image](https://cloud.githubusercontent.com/assets/10567800/12500561/2129bd78-c069-11e5-8bb7-e770f8f66237.png)

While I realize this is beyond the scope of this question, thought I'd still share my findings :smiley:

**Comment by anshooarora** [comment]
This is a good test and you see this probably because the documents gets minified each time it gets flushed.  It replaces all the extra spaces so the file does not blow up in size.

Can you see what happens when you replace `\t` and `    ` 4 spaces with `&nbsp;`?  I believe that should preserve the formats in which case the logs will have to be replaced with this keyword each time.

**Comment by testphreak** [comment]
Where do I replace `\t and 4 spaces` with `&nbsp`? I did not see it when I did an inspect on the report page containing the formatted block.

**Comment by anshooarora** [comment]
Like this:

```
ExtentReporter.getTest().log(LogStatus.INFO, "<pre>" + "Formatted JSON: " + JsonWriter.formatJson(responseBody).replace("\t", "&nbsp;").replace("    ", "&nbsp;") + "</pre>");
```

**Comment by testphreak** [comment]
Thanks Anshoo. Just needed to add an extra non-breaking space to your format to indent and align correctly.

`JsonWriter.formatJson(responseBody).replace("\t", "&nbsp;&nbsp;").replace("    ", "&nbsp;&nbsp;")`

**Comment by jsudhi** [comment]
Thanks Testphreak and Anshoo. I can see proper formatted JSON displayed in the individual report. However in the merged report I see question mark kind special characters. I tried changing the encoding of the file to UTF 8  and UTF 8 Without BOM, but I still see the same characters : 

![image](https://cloud.githubusercontent.com/assets/16775642/12506392/9f96e18a-c114-11e5-9fef-b425bf33fcc7.png)

**Comment by jsudhi** [comment]
With latest version of extent reports, this issue is resolved. Hence closing this. Thanks.
