### ISSUE TITLE
How to define custom metrics? The current metrics view is incorrect in my usage.

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#289]
Anshoo,
I am using the leaf child node for logging troubleshooting information, instead of test step.
So, all the info log will be under INFO. The test step view shows 0 tests passed.

As per attached snapshot, expected results are:
Tests View: 2 tests passed, 0 failed.
Steps View: 18 tests passed, 0 failed.

I think the mismatch might be happening becasue the steps view i am using for logging troubleshooting info.
But i need to have the metrics as per my usage of extent reports. Can you help in providing a way to define customization of metrics at each level (parent, child, subchild, etc) ?
![incorrectmetrics](https://cloud.githubusercontent.com/assets/8359360/12416382/2ff0f9a0-bec7-11e5-9ca4-ffc508c2e2bb.jpg)

FYI, i am using steps view for logging information of test data:
![loggingtestdatainfofortroubleshooting](https://cloud.githubusercontent.com/assets/8359360/12416395/4d2dd98e-bec7-11e5-9488-d37dd9e62fc0.jpg)

Please provide your views and comments.

**Comment by anshooarora** [comment]
The 'tests-view' shows 18 passed tests.
The 'steps-view' shows 127 'others' (INFO)

The above metrics are valid if you are using parent-tests as the target.

What you need is the setting to select `child-tests` as the target:

![img](https://cloud.githubusercontent.com/assets/4107384/12423616/ead99a96-be91-11e5-996b-f48e10f292ac.png)

The contributors do not provide any assistance with js/css but I am making an exception for this case.  All you have to do is insert the following under `scripts` and it will select the child-tests behavior each time you open the report.

```
$('#childNodes').click();
$('#test-count-setting .modal-action').click();
```
