### ISSUE TITLE
Question:How to get Testcase status from DB 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#291]
Hi Ansho,

Lets say i have one extent.db file for my all reports ,but when i am running my test before running it , i am querying db to check if test cases passed in the previous run ,currently i am creating separate db file for each run but if id create only db file for all report how do i query db to get testcase status for under specific report.

i need something in my query to point specific report and once i have it i can go deep inside and get testcase status

**Comment by anshooarora** [comment]
The schema has a separate table for Report:

![img](https://cloud.githubusercontent.com/assets/4107384/12424916/e9d4953c-be97-11e5-874f-54797cf84484.png)

Each report has one-to-many relationship with tests, so you can use this to query.

**Comment by jawlitkp** [comment]
Hi Anshoo,

I am using below query to get test case status from separate DB file ,i know ReportIDExcent is unique for each report and i have understanding of above solution but my problem is how would i get      ReportIDExcent from my previous report ,i guess would you be able to add extra column to report table for timestamp so i can add timestep in my query and get ReportIDExcent and then go in to deep .

this is what i am doing right now to get testcase status from separate DB files 

	public static DB_TestCaseBean getStatus(String testCaseName,String testSuite, String concept , String browserDevice) throws SQLException {
		
		
		String sql = "select Status from Test where TestIDExtent  in (select TestIDExtent as numb from Category where TestName='"+testCaseName+"'and Category.CategoryName in  ('"+testSuite+"','"+concept+"','"+browserDevice+"')  group by TestIDExtent having count(CategoryName) = 3)";
//		String sql = "select Status from Test where TestIDExtent  in (select TestIDExtent as numb from Category where TestName='s2600AddItemUpdateQuantityAndRemoveItemFromCartViaPDPForNonAuthorized_BBB_SamsungS3442' and Category.CategoryName in  ('BBB','cart','SamsungS3442')  group by TestIDExtent having count(CategoryName) = 3)";

		ResultSet rs = null;
		
		try {
			PreparedStatement stmt = conn.prepareStatement(sql);
//			stmt.setString(1, testCaseName);
			rs = stmt.executeQuery();

			if (rs.next()) {
				DB_TestCaseBean bean = new DB_TestCaseBean();
				//bean.setTestCaseStatus(testCaseName);
				bean.setTestCaseStatus(rs.getString("Status"));
				return bean;
			} else {
				return null;
			}

		} catch (SQLException e) {
			Log.error(e);
			return null;
		} finally {
			if (rs != null) {
				rs.close();
			}
		}

		
	}

**Comment by jawlitkp** [comment]
I think i can pass timestamp from system info and than query to system info table using timestamp and get reportID ,what you think ?

**Comment by anshooarora** [comment]
Would it help you if I expose the ID of the report?  So you will be able to:

```
extent.getId();
```

**Comment by anshooarora** [comment]
Or you can find the last executed test in the db, get its `ReportIDExtent` field.

**Comment by jawlitkp** [comment]
I can live with extent.getId(); 

thank much!

**Comment by anshooarora** [comment]
Available in 2.40.1 acad805.
