### ISSUE TITLE
Sorting of Test Runs in Merged Report

### ISSUE THREAD

**Issue by jsudhi** [anshooarora/extentreports#294]
Hello,

In the merged report, both on the left panel and right panel, I see all the test runs. But they are NOT sorted beginning with latest. Is there option to do this ?

I am using the latest available extentmerge jar along with 2.40 extentreports.

Thanks
Sudhi

**Comment by anshooarora** [comment]
I will have to check again, but I don't remember reports being added in chronological order.  This can be an enhancement, feel free to make changes [here](https://github.com/anshooarora/extentreports/blob/master/extentmerge/src/main/java/com/relevantcodes/extentmerge/FileInfoAggregator.java) if you are using files only, or [here](https://github.com/anshooarora/extentreports/blob/master/extentmerge/src/main/java/com/relevantcodes/extentmerge/DatabaseInfoAggregator.java) for db.

**Comment by anshooarora** [comment]
Closing this ER as ExtentMerge is deprecated and the replacement ExtentX will be available soon.
