### ISSUE TITLE
Unable to use URL in the report

### ISSUE THREAD

**Issue by skolgiri** [anshooarora/extentreports#296]
Hi Anshoo,

I have a Video Path which I m taking in the String Variable of JAVA and Just printing that path on the Extent Manger report as an Log.
But I wanted to use that Path as like URL, which after clicking from Report, the Video should get open.
Which currently I am unable to do it.
Could you please check , and let me know how to do it?

**Comment by testphreak** [comment]
You are making it hard on folks to help you without providing the necessary details that go into writing up an issue. Consider these points when you write an issue -

1. The title explains the issue in just a few words
2. The description is detailed enough and contains at least:
    * Steps/code to reproduce the issue. Add screenshots if applicable.
    * What the expected result is and what actually happens
    * The version of the software being used
    * Versions of relevant external software (e.g. browser and operating system)
3. Explain what you’ve already done trying to fix this issue
4. The report is written in proper English (given English is the main language of the software)
5. Use [Markdown](https://guides.github.com/features/mastering-markdown/) for proper formatting.

**Comment by skolgiri** [comment]
Hi,
Just a question that in below code i want the URL in report as WWW.google.es:
 ExtentManager.test.log(LogStatus.INFO,"<a href=\"WWW.google.es\"></a>");	

But this gives blank result.
Can you please check?

**Comment by anshooarora** [comment]
Closing issue as there was no response.
