### ISSUE TITLE
Invalid Run info date 

### ISSUE THREAD

**Issue by JakubAndrzej** [anshooarora/extentreports#298]
When using date format dd/MM/yyyy the test start & end date is invalid, only works correctly  when date format switched to yyyy/MM/dd
 .NET ExtentReports V2.02
![wrongdate](https://cloud.githubusercontent.com/assets/16838725/12513410/91c04b9a-c115-11e5-839b-dc0311254e46.png)

**Comment by anshooarora** [comment]
Are you doing this from config.xml?  Version 2.02 does not support this feature, it was added in 2.40.
