### ISSUE TITLE
Help with Changing Summary Report Titles

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#299]
Hi, I haven't been able to figure out exactly how to change the Headings on the Summary/Pie Charts page. Can you give me an example of how to change one of the following using the config file?

- Steps View change to Details View
- 1 step(s) passed, 2 step(s) failed, 7 others change to 1 testcase(s) passed, 2 testcase(s) failed, 7 other details
- Total Steps change to Total Details

**Comment by karthikbhatnagar** [comment]
This is from FAQs section

```
Extent comes as-is and even though it supports both JS and CSS customization, the contributors are unable to provide any support in customizing the API.
```

Better to ask this on stackoverflow..

**Comment by anshooarora** [comment]
It will have to be done via js, example:

```js
// changes the Tests View heading
$('.charts .panel-name:first-child').text('Tests View- Changed Heading');
```

**Comment by carlc986** [comment]
Thanks, does this go under the <scripts> section or the <styles> section?

**Comment by carlc986** [comment]
Sorry, does this go under the <scripts> section?

**Comment by carlc986** [comment]
Hi, I tried your suggestion in both the styles and scripts sections and it did not change the title for Tests View?

**Comment by anshooarora** [comment]
Did you put it inside document.ready in scripts?

**Comment by carlc986** [comment]
Yes, here's the code:

<scripts>
            <![CDATA[
                $(document).ready(function() {
                $('.charts .panel-name:first-child').text('Tests View- Changed Heading');
});
            ]]>
        </scripts>

**Comment by anshooarora** [comment]
Are you loading the config file using `loadConfig()`?

**Comment by anshooarora** [comment]
Btw, the above code will change the heading of the Tests View graph.

![tests-view](https://cloud.githubusercontent.com/assets/4107384/12682243/03d5eda4-c678-11e5-8f08-0fb0e99c4a5c.png)

**Comment by carlc986** [comment]
Yes, and that is working fine, I am able to change the reportTitle and heading, etc...

**Comment by carlc986** [comment]
Right, I did expect that behavior but it is not changing for me?

**Comment by carlc986** [comment]
Just to be clear, I am calling loadConfig, it is not changing the titles as you display here, just the xml nodes that it had for reportTitle and heading, etc...

**Comment by carlc986** [comment]
Does my code look OK, I noticed there's a space in between charts and .panel-name?

**Comment by anshooarora** [comment]
So when you use your config file, report is displaying the same reportTitle, heading etc on the html report.  With scripts its not working?  Version?

**Comment by carlc986** [comment]
Right, I'll attach the file as well. The stuff I've added to scripts section doesn't seem to work, although if I look at the HTML for the report, it says it is there. I'm using 2.40.1-beta5-final

**Comment by carlc986** [comment]
[Archive.zip](https://github.com/anshooarora/extentreports/files/110167/Archive.zip)

**Comment by anshooarora** [comment]
You are entiring `<!-- $('#enableDashboard').click(); -->` inside a script tag.  Use `//` or `/* */` instead.

This is what I see in your report, the headings are there:

![views](https://cloud.githubusercontent.com/assets/4107384/12683606/bf7dbe7c-c67f-11e5-8ab9-9559d3b06fbc.png)

**Comment by carlc986** [comment]
OK, why did it change all 3 when I said panel-name:first-child? Do I need to include additional hierarchy to modify just the Steps View title? Thanks.

**Comment by carlc986** [comment]
I've got it now, I needed to specify a more unique parent to just change 1 like Total Steps:

$('.suite-total-steps .panel-name:first-child').text('Total Details');

All set, thanks for your help again!
