### ISSUE TITLE
Downloaded jar from Maven contains only META-INF directory

### ISSUE THREAD

**Issue by kelumkps** [anshooarora/extentreports#3]
Hello Anshoo,
I added extentreport dependency to pom.xml of the my project as instructed on documentation. However, the downloaded jar file from Maven server does not have any compiled .class files. It contains only the META-INF directory. Below is how I added the dependency to pom.xml

```
  <dependency>
            <groupId>com.relevantcodes</groupId>
            <artifactId>extentreports</artifactId>
            <version>1.2</version>
  </dependency>
```
Could you please look into this?

**Comment by relevantcodes** [comment]
Hi Kelum

To download the sources, add the following tag in your dependency:

    <classifier>sources</classifier>

This will download the sources.  I tested with my dummy project using the following command against its pom.xml and its working.

    mvn dependency:copy-dependencies

Thanks,  Anshoo

**Comment by kelumkps** [comment]
Hi Anshoo,
Today I saw Maven repo is updated with jar files. However, still extentreports-1.2.jar file contains source files (.java files) instead of compiled files (.class files). I checked from below location.

http://repo1.maven.org/maven2/com/relevantcodes/extentreports/1.2/

It can be found on below location too.
http://search.maven.org/#artifactdetails%7Ccom.relevantcodes%7Cextentreports%7C1.2%7Cjar

**Comment by relevantcodes** [comment]
Ah, looks like I misunderstood.  I uploaded the sources files instead this morning.  I am quite new to ossrh and it looks like I will not be able to release the jars with .class files without javadoc.  It keeps kicking me out with the javadoc error:

Event: Failed: Javadoc Validation
Tuesday, March 24, 2015 22:23:11 CST (GMT-0500)
typeId	javadoc-staging
failureMessage	Missing: no javadoc jar found in folder '/com/relevantcodes/extentreports/1.2'

I will try to do it soon though, but no ETA as of now..

**Comment by kelumkps** [comment]
Okay got it. As a workaround I replaced my local repository with the .jar file provided in your website. Anyway, thanks for the help.

**Comment by anshooarora** [comment]
Kelum

Can you please try again?  Version 1.3:

<dependency>
  <groupId>com.relevantcodes</groupId>
  <artifactId>extentreports</artifactId>
  <version>1.3</version>
</dependency>

**Comment by kelumkps** [comment]
Still version 1.3 is not available on Maven.

```
[WARNING] The POM for com.relevantcodes:extentreports-java:jar:1.3 is missing, no dependency information available
```

**Comment by anshooarora** [comment]
I also see it being missing from search.maven.org - maybe it will be picked up in their next job.  it is available on ossrh though, so you can simply download using:

    mvn dependency:copy-dependencies

    <dependency>
        <groupId>com.relevantcodes</groupId>
        <artifactId>extentreports</artifactId>
        <version>1.3</version>
    </dependency>

**Comment by anshooarora** [comment]
Kelum,  it was not showing under Maven search because I had not released the artifacts after dropping them to the central repo.  Please check now.

**Comment by kelumkps** [comment]
Yes. Now it's available. I was able to build the project using v1.3 jar. Thanks a lot for making it happen.

**Comment by viszjag** [comment]
How use extentreports-java-141.jar through ANT build file

**Comment by anshooarora** [comment]
viszjag - please see this:

http://stackoverflow.com/questions/5963962/download-jars-from-nexus-using-ant-build-tool-as-done-automatically-in-maven

If it still doesn't work, please open a new ticket as this one is already closed by Kelum on April 2.

**Comment by shilpabhapkar** [comment]
Getting error at this:
ExtentReports extent= new ExtentReports(fileName,true);
while executing commant "ant run" from cmd promt.
