### ISSUE TITLE
Enhancement : Can we merge reports using ReportIDExtent

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#300]
Hi Anshoo,

Would you be able to add feature to extent merge to merge reports based on ReportIDExtent?

Thanks 
Jwalit

**Comment by karthikbhatnagar** [comment]
How did you find this field?

**Comment by anshooarora** [comment]
Karthik - this is available in the db and also in the report (if you are using 2.40.1) as `extent` tag:

```
<extent id='89a4e420....' />
```

**Comment by anshooarora** [comment]
ExtentMerge is now deprecated.  ExtentX is the replacement, a server that hosts all results.

Initial sample of extentx:  https://extentx.herokuapp.com/

Ability to update the server will be available in the next Extent version and you will also be able to deploy the server.
