### ISSUE TITLE
Issue: Testcase are getting reported multiple times in the DB 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#302]
Hi Anshoo,

Take a look on attached DB file test cases are getting reported multiple times ,i think endTest() is not cleaning up previous test cases.

here is my code 

	@AfterSuite(alwaysRun=true)
	public void afterSuite() {
		
		if(config.get("MACHINE").equals("local")){
		report.flush();
		report.close();
		}
		
	}
	@AfterMethod(alwaysRun=true)
	public void afterTest(ITestResult result){
		
		if (result.getStatus() == ITestResult.FAILURE) {
			reporter.log(LogStatus.FATAL, "<pre>" + result.getThrowable().getMessage() + "</pre>"+ reporter.extentReporter.addScreenCapture(takeScreenShot("failedFromAfterMethod")));
			reporter.log(LogStatus.FATAL, result.getThrowable());

		}        
		report.endTest(reporter.extentReporter);

		if(config.get("CLOSE_BROWSER").equals("Y")){
			Long threadID = Thread.currentThread().getId();
			WebDriver driver = (WebDriver) paramMap.get(threadID).get("Driver");
			if(driver!=null){
				if(currentDeviceBrowser.equals(BBBU_Constants.DEVICE_IOS1))
				{
					driver.close();
					driver.quit();
				}
			}
		}

	}
	public void initReporter() {

		report = getReporterInstance();

		if(config.get("MACHINE").equals("server")){
			report.startReporter(ReporterType.DB, System.getProperty("user.dir")+"//DBFiles//extent.db");
		}

		reporter = new BBBU_Reporter();

		if(config.get("MACHINE").equals("server")){
			String coreDeviceBrowser = currentDeviceBrowser.substring(0,currentDeviceBrowser.length()-1);
			reporter.extentReporter =  report.startTest(currentTestCase).assignCategory(currentTestSuite,currentConcept,currentDeviceBrowser,coreDeviceBrowser,BBBU_Listener.currentIteration);
		}else{
			reporter.extentReporter =  report.startTest(currentTestCase).assignCategory(currentTestSuite,currentConcept,currentDeviceBrowser);
		}

	}
	public ExtentReports getReporterInstance(){

		if (BBBU_TestRunnerHelper.report == null) {
			BBBU_TestRunnerHelper.report = new ExtentReports(BBBU_Utility.filePathConverter(BBBU_Listener.htmlReportFolderNamePath+"//"+"Results.html"), true);
			//BBBU_Utility.setTestExecutionReportId(BBBU_TestRunnerHelper.report.getReportId().toString(), BBBU_TestRunnerHelper.controller);
			dbReportId=BBBU_TestRunnerHelper.report.getReportId().toString();
		}
		return BBBU_TestRunnerHelper.report;
	}

<img width="512" alt="dbissue" src="https://cloud.githubusercontent.com/assets/9873362/12561624/2127f78c-c36f-11e5-8dca-2c237cd5eacc.png">

**Comment by anshooarora** [comment]
This would happen when you end the same test multiple times..

**Comment by jawlitkp** [comment]
I am not using retry listener at all.

**Comment by jawlitkp** [comment]
if u see screenshot ,2 test case got reported 2 times ,3 test case got reported 3 times

**Comment by anshooarora** [comment]
Are the start and end millis also same for all 3 tests?  Can you post a complete snapshot?

**Comment by jawlitkp** [comment]
Yes they are same ,plus i added below logic to my code to call endTest() only one time for same test cases and still same results 

	public void afterTest(ITestResult result){
		if(reportedTestCases!=null){
		reportedTestCases = new ArrayList<String>();
		}
		
		if (result.getStatus() == ITestResult.FAILURE) {
			reporter.log(LogStatus.FATAL, "<pre>" + result.getThrowable().getMessage() + "</pre>"+ reporter.extentReporter.addScreenCapture(takeScreenShot("failedFromAfterMethod")));
			reporter.log(LogStatus.FATAL, result.getThrowable());

		}
		if(!reportedTestCases.contains(currentTestCase)){
		report.endTest(reporter.extentReporter);
		reportedTestCases.add(currentTestCase);
		}

		if(config.get("CLOSE_BROWSER").equals("Y")){
			Long threadID = Thread.currentThread().getId();
			WebDriver driver = (WebDriver) paramMap.get(threadID).get("Driver");
			if(driver!=null){
				if(currentDeviceBrowser.equals(BBBU_Constants.DEVICE_IOS1))
				{
					driver.close();
					driver.quit();
				}
			}
		}

	}
[Workbook3.xlsx](https://github.com/anshooarora/extentreports/files/103874/Workbook3.xlsx)

**Comment by jawlitkp** [comment]
Issue has been introduce  in the 2.40.1 ,just tested using 2.40 and its working fine ,attached xls

[Workbook1.xlsx](https://github.com/anshooarora/extentreports/files/104060/Workbook1.xlsx)

**Comment by jawlitkp** [comment]
Please  prioritize this issue ,i have changed my framework based on 2.40.1 and need this fix asap

**Comment by anshooarora** [comment]
I am unable to reproduce this..

**Comment by anshooarora** [comment]
I am unable to reproduce this..

Can you create a sample project so I can test?

**Comment by jawlitkp** [comment]
My framework is disturbed across many java classes its hard to create sample project ,let me if any other way i can show you the issue.skype to team viewer 

you did change something related to primary key to fix unique key constrain issue ,so 2.40 also it was trying to insert multiple test case and throwing unique constrain execution but somehow it was preventing to insert same test case multiple time but now 2.40.1 it is inserting same test case multiple times.

**Comment by anshooarora** [comment]
What I noticed from your Excel file is that:

```
1st test - added only once
2nd test - added twice
3rd test - added 3 times
```

Too little data, but there is a pattern.  We can do teamviewer.

**Comment by jawlitkp** [comment]
right now? i will send you my id at your email

**Comment by anshooarora** [comment]
Okay

**Comment by jawlitkp** [comment]
Figured out issue,you can close this,thanks for help

**Comment by jawlitkp** [comment]
I was calling this for every test case 

			report.startReporter(ReporterType.DB, System.getProperty("user.dir")+"//DBFiles//extent.db");

 this was creating multiple reports here 

   protected void attach(IReporter reporter) {
        if (reporters == null) {
            reporters = new ArrayList<IReporter>();
        }

        reporters.add(reporter);
        reporter.start(this);
    }
  

and this code was adding multiple test cases 

        for (IReporter reporter : reporters) {
            reporter.addTest();
        }
