### ISSUE TITLE
TestNG XML Suite - All step logs showing only under first test.

### ISSUE THREAD

**Issue by shanep2300** [anshooarora/extentreports#303]
<b>Moved to separate question from https://github.com/anshooarora/extentreports/issues/264...</b>

I have a feeling it's something I'm easily overlooking. ExtentManager and ExtentTestManager you provided have not been changed.

Here is the main test:  
    
    public class EventsManagerTest implements IRetryAnalyzer
    {   
    protected static ExtentReports extent = ExtentManager.getReporter("test-output/ExtentReport/TestReport.html");
    protected static ExtentTest parent, child;	
	
	@BeforeTest
	public static void createParentNode(ITestContext testName)
	{
		parent = ExtentTestManager.startTest(testName.getName(), "");
	}
	
	@BeforeMethod
	@Parameters({"browser", "url", "user", "password"})
	public static void start(Method method, @Optional String browser, @Optional String url, @Optional String user,
		@Optional String password)
	{
		if (browser.equals("${browser}"))
			browser = defaultBrowser;
		if (url.equals("${url}"))
			url = defaultUrl;
		if (user.equals("${user}"))
			user = defaultUser;
		if (password.equals("${password}"))
			password = defaultPassword;

		currentTest = method.getName();
		currentBrowser = browser;
		currentUrl = url;
		currentUser = user;
		currentPassword = password;

		Driver.initialize(browser);

		child = ExtentTestManager.startTest(currentTest, "");
		parent.appendChild(child);

		LoginPage.goTo();
		LoginPage.login(user, password);

		Log.printTestStart();
	}

	@AfterMethod
	public static void close(ITestResult result)
	{
		Driver.Instance.quit();
		
		Log.printTestEnd();

		if (result.getStatus() == ITestResult.SKIP)
		{
			child.log(LogStatus.SKIP, "Error found. Retrying the test...");
		}
		else if (result.getStatus() == ITestResult.FAILURE)
		{
			child.log(LogStatus.FAIL, result.getThrowable());
		}
		else if (result.getStatus() == ITestResult.SUCCESS)
		{
			child.log(LogStatus.PASS, "Test completed successfully");
		}
		
		extent.endTest(child);
		extent.flush();
	}
	
	@AfterTest
	public static void endParentTest()
	{
		extent.endTest(parent);
		extent.flush();
	}

	@AfterSuite
	public static void closeExtentReport()
	{
		extent.close();
	}

Here is a snippet of the log class:

    public class Log
    {
	public static String screenshotDirectory = System.getProperty("user.dir") + "\\test-output\\screenshots\\";
	private static ExtentTest test = ExtentTestManager.getTest();
	
	public static void screenshot()
	{
		File srcFile = ((TakesScreenshot) Driver.Instance).getScreenshotAs(OutputType.FILE);

		String fileName = EventsManagerTest.getCurrentTest() + ".jpg";
		
		String fileDir = screenshotDirectory + fileName;

		try
		{
			FileUtils.copyFile(srcFile, new File(fileDir));
			
			test.log(LogStatus.INFO, "Snapshot below: " + test.addScreenCapture(screenshotDirectory + fileName));
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}

	public static void printAction(String info)
	{
		System.out.println(info + "...");
		
		test.log(LogStatus.INFO, info + "...");
	}

And this is what the report looks like under the first test:
![ss_000030](https://cloud.githubusercontent.com/assets/16820289/12491955/d15b1ab6-c04b-11e5-9772-47148ae0017b.jpg)

Under the next tests no info steps are seen as they are in the first test:
![ss_000031](https://cloud.githubusercontent.com/assets/16820289/12492017/1e31f10c-c04c-11e5-9264-850f100d092d.jpg)

**Comment by anshooarora** [comment]
You are creating test + logs in your test-suite and ending tests in the listener?

**Comment by shanep2300** [comment]
Currently not using the listener as I can't get it to work with the way my framework is structured. There are a number of functions that happen before @Test and after that breaks the test with the listener included. Doing it manually with your ExtentManager and ExtentTestManager has been the only way that got me to this point.

**Comment by anshooarora** [comment]
Yes, and using both logging and listener will not be beneficial either.  You should use one or the other, as using both is overkill.

**Comment by shanep2300** [comment]
So, then there must be something I'm not seeing to get the logs to work correctly. I have a feeling it's something really dumb but I haven't able to figure it out yet.

**Comment by anshooarora** [comment]
In your `@BeforeTest` and `@AfterTest`, do this:

```
@BeforeTest
public static void createParentNode(ITestContext testName) {
    parent = ExtentManager..getReporter().startTest(testName.getName(), "");
}

@AfterTest
public static void endParentTest() {
    extent.endTest(parent);
    extent.flush();
}
```

**Comment by shanep2300** [comment]
Nothing changed. Still logs under first test.

**Comment by anshooarora** [comment]
In `@AfterMethod`:

```java
@AfterMethod
public static void close(ITestResult result)
{
    Driver.Instance.quit();

    Log.printTestEnd();

    if (result.getStatus() == ITestResult.SKIP)
    {
        child.log(LogStatus.SKIP, "Error found. Retrying the test...");
    }
    else if (result.getStatus() == ITestResult.FAILURE)
    {
        child.log(LogStatus.FAIL, result.getThrowable());
    }
    else if (result.getStatus() == ITestResult.SUCCESS)
    {
        child.log(LogStatus.PASS, "Test completed successfully");
    }

    parent.appendChild(child);
    extent.flush();
}
```

**Comment by shanep2300** [comment]
Same results.

**Comment by anshooarora** [comment]
That's because you are appending in `@BeforeMethod` itself. 

```
    parent.appendChild(child);
```

It should be done when all steps of the child-test are complete.

**Comment by shanep2300** [comment]
Correct. This is what my code looks like now, and I'm still getting the same result as before:

```
    protected static ExtentReports extent = ExtentManager.getReporter("test-output/TestReport.html");
	protected static ExtentTest parent, child;

	@BeforeTest
	public static void createParentNode(ITestContext testName)
	{
		parent = ExtentManager.getReporter().startTest(testName.getName(), "");
	}

	@BeforeMethod
	@Parameters({"browser", "url", "user", "password"})
	public static void start(Method method, @Optional String browser, @Optional String url, @Optional String user,
		@Optional String password)
	{
		if (browser.equals("${browser}"))
			browser = defaultBrowser;
		if (url.equals("${url}"))
			url = defaultUrl;
		if (user.equals("${user}"))
			user = defaultUser;
		if (password.equals("${password}"))
			password = defaultPassword;

		currentTest = method.getName();
		currentBrowser = browser;
		currentUrl = url;
		currentUser = user;
		currentPassword = password;

		Driver.initialize(browser);

		child = ExtentTestManager.startTest(currentTest, "");

		LoginPage.goTo();
		LoginPage.login(user, password);

		Log.printTestStart();
	}

	@AfterMethod
	public static void close(ITestResult result)
	{
		Log.printTestEnd();

		if (result.getStatus() == ITestResult.SKIP)
		{
			Log.takeScreenshot();
			child.log(LogStatus.SKIP, "Error found. Retrying the test...<br><br>");
		}
		else if (result.getStatus() == ITestResult.FAILURE)
		{
			Log.takeScreenshot();
			child.log(LogStatus.FAIL, result.getThrowable());
		}
		else if (result.getStatus() == ITestResult.SUCCESS)
		{
			child.log(LogStatus.PASS, "Test completed successfully");
		}

		parent.appendChild(child);
		extent.flush();

		Driver.Instance.quit();
	}

	@AfterTest
	public static void endParentTest()
	{
		extent.endTest(parent);
		extent.flush();
	}

	@AfterSuite
	public static void closeExtentReport()
	{
		for (String s : Reporter.getOutput())
		{
			extent.setTestRunnerOutput(s);
		}

		extent.close();
	}
```

**Comment by shanep2300** [comment]
So, further playing around with this issue I noticed that only the '@AfterTest' is working correctly. The status of the test is being printed in the correct child. So, then would the problem stem from my log.class? You can see an excerpt of the log class in the OP.

**Comment by shanep2300** [comment]
Figured it out! It was with my log class. I was calling the child parameter wrong from my base test. Had to extend the base test into the log class. I knew it was something really dumb, but it's fixed now. :)

**Comment by ag-yoge** [comment]
Hey @anshooarora ,

First let me Thank for the Wonderful reporting tool. I am a beginner using Extent Reports and  I am facing the Same issues faced by @shanep2300  and i really need help from your side to make things right. Hope u consider my request.

Issues Faced:
1. Unable to Have separate Logs or entries for Different Test Cases. i.e Logs are Getting Appended on to a Single Test Case in the Report.

![screenshot from 2016-10-13 16 08 41](https://cloud.githubusercontent.com/assets/20103581/19346136/6ce0ab6a-915f-11e6-877c-cb765bb0f23b.png)

I am using the Following Setup using TestNG along with Listeners and Extent Version: 2.41.1

I Have a Base Class which is extended by all Test Classes as shown Below.

Base Class of TestNG:

      public static ExtentReports report;
      public static ExtentTest logger;

      @BeforeSuite
      @Parameters({"BrowserName"})
      public void beforeSuite(@Optional("Firefox") String BrowserName) 
	  {
		  date = new Date();
		  SimpleDateFormat ft = new SimpleDateFormat ("dd-MM-yyyy");
		  String TodaysDate = ft.format(date);
		  prop = ResourceBundle.getBundle("DataFile");
		  Driver = Browser_Factory_FSQA_Class.getBrowser(BrowserName);
		  path = "//home//workspace//....//FSQA.ExtentReports//FSQA_ExtentReport_" + TodaysDate;
		  File f=new File(path);
		  if(!f.exists())
		  {
			  report = new ExtentReports(path);
		  }
 	  }
      @BeforeTest
      @Parameters({"BrowserName"})
      public void SetUpConfig(@Optional("Firefox") String BrowserName)
	  {
   		 report = new ExtentReports(path, false,DisplayOrder.NEWEST_FIRST);
		 report.loadConfig(new File("//home//......//extent-config.xml"));
		 report.addSystemInfo("Build-Tag", prop.getString("Build-Tag"))
			  		.addSystemInfo("Selenium ", prop.getString("SelVer"))
					.assignProject(prop.getString("Application"))
					.addSystemInfo("Envirnoment", prop.getString("AppEnvirnoment"))
					.addSystemInfo("Extent", prop.getString("ExtRpVer"));
		 logger = report.startTest(this.getClass().getSimpleName());
		 logger.log(LogStatus.INFO,this.getClass().getSimpleName() +" will Run on "+ BrowserName +" Browser");
		 Driver.get(prop.getString("URL"));
		 Driver.manage().window().maximize();
		 Driver.manage().window().maximize();
		 Driver.manage().timeouts().implicitlyWait(45, TimeUnit.SECONDS);
	  }
      @AfterMethod(alwaysRun=true)
      public void afterMethod(ITestResult result) throws IOException
	  {
		try
		{ 
			if(result.getStatus()==ITestResult.FAILURE)
			{
				String res = captureScreenshot(Driver, result.getName());
				String image= logger.addScreenCapture(res);
				System.out.println(image);
				String TestCaseName = this.getClass().getSimpleName() + " Test Case Failure and Title/Boolean Value Failed";
				logger.log(LogStatus.FAIL, TestCaseName  + logger.addScreenCapture(res));
			}
			else if(result.getStatus()==ITestResult.SUCCESS)
			{
				logger.log(LogStatus.PASS, this.getClass().getSimpleName() + " Test Case Success and Title Verified"); 
			}
			else if(result.getStatus()==ITestResult.SKIP)
			{
				logger.log(LogStatus.SKIP, this.getClass().getSimpleName() + " Test Case Skipped");
			}
		}
		catch(Throwable t)
		{
			logger.log(LogStatus.ERROR,t.getMessage());
	        }      
          }

      public String captureScreenshot(WebDriver Driver, String TestName)
       	{
	   try 
		{
		        date = new Date();
			SimpleDateFormat ft = new SimpleDateFormat ("dd_MM_yyyy");
			String TodaysDate = ft.format(date);
		        TakesScreenshot ts=(TakesScreenshot)Driver;
 			File source=ts.getScreenshotAs(OutputType.FILE);
 			Sc_Destination = prop.getString("SC_Dest")+TestName+"__"+TodaysDate+".png";
 			FileUtils.copyFile(source,new File(Sc_Destination));
 			logger.log(LogStatus.FAIL,image, "Title verification");*/
 			return Sc_Destination;
		} 
		catch (Exception e)
		{
 			System.out.println("Exception while taking screenshot "+e.getMessage());
		} 
	  return Sc_Destination;
	}

      @AfterTest(alwaysRun=true)
	public void AfterTest()
	{
		Driver.close();
		report.endTest(logger);
		report.flush();
	}
	
      @AfterSuite
	 public void AfterSuite()
	{
		  report.close();
		  Driver.quit();
	}


My Test Classes are as Follows:
TC1:

       public classTC1 extends BaseTestNG
      {
      @Test(groups = {"Happy_Path"} , description="TC1")
	public void TestCase1() throws InterruptedException, Exception
	  {
		  logger.log(LogStatus.INFO, " Test Case2 Block Entered");
		  Thread.sleep(4000); 
		  ......
                  ......
		  logger.log(LogStatus.INFO, "Assert Flag Received");
		  Thread.sleep(4000); 
		  Assert.assertTrue(AssertFlag);		
	  }
      }

TC2:
        
      public classTC2 extends BaseTestNG
      {
      @Test(groups = {"Happy_Path"} , description="TC2")
	public void TestCase2() throws InterruptedException, Exception
	  {
		  logger.log(LogStatus.INFO, " Test Case2 Block Entered");
		  Thread.sleep(4000); 
		  ......
                  ......
		   logger.log(LogStatus.INFO, "Assert Flag Received");
		  Thread.sleep(4000); 
		  Assert.assertTrue(AssertFlag);		
	  }
      }

I am Using POM Classes along with TestNG and  running the Testcases using testng.xml.

I am able to generate the Extent Report but unable to Differentiate Between TC1 & TC2 Logs i.e all test Case logs are getting appended to single TestCase  as shown in the Above Screen Shot.
I want each Test Case Logs/Entry in separate rows in the Extent Reports.  

Can u please rectify the mistake in my code and help me out. 
Thanks in Advance!!!
