### ISSUE TITLE
Issue: Category drop down not showing list of categories for extent merge

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#304]
On clicking on dropdown nothing happening.

<img width="668" alt="mergeissue" src="https://cloud.githubusercontent.com/assets/9873362/12601552/dcf8fdfc-c46f-11e5-8139-2b6b0f03c7aa.png">

**Comment by anshooarora** [comment]
This wasn't implemented in this alpha, will be in next..

**Comment by jawlitkp** [comment]
Any ETA on this ?

**Comment by anshooarora** [comment]
No ETA.

**Comment by jawlitkp** [comment]
Not a problem ,thanks

**Comment by anshooarora** [comment]
FYI - https://github.com/anshooarora/extentreports/issues/331#issuecomment-184383807

**Comment by anshooarora** [comment]
Initial sample of extentx:  https://extentx.herokuapp.com/

Ability to update the server will be available in the next Extent version and you will also be able to deploy the server.
