### ISSUE TITLE
Enhancement:Display planned test cases(Expected) for execution

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#305]
Hi Anshoo,

Would you be able to add extra display for total test cases planned for execution, so lets say at beginning i should be able to pass totalPlannedTestCases number and it should display as below ,so at the end or during run time i should be able to figure the difference b/n totalPlannedTestCasesExpected and totalPlannedTestCasesActual.

I am creating below report when first test cases is reported to DB and then just refreshing browser gives me updated results ,so i wanted to see difference that how many executed and how many remaining 

Also is there anyway i can add custom code to refresh report automatically.

![totaltestcases](https://cloud.githubusercontent.com/assets/9873362/12618147/ad40682c-c4e0-11e5-824a-7c7d0a5d581b.png)

**Comment by jawlitkp** [comment]
<script>
     var time = new Date().getTime();
     $(document.body).bind("mousemove keypress", function(e) {
         time = new Date().getTime();
     });

    Something like this 


 function refresh() {
         if(new Date().getTime() - time >= 60000) 
             window.location.reload(true);
         else 
             setTimeout(refresh, 10000);
     }

     setTimeout(refresh, 10000);
</script>

**Comment by jawlitkp** [comment]
what if i put above code and add to js file and execute below command ?will it do auto refresh ?

java -jar extentmerge.jar -dir "location" -out "extent.html" -js-file "script.js"

**Comment by anshooarora** [comment]
This would be too specific, but can be easily added via js.  First, you will have to add the heading `th` and a `td` element corresponding to the same index as shown [here](http://stackoverflow.com/questions/1075415/jquery-add-html-table-column).
