### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder" 

### ISSUE THREAD

**Issue by VinitSandesara** [anshooarora/extentreports#306]
Hi Anshoo, I am learning extentReport and planning to use in one my project can you please help me to resolve below error. I have most recent extentReport.jar

java.lang.NoClassDefFoundError: freemarker/ext/beans/BeansWrapperBuilder

When i run testng.xml i am getting above error msg.

I also have freemaker.jar added in my lib folder which you can in below screenshot

![screen shot 2016-01-27 at 2 51 36 pm](https://cloud.githubusercontent.com/assets/12589206/12627834/a46afb0c-c505-11e5-843b-3e52ff3d353e.png)

![screen shot 2016-01-27 at 2 39 13 pm](https://cloud.githubusercontent.com/assets/12589206/12627607/693f0f24-c504-11e5-9b49-916b2f062c96.png)

![screen shot 2016-01-27 at 2 39 22 pm](https://cloud.githubusercontent.com/assets/12589206/12627612/6e95ac6c-c504-11e5-923c-fb86f4e38b4a.png)

![screen shot 2016-01-27 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/12589206/12627615/7833d06e-c504-11e5-8a46-efe071f2e864.png)

![screen shot 2016-01-27 at 2 39 34 pm](https://cloud.githubusercontent.com/assets/12589206/12627619/7bba472c-c504-11e5-8226-4ee511884581.png)

![screen shot 2016-01-27 at 2 56 16 pm](https://cloud.githubusercontent.com/assets/12589206/12627926/39c76b04-c506-11e5-835a-3cd1bf237964.png)

Thanks
Vinit

**Comment by anshooarora** [comment]
You are missing the freemarker.jar.  Please see [here](https://github.com/anshooarora/extentreports/issues/217#issuecomment-167883867).

**Comment by oligee80** [comment]
add this to your pom.xml or add the freemarker.jar:

<dependency>
  <groupId>org.freemarker</groupId>
  <artifactId>freemarker</artifactId>
  <version>2.3.23</version>
</dependency>

previous freemarker versions don't have the class BeansWrapperBuilder, so plz correct the dependencies of extent reports!

**Comment by rahul9892** [comment]
Hi anshoo,

I am getting the same type of error when i am trying to configure extent reports please suggest me if the above issue is resolved or NOT.? If resolved, how it is resolved.
