### ISSUE TITLE
Extent Report with CI

### ISSUE THREAD

**Issue by VaibhavRepo** [anshooarora/extentreports#308]
I am using HTML publisher plugin in Jenkins, and generating opening Extent Report.
By Report generated with Jenkin don't have UI. However when I open then manually they opens just fine.

![image](https://cloud.githubusercontent.com/assets/16337574/12636748/6aeb5f92-c5b5-11e5-967a-24c79732d535.png)

**Comment by anshooarora** [comment]
Its a Jenkins setting.  See [this comment](https://github.com/anshooarora/extentreports/issues/290#issuecomment-173133373).
