### ISSUE TITLE
Maybe not an issue, but I didn't see a way to do this...

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#31]
I'd like to push ALL failed tests to the top of the summary report. Is this available by default?

I'm using this a listener against a suite of tests.

The tests show up, but I see

Fail,
pass
pass
pass
Fail

I'd like to be able to show
FAIL,
FAIL, 
pass 
pass etc

And sort by default on FAIL (top of list)

**Comment by anshooarora** [comment]
Chris.. Only way possible at present is if you filter failed tests but that will hide everything else.

**Comment by cktech529** [comment]
I came up with a way (not quite clean)

    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = new ExtentReports(outputDirectory + File.separator + "Extent.html", true);
 
        System.out.println("Hit Method: generateReport ");
       
        // Put Failures on top of the report
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults(); 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                buildTestNodes(context.getFailedTests(), LogStatus.FAIL, r);
            }
        }
        
        // Skipped
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults(); 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                buildTestNodes(context.getSkippedTests(), LogStatus.SKIP, r);
            }
        }
        
        // Passed
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults(); 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                buildTestNodes(context.getPassedTests(), LogStatus.PASS, r);
            }
        }
        
        extent.flush();
    }

**Comment by anshooarora** [comment]
Great!

**Comment by anshooarora** [comment]
Chris - can this issue be closed?

**Comment by cktech529** [comment]
YES, thanks.

Chris
