### ISSUE TITLE
ExtentMerge reports - is it possible to display the name for reports?(Question)

### ISSUE THREAD

**Issue by soundaryavijendran** [anshooarora/extentreports#312]
![](http://extentreports.relevantcodes.com/extentmerge/img/analysis.png)

For Example in the ExtentMerge report, under reports sections we have date and timestamp for different test suites, is it possible to get the name of them? is there a config to sets this value.

**Comment by mukaram453** [comment]
Yes, This is what I am looking in the  ExtentMerge report, to get the name of the test suites instead of timestamp.

Also, I noticed that the dates of different test suites are not in order.

![image](https://cloud.githubusercontent.com/assets/9412497/12743148/de0b6580-c9b1-11e5-8457-0c4e5c409bb9.png)

**Comment by mukaram453** [comment]
Please note that i have used Bae64 String for image conversion and embedded the Base64 string

**Comment by anshooarora** [comment]
The only issue is, a report can be of the same name but reside in different folders in which case all names would be the same.  Also, users merging reports from database will not be able to use a name either.

**Comment by soundaryavijendran** [comment]
Thats true but when we merge is it possible to assign a different name? if we merge reports from different tests to get a master report to show all the information displaying date and timestamp alone doesn't give a clear view in the dashboard, if you have some suggestion, let me know.

Scenario - lets say we need a merge report G from report A,B and C and A,B,C all are different test features but belong to same project when we merge since its displays only timestamp its bit difficult to understand which is test result for A,B or C if we display the name it will be more clear to understand. Thanks

**Comment by anshooarora** [comment]
Closing this as ExtentMerge is deprecated, ExtentX will be the replacement and this feature will be available.
