### ISSUE TITLE
Can I get the single HTML Report while executing the more than one class in the Test Suit

### ISSUE THREAD

**Issue by anil8191** [anshooarora/extentreports#314]
Hi,
  I have Two class "A" and "B", and while executing the Test Suit then report is generating different different for both classes.
Suppose in class "A" have 4 test case and class "B" have 6 Test case then two HTML Report will Generate and in the 1st Report will display 4 Test Case and 2nd Report will display 6 Test case details.

Now my question is : can I get the single HTML Report for all the classes doesn't matter how many classes is available is the xml file while executing the Test Suit.

**Comment by testphreak** [comment]
Create the report file only once before all the tests are run. You can do this in @BeforeSuite (assuming you are using TestNG). Take a look at a basic example here. Since it appears that you're running your tests in parallel, look at the examples here - http://extentreports.relevantcodes.com/java/version2/docs.html#parallel-runs

**Comment by anil8191** [comment]
Still I'm not able to get the single HTML report in ExtentReport for TestNG.

**Comment by anil8191** [comment]
Please, can solve this issue which I ask before comments, I need that immediately

**Comment by anshooarora** [comment]
How are you instantiating Extent?  Share your  code?

**Comment by anil8191** [comment]
Thank you Anshoo for responding my request.
 please check the below code.
--------------------------------------------- Extent report code -------------------------------------------------------
public class NewReports {
	
	public static ExtentReports report;
	public static ExtentTest logger; 
	public static NewBrowserClass browser = new NewBrowserClass();
	
      @BeforeClass
	public static ExtentReports launch(){
		
		//browser.createfolder();  //Creating a new folder.
		
		String destFile=null;
		DateFormat dateFormat = new SimpleDateFormat("yyyy.MM.dd HH-mm-ss");
		destFile = "D:\\new framework selenium\\testauto_project_V2.1\\Report";
		String destDir = dateFormat.format(new Date()) + ".html";
		report = new ExtentReports(destFile + "\\" +destDir, true);
		
		// Detail of the Report Title, Name and HeadLine
		report.config().documentTitle("AKumar Report");			 //This is Report Title
		report.config().reportName("AKA VTiger");				//This is Report Name
		report.config().reportHeadline("[ AK Application ]");	//This is Report Headline
		
		return report;
	}
	@AfterMethod
	public void reportclosewindows() throws IOException, InterruptedException{
		report.endTest(logger);
		report.flush();
	}}
----------------------------------------------------------------------------------------------------------------------------

logger.log(LogStatus.FAIL, "Validation Start...");
logger.log(LogStatus.PASS, "Validation Start...");
logger.log(LogStatus.INFO, "Validation Start...");

like this I'm using this report in the class file getting the report.
Note : I'm using TestNG annotation.
So always after the test case I'm using the report.flus() method so that all the report information will write in the HTML file .

Now My issue is, I have more than two class file, suppose in class "A" has 5 test case and class "B" has 6 test case but while running the **testng.xml**  file then report is generating separate separate HTML file, it means always generating two HTML report 1st is for class "A" 5 test case and 2nd is for class "B" 6 test case, 
        But I want the report consolidated report ie only one HTML report, and I want in that report all the test cases should present doesn't matter how many classes i mention in the xml file. 
Please check my xml file below : - 

----------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" >
  <test name="Test">
    <classes>
      <class name="test.app.page.VTigerProductPage"/>
      <class name="test.app.page.VTigerContactPage"/>
    </classes>
  </test> 
</suite> 
----------------------------------------------------------------------------------------------------------------------------

In 1st class I have 5 TestNG method and in 2nd class i have 6 TestNG method, but report is generating separate separate class wise.

Please respond immediately

Thank You
Best Regards
Anil Kumar.

**Comment by anshooarora** [comment]
See @testphreak reponse above.  You should instantiate Extent in `BeforeSuite` instead of `BeforeClass`.

**Comment by anil8191** [comment]
Thank you Anshoo for responding my request.
Now my code is running fine as my expected, and I'm getting single report
Thank you soooo much for helping this.
--------------------------------------------------------------------------

How to take screenshot/screencast with the help of extent report
I used below code please check this, I'm not able to record the script, 

--------------------------------------------------------------------------------------------------------------------------
logger.log(LogStatus.INFO, "Snapshot below: " + logger.addScreenCapture(destFile));
logger.log(LogStatus.INFO, "Screencast below: " + logger.addScreencast(destDir));
--------------------------------------------------------------------------------------------------------------------------

taking screenshot is happening but in the HTML report screenshot is displaying unformatted image and after clicking on it, image is not displaying.
    so please help out can I take screenshot as well recording also.

Thank you
Best Regards
Anil Kumar.

**Comment by anil8191** [comment]
Hi Anshoo,
   Please reply the above query.

**Comment by testphreak** [comment]
Do some research by looking at past issues here. I don't have an answer for you regarding adding screen casts as I haven't implemented it, but adding screen shots has been discussed here before.

As Anshoo has already said, share what you have tried so far, so more folks who may have run into similar problems can help you.

**Comment by ManojMN** [comment]
Hi Anshooarora,

I am working on selenium C# and able to run test case parallelly using [Parallelisable], But Extent report is generating with error status . Can you please suggest how to handle this.

**Comment by mbn217** [comment]
try this 



	@AfterMethod
	public void tearDown

	(ITestResult testResult) throws IOException {
		if

		(testResult.getStatus() == ITestResult.FAILURE) {

			String path = Screenshots.takeScreenshot(driver, testResult.getName());

			String imagePath = test.addScreenCapture(path);

			test.log(LogStatus.FAIL, "Verify Welcome Text Failed", imagePath);

		}
		driver.quit();
		report.endTest(test);

		report.flush();
	}

**Comment by g-tiwari** [comment]
Hey Anshooarora,

Can you guide, which library/jar files I have to include in my build path to use KlovReports?
