### ISSUE TITLE
Incorrect Total Time Taken values in reports generated via Listener

### ISSUE THREAD

**Issue by MegaUkrainian** [anshooarora/extentreports#316]
Hi,

Total Time Taken values are incorrect after generating report via Listener
check the screenshot
![selection_024](https://cloud.githubusercontent.com/assets/13480390/12744910/832e00e4-c99f-11e5-8a32-7f3a3c2d8430.jpg)

version 2.40.1

**Comment by karthikbhatnagar** [comment]
i tested with this version and i get this result:

![listener](https://cloud.githubusercontent.com/assets/12984254/12754503/1fe00860-c991-11e5-9155-5c570703eab8.png)


you can do mvn clean, add all jars and check

fyi - i am using jar from extentreports website

**Comment by MegaUkrainian** [comment]
Are you using Listener?
http://extentreports.relevantcodes.com/java/version2/docs.html#testng-listener

**Comment by karthikbhatnagar** [comment]
yes

**Comment by anshooarora** [comment]
I am also unable to reproduce.

**Comment by MegaUkrainian** [comment]
I use version from maven repo. Also, I have reverted all my scripts from extent config file, turned on online mode, but the issue is still observed.

**Comment by Noaptea** [comment]
Hi,
Also have the total time issue when used as listener.
I added the testng reported time, for comparison.

![extent](https://cloud.githubusercontent.com/assets/13394600/13046152/e6eeabc0-d3df-11e5-8368-bf9145995d9a.jpg)

Can't you just simply change the algorithm to calculate the total time by subtracting the start time from the end time ?

**Comment by anshooarora** [comment]
I am still unable to reproduce.  New version (beta) available, can you check with that once?  2.40.2-beta1 - from extent homepage, will upload snapshot version tomorrow.

**Comment by Noaptea** [comment]
Hello again, maybe this helps:
My setup is a test suite containing two test classes and I have also set the flag "parallel" to "false".

**Comment by guneetgarg** [comment]
Just add few test script and use extent as testng listener

**Comment by anshooarora** [comment]
Can you check with v2.40.2-beta2 also?

**Comment by karthikbhatnagar** [comment]
I just tested, very nice dark theme :)

**Comment by anshooarora** [comment]
Can you check with 2.40.2.  This is fixed.

**Comment by Noaptea** [comment]
I upgraded to 2.40.2. Time is now correct. 
Thank you Anshoo.
