### ISSUE TITLE
Hosting the Merged Report

### ISSUE THREAD

**Issue by jsudhi** [anshooarora/extentreports#317]
Hello,

Now that I have the merged report, how do I host this file ? I would like to keep it updating all the time, so that when team checks, it should show the recent results along with the history. Some thing like a Dashboard.

If someone has tried similar approach, please share.

Thanks
Sudhi

**Comment by jawlitkp** [comment]
I have created .sh script and executing it at the end of execution using java code.

#!/bin/bash
DIR=$1
RESULT=$2

cd  ~/Jars
java -jar extentmerge.jar -dir $DIR -out $RESULT
