### ISSUE TITLE
i am unable to generate report in particular location & another issues is i am not getting get () function why

### ISSUE THREAD

**Issue by akashgupta11** [anshooarora/extentreports#319]
package Example;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class reports {
	WebDriver driver;
  @Test
  public void f() {
	 ExtentReports logger=new ExtentReports("D:\\report", true);
	  ExtentTest t=logger.startTest("f");
	driver=new FirefoxDriver();
	driver.manage().window().maximize();
	t.log(LogStatus.INFO, "browser is up and running");
  }
}

**Comment by anshooarora** [comment]
I would recommend checking the [docs](http://extentreports.relevantcodes.com/java/version2/docs.html#basic-usage-example) as your usage is not entirely complete.
