### ISSUE TITLE
Manually updated test times (start / end time report issues)

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#32]
When you use extent reports as a listener, the report is generated at the end of the run

When this occurs I'm seeing:

2015-07-29 15:43:422015-07-29 15:43:420h 0m 0s (for all Failed and Passed tests)

I do see differences in the actual result data though:

Maybe a manually setter for the start/ end times on a given test?

import java.io.File;
import java.util.List;
import java.util.Map;
import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;
import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
 
public class ExtentReporterNG implements IReporter {
    private ExtentReports extent;
 
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
        extent = new ExtentReports(outputDirectory + File.separator + "Extent.html", true);
 
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults();
 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext(); 
                buildTestNodes(context.getFailedTests(), LogStatus.FAIL, r);
                buildTestNodes(context.getSkippedTests(), LogStatus.SKIP, r);
                buildTestNodes(context.getPassedTests(), LogStatus.PASS, r);
                System.out.println("ISuiteResult " + r.toString() + " - " + r.getTestContext().getSuite().getName());
                System.out.println("ITestContext " + context.getName());
            }
        }
        System.out.println("Hit Method: generateReport ");
        extent.flush();
    }
 
    private void buildTestNodes(IResultMap tests, LogStatus status, ISuiteResult suiteResult) {
        
    	ExtentTest test;
    
        if (tests.size() > 0) {
        	System.out.println("Hit Method: buildTestNodes (size > 0)");
            for (ITestResult result : tests.getAllResults()) {
            	System.out.println("Result Start - " + result.getStartMillis());
            	System.out.println("Result End - " + result.getEndMillis());
            	System.out.println("Result String Rep... " + result.toString());
                test = extent.startTest(suiteResult.getTestContext().getSuite().getName());
                String message = "Test " + status.toString().toLowerCase() + "ed"; 
                if (result.getThrowable() != null)
                    message = result.getThrowable().getMessage(); 
                test.log(status, message);
                extent.endTest(test);
            }
        }        
    }
}

[selenium:testng] Result Start - 1438264421634
[selenium:testng] Result End - 1438264513124

**Comment by anshooarora** [comment]
Chris

The <code>getTest()</code> method exposes the internals which you can use to override the start and end times, along with several other properties:  https://github.com/anshooarora/extentreports/blob/master/java/2.x/src/com/relevantcodes/extentreports/model/Test.java

```
test.getTest().startedTime = startedTimeFromTestNG;
test.getTest().endedTime = endedTimeFromTestNG;
```

**Comment by cktech529** [comment]
Thanks!!!! Sorry about the "Non issue" :)

I will test it. 

Chris

**Comment by anshooarora** [comment]
The type for both fields is Date, so you can maybe try this:  http://stackoverflow.com/questions/8262333/how-to-convert-seconds-into-date-and-time-format-in-java

**Comment by anshooarora** [comment]
Chris

try this:

```
private void buildTestNodes(IResultMap tests, LogStatus status) {
    ExtentTest test;
    
    if (tests.size() > 0) {
        for (ITestResult result : tests.getAllResults()) {
            test = extent.startTest(result.getMethod().getMethodName());
            
            test.getTest().startedTime = new Date(result.getStartMillis());
            test.getTest().endedTime = new Date(result.getEndMillis());
            
            for (String group : result.getMethod().getGroups())
                test.assignCategory(group);
            
            String message = "Test " + status.toString().toLowerCase() + "ed";
            
            if (result.getThrowable() != null)
                message = result.getThrowable().getMessage();
            
            test.log(status, message);
            
            extent.endTest(test);
        }
    }
}
```

**Comment by cktech529** [comment]
Thanks,

That does put times under each test, but the total time doesn't get calculated above:

Total time taken: 0m 0s

Chris

**Comment by anshooarora** [comment]
Chris, no direct way of doing this right now.. you can add the following js for now:

```
String js = "$(document).ready(function() {var dates=[];$('.test-started-time, .test-ended-time').each(function() { dates.push(new Date($(this).text().replace('-', '/').replace('-', '/'))); });var maxDate=new Date(Math.max.apply(null,dates));var minDate=new Date(Math.min.apply(null,dates));$('.suite-started-time').text(minDate.toLocaleFormat('%Y-%m-%d %H:%M:%S'));$('.suite-ended-time').text(maxDate.toLocaleFormat('%Y-%m-%d %H:%M:%S'));function newFunc() {var ended = $('.suite-ended-time').text().replace('-', '/').replace('-', '/');var started = $('.suite-started-time').text().replace('-', '/').replace('-', '/');var diff = new Date(new Date(ended) - new Date(started));var hours = Math.floor(diff / 36e5),minutes = Math.floor(diff % 36e5 / 60000),seconds = Math.floor(diff % 60000 / 1000);$('.suite-total-time-taken').text(hours + 'h ' + minutes + 'm ' + seconds + 's');} newFunc();})";
extent.config().insertJs(js);
```

**Comment by anshooarora** [comment]
Chris,

Actually, no need to use the messy js route.

Can you please test with this jar file instead:  http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.031.zip

Minor release - has all the time fixes.. 

If it works for you, I will make it public from the downloads section.

**Comment by cktech529** [comment]
Testing now. Thanks!

**Comment by cktech529** [comment]
Looks good. Where's the source. quite curious and thanks again!

**Comment by anshooarora** [comment]
The updated source is here:  https://github.com/anshooarora/extentreports/commit/ad6b91d1e9a0fff5fa2c6779e822ed7e1d92ddc2#diff-def0ab97dc9c375e2d8b42f18a3cea3bR971

Lines 971 - 994.

**Comment by srpramod** [comment]
Hi Anshoo, 
I am trying to implement the logs
logger.log(LogStatus.INFO, "Pass the URL ");
into the test scripts, so that these logs can be observed in the HTML report. But i want to implement as method and call it in test scripts. It was very helpful with your method to get the HTML report in the same I am trying to implement the method for log. Could you please help me this.
