### ISSUE TITLE
NullPointerException when flushing with nothing in report

### ISSUE THREAD

**Issue by JonathanAstre-accor** [anshooarora/extentreports#320]
new ExtentReports(filePath, true).flush() throw a NullPointerException

Is it normal ?

**Comment by anshooarora** [comment]
It shouldn't but it won't also write anything to the file-system as there are no tests available.  So if there are no tests, a report will not be created.

**Comment by anshooarora** [comment]
Fixed in 2.40.2-beta1.

**Comment by virenv** [comment]
Can see this failure in 2.41.0 jar. The code change with this bug does not suggest that nullptr exception should have been fixed.

**Comment by virenv** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.relevantcodes.extentreports.Report.terminate(Report.java:417)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:919)
	at Configurations.program.main(program.java:14)

This is where we are getting null. testList is not initialised by the time if you do following 
		
		ExtentReports reporter = new ExtentReports("sample.html", true);
		reporter.flush();
		reporter.close();
Was this some other nullptr?
