### ISSUE TITLE
when using ExtentTest startTest, is it possible to only flush passed tests (excluding failed tests)

### ISSUE THREAD

**Issue by hdomi001** [anshooarora/extentreports#324]
When creating a new ExtentTest, flush()  is used to write the tests onto the report document. Is it possible to have a flush that only writes passed data to the document? 

The reason i am trying to do this is because, if the tests failed then i re-run them. Therefore, if the test run is the original run, then i only want to write those that passed into the report document. However, if its a re-run test, then i want to flush all tests (passed/failed/etc). 

Something like, 

flush("PASSED")
flush("ALL")

**Comment by testphreak** [comment]
The use case seems a little vague. Why would anyone not want to report failed tests, first run or re-run? Any reporting framework should report results **as is** without any superficial modification. I don't think it is the job of ExtentReports to allow you to report only certain test results.

**Comment by hdomi001** [comment]
Yeah i understand that. However, I am having trouble with the following scenario: 

Lets say we have 
3 Total Tests running, 1 Passed and 2 Failed. = 33% pass percentage
2 are then re-ran. 1 Passed and 1 Failed.

which Pass percentage would the best to display? after the execution is done, the Report would show we ran 5 Tests (3 Total Tests + 2 Re-runs) and shows we have 2 Passed and 3 Failed = 40% Pass percentage. But In reality we know that 2 Test were passed and 1 was Failed after the re-runs was completed = 67% Pass percentage

**Comment by testphreak** [comment]
Each run if running say for example in Maven, generates a new report. So after first run, the report would show 1 pass and 2 failures. In the re-run, another report gets generated that would show 1 pass and 1 failure.

If you are running your project in Maven, then you could I guess write a script for your CI run in Bamboo, Jenkins etc to store the total number of tests at the start of the **first run**, then scrape the log for the test results at the end of your **second run** and finally do your percentage calculation of 1 out of [total tests] failed.

Or you could leverage [ExtentMerge](http://extentreports.relevantcodes.com/extentmerge/docs.html) to aggregate results across multiple runs and do some calculations on it. I haven't used ExtentMerge, but that should be possible.

**Comment by anshooarora** [comment]
@testphreak answered it already, but I would only like to add that this is a feature that you won't see in any reporting tool, Extent is the same case.  Reporting should report as-is what happened during a run session.  

There is an existing request to add feature to override already run tests, but that feature won't be available for the very same reason - to let the users know that the test passed in its 2nd or 3rd trial.  It may skew result statistics depending on how to view them, but what's reported is exactly what happened while tests ran.

**Comment by hdomi001** [comment]
Thanks for the feedback @testphreak and @anshooarora . I was able to reproduce my output by having a Global Hash Table and adding the Extenttest and test number as key and value whenever a test would fail to keep the Extenttest instance saved. In the run, i just add the re-run instance as appendChild to the original instance and remove it from the hash table. Seems to work as expected :)
