### ISSUE TITLE
Malware in Extent Reports JAR file

### ISSUE THREAD

**Issue by bravehart84** [anshooarora/extentreports#326]
Hello,

I tried to download required JAR file from your website link "ExtentReports Java 2.40.1 (7655)", but I keep getting a notification of suspected malware from my windows defender, so I'm unable to use the jar files. Please can you look into this issue as I'm scared of getting a virus from your site?

**Comment by anshooarora** [comment]
Not having this issue:

![scan](https://cloud.githubusercontent.com/assets/4107384/12919426/9d8b4a54-cf09-11e5-8b5a-4e0be09acd4b.png)

Can you download maven package if you continue to have this?
