### ISSUE TITLE
How to display the OS name in the test report

### ISSUE THREAD

**Issue by jayadevmootha** [anshooarora/extentreports#327]
Hi, I am new to extent reports. Recently I have implemented extent reporting in our framework. The issue is when we execute the tests on the selenium grid (or sauce grid) for different platforms and OS, the extent report does not show the OS and Platform details for tests that executed on. My question is how to show the OS and platform details for each testcase in the report.

e.g. I have executed 25 test cases on IE 7/Windows-7 platform and 25 tests cases on chrome/Windows 8.1 platform. I want the OS platform details along with each test case in the report.  How implement this ?

**Comment by anshooarora** [comment]
You can assign categories to your tests with OS-Name and Browser.  Example [here](http://extentreports.relevantcodes.com/java/version2/docs.html#assign-category).
