### ISSUE TITLE
Not able to run the project in eclipse using testng.xml after upgrading jar from 2.40 to 2.40.1

### ISSUE THREAD

**Issue by VinitSandesara** [anshooarora/extentreports#329]
After upgrading extentReport jar from 2.40 to 2.40.1 i am NOT able to run the project in eclipse using testng.xml getting some configuration failure, can someone please help on this

***********************************************************************************************************
Note : If i continue using 2.40 version i am getting "FreeMarker template error:" which can resolved after upgrading to 2.40.1 

***********************************************************************************************************

[TestNG] Running:
  /Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/testng.xml

creating directory: Logs
DIR created
creating directory: ADBLogs
DIR created
adb service already started
Following device is connected
e9739647 samsung SM-G900P 4.4.2

Following device is connected
HT35WW918326 htc HTCOne 5.0.2

e9739647
Directory is created!
Device Serial Directory is created!
HT35WW918326
Device Serial Directory is created!
Total Number of devices detected::2
starting running tests in threads
forEach: true
forEach: true
Running test file: apps.sears.tests.LoginTest
Into TestNGRunner
Running test file: apps.sears.tests.searchTest
Into TestNGRunner
[TestNG] Running:
  Command line suite

[TestNG] Running:
  Command line suite

adb service already started
adb service already started
*************pool-2-thread-1
******Running Test in Distributed Way******1
Starting Appium Server
e9739647
*************pool-2-thread-2
******Running Test in Distributed Way******2
Starting Appium Server
HT35WW918326
[36minfo[39m: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)
[36minfo[39m: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)
[36minfo[39m: Appium REST http interface listener started on 0.0.0.0:53449
[36minfo[39m: Appium REST http interface listener started on 0.0.0.0:53448
[36minfo[39m: Console LogLevel: info
[36minfo[39m: File LogLevel: info
[36minfo[39m: Console LogLevel: info
[36minfo[39m: File LogLevel: info
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
[36minfo[39m: [37m<-- GET /wd/hub/status [39m[32m200[39m[90m 9.145 ms - 104[39m [90m{"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
true
io.appium.java_client.service.local.AppiumServiceBuilder@4368ee96
[36minfo[39m: [37m<-- GET /wd/hub/status [39m[32m200[39m[90m 3.576 ms - 104[39m [90m{"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
[36minfo[39m: [37m<-- GET /wd/hub/status [39m[32m200[39m[90m 18.985 ms - 104[39m [90m{"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m [90m{}[39m
true
io.appium.java_client.service.local.AppiumServiceBuilder@58f15779
[36minfo[39m: [37m<-- GET /wd/hub/status [39m[32m200[39m[90m 3.742 ms - 104[39m [90m{"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk","appWaitActivity":"","platformName":"Android","deviceName":"Android","platformVersion":"5.X"}}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk","appWaitActivity":"","platformName":"Android","deviceName":"Android","platformVersion":"5.X"}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
[36minfo[39m: Starting android appium
[36minfo[39m: Starting android appium
[36minfo[39m: Java version is: 1.8.0_25
[36minfo[39m: Java version is: 1.8.0_25
[[36minfo[39m3:6 mRientfroie[v3i9nmg:  dReevtirciee
ving device
[36minfo[39m: Found device e9739647
[36minfo[39m: Found device HT35WW918326
[36minfo[39m: Device API level is: 21
[36minfo[39m: Device API level is: 19
[33mwarn[39m: Could not get strings, continuing anyway
[36minfo[39m: App is already installed, resetting app
[36minfo[39m: App is already installed, resetting app
[36minfo[39m: Starting App
[36minfo[39m: Starting App
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[36m303[39m[90m 13207.550 ms - 74[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/74f6ff0c-a142-4889-b0c4-c48113f76a67[39m [90m{}[39m
[36minfo[39m: [37m<-- GET /wd/hub/session/74f6ff0c-a142-4889-b0c4-c48113f76a67 [39m[32m200[39m[90m 3.262 ms - 672[39m [90m{"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk","appWaitActivity":"","platformName":"Android","deviceName":"Android","platformVersion":"5.X"},"app":"/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk","appWaitActivity":"","platformName":"Android","deviceName":"HT35WW918326"},"sessionId":"74f6ff0c-a142-4889-b0c4-c48113f76a67"}[39m
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[36m303[39m[90m 13437.748 ms - 74[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/a0a6f7c1-2f13-447f-b14f-67d78e3fca55[39m [90m{}[39m
[36minfo[39m: [37m<-- GET /wd/hub/session/a0a6f7c1-2f13-447f-b14f-67d78e3fca55 [39m[32m200[39m[90m 7.347 ms - 668[39m [90m{"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk","appWaitActivity":"","platformName":"Android","deviceName":"Android","platformVersion":"5.X"},"app":"/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk","appWaitActivity":"","platformName":"Android","deviceName":"e9739647"},"sessionId":"a0a6f7c1-2f13-447f-b14f-67d78e3fca55"}[39m
/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps

===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 2
Configuration Failures: 1, Skips: 5
===============================================

===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 2
Configuration Failures: 1, Skips: 5
===============================================

ending

===============================================
Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

**Comment by anshooarora** [comment]
You will have to rebuild your project, do a maven clean, remove all manually added jars used by Extent (freemarker, xerial sql lite, jsoup).  This is a project configuration error, your best bet would be to ask this question on StackOverflow or other forums.

**Comment by VinitSandesara** [comment]
Hi Anshoo, I have rebuilt my project, did a maven clean, removed all existing jars downloaded using maven, did mvn eclipse:eclipse again to re-download jars but still getting same error with 2.40.1 version, if i switch it back to 2.40 it works fine. 

Also with 2.40.1 it works fine when i run the project on terminal using pom.xml maven command, then why only issue is when i try to run it from eclipse using testing.xml.

Thanks
Vinit
