### ISSUE TITLE
Typo in docs? extent.log doesn't seem to exist....

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#33]
Inserting custom HTML
Simply insert any custom HTML in the logs by using an HTML tag:

extent.log(LogStatus.INFO, "HTML", "Usage: <span style='font-weight:bold;'>BOLD TEXT</span>");

**Comment by anshooarora** [comment]
Chris,  this is now fixed.

http://extentreports.relevantcodes.com/1x/docs.html#add-html

**Comment by cktech529** [comment]
I still see extent.log there...

**Comment by anshooarora** [comment]
Really fixed now :)

Had corrected the HTML source but forgot to correct extent to test.

**Comment by cktech529** [comment]
Excellent, let me know if these posts are bothering folks :-D

**Comment by anshooarora** [comment]
Closing ticket as issues fixed with docs.
