### ISSUE TITLE
Compare results in ExtentMerge

### ISSUE THREAD

**Issue by email2vimalraj** [anshooarora/extentreports#330]
This would be cool if we can implement it.

1. Many runs
2. Merge the results using ExtentMerge
3. In the merged html, select the runs and click compare.
4. The comparison should show list of test cases between selected runs and the status of each test cases, if mismatches between status should highlight. If a particular test case is failed in all the runs, the stack trace / error log comparison.

**Comment by anshooarora** [comment]
FYI - https://github.com/anshooarora/extentreports/issues/331#issuecomment-184383807

**Comment by email2vimalraj** [comment]
Great. I'm a javascript (nodejs, angular) developer. Let me know if you need any contribution from my side. I've done similar thing on my current organization using nodejs, angular and mongodb.

**Comment by anshooarora** [comment]
Thanks, very good to know.  Would love to have contributions.  I will push the initial build sometime next week here:  https://github.com/anshooarora/extentx.  I am currently using SailsJs + MongoDb + jQuery + Semantic UI + eJS.

**Comment by email2vimalraj** [comment]
Waiting for the initial build.

**Comment by anshooarora** [comment]
Initial sample of extentx: https://extentx.herokuapp.com/

Ability to update the server will be available in the next Extent version and you will also be able to deploy the server.

**Comment by email2vimalraj** [comment]
Great @anshooarora. I forked extentX and will start work on few UI updates. Let me know if you have some requirements jotted down.

**Comment by anshooarora** [comment]
I have converted most of the features on the Merge tool over, but lots of UI improvements are required as most of my effort was on the server side.  I made some improvements this morning (new font) etc. and will push changes soon.  

Feel free to commit and suggest any improvements - would really help this project grow.

**Comment by email2vimalraj** [comment]
Do we have any chat tool use to communicate between developers? If not, can we setup the [Gitter](https://gitter.im) for this project and extentX. What are your thoughts?

**Comment by anshooarora** [comment]
Done for both projects.
