### ISSUE TITLE
I am trying to understand the usage of extent.db, but could not find use case info

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#331]
Anshoo,
I am trying to understand the usage of extent.db. I didn't find usecase info on when to use extent.db and how to retrieve the results across runs.

I am facing the problem of finding regression issue across the test runs. To detect the regression issues, i need to explicitly check the older test reports and current test report.

I am thinking extent.db usage might help in storing all the test runs and whenever there is a mismatch in previous test run and current test run result in db storage, it will throw an alert. 

Can you please share/ point me to the extent db use case info?

Thanks
Madhusudhan G

**Comment by anshooarora** [comment]
See [here](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/common/ExtentManager.java#L15) for quick usage.  It creates a new extent.db file which you can use for all your runs to store a comprehensive history.  Note:  you must use the same .db file for all your runs even if your HTML files change.

The feature you've mentioned: throwing errors for mismatches - it will be a self-implemented one as none of the extent tools do this.

You can merge reports with ExtentMerge and view the differences though..

**Comment by gsaimadhu** [comment]
Anshoo, 
With ExtentMerge, it will be a manual effort to detect the regression issues ie. same test id passed previous runs, but failing now.

Can we have API support from extent, to check the existing test result (from previous run) in extent db, before inserting the current test result of the same test id?

Thanks
Madhu

**Comment by anshooarora** [comment]
It will be a simple query to extent.db, and you can easily do that using xerial-sqllite.  

What I can do is add an extension (a node server) which will allow monitoring of all test runs from a single dashboard, will also allow comparison.  However, you will have to deploy the server locally to be able to utilize this.  The very reason I didn't want to go the server route is its much easier using static files, but for a scenario like yours, having a database/server setup makes more sense.  This enhancement might take a few months for sure.

**Comment by gsaimadhu** [comment]
Anshoo,
The idea having a db/server setup looks good to enable monitoring all test runs from a single dash board and compare. In which release can we expect?

Meanwhile i will explore querying of extent.db using sqllite.

Thanks
Madhu

**Comment by anshooarora** [comment]
I am not quite sure how long this is going to take, there are lots of design decisions to be taken as I would ideally like to use Mongo instead of sqlite with Node.  Also, once its ready, creation of all templates for views take forever.  Would love to have some contributors but so far, contribution has been minimal..

**Comment by anshooarora** [comment]
Working on a server that will centralize all this information, provide powerful search capabilities and also superb metrics/dashboards.  It will allow you to monitor all your reports from the server itself.  Will post a demo sometime in march, lots of work still remaining on the server side.  A new extension will also have to be created for Java to push reports to MongoDB.

**Comment by anshooarora** [comment]
PS. ExtentMerge will deprecate with the release of this server.

**Comment by jawlitkp** [comment]
Are you still supporting extent report ? Or everything will be in one server report going forward ?

**Comment by anshooarora** [comment]
Yes, extent will remain the primary reporting.

**Comment by anshooarora** [comment]
Initial sample of extentx:  https://extentx.herokuapp.com/

Ability to update the server will be available in the next Extent version and you will also be able to deploy the server.

**Comment by gsaimadhu** [comment]
Anshoo,
Excellent, I went through this link.

I have few doubts:
1. In the search option, will the test start and end dates  fetch multiple test execution reports in this time interval?
2. In search option, if we select FAIl, will it present all the tests failed in the test start and end duration?
How regression issues will be presented in report? The test used to pass, now failing in current builds.
 
How status of the test is presented over a period of time? 
Example: In the selected range of date, the test may be failing, then fix is applied and the test might be passing now. How do we represent this status from fail to pass? Is the progress of the test shown from fail, fail, pass (say 3 reports in duration)?

3. In the search option, i see test name. Will this fetch the test result of the test across all the reports in the test start and end dates?

4. To understand better, on how the test cases and results are getting stored across test runs, can you share the db schema? 

5. Are there any additional APIs to be called from test framework?

**Comment by anshooarora** [comment]
This is a very initial build of the server, so some functionality is missing, not all details are available etc.  The app is a NodeJS server connected to MongoDB, you can view the schema here:  https://github.com/anshooarora/extentx/tree/master/api/models

If a failed test now passed, it will become part of the history.  If you see this link:  http://extentx.herokuapp.com/lastRunReport, the history table is present which shows all the runs for this particular test:

![history](https://cloud.githubusercontent.com/assets/4107384/13376156/8c09f708-dd78-11e5-8822-6f80cbd2dfee.png)

In the next version of Extent, there will be an option to automatically update the DB while your test is running.  So, you will view the normal Extent report and the DB will keep getting updated which you will be able to view via the ExtentX server.  You will be able to add logs to the database using:

```
// host and port of mongo database
extent.x(host, port);
```

1. The search option allows you to search for tests in a given duration.
2. If you select fail, all failed tests will be populated

The only additional thing required from your side would be to add a mongo-db-core dependency.  And obviously setup the server in your environment so all executions are able to update the database.  The host machine will need an installation of NodeJS + MongoDb.

**Comment by gsaimadhu** [comment]
Fine.
