### ISSUE TITLE
Jenkins HTML Publisher is rendering an unstylized html

### ISSUE THREAD

**Issue by dotautomation** [anshooarora/extentreports#332]
Hi, we're using Jenkins to trigger automated tests and as a post-build action are publishing the html generated by ExtentReports. However, upon viewing the html output via Jenkins, an unstylized page is displayed per the screenshot. Is this an issue with ExtentReports? Thanks.
![extent](https://cloud.githubusercontent.com/assets/16649893/12978980/46c2b5be-d0a2-11e5-891e-cef52ab5c793.png)

**Comment by anshooarora** [comment]
Duplicate #290.  See [here](https://github.com/anshooarora/extentreports/issues/290#issuecomment-173133373).

**Comment by dotautomation** [comment]
Thanks. That worked. Any planned fix for the issue, other than the workaround? Seems like a security issue.
