### ISSUE TITLE
Jenkins HTML Publisher-published report is missing screenshots

### ISSUE THREAD

**Issue by dotautomation** [anshooarora/extentreports#333]
Upon publishing the html report using Jenkins' HTML Publisher, the screenshots for the failed cases are referencing an absolute path (e.g. file:///C:\mydir\screenshots\failed\xyz.png).

Opening the ExtentReport on the local machine renders the screenshots as expected, but opening via Jenkins' web interface results in a missing screenshot.

How should we tweak the file path to be relative, as opposed to absolute, so screenshots display via Jenkins' web interface?

Thanks.

![extentss](https://cloud.githubusercontent.com/assets/16649893/12992115/8f945d7c-d0e0-11e5-97ea-d9c527499094.png)

**Comment by dotautomation** [comment]
This was an issue with the use of an absolute vs. relative path for the screenshot.
Once changed, the screenshot displayed correctly.
Perhaps, this can be marked as an enhancement to automatically parse the absolute path and convert it to a relative path while publishing the report.

**Comment by anshooarora** [comment]
I would prefer to keep this part up to the user to select the best possible relative path.

**Comment by praveen-4705** [comment]
I am getting the same issue, What was the solution for this

**Comment by Anandp1995** [comment]
Not able to resolve the issue.

Screenshot is not shown in the Extent Report in Jenkins.

It is visible if I open the html file in local browser.

**Comment by kselv07** [comment]
i have a similar issue, what is the solution to resolve this?

**Comment by Anandp1995** [comment]
Try using relative path like "../<Folder Name>/<Screenshot name>"

I did not try it in Jenkins but it dos work for me when I send the Extent Report via E mail and open it on any other machine.
