### ISSUE TITLE
Need Scroll Bar on Summary Page

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#335]
Hi, the scroll bar you just added to the test runner logs page work great, it also needs to be added to the summary page for situations where the Param : Value combinations exceeds the screen. How hard would it be to get it there also?

**Comment by anshooarora** [comment]
Same as #309.

The dashboard view requires additional work, will add in next beta.  I will have to add a new container and enable scrolling on that. Although doing so will break existing styles..

**Comment by anshooarora** [comment]
Released fix with 2.40.2-beta2.
