### ISSUE TITLE
Responsive design issues in version v2.40.1-beta-3

### ISSUE THREAD

**Issue by DiForest** [anshooarora/extentreports#336]
This happen on my pc, not sure for others. Hope it helps. 
p.s: "English is not my mother tongue; please excuse any errors on my part."

1. When I re-size the browser to smaller size. The top-down navigation tabs [Test] [Category] [Overall] on the left side is disappear.
![extent report issues](https://cloud.githubusercontent.com/assets/8066161/13099503/ca96cf68-d56d-11e5-9f3d-3a72cd17e61b.png)

2. When I select [Overall] tabs and re-size the browser to smaller size. I cant scroll down to view more information. I cant view my [Pass percentage]

![extent report bug](https://cloud.githubusercontent.com/assets/8066161/13099539/1b7eee56-d56e-11e5-9630-aaa4b0b41697.png)

3. When I select [Overall] tabs and browser is maximized(size), I cant scroll down to view more information(category). My category should have more data than that.

![extent report issues2](https://cloud.githubusercontent.com/assets/8066161/13099579/8a37edde-d56e-11e5-81ae-44de1c5eb2a8.png)

I can see the completely data set when I drag to a my second window which is higher resolution.

**Comment by anshooarora** [comment]
Some are similar as #309, and fixed in 2.40.2-beta1.

**Comment by anshooarora** [comment]
The dashboard view is similar as #309 and #335.

**Comment by anshooarora** [comment]
I am marking `#1` as an enhancement as the report was not setup for responsiveness for device viewport medium and smaller.  The other 2 are bugs in #309, and will be fixed in the next beta.

**Comment by anshooarora** [comment]
Can you test with [this](http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html#) file?  It has includes the 2 fixes and the ER for responsive sidenav.

**Comment by anshooarora** [comment]
Released fix with 2.40.2-beta2.
