### ISSUE TITLE
Test cases are not sorted in order by runtime

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#337]
Using the latest 2.40.2-beta1 release, the test cases listed in the Tests or Categories views are not sorted by the runtime. I'm not exactly sure how they were sorted, but it does seem to put the failures at the bottom? I'll try to attach a bitmap here. I have not integrated this with a TestListener class although I have one running.
![screen shot 2016-02-17 at 6 47 45 am](https://cloud.githubusercontent.com/assets/14335696/13108748/0808205c-d543-11e5-9daa-beceeb346bbb.png)

**Comment by carlc986** [comment]
The order they ran is as follows:

tc001_login01.01
tc001_login01.02
tc001_login01.03
tc001_login01.04
tc001_login01.05
tc001_login02.01
tc001_login02.02

**Comment by carlc986** [comment]
Second bitmap view of categories
![screen shot 2016-02-17 at 6 54 27 am](https://cloud.githubusercontent.com/assets/14335696/13108827/78475e8c-d543-11e5-8c91-cf77453640c1.png)

**Comment by anshooarora** [comment]
The fonts appear quite big in your snapshot.. I will check the report on smaller screens too starting this release so we don't run into this again.

**Comment by carlc986** [comment]
right but as you can see, it is not sorting correctly. Here's the code sniper:

for ( ISuite suite : suites ) {
            Date date = new Date();
            extent = new ExtentReports(Globals_UX.TEST_REPORT_PATH + suite.getName() + "_" + dateFormat.format(date) + ".html",true,DisplayOrder.OLDEST_FIRST); // outputDirectory not used...
            extent.loadConfig(new File(configFile));

**Comment by anshooarora** [comment]
Was it sorting correctly in 2.40 or 2.40.1?

**Comment by anshooarora** [comment]
Also, are you using the listener to build this report?  Because, listener will put all the `PASSED` tests on top by default.  To change this behavior, simply put the failed statement [here](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ExtentReporterNG.java#L36) above `PASSED'.

**Comment by carlc986** [comment]
No, it wasn't sorting correctly in 2.40.1-beta5 either. I am using a TestNG TestListener class I built, but I haven't integrated it into this ExtentReports that I can tell, other than it will track the status of the tests as they are run. That's how TestNG works anyway, right? Maybe I am not following what you're asking?

**Comment by carlc986** [comment]
Right, but they are running in the correct order as you can see by the 2nd bitmap with the timestamps, so I'm not sure why the report "unsorts" them when it gets built?

**Comment by anshooarora** [comment]
Report will add everything in an array-list, so they're always sorted in the same way they are added..  Can you do a console.out to see the order that is output in the listener?  

For example, the below code from the [listener](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/ExtentReporterNG.java#L54):

```java
for (ITestResult result : tests.getAllResults()) {
    test = extent.startTest(result.getMethod().getMethodName());

    // .. other code
}
```

add a console out:

```java
for (ITestResult result : tests.getAllResults()) {
    test = extent.startTest(result.getMethod().getMethodName());

    // added
    System.out.println(result.getMethod().getMethodName());    

    // .. other code
}
```

**Comment by carlc986** [comment]
FYI - You can close this now as I was able to explicitly sort the results by Date using the following code added to buildTestNodes:

private void buildTestNodes(IResultMap tests, LogStatus status) {
        ExtentTest test;
        String message = null;
        
        if ( tests.size() > 0 ) {
            // Set sorted by the Date field... (Wed Feb 17 14:22:50 EST 2016)
            List<ITestResult> resultList = new LinkedList<ITestResult>(tests.getAllResults());

            class ResultComparator implements Comparator<ITestResult> {
                public int compare(ITestResult r1, ITestResult r2) {
                    return getTime(r1.getStartMillis()).compareTo(getTime(r2.getStartMillis()));
                }
            }
            
            Collections.sort(resultList , new ResultComparator ());
            
            for ( ITestResult result : resultList ) {
               ...

**Comment by anshooarora** [comment]
Good solution using comparator.
