### ISSUE TITLE
Font Too Large in Latest Release

### ISSUE THREAD

**Issue by carlc986** [anshooarora/extentreports#338]
It looks like the font was enlarged for the overall report in the latest 2.40.2-beta1 release. That is causing a weird wrapping issue in Firefox when displaying the test cases. Is there anyway to change to back for the entire report using the config file?
![screen shot 2016-02-17 at 7 03 12 am](https://cloud.githubusercontent.com/assets/14335696/13109031/e863824e-d544-11e5-9c56-a252a44e3958.png)

**Comment by carlc986** [comment]
This fixed it: 

.extent { font-size: 12px; }

**Comment by anshooarora** [comment]
Is this for the offline report?  The font-size has gotten 1px smaller than the last release..

**Comment by carlc986** [comment]
No, I have not enabled offline reporting, so it was for the standard theme format, which I selected in the config xml file. It was defaulted to 14px so I changed it to 12px, which I believe is what the last release created? It was using it in both FF and Chrome browsers. .extent { font-size: 12px; } fixed it!

**Comment by anshooarora** [comment]
The fonts appear quite big in your snapshot.. I will check the report on smaller screens too starting this release so we don't run into this again.

**Comment by carlc986** [comment]
A lot of the headings in the sections are a little too big now also, but I did not bother to change those at this point, let me know if this all gets addressed in a new release, thanks...

**Comment by anshooarora** [comment]
Are you using firefox?

**Comment by carlc986** [comment]
Both Firefox and Chrome, but the wrapping occurred only on FF/Linux

**Comment by anshooarora** [comment]
Does [this](http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html) look better on your screen?

**Comment by carlc986** [comment]
I don't see any wrapping issues in FF with this one...

**Comment by anshooarora** [comment]
Released fix with 2.40.2-beta2.
