### ISSUE TITLE
Test names to differentiate instances data driven test

### ISSUE THREAD

**Issue by rkkreddy** [anshooarora/extentreports#339]
I have a data driven test where I am using @Factory of testng to read data from excel files.
When I run this test, extentreports generate a report with the same test name for all the instances.
1. Any idea on how to have unique name displayed in the report for data driven tests?
2. I can have the test name passed from the excel file itself. If I do so, how can I set the test name to get it displayed in the report?
Attached is the test names clip from the report.
![image](https://cloud.githubusercontent.com/assets/6282147/13290634/8d5b6c06-dae2-11e5-8917-8236b6c6bceb.png)

**Comment by anshooarora** [comment]
You can create child tests for this purpose - to add different sets under the same test.  

Unique names depend upon your data source + usage.
