### ISSUE TITLE
Enhancement suggestion: can add comparison feature to decide pass / fail 

### ISSUE THREAD

**Issue by patro1985** [anshooarora/extentreports#34]
Hi Ansoo, 

I am using ExtentReports 2.X version, and was thinking if you could add the compare functionality like, send 4 parameters to result, 1. description 2.expected value 3. actual value 4. compare operator (like = / > / <) and, 
Your code will decide logstatus.pass and logstatus.fail depend on the operator evaluation 
Then print the description, expected, actual result along with status. 
I am working on such kind of functionality, but its just printing to a simple html page, I saw same kind of post on Bas's site http://www.ontestautomation.com/create-your-own-html-report-from-selenium-tests/, 
Wondering if this could mix up with your ExtentReport, thanks!

**Comment by anshooarora** [comment]
Do you mean the following method as Bas has shown:

```
public static void report(String actualValue,String expectedValue) {
    if(actualValue.equals(expectedValue)) {
        Result r = new Result("Pass","Actual value '" + actualValue + "' matches expected value");
        details.add(r);
    } else {
        Result r = new Result("Fail","Actual value '" + actualValue + "' does not match expected value '" + expectedValue + "'");
        details.add(r);
    }
}
```

**Comment by patro1985** [comment]
Not exactly same, but I have code similar to what I expect

public class Library {
	
	private static Properties prop;
	private static final String resultPlaceholder = "";
	private static List<Result> details;
//	private static String[] themeType={"responsive-themes","mobile-friendly-themes","classic-themes"};
	private static String resultValue;
//	private static String result;
	static String returnVal[] = new String[3];
	static WebDriver driver;
	static Actions actions;
	static ProfilesIni allprofiles = new ProfilesIni();
	static WebDriverWait wait;
	static boolean flag;
	
	public static void htmlReportinitialize() {
		details = new ArrayList<Result>();
	}
//creating HTML file for result logging
	private static void createHtmlFile(String className) throws IOException{
		String path = null,htmlBody = null;
		DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy HH:mm:ss");
		Date date = new Date();
		String dir = System.getProperty("user.dir");
		htmlBody = "<html><head><title>Test Report</title><head><body><h3>Test results : "+className+"</h3><h4>Date : "+dateFormat.format(date)+"</h4><table><tr><th width=\"10%\">Step</th><th width=\"10%\">Result</th><th width=\"40%\">Step Description</th><th width=\"40%\">Remarks</th></tr></table></body>";
		path = dir+"\\logs\\"+className+".html";
		File newResultFile = new File(path);
		newResultFile.createNewFile();
		FileWriter fWriter = null;
        BufferedWriter writer = null;
        try {
            fWriter = new FileWriter(path);
            writer = new BufferedWriter(fWriter);
            writer.write(htmlBody);
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
	}
//Adding result rows to the result file located under the logs folder
	public static void writeResults(String className) {
		boolean flagstatus = false;
		boolean testStatusNC = false;
		String templatePath = "";
		try {
			createHtmlFile(className);
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		String dir = System.getProperty("user.dir");
		templatePath = dir+"\\logs\\"+className+".html";

		try {
			String reportIn = new String(Files.readAllBytes(Paths.get(templatePath)));
			for (int i = 0; i < details.size();i++) {
				if(details.get(i).getResult().equalsIgnoreCase("Passed")){
					reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#00FF00\"><td>" + Integer.toString(i+1) + "</td><td>" + details.get(i).getResult() + "</td><td>" + details.get(i).getResultDesc() + "</td><td>" + details.get(i).getResultText() + "</td></tr>" + resultPlaceholder);
				}
				if(details.get(i).getResult().equalsIgnoreCase("Failed")){
					reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FF0000\"><td>" + Integer.toString(i+1) + "</td><td>" + details.get(i).getResult() + "</td><td>" + details.get(i).getResultDesc() + "</td><td>" + details.get(i).getResultText() + "</td></tr>" + resultPlaceholder);
					flagstatus = true;
				}
				if(details.get(i).getResult().equalsIgnoreCase("Not Complete")){
					reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FFA500\"><td>" + Integer.toString(i+1) + "</td><td>" + details.get(i).getResult() + "</td><td>" + details.get(i).getResultDesc() + "</td><td>" + details.get(i).getResultText() + "</td></tr>" + resultPlaceholder);
					testStatusNC = true;
				}
			}
			
			Files.write(Paths.get(templatePath),reportIn.getBytes(),StandardOpenOption.CREATE);
			if(String.valueOf(testStatusNC).matches("false")){
				endTest(className,flagstatus);
			}else{
				endTest(className,flagstatus,"Not Complete");
			}
				
		} catch (Exception e) {
			System.out.println("Error when writing report file:\n" + e.toString());
		}
	}
	
	//Result logging method for matching string outputs
	public static void reproterFunctionHtml(String stepDesc,String expectedResult,String actualResult,String operator) throws IOException{
		switch (operator){
		case "=":
			if(expectedResult.equals(actualResult)){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
				
			break;
		case "!=":
			if(expectedResult!=actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		}
	}
	
	//Result logging method for matching integer outputs
	public static void reproterFunctionHtml(String stepDesc,int expectedResult,int actualResult,String operator) throws IOException{
		switch (operator){
		case "=":
			if(expectedResult==actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case "<":
			if(expectedResult<actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case ">":
			if(expectedResult>actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case "!=":
			if(expectedResult!=actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		}
	}
	
	//Result logging method for matching boolean outputs
	public static void reproterFunctionHtml(String stepDesc,boolean expectedResult,boolean actualResult,String operator) throws IOException{
		switch (operator){
		case "=":
			if(expectedResult==actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case "!=":
			if(expectedResult!=actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		}
	}
	
	//Result logging method in case of exception
	public static void reproterFunctionHtml(Exception e) throws IOException{
		Result r = new Result("Failed","The Test did Not Complete",e.getMessage().toString());
		details.add(r);
	}
	
	//Result logging method for Not Completed steps(Steps which require manual intervention)
	public static void reproterFunctionHtml(String resultStatus,String stepDesc) throws IOException{
		Result r = new Result(resultStatus,"Not Completed",stepDesc);
		details.add(r);
	}
	
	//Returns current date in yyyy-MM-dd format
	public static String getCurrentDate() {
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
	    
		//get current date time with Date()
	    Date date = new Date();
	    return dateFormat.format(date).replace("/","-");
	}

//Logging result of each test into the Results file for the final status
	public static void endTest(String className,boolean status) throws IOException {
		String dir = System.getProperty("user.dir");
		String file = className+".html";
		File myFile = null; 
		myFile = new File(dir + "//logs//" + file);		
		String htmlPath = dir+"\\logs\\ResultFile.html";
		String reportIn = new String(Files.readAllBytes(Paths.get(htmlPath)));
		//String dirPath = myFile.getPath();
		boolean testS = status;
		if(String.valueOf(testS).matches("true")){
				reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FF0000\"><td>Failed</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}else{
				reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#00FF00\"><td>Passed</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}	
		Files.write(Paths.get(htmlPath),reportIn.getBytes(),StandardOpenOption.CREATE);
	}
	
	//Logging result of each test into the Results file for the final status(Not Complete)
	public static void endTest(String className,boolean status,String testStatus) throws IOException {
		String dir = System.getProperty("user.dir");
		String htmlPath = dir+"\\logs\\ResultFile.html";
		String reportIn = new String(Files.readAllBytes(Paths.get(htmlPath)));
		String file = className+".html";
		File myFile = new File(dir + "//logs//" + file);
		if(String.valueOf(status).matches("true")){
			reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FF0000\"><td>Failed</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}else{
			reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FFA500\"><td>Not Complete</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}
		Files.write(Paths.get(htmlPath),reportIn.getBytes(),StandardOpenOption.CREATE);
	}	
}


and the testcase looks like:

public class Testing {

    String ClassName;
	WebDriver driver;
	
	@BeforeTest
	public void setup()
	{
		ClassName = this.getClass().getSimpleName();
	}
	
	@Test
	public void TC1() throws InterruptedException, IOException {
    try{
		Library.htmlReportinitialize();
    	driver = new FirefoxDriver();
    	driver.get("http://www.qavalidation.com/");
    	Library.reproterFunctionHtml("LaunchBrowserwithURL", true, driver.getTitle().contains("QAValidation"), "=");
    }catch(Exception e){Library.reproterFunctionHtml(e);Utils.captureScreenShot(driver, "./"+ClassName+".jpg");}
	finally{Library.writeResults(ClassName);}
	}
	
	@AfterTest
	public void TearDown() throws InterruptedException{
		Thread.sleep(1000);
		driver.quit();
	}
}

The above Library class will compare the expected and actual with the operator, evaluates and write the results to html file, 
currently I have this code with my framework, if this could implement in your framework, this would really help...

**Comment by patro1985** [comment]
Hello,

Please see the attached file for the code and implementation, let me know
if you need any more information.

On Fri, Jul 31, 2015 at 9:53 PM, Anshoo Arora <notifications@github.com>
wrote:

> Do you mean the following method as Bas has shown:
>
> public static void report(String actualValue,String expectedValue) {
>     if(actualValue.equals(expectedValue)) {
>         Result r = new Result("Pass","Actual value '" + actualValue + "' matches expected value");
>         details.add(r);
>     } else {
>         Result r = new Result("Fail","Actual value '" + actualValue + "' does not match expected value '" + expectedValue + "'");
>         details.add(r);
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/34#issuecomment-126740169>
> .
>



-- 
THANKS&REGARDS
SUNIL PATRO
7893903025


The below Library class will compare the expected and actual with the operator, evaluates and write the results to html file, 

public class Library {
	
	private static Properties prop;
	private static final String resultPlaceholder = "";
	private static List<Result> details;
//	private static String[] themeType={"responsive-themes","mobile-friendly-themes","classic-themes"};
	private static String resultValue;
//	private static String result;
	static String returnVal[] = new String[3];
	static WebDriver driver;
	static Actions actions;
	static ProfilesIni allprofiles = new ProfilesIni();
	static WebDriverWait wait;
	static boolean flag;
	
	public static void htmlReportinitialize() {
		details = new ArrayList<Result>();
	}
//creating HTML file for result logging
	private static void createHtmlFile(String className) throws IOException{
		String path = null,htmlBody = null;
		DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy HH:mm:ss");
		Date date = new Date();
		String dir = System.getProperty("user.dir");
		htmlBody = "<html><head><title>Test Report</title><head><body><h3>Test results : "+className+"</h3><h4>Date : "+dateFormat.format(date)+"</h4><table><tr><th width=\"10%\">Step</th><th width=\"10%\">Result</th><th width=\"40%\">Step Description</th><th width=\"40%\">Remarks</th></tr></table></body>";
		path = dir+"\\logs\\"+className+".html";
		File newResultFile = new File(path);
		newResultFile.createNewFile();
		FileWriter fWriter = null;
        BufferedWriter writer = null;
        try {
            fWriter = new FileWriter(path);
            writer = new BufferedWriter(fWriter);
            writer.write(htmlBody);
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
	}
//Adding result rows to the result file located under the logs folder
	public static void writeResults(String className) {
		boolean flagstatus = false;
		boolean testStatusNC = false;
		String templatePath = "";
		try {
			createHtmlFile(className);
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		String dir = System.getProperty("user.dir");
		templatePath = dir+"\\logs\\"+className+".html";

		try {
			String reportIn = new String(Files.readAllBytes(Paths.get(templatePath)));
			for (int i = 0; i < details.size();i++) {
				if(details.get(i).getResult().equalsIgnoreCase("Passed")){
					reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#00FF00\"><td>" + Integer.toString(i+1) + "</td><td>" + details.get(i).getResult() + "</td><td>" + details.get(i).getResultDesc() + "</td><td>" + details.get(i).getResultText() + "</td></tr>" + resultPlaceholder);
				}
				if(details.get(i).getResult().equalsIgnoreCase("Failed")){
					reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FF0000\"><td>" + Integer.toString(i+1) + "</td><td>" + details.get(i).getResult() + "</td><td>" + details.get(i).getResultDesc() + "</td><td>" + details.get(i).getResultText() + "</td></tr>" + resultPlaceholder);
					flagstatus = true;
				}
				if(details.get(i).getResult().equalsIgnoreCase("Not Complete")){
					reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FFA500\"><td>" + Integer.toString(i+1) + "</td><td>" + details.get(i).getResult() + "</td><td>" + details.get(i).getResultDesc() + "</td><td>" + details.get(i).getResultText() + "</td></tr>" + resultPlaceholder);
					testStatusNC = true;
				}
			}
			
			Files.write(Paths.get(templatePath),reportIn.getBytes(),StandardOpenOption.CREATE);
			if(String.valueOf(testStatusNC).matches("false")){
				endTest(className,flagstatus);
			}else{
				endTest(className,flagstatus,"Not Complete");
			}
				
		} catch (Exception e) {
			System.out.println("Error when writing report file:\n" + e.toString());
		}
	}
	
	//Result logging method for matching string outputs
	public static void reproterFunctionHtml(String stepDesc,String expectedResult,String actualResult,String operator) throws IOException{
		switch (operator){
		case "=":
			if(expectedResult.equals(actualResult)){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
				
			break;
		case "!=":
			if(expectedResult!=actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		}
	}
	
	//Result logging method for matching integer outputs
	public static void reproterFunctionHtml(String stepDesc,int expectedResult,int actualResult,String operator) throws IOException{
		switch (operator){
		case "=":
			if(expectedResult==actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case "<":
			if(expectedResult<actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case ">":
			if(expectedResult>actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case "!=":
			if(expectedResult!=actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		}
	}
	
	//Result logging method for matching boolean outputs
	public static void reproterFunctionHtml(String stepDesc,boolean expectedResult,boolean actualResult,String operator) throws IOException{
		switch (operator){
		case "=":
			if(expectedResult==actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		case "!=":
			if(expectedResult!=actualResult){
				resultValue = "Passed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}else{
				resultValue = "Failed";
				Result r = new Result(resultValue,stepDesc,"Expected Value '" + expectedResult + "' "+operator+" Actual Value '"+ actualResult +"'");
				details.add(r);
			}
			break;
		}
	}
	
	//Result logging method in case of exception
	public static void reproterFunctionHtml(Exception e) throws IOException{
		Result r = new Result("Failed","The Test did Not Complete",e.getMessage().toString());
		details.add(r);
	}
	
	//Result logging method for Not Completed steps(Steps which require manual intervention)
	public static void reproterFunctionHtml(String resultStatus,String stepDesc) throws IOException{
		Result r = new Result(resultStatus,"Not Completed",stepDesc);
		details.add(r);
	}
	
	//Returns current date in yyyy-MM-dd format
	public static String getCurrentDate() {
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
	    
		//get current date time with Date()
	    Date date = new Date();
	    return dateFormat.format(date).replace("/","-");
	}

//Logging result of each test into the Results file for the final status
	public static void endTest(String className,boolean status) throws IOException {
		String dir = System.getProperty("user.dir");
		String file = className+".html";
		File myFile = null; 
		myFile = new File(dir + "//logs//" + file);		
		String htmlPath = dir+"\\logs\\ResultFile.html";
		String reportIn = new String(Files.readAllBytes(Paths.get(htmlPath)));
		//String dirPath = myFile.getPath();
		boolean testS = status;
		if(String.valueOf(testS).matches("true")){
				reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FF0000\"><td>Failed</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}else{
				reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#00FF00\"><td>Passed</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}	
		Files.write(Paths.get(htmlPath),reportIn.getBytes(),StandardOpenOption.CREATE);
	}
	
	//Logging result of each test into the Results file for the final status(Not Complete)
	public static void endTest(String className,boolean status,String testStatus) throws IOException {
		String dir = System.getProperty("user.dir");
		String htmlPath = dir+"\\logs\\ResultFile.html";
		String reportIn = new String(Files.readAllBytes(Paths.get(htmlPath)));
		String file = className+".html";
		File myFile = new File(dir + "//logs//" + file);
		if(String.valueOf(status).matches("true")){
			reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FF0000\"><td>Failed</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}else{
			reportIn = reportIn.replaceFirst(resultPlaceholder,"<tr bgcolor=\"#FFA500\"><td>Not Complete</td><td><a href=\""+myFile.getName()+"\">"+className+"</a></td></tr>" + resultPlaceholder);
		}
		Files.write(Paths.get(htmlPath),reportIn.getBytes(),StandardOpenOption.CREATE);
	}	
}


and the testcase looks like:

public class Testing {

    String ClassName;
	WebDriver driver;
	
	@BeforeTest
	public void setup()
	{
		ClassName = this.getClass().getSimpleName();
	}
	
	@Test
	public void TC1() throws InterruptedException, IOException {
    try{
		Library.htmlReportinitialize();
    	driver = new FirefoxDriver();
    	driver.get("http://www.qavalidation.com/");
    	Library.reproterFunctionHtml("LaunchBrowserwithURL", true, driver.getTitle().contains("QAValidation"), "=");
    }catch(Exception e){Library.reproterFunctionHtml(e);Utils.captureScreenShot(driver, "./"+ClassName+".jpg");}
	finally{Library.writeResults(ClassName);}
	}
	
	@AfterTest
	public void TearDown() throws InterruptedException{
		Thread.sleep(1000);
		driver.quit();
	}
}

currently I have this code with my framework, if this could implement in your framework, this would really help...

**Comment by anshooarora** [comment]
I saw your code however I feel it is not right fit for this reporting because it adds a layer of dependency on validation as well.  Closing this ticket as validation should be a separate component and the results from it should only be reported to Extent.
