### ISSUE TITLE
Inserting custom HTML

### ISSUE THREAD

**Issue by russel2005** [anshooarora/extentreports#340]
hi Asnhoo,
ExtentReports extent = new ExtentReports (file-path, false);
ExtentTest test = extent.startTest("Test name", "Sample description");

in sample document provided below code:
extent.log(LogStatus.INFO, "HTML", "Usage: <span style='font-weight:bold;'>BOLD TEXT</span>");

as mentioned:  it is not working with **extent** instance but it's working fine with **test** instance. and also it is working after "srartTest" method declaration which one was not mentioned into the document file.

**is there any other way i can add any text into the reporting html page?** not as a test step.
are you considering to use again config() method (version 2.05) like below for future release or something like that?
extent.config()
                .documentTitle("Title")
                .reportName("ProjectName")
                .reportHeadline(" Automation Test Reports on " +date);    

Thanks.
Russel.

**Comment by anshooarora** [comment]
Where in the report are you trying to add HTML?  Depending on the location, there may be several ways possible. 

The config method won't be coming back as it was replaced with an XML file.  Those are typos in the docs, I will correct them.

**Comment by mukulsehra** [comment]
@anshooarora : Hi!
I want to add custom HTML and also want to alter the existing HTML components.
I have added custom css in extent-config.xml and it worked well. Here is the screen shot : 
![customized_extent_report](https://cloud.githubusercontent.com/assets/2979526/24308676/0368b1ae-10ef-11e7-92a0-d61c839304a5.png)


I have added Total, Passed and Failed count beside the Regression category as you can see in the screenshot.
Now, what I want is, to make these **spans** i.e Total, Pass and Fail as buttons and add such an event that on click of Pass button  only those **divs** should be displayed which have the status Pass and likewise for Fail button. **Means it should work as a filter on divs**.
How can I do this ? Where should I add the HTML to convert the category span to button?

Please revert ASAP.

Thanks :)

**Comment by mukulsehra** [comment]
@anshooarora : Hi!
I have done that using jquery :) 

Now, the only question is "How to inject HTML in extent report ?"
Please revert on this.

Thanks! :)

**Comment by testgitpavi** [comment]
@anshooarora Hi 

I tried to bold the Info log with bold text but in my report I am getting stepName as HTML and in details as "Usage: BOLD TEXT". I have provided the screenshot below. I would like to know how to highlight the info text using Bold option?

![bold issue](https://user-images.githubusercontent.com/31283397/34986269-f21dc906-fadc-11e7-813e-7cf6f52c7984.PNG)

**Comment by mukulsehra** [comment]
You can add the BOLD css for the required selector in the extent’s config.xml
