### ISSUE TITLE
Any Update on ExtentX??

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports#341]

**Comment by anshooarora** [comment]
Some initial code is ready, I will push the entire repo here soon: https://github.com/anshooarora/extentx.  Do you know any good free or cheap cloud solutions that I can use to deploy a test app?  I am considering deploying on Heroku but they have a policy of 18 online hours/day so leaning towards OpenShift.

**Comment by anshooarora** [comment]
Sources now available.

**Comment by anshooarora** [comment]
Here is the initial sample:  https://extentx.herokuapp.com/

**Comment by vigneshwar-v** [comment]
Thanks anshoo

**Comment by vigneshwar-v** [comment]
when can i expect this??
