### ISSUE TITLE
i am running nunit 3 with parallelizable attribute and using selenium grid. In this scenario, i am getting only the latest module's test results and the old module's results gets replaced

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports#343]

**Comment by vigneshwar-v** [comment]
I am getting relevantCodes.ExtentReports.ExtentTestInterruptedException, even if I can able to achieve in getting all modules' results

**Comment by anshooarora** [comment]
Are you calling `endTest()`?  Please share your code.

**Comment by vigneshwar-v** [comment]
yep.. problem with my code.. thanks for your reply... I have synchronized all methods , now works perfect :)

**Comment by xenaree** [comment]
Hi @vigneshwar-v, I'm having the same problem. could you please tell me how did you manage to fix the problem.

**Comment by vigneshwar-v** [comment]
Hey @xenaree, I have added a wrapper for reporting plugin and all calls should come through  the methods in the wrapper and all methods should be thread - safe
