### ISSUE TITLE
Filter by author

### ISSUE THREAD

**Issue by subratkumarmandal** [anshooarora/extentreports#346]
@anshooarora is there a feature to filter test cases by author similar to categories?

**Comment by email2vimalraj** [comment]
How do you define an author to test cases? Does testng has any annotation for author? Any example would help me.

**Comment by anshooarora** [comment]
This was a planned feature which got delayed due to ExtentX.  Once it is released, I will work on this.  There is an existing ER for this. #233

To define an author, use `assignAuthor`.  With TestNG, you can pass a parameter defining this.
