### ISSUE TITLE
When I use retry attribute with nunit3, the test reports are repeated (since i am retrying), even when i use replaceexisting=true

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports#348]
can the replace exisitng work within the same run instance ??

**Comment by anshooarora** [comment]
`replaceExisting` is for the entire run, not a single test instance..  The feature to replace a test being retried is not implemented.

**Comment by vigneshwar-v** [comment]
Can I expect this implementation??

**Comment by vigneshwar-v** [comment]
yes, i know its for the entire run, but i think it will be good if the tests values are replaced if they have are retried again.. correct??
