### ISSUE TITLE
In eclipse Ide browser Test summary is not reflecting

### ISSUE THREAD

**Issue by samiullah** [anshooarora/extentreports#349]
I am not able to see Test summary in eclipse browser while as in normal chrome or FF it is working fine. I am using 1.2a version of extent reports

**Comment by anshooarora** [comment]
Version 1 is no longer supported, please update to version 2.40.2.  Also, summary won't be provided by Extent in Eclipse, but if you are using TestNG or JUnit, you will see this information.  Extent only creates a static HTML file that you can view in the browser.
