### ISSUE TITLE
Moving and removing of widgets, disable unused feature such as categories etc. 

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#35]
Most developers won't look at top widgets.  Managers might, but not developers. I'd like to move that to the bottom of the report and have the Failed/ Passed tests show up on top.

Also, a toggle to turn off the Steps View if it's not being used (the way our tests are written, Steps and Tests are coming up with the same counts...) -- test.log(status,blah) = a 'STEP' so if a test has 1 test.log(FAIL, blah) entry, then test counts and step counts are the same... (If this is the case, why show both on the report?) 

Next, if there are no categories configured, could the report remove the link to categories (avoids confusion)

Could we force auto collapse on the Details view for "Failed" tests?

Finally, since we don't really care about passed tests, could we default to the Details view if a test has failed, with failed tests fully collapsed?

Sorry for the boat load of info here :)

**Comment by anshooarora** [comment]
Chris, these are 5 tickets in 1 :)

1. Moving the dashboard to bottom of the report may have some side-affects but should be handled using CSS.  So add a control that changes the layout to drop the dashboard below all the important stuff?

2. Disable toggles if only 1 step is there?  This may not be a good thing because in case of a failure, the failure details will be present in the step details..

3. Categories tab can be removed by simply CSS:

```
.tabs .tab:nth-child(2) {
    display: none;
}
```

```
String css = ".tabs .tab:nth-child(2) { display: none; }";
extent.config().insertCustomStyles(css);
```
4. Do you mean, auto-expand?  All tests are by-default in "collapsed" state.

5. Do you mean, if there are failed tests, the first view when you open the report is on the "details view" with the failed tests open by default?

**Comment by anshooarora** [comment]
For #-3 above, that css will hide the Categories tab but is not the right way because it will break the tab layout..  will have to research this one.

**Comment by cktech529** [comment]
Auto Expand! Whoops.

**Comment by anshooarora** [comment]
Chris

To open in "details-view" by default, simply append "#tests-details-view" at the end of the URL:  <code>http://Extent.html#tests-details-view</code>.

To open all failed tests by default in the Details view, you can use the following js in the <code>setUp</code> method:

```
String js = "$('.test.fatal, .test.fail').click();";
extent.config().insertJs(js);
```

**Comment by cktech529** [comment]
I didn't get this to work doing the following.. Is there a setup method to overide in this instance (listener only mode?)

import java.io.File;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.testng.IReporter;
import org.testng.IResultMap;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
 
public class ExtentReporterNG implements IReporter {
    private ExtentReports extent;
 
    @Override
    public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
    	
        extent = new ExtentReports(outputDirectory + File.separator + "Extent.html", true);
        String js = "$('.test.fatal, .test.fail').click();";
        extent.config()
            .documentTitle("Automation Report")
            .reportName("HTML GUI Automation")          
            .reportHeadline(new Date().toString())
            .insertJs(js);
                       
        // Put Failures on top of the report
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults(); 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                buildTestNodes(context.getFailedTests(), LogStatus.FAIL, r);
            }
        }
        
        // Skipped
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults(); 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                buildTestNodes(context.getSkippedTests(), LogStatus.SKIP, r);
            }
        }
        
        // Passed
        for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults(); 
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                buildTestNodes(context.getPassedTests(), LogStatus.PASS, r);
            }
        }
        extent.flush();
    }
 
    private void buildTestNodes(IResultMap tests, LogStatus status, ISuiteResult suiteResult) {
        
    	ExtentTest test;
    	String[] failureDetails;
    	String[] errorSplit;
    	String errorMessage = ("<pre>Test Error</pre>");
    	String stackTrace = "";
    
        if (tests.size() > 0) {
            for (ITestResult result : tests.getAllResults()) {
            	int p = suiteResult.getTestContext().getSuite().getName().lastIndexOf(".");
                test = extent.startTest(suiteResult.getTestContext().getSuite().getName().substring(p + 1) + " --> " + suiteResult.getTestContext().getName());
                test.getTest().startedTime = new Date(result.getStartMillis());
                test.getTest().endedTime = new Date(result.getEndMillis());
                String message = "<pre>Test " + status.toString().toLowerCase() + "ed</pre>";                 
				if (result.getThrowable() != null) {
					failureDetails = result.getThrowable().getMessage().split("\\|");
					for (int i = 0; i < failureDetails.length; i++) {
						if (failureDetails[i].startsWith("Error: ")) {
							errorSplit = failureDetails[i].split("Error: ");							
							for (int j = 0; j < errorSplit.length; j++) {
								if (!errorSplit[j].isEmpty()){
									errorMessage+=("<pre>" + errorSplit[j] + "</pre>");	
								}
							}
						} else if (failureDetails[i].startsWith("Stack:")) {
							stackTrace = failureDetails[i];
						} else {
							message+=("<pre>" + failureDetails[i] + "</pre>"); 
						}
					}
				}
				test.log(status, message);
				if (!errorMessage.isEmpty() && (!errorMessage.trim().equalsIgnoreCase("<pre>Test Error</pre>"))) {				
					test.log(LogStatus.ERROR, ("<pre>" + errorMessage + "</pre>"));
					if (!stackTrace.isEmpty() && (!stackTrace.trim().equalsIgnoreCase("Stack:"))) {
						test.log(LogStatus.ERROR, ("<pre>" + stackTrace + "</pre>"));
					}
				}
                extent.endTest(test);
            }
        }        
    }
}

**Comment by anshooarora** [comment]
Woops.  I forgot to add the document part in the js, this would work:

```
String js = "$(document).ready(function() { $('.test.fatal, .test.fail').click(); })";
```

**Comment by cktech529** [comment]
Lol,

How did I miss that!

Thanks!

**Comment by anshooarora** [comment]
Closing this ticket as most of the items do not apply to version 2.10.  Please reopen a new ticket if any of these items still need to be added as features.

**Comment by Aeeshaa** [comment]
gud!
