### ISSUE TITLE
How to create global(single) report for multiple testNg calsses

### ISSUE THREAD

**Issue by hari4401** [anshooarora/extentreports#350]
Hi how to create single report for multiple TestNg classes 

Ex: I  have @Test method in two different testNG classes and handling Start in Each @Test  methodd 
and end in @AfterMethod and Flush in @AfterSuit
finally in report its displaying only 1st TestNg Class steps .

**Comment by anshooarora** [comment]
Simply create the extent instance in `@BeforeSuite` and `flush()` in `@AfterMethod` so your report gets updated after each test.

**Comment by hari4401** [comment]
Fallowing above for second test ExtentReport object displaying as null.

**Comment by anshooarora** [comment]
Are you calling `close()`?  Is Extent instance globally available?
