### ISSUE TITLE
Version 2.40.2 + all past version screenshot and .txt file (example: log.txt) are NOT getting attached in report when project running in intelliJ, same works fine in eclipse Ide

### ISSUE THREAD

**Issue by VinitSandesara** [anshooarora/extentreports#351]
Hi Anshoo, Screenshot  .txt file (example: log.txt) are not getting attached in report when project running in IntelliJ whereas same works fine in eclipse.

PFB screenshot of report ran on IntelliJ.

![screen shot 2016-03-04 at 1 29 09 pm](https://cloud.githubusercontent.com/assets/12589206/13538068/062762c0-e20e-11e5-9bd3-103b1d2c0c9f.png)

PFB screenshot of report ran on eclipse.

![screen shot 2016-03-04 at 1 28 22 pm](https://cloud.githubusercontent.com/assets/12589206/13538075/09688c7a-e20e-11e5-9c28-39c535056c55.png)

Thanks
Vinit

**Comment by anshooarora** [comment]
What is the path you have passed?  Are different IDEs saving it correctly, i.e. using the correct path?

**Comment by VinitSandesara** [comment]
Hi Anshoo, I kept the same path for both IDEs (Eclipse and IntelliJ), Yes Images and .txt file are saving at given folder in both IDE2, only issue is saved screenshot and .txt file doesn't get attached in report thru intelliJ, works fine thru eclipse.

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Anshoo, Any update on this ? i am on hold to deliver the report to my management for review.

Thanks
Vinit

**Comment by anshooarora** [comment]
I am not sure quite, doesn't seem like an Extent issue.. it only converts the paths and links them as `<a>` and `<img>` so if the path is not being passed correctly, they won't display.  Can you use developer tools and see what the path is, and if the file is available using that path between different IDEs?

**Comment by VinitSandesara** [comment]
Hi Anshoo, It is working now, it was just due to target folder locked where report was getting stored.

Thanks
Vinit
