### ISSUE TITLE
when i make child nodes inside extentreport version2 it only shows time for parent which shows toatal time for 2 childs and 0time inside child node,means i need tht time to be shown for child node rather than sum inside parent node

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#352]

**Comment by anshooarora** [comment]
Parent will show the total time, child-nodes show the individual times when you click on the node.  Is that not so?  

Please do not create the entire issue in the subject line, and see here for future reference:  https://upthemes.com/blog/2014/02/writing-useful-github-issues/
