### ISSUE TITLE
unknown status comes by default in case of parent node even if child nodes fail,so how to remove default status or add status of parent according to child node.

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#353]

**Comment by anshooarora** [comment]
Please share sample code.

**Comment by meenakshi127616** [comment]
[cid:image001.png@01D17923.9DD6EEA0]

Here I want that parent TestCase0  should not show any default status or status dependent on its child(Iteration0 and Iteration1 in my case) since it gets added inside pie chart of testviews and steps view and I get extra number of count inside pie chart

Also I need that Testcase0 which is a parent should not be clickable as  such but if we click it it show show its childs.


But I think these changes needs gto be done inside jar rather than in code?
My code:


package Package1;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class Extentchild1 {


    ExtentReports report=new ExtentReports("C:\\Users\\msingh\\Desktop\\report.html",true);

    ExtentTest parent[]=new  ExtentTest[5];
       ExtentTest child[]=new  ExtentTest[5];
       ExtentTest chil[]=new  ExtentTest[5];//max size not k


       @Test
       public void verifyBlogTitle()
       {

       for(int i=0;i<3;i++){
       parent[i]=report.startTest("Browser"+i);

       for(int j=0;j<3;j++){

    child[j] = report.startTest("Testcase"+j);
       child[j].log(LogStatus.INFO, "Info");////log status condition check  no need?//no need iteration result see//unknown show?


       for(int k=0;k<3;k++){//makes parent dependent child
       chil[k]=report.startTest("Iteration"+k);

       if(k==0){
       chil[k].log(LogStatus.FAIL,"inside iteration:"+k, "Info/fail");//log status condition check
       }
       if(k!=0){
              chil[k].log(LogStatus.PASS,"inside iteration:"+k, "pass");//log status condition check
              }

       child[j].appendChild(chil[k]);//append just before end or after test
       report.endTest(chil[k]);


       }//k end
          parent[i].appendChild(child[j]);
       report.endTest(child[j]);
       }//j end

       report.endTest(parent[i]);
       }//i end
}



       @AfterTest
       public void aftertest(){
              report.flush();
              report.close();
       }

       }
