### ISSUE TITLE
i want parent node to remain unclickable and only click child nodes inside it but now it shows parent node empty when i click means it is just a parent in hierarchical sense but not actually?means if i click on parent it should show child nodes

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#354]

**Comment by anshooarora** [comment]
Please reword your query + provide sample code.

**Comment by meenakshi127616** [comment]
![snip1](https://cloud.githubusercontent.com/assets/17696918/13592512/d7f22436-e518-11e5-840c-16a92df2ee55.PNG)


Here I want that parent TestCase0  should not show any default status or status dependent on its child(Iteration0 and Iteration1 in my case) since it gets added inside pie chart of testviews and steps view and I get extra number of count inside pie chart

Also I need that Testcase0 which is a parent should not be clickable as  such but if we click it it show show its childs.


But I think these changes needs to be done inside jar rather than in code?


package Package1;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class Extentchild1 {
	public static  String reportLocation = ".//reports//";
	public static  String imageLocation = ".//images//";
	 public static File lDir = new File("");
	 public static String absolutePath = lDir.getAbsolutePath();
	// static File folder1 = new File(reportLocation);
	 
	 public static	DateFormat dateformat2 = new SimpleDateFormat("MM_dd_yyyy"); 
	 public static	Date date_2 = new Date();
	 public static  String date2 = dateformat2.format(date_2);// for date
	//report=new ExtentReports("C:\\Users\\msingh\\Downloads\\Report_extent.html");
	public static DateFormat dateformat1 = new SimpleDateFormat("HH_mm_ss"); 
	 public static   Date date_1 = new Date();
	 public static  String date1 = dateformat1.format(date_1);//time
	 
    ExtentReports report=new ExtentReports("C:\\Users\\msingh\\Desktop\\report.html",true);
    
    ExtentTest parent[]=new  ExtentTest[5];
	ExtentTest child[]=new  ExtentTest[5];
	ExtentTest chil[]=new  ExtentTest[5];//max size not k
	
	
	@Test
	public void verifyBlogTitle()
	{

	for(int i=0;i<3;i++){
	parent[i]=report.startTest("Browser"+i);
	
	for(int j=0;j<3;j++){
		
    child[j] = report.startTest("Testcase"+j);
	child[j].log(LogStatus.INFO, "Info");////log status condition check  no need?//no need iteration result see//unknown show?
    
	
	for(int k=0;k<3;k++){//makes parent dependent child
	chil[k]=report.startTest("Iteration"+k);
	
	if(k==0){
	chil[k].log(LogStatus.FAIL,"inside iteration:"+k, "Info/fail");//log status condition check
	}
	if(k!=0){
		chil[k].log(LogStatus.PASS,"inside iteration:"+k, "pass");//log status condition check
		}
	
	child[j].appendChild(chil[k]);//append just before end or after test
	report.endTest(chil[k]);
	
	
	}//k end
	   parent[i].appendChild(child[j]);
       report.endTest(child[j]);
	}//j end
	
	report.endTest(parent[i]);
	}//i end
}
	
	
	
	@AfterTest
	public void aftertest(){
		report.flush();
		report.close();
	}
	
	}

**Comment by meenakshi127616** [comment]
![image](https://cloud.githubusercontent.com/assets/17696918/13592541/240294be-e519-11e5-8897-6d7b69e61072.png)
actually Browser0,1,2 are parent to children:Testcases 0 and 1 which are parent to children: Iteration0, 1,2 i need + sign to click on parent shows child nodes.please reply asap

**Comment by karthikbhatnagar** [comment]
wow, glad to see a team who removed the Extent name altogether from their report :)

**Comment by meenakshi127616** [comment]
In summary:
We want to run our tests on 3 browsers and every test will have some iterations underneath test cases just as given below 
Browser01
    - Test Case01
            - Iteration 1
            - Iteration 2
Now if Iteration 1 gets "Pass" and Iteration 2 gets "Fail" than TestCase 01 is also displayed as "Fail" and Browser01 is Also "Fail" as result of child nodes are propagating upwards This has 2 problems
1. It is giving an impression that broswer01 is failed even if a single test iteration among hundreds of test cases gets failed.
2.  A wrong test summary is presented, for instance for the above example quoted a single iteration failure for a test case. results in 1 Pass, 3 Fail (1-Browser, 1-Testcase, 1- Iteration). Instead of showing 1 Pass and 1 Fail.

**Comment by karthikbhatnagar** [comment]
its possible, but not going to be easy..  can you share a sample report and code in zipfile?

**Comment by meenakshi127616** [comment]
I have attached code for making report and report.html what we get.

**Comment by meenakshi127616** [comment]
I need to correct Test step count because even if 1 child fails,it adds parent also as fail inside test step summary.
I need something like " +" ,if we click + on parent it opens child that sort of hierarchy.
If we click parent it should show its child nodes.

**Comment by meenakshi127616** [comment]
Please provide sample code or any example for the same.
or any basic idea how i can solve this issue.

**Comment by anshooarora** [comment]
This is not possible.  To change this behavior, you will have to modify the template as well as the javascript.
