### ISSUE TITLE
Reports are distorted when opening in Firefox or IE11

### ISSUE THREAD

**Issue by NishantSinghh** [anshooarora/extentreports#355]
Hi,

Whenever I am trying to open reports in Firefox or IE the results are not displaying properly and all the links are blocked.

Please let me know how to resolve it.

![extentreport](https://cloud.githubusercontent.com/assets/11394228/13567745/070a5ae0-e483-11e5-9446-8090d1e4817a.png)

Regards,
Nishant Singh

**Comment by anshooarora** [comment]
Looks like external scripts are being blocked by your network.  I would recommend you to upgrade the latest (at the time of this writing, 2.40.2) and change protocol settings in config.xml.

Closing this issue as it does not relate to Extent, but is affected by your network.

**Comment by NishantSinghh** [comment]
OK thanks for clarifying I will check this can you please let me know where can I find this config.xml and how to change the protocol settings
