### ISSUE TITLE
Unable to set Boolean replaceExisting as false when running testNG suite

### ISSUE THREAD

**Issue by shafiq-eric** [anshooarora/extentreports#356]
**OS:** Mac OSX El Capitan
**IDE: **Eclipse
**Project code: **Java + TestNG with Maven
**Extent report version:** 2.40.2
**Java version: **1.8.0_51

Hi, I've been testing out your report feature and I really like it, however I am unable to set my files to be replace each time the suite runs. The suite works ok when I have the boolean set to **_true_**. Below are my codes.

I have this running on a different machine with the same configurations. I'm wondering if you can shed some light as to what may be going on.

I've pasted my codes below that is a breakdown of the actual Test Class, the method used in the Class, the BaseSample file (or I call it ExtentManager), the testNG.xml and the Error.

Also to inform, I'm not quite sure what am I supposed to do with the part in your documentations that says "Configurations 2.40.2". I see two older versions as well. What am I supposed to do?

Last but not least I'm keen to know when ExtentX maybe out?

Cheers,

Shafiq

/*+++++++++++++++++++++++++++ Test Class +++++++++++++++++++++++++++*/

public class SampleTest_testng extends ExtentManager {
	static ReusableMethods global_method = new ReusableMethods();
	
	@BeforeClass
	public void openBrowser() {
		extent = new ExtentReports(report_path, false); << **Failure happens here**
		
		wd = new FirefoxDriver();
		wd.get("http://www.mudah.my/support.htm?ca=9_s");
		wd.manage().window().maximize();
		wd.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	}
	
	@Test
	public void getTitle(Method method_name) {
		String test_name = method_name.getName();
		logger = extent.startTest("Verifying " + test_name, 
				"This test is to check the page title");
		global_method.assertPageTitle(
				wd,
				logger,
				"Customer Service", 
				"Regression",
				"Author1, Author2",
				"Awesome!");
	}

/*+++++++++++++++++++++++++ Check page title method +++++++++++++++++++++++++++*/

public void assertPageTitle(
			WebDriver wd, // passing WebDriver 
			ExtentTest logger, // 
			String page, 
			String category,
			String authors,
			String expected_title) {
		try {
			logger.assignCategory(category);
			logger.assignCategory("Mudah.my Automation");
			logger.assignCategory("WebDriver");
			logger.assignAuthor(authors);
			
			String title = wd.getTitle();
			System.out.println(title);
			logger.log(LogStatus.INFO, "Get page title & print");
			
			if (title.equals(expected_title)) {
				logger.log(LogStatus.INFO, "Page title compared and verified.");
				logger.log(LogStatus.PASS, "Title looks OK!");
				System.out.println(pass);
			} else {
				logger.log(LogStatus.INFO, "Page title compared and verified.");
				logger.log(LogStatus.FAIL, "Title is WRONG!");
				System.out.println(fail);
			}
			Assert.assertEquals(title, expected_title);
		} catch(Exception e) {
			throw(e);
		} 
	}

/*++++++++++++++++ ExtentManager or your Base Example +++++++++++++++++++++++*/

public abstract class ExtentManager {
	
	static ReusableMethods global_method = new ReusableMethods();
	protected static WebDriver wd;
        protected ExtentReports extent;
        protected ExtentTest logger;
        public static String report_path = "./Extentreport/" + global_method.datetime + ".html";
        public static Boolean replace_file = false;
    
    @AfterMethod
	protected void afterEachTest(ITestResult result) {
			String screenshotFile = "./Screenshot/" + global_method.datetime + "/" + result.getName() + ".png";
			if ((!result.isSuccess())) {
				logger.log(LogStatus.FAIL, result.getThrowable());
				try {
					TakesScreenshot ts=(TakesScreenshot)wd;
					File source=ts.getScreenshotAs(OutputType.FILE);
					FileUtils.copyFile(source, new File(screenshotFile));
					 
					System.out.println("Screenshot taken");
					logger.log(LogStatus.INFO, "Snapshot below: " + logger.addScreenCapture("." + screenshotFile));
				} catch (Exception e) {
					System.out.println("Exception while taking screenshot " + e.getMessage());
				}
			}
		extent.endTest(logger);	
		extent.flush();
	}
    
	@AfterClass
	protected void closeBrowser() {
		wd.close();
		extent.close();
	}
	
	@AfterSuite
	protected void afterSuite() {
		wd.quit();
	}

/*+++++++++++++++++++++++++++ Test NG. xml ++++++++++++++++++++++++++++*/

<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name = "Selenium Suite V3">
	<test name = "Test">
	<classes>

		<class name="web.SampleTest_testng" />
		<class name="web.HomepageNavBox_TextVerification_Test" />

	</classes>
	</test>
	
</suite>

/*+++++++++++++++++++++++++++ ERROR when running ++++++++++++++++++++++++++++*/

FAILED CONFIGURATION: @BeforeClass openBrowser
java.lang.NullPointerException
	at com.relevantcodes.extentreports.converters.TestConverter.createTestList(TestConverter.java:47)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:85)
	at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:362)
	at web.HomepageNavBox_TextVerification_Test.openBrowser(HomepageNavBox_TextVerification_Test.java:23) << **this point to the above where i marked the boolean as true or false**
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)

**Comment by anshooarora** [comment]
> The suite works ok when I have the boolean set to true. Below are my codes.

You should instantiate Extent in `@BeforeSuite`. 

Mark `replaceExisting` as `true` if you want a new report created each time.


> Also to inform, I'm not quite sure what am I supposed to do with the part in your documentations that says "Configurations 2.40.2". I see two older versions as well. What am I supposed to do?

New versions has more enhanced configuration features, use the config settings that belong to the version you are using.  For example, version 2.40.2 has a new config flag: `theme` which is not available to the versions prior to it.


> Last but not least I'm keen to know when ExtentX maybe out?

No ETA available, lots of work is still remaining, but I am targeting sometime next month.

**Comment by shafiq-eric** [comment]
I don't think you understand my issue. I want to set `replaceExisting` as `false`. I have two test cases running through testNG

```
    <class name="web.SampleTest_testng" />
    <class name="web.HomepageNavBox_TextVerification_Test" />
```

if i set the value to `true`, extent will run web.SampleTest_testng << compile the results but when web.HomepageNavBox_TextVerification_Test is completed, it will replace the report of the first. i want one report to be generated for the two or more test cases.

As for Configurations 2.40.2. What am I supposed to do? Create a new xml? Place that into my POM file? I understand that there are settings that may belong to the version I use.

**Comment by karthikbhatnagar** [comment]
Did you try instantiating extent in beforeSuite? that should solve your problem, using replaceexisting this way is not a good practice in my opinion.
