### ISSUE TITLE
Log in .txt format??

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports#359]
Is the log is getting saved in .txt format or can I export the log results to .txt format ?

**Comment by anshooarora** [comment]
Extent log?  From HTML to txt?  Its not generated in text, it comes from the models and with templating, the HTML file gets created. You can extract this info from the report using jsoup for example.

**Comment by vigneshwar-v** [comment]
i have two different C# projects. One is, for maintaing page objects and methods and another one is holding test classes which runs in parallel. So, I have a extentreports wrapper in my TESTS project and i cant get the logs from my PAGE project? have you ever experienced any scenarios like this , before??

**Comment by testphreak** [comment]
This issue in general is vague. The short answer is a .html report file is generated in the directory of your choosing when you initialize ExtentReports. I doubt anyone would have experienced this issue as both page classes and test classes are usually in one project. The fact that you somehow have 2 projects and using ExtentReports across 2 projects is unheard of and maybe the reason why can't get the logs from another project. Also to make sense of all the test steps in the report, the same instance of ExtentReports would need to be used. Not sure how you can do that in this scenario. 

I suggest improving on your existing test framework based on best practices.
