### ISSUE TITLE
Filtering on Details is broken (case sensitivity issues)

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#36]
If you have test named something like "UserTestLah" and another "UserSchmestBlue" and you filter on "Use" it doesn't show your tests. If you filter on "use" it shows the 2 tests.

**Comment by anshooarora** [comment]
This is now fixed and will be part of the upcoming release.

**Comment by cktech529** [comment]
Thanks :)

**Comment by anshooarora** [comment]
Issue fixed with ad6b91d (version 2.04).  Closing ticket.
