### ISSUE TITLE
Screenshots not displaying on exported reportshtml file

### ISSUE THREAD

**Issue by samiullah** [anshooarora/extentreports#361]
Hi anshu , we tried using both relative and absolute paths for screenshot and reports. Screenshots are displaying in reports when we are accessing them locally, but when we send the report html file via email to other person, for him screenshots are not appearing on reports. Kindly let us know how this can be fixed

**Comment by anshooarora** [comment]
from [gitter/extent](https://gitter.im/anshooarora/extentreports): @samiullah - this is expected behavior. you should package the report along with all image files and send it over email. the recipient won't be able to access your local drive

So you can do something like:

```
/report
    - report.html
    /snapshots
        - 1.jpg
        - 2.jpg
```

and use the paths such as: `./snapshots/1.jpg' or `snapshots/1.jpg'.

**Comment by hari4401** [comment]
Hi Anshooarora,

The relative path is not working as you are suggested in this post in reports images shows blank
![untitled](https://cloud.githubusercontent.com/assets/17642664/21327476/59505ed0-c655-11e6-9566-f80446f5248e.jpg)

**Comment by shailendra0090** [comment]
I am noticing the same , when we send the report html file via email to other person, for him screenshots are not appearing on reports. I am using the path as mentioned above: e.g ./Screenshots/TestCase1/1.png

![capture](https://cloud.githubusercontent.com/assets/24816386/21532185/7665e71e-cd13-11e6-8e4f-da4e4e0be3ac.PNG)

**Comment by email2vimalraj** [comment]
@samiullah , @hari4401 and @shailendra0090 : Are you guys sending the report html file along with screenshots as well with the same directory structure? If not, no one will be able to view the screenshot, that is the expected behavior.

You can try using the base64 screenshot option to capture the screenshots in base64 format instead of a file which will be embedded in the report. So sharing would be easier. Refer here for more details: http://extentreports.relevantcodes.com/java/#insert-screenshots

**Comment by poojagadekar89** [comment]
Anyone got the solution ?

**Comment by littleh322** [comment]
Following @email2vimalraj, I'm still having the same issue here. I used the ExtentTest.addBase64ScreenShot() method and 'data:image/png;base64' output type. This has always worked locally... For some reason, Jenkins is no longer displaying any images on test failures.

**Comment by Iamshubhk** [comment]
i am having the same issue, screenshot get attached on local but on jenkins screenshot is not visible and getting below mentioned output.
![report](https://user-images.githubusercontent.com/23064259/30991026-f735e2e2-a4c0-11e7-82f9-4bf3d3654a80.png)

**Comment by littleh322** [comment]
Here's a picture of my output and another picture of when I click on the photo. Both previews appear blank. However, if I right-click on the photo and select 'Open in New Tab' (Chrome), it'll display the photo with no issue. Is anyone able to use that workaround? 

![extentreport_images](https://user-images.githubusercontent.com/16089976/31017565-88333ff6-a4ee-11e7-87f0-04648ae9457d.jpg)
![extentreport_images_clicked](https://user-images.githubusercontent.com/16089976/31017566-884916aa-a4ee-11e7-96d0-3efb9f661b4e.jpg)

**Comment by Ahmedz1984** [comment]
Is anybody found the solution for this, please let me know, I am having the same issue after setting up relative path. Please let me know.

**Comment by RajendranSubramaniam** [comment]
Hi Ahmedz, Did you get the solution for this?

**Comment by RajendranSubramaniam** [comment]
I am also facing the same issue?

**Comment by GMVictor** [comment]
This did the trick for me: 

`test.fail("Details", MediaEntityBuilder.createScreenCaptureFromPath(Paths.get("").toAbsolutePath().toString() + "/screenshotFolder/screenshot.png").build());`

I hope it helps :)

**Comment by RajendranSubramaniam** [comment]
Hi Victor,
My issue was related to Screenshot not getting captured in Jenkins. But I run locally(with in eclips), it works fine, able to see the screenshot for failed case. When I run the same scripts it becomes empty box.
If your above comment is related my issues, where exactly I need to insert this code? Please suggest me.

**Comment by RajendranSubramaniam** [comment]
Hi Victor,
I meant it is not capturing in extent report when we execute from Jenkins.

**Comment by GMVictor** [comment]
Do you get an image or nothing at all?  What's the configuration of your Jenkins job? Are you running in a slave machine or in the master? 
Check the path of the screenshot in the report, it should point to an accessible location in the machine where Jenkins jobs run and generate reports.  
You could use a shared folder as image repository, accessible to the job to with write rights to create the screenshots.  Then point the image to that path.  
`src ="<sharedFolder>/screenshotName.png" `

For example:  `src:="D:/JenkinsScreenshots/screenshot1.png"`
This works as long as the screenshots remain in that location. See below: 

Not accessible screenshot: 
![image](https://user-images.githubusercontent.com/36865667/36883259-9adc1352-1d9e-11e8-803d-334395eb33f5.png)

Accessible Screenshot: 
![image](https://user-images.githubusercontent.com/36865667/36883226-569a8bba-1d9e-11e8-884d-7c3913735363.png)

Please let us know if this helps.

**Comment by dipesh17** [comment]
Hi,

**Project Structure**

- src/main/java
- src/main/resource
- src/test/java
- report 

Note: The above Report Folder will have report.html and all images in one folder. This helps us to zip this folder and send as an email attachment when failure will kick in while running the build on Jenkins.

```

               Calendar calendar = Calendar.getInstance();
		SimpleDateFormat formater = new SimpleDateFormat("dd_MM_yyyy_HH_mm_ss");

		StringBuilder builder = new StringBuilder();
		builder
			.append("./report/Report")
			.append(formater.format(calendar.getTime()))
			.append(".html");
		
		extentHtmlReport = new ExtentHtmlReporter(builder.toString());

		extentHtmlReport.config().setTestViewChartLocation(ChartLocation.TOP);
		 extentHtmlReport.config().setChartVisibilityOnOpen(true);
		 extentHtmlReport.config().setTheme(Theme.DARK);
		extentHtmlReport.config().setDocumentTitle("END API Report");
		 extentHtmlReport.config().setEncoding("utf-8");
		 extentHtmlReport.config().setFilePath("./report/");
		
		 extentHtmlReport.config().setReportName("API Automation Report");
		 
		 extentReports = new ExtentReports();
		 extentReports.attachReporter(extentHtmlReport);
```

While saving images you can keep image path as

```
String imagepath = "./report/";
String imageName = "fail_test.png";

File scrFile = ((TakesScreenshot) getConfig().getDriver()).getScreenshotAs(OutputType.FILE);
destFile = new File((String) imagePath + imageName);

FileUtils.copyFile(scrFile, destFile);

```
This is working for us and I hope this will help.

**Comment by gineanne** [comment]
Hello, 
I solved the issue by using this folder structure:
- target/html_report/screenshots/sample.png

And this is my sample code:

File destination = new File(System.getProperty("user.dir") + "\\target\\html_report\\screenshots\\" +"sample.png");
File scrFile = ((TakesScreenshot) getDriver()).getScreenshotAs(OutputType.FILE);
			FileUtils.copyFile(scrFile, destination.getAbsoluteFile());
Reporter.addScreenCaptureFromPath("screenshots\\" + scenario.getId().split(";")[0] + "\\" + scenario.getName().replaceAll("\\s", "_") + "_" + timeStamp + ".png");

I'm using the cucumber-extentsreport by vimalselvam

**Comment by raghavilatha** [comment]
Hello @GMVictor 

I too facing the same issue, Screenshots are getting break when i run by build through Jenkins. Can you help me out?
![image](https://user-images.githubusercontent.com/11693873/39283413-b7da3420-4940-11e8-9db1-d05afcbaf1ee.png)

**Comment by anilnagaraju** [comment]
Even am facing the same issue.. Can any one please provide solution for the same.

**Comment by abhilashtc** [comment]
I kept the screenshots on the Tomcat hence its accessible from any system in the intranet. Repositories are created dynamically for the respective test, so it can be archived on a later date.

**Comment by arjun0110** [comment]
Am having the issue. In my local reports are there but when sent to mail via Jenkins the images are broken

**Comment by adrian-arg** [comment]
I see the issue is closed.
Which was the actual solution?

**Comment by arjun0110** [comment]
I don't know as who closed it
I still have the issue
