### ISSUE TITLE
using postsharp with extent reports

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports#368]
can we use postsharp for generating reports using extent reports??

**Comment by vigneshwar-v** [comment]
??

**Comment by anshooarora** [comment]
As per the docs:

> PostSharp is the #1 pattern-aware extension to C# and VB. It allows developers to eradicate boilerplate by offloading repeating work from humans to machines. PostSharp contains ready-made implementations of the most common patterns and gives you the tools to build automation for your own patterns.

So I don't see why not.
