### ISSUE TITLE
[HelpNeeded] Not able to have child nodes when running tests in parallel

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports#369]
@anshooarora @virenv i was trying to add child nodes to my test execution when running the tests in parallel, i see for failed cases it doesnt display the results corrected. 

Can you please check me on this n help me ?

i'm attaching a sample test project :+1: 

[ExtentChildTest.zip](https://github.com/anshooarora/extentreports/files/171648/ExtentChildTest.zip)

**Comment by virenv** [comment]
@saikrishna321 
Hey, I am getting following exception while running tests. 

Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@762efe5d
Tests run: 12, Failures: 1, Errors: 0, Skipped: 11, Time elapsed: 1.325 sec <<< FAILURE!
beforeMethod on [Sample2Test passed=0 failed=0 skipped=0](com.tests.Sample2Test)  Time elapsed: 0.73 sec  <<< FAILURE!
java.lang.IllegalArgumentException: wrong number of arguments
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
        at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at org.testng.TestRunner.privateRun(TestRunner.java:782)
        at org.testng.TestRunner.run(TestRunner.java:632)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
        at org.testng.SuiteRunner.run(SuiteRunner.java:268)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
        at org.testng.TestNG.run(TestNG.java:1064)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Please specify the steps to run your code.

**Comment by saikrishna321** [comment]
@virenv 

```
 mvn clean -Dtest=Runner test
```

**Comment by anshooarora** [comment]
I see that in changing`@AfterClass` in your BaseTest.java to `@AfterMethod`.  And in `@AfterClass`:

```
@AfterClass
public void afterClass() {
    ExtentManager.getInstance().endTest(parent);
    ExtentManager.getInstance().flush();
}
```

I haven't tested this, only looked at your code from BaseTest.java though but the above should work in my opinion.

**Comment by saikrishna321** [comment]
@anshooarora no luck 

```
package com.tests;

import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;

import java.lang.reflect.Method;

public class BaseTest extends TestListenerAdapter {
    public ExtentTest testReporter;
    public ExtentTest parent;
    public ExtentTest child1;
    public ExtentTest child2;

    @BeforeMethod
    public void beforeMethod(Method caller) {
        parent = ExtentTestManager.startTest(caller.getName(), "This is a simple test.").assignCategory(Thread.currentThread().getName());
        child1 = ExtentTestManager.startChild1Test(caller.getName()).assignCategory(Thread.currentThread().getName());
    }

    @AfterMethod
    public void afterMethod(ITestResult result) {
        if (result.isSuccess()) {
            ExtentTestManager.getTest().log(LogStatus.PASS, "Test passed");
        } else if (result.getStatus() == ITestResult.FAILURE) {
            ExtentTestManager.getTest().log(LogStatus.FAIL, "Test failed");
            ExtentTestManager.getTest().log(LogStatus.ERROR,"Error Stacker");

            parent.appendChild(child1);
        } else if (result.getStatus() == ITestResult.SKIP) {
            ExtentTestManager.getTest().log(LogStatus.SKIP, "Test skipped");
        }
        
        ExtentManager.getInstance().endTest(parent);
        ExtentManager.getInstance().flush();
    }

}

```
I still see tests which is executed as pass are also tagged as Unknown

<img width="1439" alt="screen shot 2016-03-15 at 10 08 34 pm" src="https://cloud.githubusercontent.com/assets/4045041/13785824/0354143a-eafb-11e5-95cb-f21247739779.png">

**Comment by anshooarora** [comment]
you missed this part:

```
@AfterClass
public void afterClass() {
    ExtentManager.getInstance().endTest(parent);
    ExtentManager.getInstance().flush();
}
```

**Comment by saikrishna321** [comment]
@anshooarora still there is issue,

1. Why do i have to use the below code in @AfterMethod and @AfterClass as well.
```
    ExtentManager.getInstance().endTest(parent);
    ExtentManager.getInstance().flush();
```
2. When i startTest report in @BeforeClass its again nothing works .Why is that so ?

 refactored code below as per your comments above 
```
package com.tests;

import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;

import java.lang.reflect.Method;

public class BaseTest extends TestListenerAdapter {
    public ExtentTest testReporter;
    public ExtentTest parent;
    public ExtentTest child1;
    public ExtentTest child2;

    @BeforeMethod
    public void beforeMethod(Method caller) {
        parent = ExtentTestManager.startTest(caller.getName(), "This is a simple test.").assignCategory(Thread.currentThread().getName());
        child1 = ExtentTestManager.startChild1Test(caller.getName()).assignCategory(Thread.currentThread().getName());
    }

    @AfterMethod
    public void afterMethod(ITestResult result) {
        if (result.isSuccess()) {
            ExtentTestManager.getTest().log(LogStatus.PASS, "Test passed");
        } else if (result.getStatus() == ITestResult.FAILURE) {
            ExtentTestManager.getTest().log(LogStatus.FAIL, "Test failed");
            ExtentTestManager.getTest().log(LogStatus.ERROR,"Error Stacker");

            parent.appendChild(child1);
        } else if (result.getStatus() == ITestResult.SKIP) {
            ExtentTestManager.getTest().log(LogStatus.SKIP, "Test skipped");
        }
        ExtentManager.getInstance().endTest(parent);
        ExtentManager.getInstance().flush();
    }

    @AfterClass
    public void afterClass() {
        ExtentManager.getInstance().endTest(parent);
        ExtentManager.getInstance().flush();
    }

}

```
I still see unknowns picked in the report 
<img width="1435" alt="screen shot 2016-03-16 at 5 58 23 am" src="https://cloud.githubusercontent.com/assets/4045041/13798435/6aa71e0c-eb3c-11e5-8c81-e5693ba5d678.png">

**Comment by anshooarora** [comment]
Are you running parallel classes or methods?

**Comment by anshooarora** [comment]
With parallel-classes:

thread-1:
![thread-1](https://cloud.githubusercontent.com/assets/4107384/13799225/7b106722-eaeb-11e5-9b80-9988d9043ee2.png)

thread-2:
![thread-2](https://cloud.githubusercontent.com/assets/4107384/13799226/7b143c9e-eaeb-11e5-8bf3-1e86386bee3c.png)

Code:

```java
public class BaseTest extends TestListenerAdapter {
    public ExtentTest testReporter;
    public ExtentTest parent;
    public ExtentTest child;

    private Map<Long, ExtentTest> parentContext = new HashMap<Long, ExtentTest>();
    
    @BeforeClass
    public synchronized void beforeClass(ITestContext caller) {
        parent = ExtentTestManager
                .startTest(caller.getName() + " " + Thread.currentThread().getName(), "This is a simple test.")
                .assignCategory(Thread.currentThread().getName());
        parentContext.put(Thread.currentThread().getId(), parent);
    }
    
    @BeforeMethod
    public void beforeMethod(Method method) {
        child = ExtentTestManager.startTest(method.getName()).assignCategory(Thread.currentThread().getName());
    }

    @AfterMethod
    public void afterMethod(ITestResult result) {
        if (result.isSuccess()) {
            ExtentTestManager.getTest().log(LogStatus.PASS, "Test passed");
        } else if (result.getStatus() == ITestResult.FAILURE) {
            ExtentTestManager.getTest().log(LogStatus.FAIL, "Test failed");
            ExtentTestManager.getTest().log(LogStatus.ERROR,"Error Stacker");
        } else if (result.getStatus() == ITestResult.SKIP) {
            ExtentTestManager.getTest().log(LogStatus.SKIP, "Test skipped");
        }
        
        parentContext.get(Thread.currentThread().getId()).appendChild(child);
        ExtentManager.getInstance().flush();
    }

    @AfterClass
    public void afterClass() {
        ExtentTestManager.endTest(parent);
        ExtentManager.getInstance().flush();
    }
}
```

**Comment by saikrishna321** [comment]
I'm running parallel classes

**Comment by anshooarora** [comment]
Solution for parallel classes right above

https://github.com/anshooarora/extentreports/issues/369#issuecomment-197096014

**Comment by saikrishna321** [comment]
@anshooarora .. Thanks for your help :) works mate :+1: closing the ticket


FYI -- i have used extent reports for one of my appium parallel framework .. 

https://www.thoughtworks.com/insights/blog/speeding-test-execution-appium

**Comment by saikrishna321** [comment]
@anshooarora 

When i have retry trigger in ma tests, in the tests its displayed as skips can i have all skips inside a single node

**Comment by anshooarora** [comment]
Do you mean skip for all steps/logs?

**Comment by saikrishna321** [comment]
look at the screenshot below : testMethodOne_7 is holding 2 skips and 1 fail status.. i need to put all the testMethodOne_7 status together... is this possible ?

![screen shot 2016-03-16 at 1 07 53 pm](https://cloud.githubusercontent.com/assets/4045041/13837314/cf9a8f80-ec2f-11e5-8225-530ab6242fb9.png)

**Comment by VinitSandesara** [comment]
Yes Sai i am agree with you, if Skip test can group (Append) in same test method then it looks good (I have delivered report to my management and he came to me asking why there are duplicate test in class, he didn't know what is Retry so to avoid this we need to append Skip test in same test method) , Anshoo, PFB screenshot with highlighted area and comment. 

![screen shot 2016-03-17 at 11 21 32 am](https://cloud.githubusercontent.com/assets/12589206/13853777/512ca6e0-ec36-11e5-8b8d-03977bac22fb.png)

Thanks
Vinit

**Comment by jiggy-rc** [comment]
Hi Anshoo,

I am trying to use this exact code that you gave (for Parent-Child parallel testing) above w version 2.41, but ExtentTestManager is throwing compile time error. I created a new Class BaseTest ... just copied and pasted the code ... nothing else but getting error (ExtentTestManager cannot be resolved). Please help.
