### ISSUE TITLE
Log Failed versius Error has different formatting..

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#37]
![image](https://cloud.githubusercontent.com/assets/6800679/9011264/21cbf764-377a-11e5-9d62-eb5c41578d0c.png)

Nothing major, just noticed the following differences when logging FAIL versus ERROR.

Each start with plain text and are followed by some <pre> </pre> entries.

**Comment by anshooarora** [comment]
They look different because the HTML is different:

Test failed is not part of <code>pre</code> tag:

```
Test failed 
<pre>Test Description: User Role based control behavior..</pre>
<pre>Class Name:..</pre>
```

Test Error is part of <code>pre</code> tag:
```
<pre>Test Error
    <pre>EMCAutomation.view.common...</pre>
    <pre>I/O limit delete option..</pre>
</pre>
```

**Comment by cktech529** [comment]
On your end? I had Test Failed and Test Error as both Strings. I'd then append <pre></pre> content to both...

**Comment by anshooarora** [comment]
Chris

How are you reporting these steps?  Can you provide a sample log for each?

**Comment by anshooarora** [comment]
Closing ticket as issue was due to extra pre tags.
