### ISSUE TITLE
Assigning Different categories for parent nodes??question

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#370]
![new doc 16_1](https://cloud.githubusercontent.com/assets/17696918/13744866/c483f8a0-ea10-11e5-903b-b986d5e37cc5.jpg)

Actually i need 3 categories for Browsers as shown in picture and if i click Browser0 it should show nodes inside it which are Testcases(maybe it are its child/not) which has children Iteration0,Iteration1 ,Iteration2.How can i achieve this having seperate buttons at left most side of report, like a button of  dashboard view,having buttons for Browsers,as shown in picture above.

**Comment by MaxiTalenti** [comment]
+1

**Comment by meenakshi127616** [comment]
![capture](https://cloud.githubusercontent.com/assets/17696918/13880603/f5b093c2-ed42-11e5-8468-3db00d6fa6b6.PNG)
So earlier i had hierarchy(Refer image above)
Browser01 (Parent)

Test Case01 (Child L1)

             - Iteration 1 (Child L2)
             - Iteration 2 (Child L2)

But now i want that my topmost parent(level1) which is Browsers should come as Categories in side bar something like(refer image below)
![snip](https://cloud.githubusercontent.com/assets/17696918/13880847/4584179c-ed44-11e5-848d-e1cee5bd9b84.PNG)

So how can i make my Browser as a category rather than a parent and append testcases inside it which we earlier its children?Please suggest any better solution insted of parent -child hierarchy.

**Comment by meenakshi127616** [comment]
Any help would be appreciated as i was exploring different features of this report but could not get much help from this page.

**Comment by meenakshi127616** [comment]
Please provide sample code or any example for the same.
or any basic idea how i can solve this issue.

**Comment by MaxiTalenti** [comment]
![lol](https://cloud.githubusercontent.com/assets/7159779/13887596/5ea3630a-ed1b-11e5-8424-37ee1170741f.jpg)

this.TestT = ExtentR.StartTest(methodBase.Name,**Browser.Chrome**);

**Comment by anshooarora** [comment]
This is not currently possible.  All child test categories will automatically be displayed at the parent level.  

I will accept pull-requests with this feature included though, and remember, the same hierarchy must be implemented for the categories views.

**Comment by anshooarora** [comment]
Duplicate #360.
