### ISSUE TITLE
Can you remove "File:///" in img tag when adding screenshot??

### ISSUE THREAD

**Issue by vigneshwar-v** [anshooarora/extentreports#371]
When I copy the report with screenshots folder to another place, it expects for an exact match because of "File:///" value. can you do something about this issue??

**Comment by anshooarora** [comment]
`file:///` will only appear for absolute paths, that are local to your system.  Otherwise, the images will not display.

**Comment by vigneshwar-v** [comment]
u mean if I pass relative path , the "file:///" will not appear in the generaed html report?
