### ISSUE TITLE
Parent child relationship between Skip test (Retry) with test method 

### ISSUE THREAD

**Issue by VinitSandesara** [anshooarora/extentreports#373]
Hi Anshoo, I have various test method in each class with Retry on it, how do i append Skip test (Retry) in same test method, PFB screenshot with highlighted area with comment, I need the solution to append Skip test (Retry) in same test method instead of appending alone in class which looks like a duplicate name in report under class.

![screen shot 2016-03-17 at 11 21 32 am](https://cloud.githubusercontent.com/assets/12589206/13853394/79ffd152-ec34-11e5-9ed8-860d9df2f889.png)

Thanks
Vinit

**Comment by VinitSandesara** [comment]
Hi Anshoo, any update on this ?

Thanks
Vinit

**Comment by anshooarora** [comment]
This is an enhancement, same as #106.  Feel free to update that ticket with additional scenarios.  I will close this as being duplicate.
