### ISSUE TITLE
IDE shows test is fail however dashboard show test is pass.

### ISSUE THREAD

**Issue by hitesh02sharma** [anshooarora/extentreports#374]
Hi Team,

Below is my test

  @Test(groups = {"ONLINESHOP"})
    public void CreateCharityCompanyOrderTest() throws InterruptedException,AWTException {
        ExtentTest extentReports = ComplexReportFactory.getTest();
        extentReports.assignCategory("Regression");
        extentReports.assignCategory("Hitesh");
        extentReports.log(LogStatus.INFO,"TC01 : Charity Order");
        line 1
	line 2
	line 3
	line 4
	line 5
        extentReports.log(LogStatus.PASS,"Wow, I am able to place order");
    }
}

While executing via intelliji idea,my test failed at line 3 however in dashboard its showing PASS.

Any pointer please 

regards
Hitesh

**Comment by hitesh02sharma** [comment]
Adding few more information

I have also added below code under BaseTest.java
@AfterMethod
    public void tearDown(ITestResult result) {
        if (result.getStatus() == ITestResult.FAILURE) {
            test.log(LogStatus.FAIL, "<pre>" + result.getThrowable().getMessage() + "</pre>");
        }
    }

and then change the Line in test case as well

extentReports.log(LogStatus.PASS,"Wow, I am able to place order");
extentReports.log(LogStatus.FAIL,"Opps ! failed");

In case if Test is failed then it should pick only Fail test case however i can see success log is logged in extent report rather failure

**Comment by anshooarora** [comment]
There is an example of `@AfterMethod` [here](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/BaseExample.java).  You can include another condition for skip, and remember to call `endTest` and `flush` at the end.

**Comment by hitesh02sharma** [comment]
[ExtentReport.docx](https://github.com/anshooarora/extentreports/files/179948/ExtentReport.docx)

Hi Anshoo

Thanks for reply.

Can you please have a quick look in document. I am trying what you have mentioned earlier but  still I am getting same error.

Please any pointer.

Hitesh
