### ISSUE TITLE
HTML display latest result only

### ISSUE THREAD

**Issue by voravuth** [anshooarora/extentreports#375]
Hello,

First of all, thanks for very good and beautiful report. I really like it a lot.

However, I have a little bit problem. Currently, I'm running my test using testng.xml. The problem is if there are more than 1 test case in the xml file, the report will only display the latest result even I've already set the replace existing to false.

For example,

This is my testng.xml

```
 <suite name="Smoke Test Suite" verbose="1" parallel="false">
   <test name="Smoke Test">
        <classes>
           <class name="TestGoogle" />
           <class name="TestGoogle2" />
        </classes>
    </test>
</suite>
```

After executed the xml file, only the TestGoogle2 will display in the html file. I try to open the html file after the first test case executed, the html displayed correctly but after second test case executed. The first test case has been overwritten.

Could you help investigate on this ?

Thank you very much.
Vora

**Comment by anshooarora** [comment]
If multiple threads run at the same time, to be saved in the same location & same file, only 1 report will be created.  In your scenario, if you are dealing with multiple concurrent files, I would recommend creating multiple reports instead of 1.  Can you share your code also?  Are you instantiating Extent multiple times for the same run session?

**Comment by voravuth** [comment]
Hi anshoo,

Sorry that I can't share you my code at this time. Currently, I'm writing the automation framework that can reuse Extent Report in every test classes and yes, I instantiating Extent multiple times in the same run session.

Actually, I agree with your solution, generating multiple reports is a good idea. However, I just want a one result file that summarize all of the test execution.

Right now, I'm using extentMerge to merge the result files but it would be better if I can just run the test and the report will generate all of the test execution results for me.

Thank you,
Vora

**Comment by anshooarora** [comment]
Use [this](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/common/ExtentManager.java) for example - this will not allow more than 1 instance created.  Multiple instances = multiple reports. So, with the ExtentManager singleton, you can just access the same instance over and over to build a single report for all your test classes.
