### ISSUE TITLE
Reports contain unknown status tag.

### ISSUE THREAD

**Issue by pavankumar9** [anshooarora/extentreports#376]
There is a problem with report generation. I am getting unknown status tag as well. Can you please look into this and let me know what I am missing.
![extent_report_issue](https://cloud.githubusercontent.com/assets/16286975/13876252/ca87a27c-ed28-11e5-9f7a-0fcf65f741d8.png)

Version: 2.40.2

**Comment by anshooarora** [comment]
Looks like the status of the log isn't being set, and your test is being executed/saved twice.  What testrunner are you using?  If TestNG, add [this](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/BaseExample.java) for `AfterMethod`.

**Comment by pavankumar9** [comment]
Thanks this got fixed. The following piece of code was called twice. Strange I was not getting any error in report for version 2.031.

extent.startTest(testName,description);

**Comment by poojavithal** [comment]
There is a problem with report generation. I am getting unknown status tag as well. Can you please look into this and let me know what I am missing. and how to fix this issue **extent reports version:2.41.0**

![image](https://cloud.githubusercontent.com/assets/23046667/25986128/e1802aac-370b-11e7-8321-b1f31f7daddf.png)

**Comment by anshooarora** [comment]
Would it be possible to upgrade to version 3.0.6 (latest as of today)?  This issue will go away automatically.  If not, please make sure to call `endTest` in your `@AfterMethod` as I have suggested in my previous comment.
