### ISSUE TITLE
Dashboard open unable to scroll to the bottom of the report

### ISSUE THREAD

**Issue by seanmcguire413** [anshooarora/extentreports#378]
![extent report](https://cloud.githubusercontent.com/assets/17932532/13885509/6c7fafd8-ecf8-11e5-9664-5429e65a9b17.PNG)

If you have a large amount of info statements and have the dashboard open it will not allow you to scroll all the way down to the bottom of the report.

**Comment by anshooarora** [comment]
Please update your version for 2.40.2 - this was one of the bug fixes.

**Comment by seanmcguire413** [comment]
Thanks Great program

**Comment by seanmcguire413** [comment]
It is not fixed all the way.  I upgraded to 2.40.2 and I have 127 lines of
info and I am missing 5 lines with the dashboard open.
