### ISSUE TITLE
How to Merge Extent Report at logging and Listener level

### ISSUE THREAD

**Issue by RahulVermaAutomation** [anshooarora/extentreports#379]
I want to add Extent report at listeners and logging level on my project such that test logging that I input at test scripts and listeners output both will be available after execution of the test suite. Basically i want to mix extent report at listeners and logging level simultaneously. Currently while trying to add, testng is executing single method twice from logging and from extent report but I want that to execute single method only and both logging and result any exception comes in a single method.

Please help.

Cheers!!

-Rahul

**Comment by anshooarora** [comment]
The difference between the 2 approaches is:

- The listener is kicked off when all tests are completed
- Normal logging occurs as the tests are being executed

To combine the 2, you will have to maintain references while the tests are being executed (without ending tests) and use those references when ending tests in listener. 

But, why go down this route?  Just use it as a normal logger and configure `@AfterMethod` to manage end-of-test reporting.

**Comment by RahulVermaAutomation** [comment]
Hi Anshu,

I am using combination of 2 because i am also attaching screenshots on failure and for that I have to use listeners which is currently implemented on my project.

Below is the sample code i have tried but could't succeed.

Test Code below for the listeners:

I am using single instance for the instance report so added below method in the Extenet report.

public synchronized static ExtentReports getReporter(String filePath) {
if (extent == null) {
extent = new ExtentReports(filePath + File.separator + “Extent.html”, true, NetworkMode.ONLINE);

extent
.addSystemInfo(“Host Name”, “Rahul”)
.addSystemInfo(“Environment”, “SIT”);
}

return extent;
}

Also, in the script level i have added below code for logging purpose:

public class GoogleTest extends ExtentReporterNG{

public void googleAssertPass() {

ExtentReporterNG.getReporter(outputDirectory);
test = extent.startTest(“test1”, “test1 – description”);
System.setProperty(“webdriver.chrome.driver”, “C:\\projects\\test\\chromedriver.exe”);
driver = new ChromeDriver();
test.log(LogStatus.INFO, “Calling google”);
driver.get(“http://google.com”);
test.log(LogStatus.INFO, “Verifying google Search button”);
Boolean isFound = IsElementPresent(driver,
By.cssSelector(“input[value*=’Google Search’]”));

Assert.assertTrue(isFound);
driver.quit();
extent.endTest(test);
extent.flush();

}

}


Thanks,
Rahul
