### ISSUE TITLE
pie charts not refreshed after filter Tests.

### ISSUE THREAD

**Issue by meenakshi127616** [anshooarora/extentreports#382]
when i set filter based on fail, my pie charts on dashboard view still shows fail,pass and skip inside pie chart area,in my case but i need pie chart to just show fail after filtering fail?
it shows:
![snip1](https://cloud.githubusercontent.com/assets/17696918/13915250/91ba9302-ef79-11e5-9542-7b6d09cb3e3d.PNG)

after filtering it still stays same,i need something like
![snip2](https://cloud.githubusercontent.com/assets/17696918/13915293/cc0e8e5a-ef79-11e5-8ddc-50bc846339ab.PNG)

**Comment by testphreak** [comment]
Dashboard is just that, it gives you a high level quick glance of how your run did. I don't think the dashboard view was ever meant to link with the tests view. Also, why would you want a pie chart with a single data point? It only makes sense with multiple data points.

**Comment by meenakshi127616** [comment]
when i filter tests based on pass/fail/skip the pie chart on dashboard view shows status of all tests,should not it show 100% green pass when i filter pass,100% red fail when i filter fail in tests and back to multiple data on clearing filter,which means pie chart in  dashboard is not synchronized with filters?
i am getting a pie chart with a single data point which i have shown above, when i "save" the modal view as parent without child tests+child tests.
(refer image),after saving here my pie charts are showing single data points after filtering but i want it to default show pie chart with single entries when i filter that specific entry in tests.

![snip1](https://cloud.githubusercontent.com/assets/17696918/13940761/5f581d3e-f006-11e5-8e45-3eb05ced28b7.PNG)

**Comment by meenakshi127616** [comment]
how can i add this feature inside inside my code or jar?please provide useful suggestions.

**Comment by anshooarora** [comment]
Does selecting "child nodes only" provide the correct representation?

**Comment by meenakshi127616** [comment]
selecting "child nodes only" / " parent without child tests+child tests" gives same result in my case,but i was saying clicking on "save" gives pie chart with single entries when i filter that specific entry in tests which i need by default without explicitly clicking on save button means it does not refresh after filtering only refreshes after save,but i comes only when i click save button in modal.

**Comment by anshooarora** [comment]
Can you share a sample report?  There may be something wrong with the filter logic, I will have to check to be sure.

**Comment by meenakshi127616** [comment]
yes it is working fine now, i by mistake made some wrong changes inside javascript to calculate pass percentage variable,due to which pie charts were not coming correctly.
thanks.

**Comment by anshooarora** [comment]
Please don't open tickets if you are making changes to the source.  Once you do that, we can no longer know what you've done.

**Comment by karthikbhatnagar** [comment]
@anshooarora  -  you might want to check also if they (Lochbridge) are in violation of license terms.
