### ISSUE TITLE
extent report for Data-provider test

### ISSUE THREAD

**Issue by aksharpanchal** [anshooarora/extentreports#385]
**Is there a better way to integrate data provider tests?**

<img width="1332" alt="before" src="https://cloud.githubusercontent.com/assets/12203468/13956556/dee54560-f00e-11e5-9dce-91c0fe9ab587.png">

**As a work around added test parameters in method name :**

<img width="567" alt="after" src="https://cloud.githubusercontent.com/assets/12203468/13956514/a350e0c2-f00e-11e5-87a8-a24b81980628.png">

This is just a example of test that I have, Some of my test which are data-provider driven can end up being 100+

**Comment by anshooarora** [comment]
Not sure. My initial thought is, it will be quite difficult to manage this much data in such a small block.  It will eventually start looking messy.  Let me know if you have any ideas though.

**Comment by aksharpanchal** [comment]
If Tests Step can be coupled with parameters that would be ideal allowing user to use toggle option to open or close Test Detail.

Just to give it a thought here is what I was thinking :
![test](https://cloud.githubusercontent.com/assets/12203468/13969922/2f02160e-f04b-11e5-98a7-21cec7d84496.png)

**Comment by anshooarora** [comment]
You can already do this as child tests (see appendChild method).

**Comment by aksharpanchal** [comment]
Yes that what I initially thought and the example shows child tests having indentation but I tried with 100+ test and works like a charm thanks!

**Comment by Vishwajeet-Mishra** [comment]
Can you give some examples for dataprovider testcases

**Comment by nsharma-git** [comment]
@aksharpanchal I'm using testng listener and not able to use appendChild. For my use case it would be sufficient to add parameters in the testmethod name. I tried overriding getTestName but the extent report always taking the actual method name and not the overriden one. Can you paste some sample code the way you got dataprovider parameters in the report.

**Comment by Vishvajeetcse** [comment]
@aksharpanchal I'm using testng listener. Can you please provide the sample code the way you got dataprovider parameters in the report.

**Comment by rashiatry** [comment]
@Vishvajeetcse Are you able to display your test-data (passed through dataprovider) get displayed on ExtentReport. If yes, how did you do it using testng listener? Can you share your code here. 

thanks for your help.
