### ISSUE TITLE
Need to load config file and add screen shot on report

### ISSUE THREAD

**Issue by haribabu123** [anshooarora/extentreports#386]
hi i am unable to load config file or config data on my class (using Java)

and unable to get screen shot in my report, see below code for reference..
String img = log.addScreenCapture("F://reports//screen"+ uuid +".png");
			log.log(LogStatus.INFO, "Checked mart URL" + img);

Please let me know soon..thank you so much

**Comment by email2vimalraj** [comment]
What do you mean the config file or config data? Are you referring to extent-config file?
For screenshot issue, could you please share us the report html file?

**Comment by haribabu123** [comment]
Hi anshooaroa,

For config file load is now working fine

1. and for scree shot, i used below code to get my screen shot and dispaly
in my extent log

String img = log.addScreenCapture("F://reports//screen");
log.log(LogStatus.INFO, "Checked mart URL" + img);

2. and how can i share my screen shots  along with html file in mail or to
view globally

3. and also could you please let me know, how to add extent merge in my
code instead of doing manual (jave - jar extentmerge.jar -dir filepath out
filepath)

means i need a code and maven dependency for merge, after competing my
execution, i will do merge different reports to single report

Thank you so much for your support in advance..



Thanks & Regards,
Haribabu CH
Skype ID: haribabu_qa
Ph No.:+91 897 888 3377

**Comment by anshooarora** [comment]
1. The screenshot must exist in the supplied path and the path must be correct for the snapshot to show
2. Zip the report along with folder and forward
3. Just run a command line to automatically merge reports after each execution

**Comment by haribabu123** [comment]
hi Anshooora,

Thanks you so much for your support

if you dont mind , could you send me sample code to get screen shots on my
log

i am expecting the merge in my selenium code with out running code
manually, is this possible



Thanks & Regards,
Haribabu CH
Skype ID: haribabu_qa
Ph No.:+91 897 888 3377
