### ISSUE TITLE
could not add the result of two class in the report 

### ISSUE THREAD

**Issue by hajarbabour** [anshooarora/extentreports#387]
when i run   first class the result is added to the report but when i  run the second class  the report don't keep the result of the first class  
// SimpleReportFactory {

package Rapport;

import com.relevantcodes.extentreports.DisplayOrder;
import com.relevantcodes.extentreports.ExtentReports;

public class SimpleReportFactory {

	private static ExtentReports reporter;

	public static synchronized ExtentReports getReporter() {
		if (reporter == null) {
			reporter = new ExtentReports("/Users/user/Desktop/untitled folder/SimpleReport3.html", true, DisplayOrder.NEWEST_FIRST);
		}
		return reporter;
	}

	public static synchronized void closeReporter() {
		reporter.flush();
		reporter.close();
	}

}

//First class Test001
package Rapport;

import org.testng.annotations.AfterSuite;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class Test001 {
	
	private ExtentReports reporter =  SimpleReportFactory.getReporter();
	

	@Test
	public void simpleTest002()
	{
		ExtentTest testReporter = reporter.startTest("simpleTest002", "This is a simple simpleTest002");
		testReporter.log(LogStatus.INFO, "Starting test simpleTest002");
		int a = 100;
		int b = 30;

		testReporter.log(LogStatus.INFO, "Loading the value of a to " + a);
		testReporter.log(LogStatus.PASS, "Loading the value of b to " + b);
		reporter.endTest(testReporter);
		
	}
	
	@AfterSuite
	public void afterSuite()
	{
		reporter.close();
	}
}
// second class Test002
package Rapport;

import org.testng.annotations.AfterSuite;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;

public class Test002 {
	
	private ExtentReports reporter =  SimpleReportFactory.getReporter();
	
	
	@Test
	public void simpleTest004()
	{
		ExtentTest testReporter = reporter.startTest("simpleTest004", "This is a simple simpleTest004");
		testReporter.log(LogStatus.INFO, "Starting test simpleTest004");
		int a = 100;
		int b = 30;

		testReporter.log(LogStatus.INFO, "Loading the value of a to " + a);
		testReporter.log(LogStatus.PASS, "Loading the value of b to " + b);
		reporter.endTest(testReporter);
		
	}
	
	@AfterSuite
	public void afterSuite()
	{
		reporter.close();
	}
}

**Comment by anshooarora** [comment]
You need to use only 1 `@AfterSuite`.  Use a baseClass `@AfterMethod` and add `SimpleReportFactory.getReporter().flush()` so the output is written after each test.

**Comment by hajarbabour** [comment]
ok thank's
