### ISSUE TITLE
Child tests are always placed in bottom

### ISSUE THREAD

**Issue by JobvandenBerg** [anshooarora/extentreports#389]
Hello,

I have a few testcases in which some teststeps are logged in the _parent test_ and some teststeps in a _child test_. This is done so that the tester has a quick overview of what set of teststeps are PASSed. 

My question is; why are childtests always placed at the bottom in the report? Is there a way to present the tester with a structure like;

- Several teststeps
- Child test with several teststeps
- Several teststeps
- Child test with several teststeps
- etc..

Kind Regards,

Job van den Berg

**Comment by anshooarora** [comment]
This is by design, all logs of the test will be grouped together, followed by child tests.  The structure you have shared will not be possible..  A workaround would be to use child steps instead of logging separate steps for the parent.
