### ISSUE TITLE
standalone/offline extentreports

### ISSUE THREAD

**Issue by sabonbon** [anshooarora/extentreports#39]
Hi,
I understand that there is a problme with the issue because of the visualization library of google that doesn't support offline usage, i would really appreciate it if you could try creating something like that or even tell me how to do it by myself and where do i need to chagne the code of the extentreports.
I'm using java

**Comment by anshooarora** [comment]
I am open to providing this solution though as a few other users have also requested it.  Although, it won't be soon as I am working on a few other features for now.

If you would like to do this, you can use an open-source charting library such as Flot charts.  See here for example:  http://www.flotcharts.org/flot/examples/series-pie/.  To make it look like a donut chart, you can set the <code>innerRadius</code> property.

You would also have to save all other resources: jQuery, all CSS files to a folder which you can point to for the report to work correctly.  Although this would be the easy part - just save all files locally and update path in src -> com -> relevantcodes -> extentreports -> source -> Standard.html.

**Comment by anshooarora** [comment]
I have completed the offline version and will launch it in a few weeks.. Besides the report, it will have an accompanying folder with all styles/js/fonts/icons.

**Comment by anshooarora** [comment]
Initial 0aefb5b.

**Comment by anshooarora** [comment]
Offline support (beta) is ready.  Please let me know if you would like to test.

**Comment by sabonbon** [comment]
yes i would like to test it

**Comment by anshooarora** [comment]
Here is the jar:  http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.05-beta.jar.zip

To create offline report, simply set the AccessType enum to OFFLINE:

```
ExtentReports(String filePath, Boolean replaceExisting, DisplayOrder displayOrder, AccessType accessType)
ExtentReports(String filePath, Boolean replaceExisting, AccessType accessType)
ExtentReports(String filePath, AccessType accessType)
```

A folder named "extent" will be created in the same folder as the report with the following structure:

```
extent
  - /css
     - css.css
     - fontawesome files
  - /js
     - scripts.js
```

**Comment by perwez123** [comment]
Hi Anshoo ,

 I have tested the 2.05 beta version and its working as expected but
mismatching in the status representation in the pie chart between  the
following mode mentioned below . I have highlighted that in the chart


*Online *Mode : It display the status which really exist in the report
(Working perfectly)
*OFFLine *Mode:  It display all the status (This is not expected to display
all the status)

One question : Are you using different library file for the chart in two
different mode ?

Screen shot :

[image: Inline image 1]

On Sun, Aug 23, 2015 at 10:40 PM, Anshoo Arora <notifications@github.com>
wrote:

> Here is the jar:
> http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.05-beta.jar.zip
>
> To create offline report, simply set the AccessType enum to OFFLINE:
>
> ExtentReports(String filePath, Boolean replaceExisting, DisplayOrder displayOrder, AccessType accessType)
> ExtentReports(String filePath, Boolean replaceExisting, AccessType accessType)
> ExtentReports(String filePath, AccessType accessType)
>
> A folder named "extent" will be created in the same folder as the report
> with the following structure:
>
> extent
>   - /css
>      - css.css
>      - fontawesome files
>   - /js
>      - scripts.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/39#issuecomment-133879610>
> .
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
Perwez, the image did not come through but do you mean the status for the legend?

![legend](https://cloud.githubusercontent.com/assets/4107384/9468214/07976f78-4b06-11e5-9d5f-cc388fe978b7.png)

If yes, I will have to research how to hide this as the docs do not show it.  For offline, Flot charts are being used.

**Comment by perwez123** [comment]
Yes , I was talking about legends only . rest of the features working fine

**Comment by twarenius** [comment]
This was only implemented in the Java version of ExtentReports, right?

Any chance of getting this in the .NET version also?
