### ISSUE TITLE
Remove old reports from merged report

### ISSUE THREAD

**Issue by SteveMeskers** [anshooarora/extentreports#390]
I am trying to remove some old reports from my merged report. I deleted all the old reports that I do not want anymore and I deleted the merged report to make a new one. Somehow the old reports still show up on my new merged report. I scanning a directory and sub directories to merge my reports, but  I have deleted the reports that I do not want anymore. Do you know why they would still be showing up? I even tried to name the merged report something different and the deleted reports still show up.

**Comment by anshooarora** [comment]
They shouldn't show, I suspect a path issue.  What is the command you've used to merge all files within a directory?

**Comment by SteveMeskers** [comment]
java -jar extentmerge.jar -dir . -out "C:\Users\%USERNAME%\Box Sync\InfoTech\Software Development\Testing\MergedReports\AllReports.html"

**Comment by anshooarora** [comment]
Steve

I would suggest using ExtentX as ExtentMerge is deprecated.  Also, there will be no manual merging involved as all the reports will be available on the server.  Many other great features besides that!

Download:  http://extentreports.relevantcodes.com
