### ISSUE TITLE
how can i add  screencast to my extenreports

### ISSUE THREAD

**Issue by hajarbabour** [anshooarora/extentreports#392]
I have add screenshot successfully  but i don't know how to proceed  to  add screencast when the test failed  
	@AfterMethod
	public void tearDown(ITestResult result) {
	    if (result.getStatus() == ITestResult.FAILURE) {
	    	String screenshot_path=SimpleReportFactory.captureScreenshot(driver,result.getName());
	    	String image=testReporter.addScreenCapture(screenshot_path);
	    	testReporter.log(LogStatus.FAIL, "<pre>" + result.getThrowable().getMessage() +</pre>",image);
	    }        
	    reporter.endTest(testReporter);
	    
	    reporter.flush();
	}
Any assistance would be greatly appreciated!

**Comment by anshooarora** [comment]
It is the same way you add screenshots, no difference as you are only linking the path.  However, now all video formats may be supported if you are viewing the static file locally and without using a server.

**Comment by hajarbabour** [comment]
but it doesn't work for me i don 't know by why should i replace captureScreenshot ???
