### ISSUE TITLE
I need black color for backgroung

### ISSUE THREAD

**Issue by mashek347** [anshooarora/extentreports#394]
Thanks for the extent report. Could you please send me the code for background color black. I like very for black background. I am not a developer I am just a selenium tester. I would like to make background color black. I will be must appreciate if you provide me how to create black color for XSLT report.
Here is my email-masheknyus@gmail.com

Note: I am very new to use. Please do needful.

**Comment by anshooarora** [comment]
Version?

**Comment by mashek347** [comment]
Current version.

**Comment by mashek347** [comment]
Name Is Extentmerge.

**Comment by mashek347** [comment]
Hi Arora,

I am looking for this format. Please refer screen shot
![testview-dark](https://cloud.githubusercontent.com/assets/15705106/14057352/38924b3c-f2d3-11e5-8e21-08ba45b2b150.png)
![testview-dark](https://cloud.githubusercontent.com/assets/15705106/14057354/3e1eebfa-f2d3-11e5-8795-6dd6a9f48328.png)

**Comment by anshooarora** [comment]
ExtentMerge is deprecated, and no dark theme is available for it.  The replacement - ExtentX will be available sometime next month.

**Comment by mashek347** [comment]
Thanks for update. Please do let me know if is available. I am very much interested. Thanks for done very good job. 


Thanks
Alam
