### ISSUE TITLE
Issue Regarding UI of Extent Reports

### ISSUE THREAD

**Issue by vandanamaurya347** [anshooarora/extentreports#395]
Hi,

I am using Latest Version of ExtentReports v2.40.2 in my Current Project.  It’s working very well for me but I am facing two Issues regarding UI of Reports. 

1.	In the Log section where user attached a screenshot should Expand/Collapse on click.
2.	On the List View of executed test cases and dashboard is enabled. User is unable to scroll the List till the end. Please find the screenshot in attached File:

Please update me regarding fixes and let me know in case of any Concern.
![abc](https://cloud.githubusercontent.com/assets/17310162/14071972/8c923402-f4d8-11e5-8762-e7677c34ff35.png)

**Comment by anshooarora** [comment]
This is a bug, will be fixed in next release.
