### ISSUE TITLE
[Question] Is there any way to control system info item order?

### ISSUE THREAD

**Issue by SealviewTW** [anshooarora/extentreports#399]
Hello,

I have been trying to use the addSystemInfo feature. I have two threads running the tests in parallel, and in the System info page I would like to add the configuration file for each run. However, I am unable to control the order of the items in that section (one of my custom additions always places itself between the 4 default values) as seen in the [screenshot](http://imgur.com/XFSyLw6)

Is there any way I can sort these items?

Thank you,
Sealview

**Comment by anshooarora** [comment]
The system info model is a hash, so it will unsort the elements once added.  This can be added as an ER for the upcoming release to main order.

**Comment by anshooarora** [comment]
Changed to LinkedHashMap:  [view](https://github.com/anshooarora/extentreports/commit/c0bc6d768adf1f77a0e1254d9742f57735d847a4).  Would this work?

**Comment by SealviewTW** [comment]
That is great. Exactly what I needed, to be able to add stuff AFTER the 4
initial values.

Thanks for your support

**Comment by anshooarora** [comment]
Great!  The release should be available soon, lots of new features will be available besides this one.
