### ISSUE TITLE
When are you releasing Version 2.xx?

### ISSUE THREAD

**Issue by toolsqa** [anshooarora/extentreports#4]
Hi Anshoo,

We have used your extentreports 1.XX in our framework. Now that we have added multi threading capabilities to the framework, we would like to use version 2. Assuming that is made for multi threading purpose.

Any dates for that? Or if you have a private jar? We would like to test it out and include in our framework.

Thanks
Virender

**Comment by anshooarora** [comment]
Virender

I have added a link to 2.0 Beta here:  http://relevantcodes.com/extentreports-for-selenium.  It will remain active for 24 hours.

Please consider leaving feedback - it will help me expedite the stable release.
