### ISSUE TITLE
[Question]:How get report if test execution interrupted 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#400]
Hi Anshoo,

So my framework is getting bigger and bigger with testcases i would like to know if there's any solution.

here is scenario ; lets say i am execution 400 testcases and for some reason my system got crashed after execution of 200 testcases and report.close() method never got called so in such scenario as per my understanding i wont be able to get report but do you know any workaround to over come this situation

**Comment by anshooarora** [comment]
you can flush your report after each test, in `@AfterMethod` and you will always have the report with the last finished test.  A very basic example [here](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/test/java/com/relevantcodes/extentreports/testngexamples/BaseExample.java#L25).

**Comment by jawlitkp** [comment]
awesome! thanks much
