### ISSUE TITLE
Issue: Not able to view screenshot after moving report folder to sharedrive 

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#401]
Hi Anshoo,

I am moving my report folder to share drive and when my team members are trying to access, they are not able to see screenshots in the report,I am moving report folder along with screenshot folder in it.

Thanks

**Comment by MaxiTalenti** [comment]
To do that i did the following:

Screenshot sst = ((ITakesScreenshot)ExtReports.Driver).GetScreenshot();
                sst.SaveAsFile(ExtReports.logpath + "\\Imagenes\\Build " + iBuild.ToString() + ".jpg", System.Drawing.Imaging.ImageFormat.Jpeg);

                String Unidad = ExtReports.logpath.Substring(0, 1);
                String LogImg = ExtReports.logpath.Replace(Unidad + ":", Environment.MachineName);

                TestT.Log(Resultado, Descripcion + TestT.AddScreenCapture("\\" + LogImg + "\\Imagenes\\Build " + iBuild.ToString() + ".jpg"));

**Comment by anshooarora** [comment]
Looks like the path is invalid.  When you move, you have to ensure the relative path is the same as on your system.  You can do this for future runs:

```
/ReportFolder
    - Extent.HTML
    /IMG
        1.PNG
        2.PNG 
```

Relative paths in extent.html: 

```
img/1.PNG
img/2.PNG
```

When you move or transfer, simply transfer the ReportFolder and all paths will remain valid.

**Comment by jawlitkp** [comment]
I have modified folder structure as you mentioned but still not working. when i tried to see image path for share drive report ,it was showing me local path so basically path which is getting saved remains same no matter where you move folder

**Comment by anshooarora** [comment]
Can you share the zip file with report + images?

**Comment by jawlitkp** [comment]
[THU_APR_07_12_39_40_EDT_2016.zip](https://github.com/anshooarora/extentreports/files/208824/THU_APR_07_12_39_40_EDT_2016.zip)

**Comment by anshooarora** [comment]
The path I see in the report is not relative, for example:

```
file:///C:\Users\japatel\workspace\BBBAutomation\Reports\ReportsDeskATG\LocaL\THU_APR_07_12_39_40_EDT_2016\HTMLReport\Screenshots_Fail\launchScreenShot057.png
```

It should simply be:

```
Screenshots_Fail/launchScreenShot057.png
```

**Comment by jawlitkp** [comment]
Do you have any example or use case ? 

what i am using in my code for path variable is below,which is giving entire dir path

public static final String LOC_APPCONFIGFILES=System.getProperty("user.dir")+"//AppConfigFiles";

**Comment by anshooarora** [comment]
You can use this path for everything that will not be reused by other machines..  for everything else, use relative paths as above so it works on all machines.

Simply save your screenshots with the following path:

```
test.log(LogStatus.FAIL, test.addScreenCapture("Screenshots_Fail/launchScreenShot057.png"));
```

**Comment by jawlitkp** [comment]
Thanks resolved adding below code 

		file = ".\\"+ file.substring(file.indexOf("Screenshots"));

**Comment by Shroet** [comment]
File path: 
C:/Project/ProjectName/src/screenshots/TC-4-Login.png
_test.log(LogStatus.PASS, _test.addScreenCapture("src/screenshots/TC-4-Login.png")); 
It's not working for me  - on the report I see an empty image

**Comment by PrabhanjanDesai** [comment]
Same here,it did not work for me and I see an empty inage

**Comment by Shroet** [comment]
Additional question: What path to the file should I specify to view this screenshot not only on my local machine? For example, I need to send a report to another person, but they didn't see any images because these files are on my local machine. How can I store this screenshots in the report?

**Comment by noviceuser26** [comment]
I am also having the same issue here related to using relative path . I am seeing only test.addScreenCaptureFromPath(path) and not test.addScreenCapture()

**Comment by harishgk0406** [comment]
Is there Any solution anyone came across for this  Requirement

**Comment by jopijuco** [comment]
hey, I'm with the same issue.. and that's what I intend to do !
but how can I define the Parent directory to the report ? bcs everytime I use relative path to my screenshots folder like "/Screenshots/img.png" they get related to my Desktop or to my C:
I'm with this issue for a couple of days.. help would be appreciated
congrats for this amazing tool !
thanks

> Looks like the path is invalid. When you move, you have to ensure the relative path is the same as on your system. You can do this for future runs:
> 
> ```
> /ReportFolder
>     - Extent.HTML
>     /IMG
>         1.PNG
>         2.PNG 
> ```
> Relative paths in extent.html:
> 
> ```
> img/1.PNG
> img/2.PNG
> ```
> When you move or transfer, simply transfer the ReportFolder and all paths will remain valid.

**Comment by rajikuchana** [comment]
> Thanks resolved adding below code
> 
> ```
>     file = ".\\"+ file.substring(file.indexOf("Screenshots"));
> ```

Can u please provide complete code..
