### ISSUE TITLE
Using ExtentReporterNG how to print the complete log hierarchy as shown in the LogHierarchyTest.html

### ISSUE THREAD

**Issue by dhanuuvce** [anshooarora/extentreports#402]
Hi Anshoo,

I am using ExtentReporterNG as testNG listener. But I am unable to print the complete Extent test logs as like LogHierarchyTest.html. My commonhelper class which is used for printing the logs throws NPE. Could you please help me in printing the complete logs as like LogHierarchyTest.html using ExtentReporterNG as testNG listener.

**Comment by anshooarora** [comment]
Can you share the code you used? Its a little hard to know what's going on without it.

**Comment by dhanuuvce** [comment]
Hi Anshoo,

Thanks for your response.
I was able to get what I wanted from the following post.
https://github.com/anshooarora/extentreports/issues/102
