### ISSUE TITLE
On Enabling Dashboard, one cannot scroll down on the test cases.

### ISSUE THREAD

**Issue by rvsubrahmanyam** [anshooarora/extentreports#404]
1) Open the Reports, make sure you have more than 6 test cases.(scroll should not be there for test cases)
2) Enable Dashboard.

Actual:Once Dashboard is enabled, user cannot scroll the test cases shown below the Dashboard.

Note: If the test cases count is large, then scroll will automatically be applied. In that case this issue wont reproduce. Only when test cases do not have scroll and on enabling dashboard, last few test cases are not in view of web browser, then user cant reach the last test case by scrolling.

**Comment by anshooarora** [comment]
Duplicate #395.  Issue has been fixed and will be available in the next release
