### ISSUE TITLE
Skipped methods are not getting reported in Extent Report

### ISSUE THREAD

**Issue by Niharmyth** [anshooarora/extentreports#405]
I'm using dependsonMethod annotation in few of my testcases.

Suppose I have 2 test methods in 1 class.
 - Test1 &
 - Test2 (dependsOnMethod = "Test1")

Whenever Test1 fails, Test2 gets skipped.
Only Test1 is getting reported as failed testcase, Test2 is not getting reported as Skipped testcase.
Please advice.

**Comment by anshooarora** [comment]
I am not very sure, if Test2 is skipped, does the `afterMethod` get called for it?

**Comment by jawlitkp** [comment]
afterMethod is not getting called all the time specially when something wrong at driver level or grid or session. i was running in same issue. best option I found is call reporter.end() method under TestNG listener under OnFail ,OnSkipped OnPassed. Those methods are getting executed in any situations

**Comment by anshooarora** [comment]
That's good information Jawlit.  

@Niharmyth - see [here](https://github.com/khmarbaise/testng-example/blob/master/src/test/java/com/soebes/testing/testng/IntegrationTestListener.java).  You will have to implement `onTestSkipped` to ensure your test is reported correctly.
