### ISSUE TITLE
[Question] Integration of ExtentReports with TestNG & Cucumber

### ISSUE THREAD

**Issue by dmtraining** [anshooarora/extentreports#406]
Hello,

I don't know if it's the right place for that but I have a question about the integration of ExtentReports with TestNG & Cucumber. I'd like to log the information related to the Cucumber steps in the report file.

Example of log in the console output that I'd like to have in my report file:
3 Scenarios (1 failed, 2 passed)
14 Steps (1 failed, 1 skipped, 12 passed)

It's OK for the scenarios details but not for the steps ones.
Could you please help me?

Thanks.

**Comment by anshooarora** [comment]
Vimal has written a plugin to integrate Extent with Cucumber, see [here](https://github.com/email2vimalraj/CucumberExtentReporter).  You can write your tests as you normally do and the plugin will do the rest.

**Comment by dmtraining** [comment]
Thanks for your help @anshooarora
