### ISSUE TITLE
Extent Report | Usage details

### ISSUE THREAD

**Issue by vishalmgada** [anshooarora/extentreports#407]
Hi 
We are planning to use extent report jars for one of our client projects for reporting and would like to know if the jar shares any of usage details to the owner of the jar.?

Regards,
Vishal Gada

**Comment by karthikbhatnagar** [comment]
what do you mean? are you making changes to source that you want the ppl to not know about? :)

**Comment by vishalmgada** [comment]
We are not doing any updates to this jar. i wanted to know if this jar is reporting back the usage details to the extent reporting team.

**Comment by anshooarora** [comment]
@vishalmgada - usage details are not reported.  It does hit a few URLs to download stylesheets/js resources, which may be fine because no report/sensitive information is exchanged doing that.
