### ISSUE TITLE
Is there a way to get version 2.40.1?

### ISSUE THREAD

**Issue by atomar09** [anshooarora/extentreports#409]
I see that 2.40.2 is available but I need to get the previous version and I don't see a link on the website.
It's more of a question than an issue.

Please help.

**Comment by anshooarora** [comment]
You can download all versions from [here](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.relevantcodes%22%20AND%20a%3A%22extentreports%22).

**Comment by atomar09** [comment]
Thanks a lot.
