### ISSUE TITLE
Result is Pass even if Test Case shows Info Only

### ISSUE THREAD

**Issue by vandanamaurya347** [anshooarora/extentreports#411]
I am using extent reports in my current project and its working perfect for me.
1. While Executing a Test Case, I have printed only logs then why it shows Status as PASS.
2. Is it possible to Remove the Link (Website) appended on the Top Left corner of the Report.

please let me know in case of any query.

**Comment by anshooarora** [comment]
By default the status will remain Passed, until any other status is applied to the test with a higher hierarchy: skip, warning, error, fail, fatal.
