### ISSUE TITLE
Extent Report-BDD Framework - Unable to write the extent report with attached screen shot

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#415]
I have used the Hooks class implementing the Before and after method . When my test is failed and screen shot is captured , But it fails to write the test report .

If test is passed the it works fine , But the issue exist only when test is failed and screen shot is captured . The issue exist only when trying to attach the captured screen shot in the extent report .

error message 
-----------------------------

Apr 11, 2016 8:02:33 PM com.relevantcodes.extentreports.Report flush
SEVERE: Stream closed
java.io.IOException: Unable to write source: Stream closed.
	at com.relevantcodes.extentreports.Report.flush(Report.java:155)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:490)
	at main.java.com.cucumber.listener.ExtentCucumberFormatter.eof(ExtentCucumberFormatter.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy12.eof(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.eof(JUnitReporter.java:198)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:71)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Attached my code below .You need to create feature file for this alone use my code to reproduce the issue
-----------------------------------
[Hook.txt](https://github.com/anshooarora/extentreports/files/213309/Hook.txt)
[StepDefs.txt](https://github.com/anshooarora/extentreports/files/213310/StepDefs.txt)
[TestRunner.txt](https://github.com/anshooarora/extentreports/files/213312/TestRunner.txt)
[ExtentReportFormatter.txt](https://github.com/anshooarora/extentreports/files/213313/ExtentReportFormatter.txt)

**Comment by perwez123** [comment]
If you want to reproduce the issue then , Create the separate class for hooks for Before and After annotation and step defs and test runner .

**Comment by perwez123** [comment]
Its works fine when After and Before annotation is implemented in stepdef class . But it fails when creating separate Hook class for instantiating the browser and teardown .

**Comment by perwez123** [comment]
I have the following requirement .

1.Multiple scenario in single feature file.
2. I want to launch the browser only one time for each feature file , it means the same instance should be used for all the scenario that exist in that feature file and terminate the instance when all scenario is executed .
3.If any scenario is failed then capture the screen shot and continue to execute the next scenario using the same browser instance .
4. I am not able to achieve this requirement using the extent report . The example which you have provided does not have this scenario included .

Can you please provide any working example of it , if it is currently supported by Extent report or yet to be enhanced . This is the basic requirement for BDD framework .

**Comment by email2vimalraj** [comment]
@perwez123 : Is this related to the CucumberExtentReport plugin? Then I would recommend you to raise this issue there for quick address.

I'm worried about the 3rd point you mentioned. Do you want to continue other scenarios if a scenario is failed? Why do you do that? Typically we keep the browser instance open if my scenarios are kind of continuing from the previous scenario. If the scenario fails, we would actually don't even execute other scenarios.

**Comment by email2vimalraj** [comment]
And after analyzing your stack trace, it seems the exception is thrown at the end of feature, not at the end of scenario.
I'll investigate further and keep you posted.

**Comment by perwez123** [comment]
Hi VimalRaj ,

Thank you so much looking onto this issue .
As you mentioned in above email that , if scenario is failed then we stop
the execution for other scenario of the same feature file . I believe this
is not actually happening in the BDD framework . Each scenario is
considered to be the separate test case and if any one steps fails of the
scenario then that particular scenario is failed and proceed for the next
scenario (That is how it works).


Now the problem is in extentreport .

1.When any scenario is failed , and screen shot is captured and try to
write the extent test report , then it throws an error as i had shared with
you . If I do not attach the screen shot then it works perfectly .

So the problem occurs during the attaching screen shot when I use the Hook
class for After and Before Annotation . Is very easy to reproduce .

* Follow the below steps to reproduce this .*

1.Create the Hook Class and implement the Before and After annotation .
2.Create more than 2 scenario in feature file
3.Implement the stepdef
4.Run the Test runner .
5.Any one scenario must fail and capture the image and attach the same in
report . (here is the problem)


*Note *: The BDD code which yiu had shared is working fine , As the After
and Before annotation implemented in the stepdef class only . But in my
case there is separate class for Hooks.


 Please let me know if want more info.

Thanks
perwez

On Wed, Apr 13, 2016 at 10:11 AM, VimalRaj Selvam <notifications@github.com>
wrote:

> And after analyzing your stack trace, it seems the exception is thrown at
> the end of feature, not at the end of scenario.
> I'll investigate further and keep you posted.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-209225033>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by anshooarora** [comment]
The above error stems from close, once it is called, no more actions can be performed as it closes the stream.  Better to use flush instead if events are to be passed after failure.

Also, I disagree with what you've said about continuing execution if a scenario fails.  Any scenario fail should stop execution of that feature.  If B is dependant on A, and if A fails, why move further?

**Comment by perwez123** [comment]
Hi Anshoo,

I have just used the plugin which is provide by VimalRaj . I have not
called any function of the extent report . Where do I need to use the flush
?

Can you please run the test with Hooks in separate class and see where the
actual problem exist? I have no idea where to use flush , As there is no
way provided to invoke any extent report function while using BDD.
Everything is being invoked automatically by Cucumber I think ?

On Wed, Apr 13, 2016 at 11:21 AM, Anshoo Arora <notifications@github.com>
wrote:

> The above error stems from close, once it is called, no more actions can
> be performed as it closes the stream. Better to use flush instead if events
> are to be passed after failure.
>
> Also, I disagree with what you've said about continuing execution if a
> scenario fails. Any scenario fail should stop execution of that feature. If
> B is dependant on A, and if A fails, why move further?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-209239643>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by perwez123** [comment]
I tried all they way but it did not work . This issue happens only when
trying to attach screen shot in after annotation . I believe that the close
function are being called before attaching the screen shot in after
annotation . this fixes need to be made in jar file provided by VimalRaj I
believe .

Thanks

On Wed, Apr 13, 2016 at 1:54 PM, Perwez Alam <perwez123@gmail.com> wrote:

> Hi Anshoo,
>
> I have just used the plugin which is provide by VimalRaj . I have not
> called any function of the extent report . Where do I need to use the flush
> ?
>
> Can you please run the test with Hooks in separate class and see where the
> actual problem exist? I have no idea where to use flush , As there is no
> way provided to invoke any extent report function while using BDD.
> Everything is being invoked automatically by Cucumber I think ?
>
> On Wed, Apr 13, 2016 at 11:21 AM, Anshoo Arora <notifications@github.com>
> wrote:
>
>> The above error stems from close, once it is called, no more actions can
>> be performed as it closes the stream. Better to use flush instead if events
>> are to be passed after failure.
>>
>> Also, I disagree with what you've said about continuing execution if a
>> scenario fails. Any scenario fail should stop execution of that feature. If
>> B is dependant on A, and if A fails, why move further?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-209239643>
>>
>
>
>
> --
>  Thanks & Regards
>
> *  Md Perwez  Alam*
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by perwez123** [comment]
Hi Ansho ,

I have made the fixes in the plugin ExtentCucumberFormmater.java file  , I
have made changes in the following function mentioned below .

*Before Fixes*
-----------------
public void write(String s) {
        extent.close();
    }
 public void eof() {
        extent.endTest(featureTest);
        extent.flush();

    }

*After fixes*
-----------------------------------
public void write(String s) {
        extent.flush();
    }

 public void eof() {
        extent.endTest(featureTest);
        extent.flush();
        extent.close();
    }


Now its working fine and attaching the screen shot perfectly . I think you
should update the same in Original Plugin of ExtentCucumberFormmater  java
file .


Correct me if am wrong .

On Wed, Apr 13, 2016 at 2:04 PM, Perwez Alam <perwez123@gmail.com> wrote:

> I tried all they way but it did not work . This issue happens only when
> trying to attach screen shot in after annotation . I believe that the close
> function are being called before attaching the screen shot in after
> annotation . this fixes need to be made in jar file provided by VimalRaj I
> believe .
>
> Thanks
>
> On Wed, Apr 13, 2016 at 1:54 PM, Perwez Alam <perwez123@gmail.com> wrote:
>
>> Hi Anshoo,
>>
>> I have just used the plugin which is provide by VimalRaj . I have not
>> called any function of the extent report . Where do I need to use the flush
>> ?
>>
>> Can you please run the test with Hooks in separate class and see where
>> the actual problem exist? I have no idea where to use flush , As there is
>> no way provided to invoke any extent report function while using BDD.
>> Everything is being invoked automatically by Cucumber I think ?
>>
>> On Wed, Apr 13, 2016 at 11:21 AM, Anshoo Arora <notifications@github.com>
>> wrote:
>>
>>> The above error stems from close, once it is called, no more actions can
>>> be performed as it closes the stream. Better to use flush instead if events
>>> are to be passed after failure.
>>>
>>> Also, I disagree with what you've said about continuing execution if a
>>> scenario fails. Any scenario fail should stop execution of that feature. If
>>> B is dependant on A, and if A fails, why move further?
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-209239643>
>>>
>>
>>
>>
>> --
>>  Thanks & Regards
>>
>> *  Md Perwez  Alam*
>>
>
>
>
> --
>  Thanks & Regards
>
> *  Md Perwez  Alam*
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by perwez123** [comment]
I created 3 scenario in single feature file , and first scenario fails ,
Second pass , third scenario fail. All these scenario exists in single
feature file and for every scenario , the Before and After annotation are
called

Now if browser is instantiated in Before annotation then for every scenario
the new instance will be created , But the test will continue even if the
one fails . There is no dependency between the scenario , Its all are
independent .

As per my understanding the Cucumber framework consider each scenario as
separate test , That is why Before and After annotation are invoked for
each scenario .

Test results will be updated for each scenario (Pass/Fail) . If the
scenario is not executed after one fails then what status will be updated
in report .

If you want more evidence then , Please multiple scenario in single feature
file and create the Hooks class and run the test.

I have attached the screen shot also





On Wed, Apr 13, 2016 at 2:14 PM, Perwez Alam <perwez123@gmail.com> wrote:

> Hi Ansho ,
>
> I have made the fixes in the plugin ExtentCucumberFormmater.java file  , I
> have made changes in the following function mentioned below .
>
> *Before Fixes*
> -----------------
> public void write(String s) {
>         extent.close();
>     }
>  public void eof() {
>         extent.endTest(featureTest);
>         extent.flush();
>
>     }
>
> *After fixes*
> -----------------------------------
> public void write(String s) {
>         extent.flush();
>     }
>
>  public void eof() {
>         extent.endTest(featureTest);
>         extent.flush();
>         extent.close();
>     }
>
>
> Now its working fine and attaching the screen shot perfectly . I think you
> should update the same in Original Plugin of ExtentCucumberFormmater  java
> file .
>
>
> Correct me if am wrong .
>
> On Wed, Apr 13, 2016 at 2:04 PM, Perwez Alam <perwez123@gmail.com> wrote:
>
>> I tried all they way but it did not work . This issue happens only when
>> trying to attach screen shot in after annotation . I believe that the close
>> function are being called before attaching the screen shot in after
>> annotation . this fixes need to be made in jar file provided by VimalRaj I
>> believe .
>>
>> Thanks
>>
>> On Wed, Apr 13, 2016 at 1:54 PM, Perwez Alam <perwez123@gmail.com> wrote:
>>
>>> Hi Anshoo,
>>>
>>> I have just used the plugin which is provide by VimalRaj . I have not
>>> called any function of the extent report . Where do I need to use the flush
>>> ?
>>>
>>> Can you please run the test with Hooks in separate class and see where
>>> the actual problem exist? I have no idea where to use flush , As there is
>>> no way provided to invoke any extent report function while using BDD.
>>> Everything is being invoked automatically by Cucumber I think ?
>>>
>>> On Wed, Apr 13, 2016 at 11:21 AM, Anshoo Arora <notifications@github.com
>>> > wrote:
>>>
>>>> The above error stems from close, once it is called, no more actions
>>>> can be performed as it closes the stream. Better to use flush instead if
>>>> events are to be passed after failure.
>>>>
>>>> Also, I disagree with what you've said about continuing execution if a
>>>> scenario fails. Any scenario fail should stop execution of that feature. If
>>>> B is dependant on A, and if A fails, why move further?
>>>>
>>>> —
>>>> You are receiving this because you were mentioned.
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-209239643>
>>>>
>>>
>>>
>>>
>>> --
>>>  Thanks & Regards
>>>
>>> *  Md Perwez  Alam*
>>>
>>
>>
>>
>> --
>>  Thanks & Regards
>>
>> *  Md Perwez  Alam*
>>
>
>
>
> --
>  Thanks & Regards
>
> *  Md Perwez  Alam*
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by email2vimalraj** [comment]
@perwez123 : I doubt, I understand your issue exactly. But if a scenario is not even executed, then the Cucumber Listener doesn't even know the scenario exists. Again, this is the BDD behavior.

It would be great if you can provide me the exact requirement.

**Comment by perwez123** [comment]
HI


My Requirement is

1.Created Feature file with only one scenario
2.Implemented all step defs in class
3.Created Hook class , This class only have the before and after annotation
implemented .
4.Create the Test runner class with your ExtentCucumber plugin .

Run the test .You can encounter the same issue .

I think the problem is in ExtentCucumberFormatter file only .

When one scenario is completed then below function is called and the report
instance is closed before doing any task in after annotation



*public void write(String s) {        extent.close();    }*

Now the problem is , after closing the report instance only the after
annotation is called where the code is written to attach the screen shot .
Then it finds the report instance is closed and throwing an error . This
plug is not supported properly when the Before and After annotation are
implemented in separate class rather than in step def class.


Suggestions : You need to call the  *extent.flush() *in *write() *function
instead of *close() , *and *close() *function in
* eof().*

Any Way I have fixed the issue after changing the following code in your
ExtentCucumberFormatter plugin

*Before Fixes*
-----------------
public void write(String s) {
        extent.close();
    }
 public void eof() {
        extent.endTest(featureTest);
        extent.flush();

    }

*After fixes*
-----------------------------------
public void write(String s) {
        *extent.flush();*
    }

 public void eof() {
        extent.endTest(featureTest);
        extent.flush();
       * extent.close();*
    }


If you want to reproduce this issue , then please use the attached code in
you environment . Please once try this and let me know whether you can
reproduce the issue.


On Fri, Apr 15, 2016 at 10:38 AM, VimalRaj Selvam <notifications@github.com>
wrote:

> @perwez123 <https://github.com/perwez123> : I doubt, I understand your
> issue exactly. But if a scenario is not even executed, then the Cucumber
> Listener doesn't even know the scenario exists. Again, this is the BDD
> behavior.
>
> It would be great if you can provide me the exact requirement.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-210288936>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

package com.test;

import java.net.MalformedURLException;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebDriverException;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import cucumber.api.Scenario;
import cucumber.api.java.After;
import cucumber.api.java.Before;

public class Hooks{
    public static WebDriver driver;

    
    @Before()
    /**
     * Delete all cookies at the start of each scenario to avoid
     * shared state between tests
     */
    public void openBrowser() throws MalformedURLException {
    	System.out.println("Called openBrowser");
    	driver = new FirefoxDriver();
    	driver.manage().deleteAllCookies();
    	driver.get("https://www.google.co.in/?gfe_rd=cr&ei=tLQLV8P0JcqBoAPhqYG4BA");
    	driver.manage().window().maximize();
    }

     
    @After()
    /**
     * Embed a screenshot in test report if test is marked as failed
     */
    public void embedScreenshot(Scenario scenario) {
     
        if(scenario.isFailed()) {
        try {
        	 scenario.write("Current Page URL is " + driver.getCurrentUrl());
//            byte[] screenshot = getScreenshotAs(OutputType.BYTES);
            byte[] screenshot = ((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES);
            scenario.embed(screenshot, "image/png");
        } catch (WebDriverException somePlatformsDontSupportScreenshots) {
            System.err.println(somePlatformsDontSupportScreenshots.getMessage());
        }
        
        }
        driver.quit();
        
    }
    
}

**Comment by email2vimalraj** [comment]
@perwez123 : I don't see any problem when I followed exactly the same approach you mentioned.
Refer the attached zip [TestCucumberExtent.zip](https://github.com/anshooarora/extentreports/files/222517/TestCucumberExtent.zip). 

Also, as an evidence, refer the output folder which is also part of the zip file.
Extract and run the **RunCukesTest**. Let me know how it goes.

**Comment by perwez123** [comment]
Hi VimalRaj ,

Yes you are write , there is no issue in the plugins . It was my bad luck ,
I had called the *scenario.write()* function in after annotation , So that
whenever after annotation was called it was closing  the extentreport
instance before embedding the image into report . After removing this it
works like charm .


I apologize for wasting your time on it .


Is there way to add the environment details such as

Report HeadLine
Browser Name
Selenium Version
Cucumber Plugin Version

I think* Report HeadLine* can be added from after or before annotation if
you provide some function . And rest of other environment name can be added
at run time itself

Bug in the report
-----------------------------
It seems there is a bug in the report . I have total 3 scenario in single
feature file , But it displaying 4 test in the report . i believe it
includes the counts of the feature file also .

Please see the screen shot attached for evidence. Let me know whether i
need to file this issue in separate ticket .










On Sun, Apr 17, 2016 at 11:13 AM, VimalRaj Selvam <notifications@github.com>
wrote:

> @perwez123 <https://github.com/perwez123> : I don't see any problem when
> I followed exactly the same approach you mentioned.
> Refer the attached zip TestCucumberExtent.zip
> <https://github.com/anshooarora/extentreports/files/222517/TestCucumberExtent.zip>.
>
>
> Also, as an evidence, refer the output folder which is also part of the
> zip file.
> Extract and run the *RunCukesTest*. Let me know how it goes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/anshooarora/extentreports/issues/415#issuecomment-210960518>
>



-- 
 Thanks & Regards

*  Md Perwez  Alam*

**Comment by email2vimalraj** [comment]
@perwez123 : I would be happy if you can open the issue here: https://github.com/email2vimalraj/CucumberExtentReporter/issues

@anshooarora : You can close this issue.

**Comment by perwez123** [comment]
Its working fine after removing the redundant code . I closed this issue

**Comment by Udhay1316** [comment]
@email2vimalraj - I would like to add browser name and version to the extent report during run time. Please help me I can achieve it

**Comment by rohittyagi83** [comment]
I would like to add browser name and version to the extent report during run time. Please help me to know how can I achieve it for Cucumber
