### ISSUE TITLE
Extent Report-BDD Framework - How to attach the screen shot in report when After annotation is not called for every scenario

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#416]
I want to avoid calling the Before and after annotation for every scenario to avoid relaunching the browser for every scenario as after and before is being called for every scenario by its framework itself .

For this i have used the tagging function in feature file to avoid this situation. In this case screen shot can not be attached if after annotation (tearDown) is not called where i have written the code to capture screen shot .

What is the correct way of handling this situation .

I have a solution for this mentioned below , but i am not sure whether there is any better solution for it than this .

1.Instantiating the browser in first step of the first scenario in each feature file and close the instance in last step of the each feature file . I thinks should solve this problem 

Please let me know if you have any better solution for it . Your help is appreciated .

Thanks

**Comment by email2vimalraj** [comment]
When you don't call the after annotation, then we cannot get the instance of the scenario object which has the method to embed the screenshot. So at any way this would not be possible from our end to support. Rather it seems a cucumber / BDD enhancement. I would recommend you to post this question in their forum.

@anshooarora : I suggest to close this issue.

**Comment by anshooarora** [comment]
Closing issue as per @email2vimalraj - its a BDD enhancement rather than the ExtentCucumber plugin.
