### ISSUE TITLE
Question on using UTF-8

### ISSUE THREAD

**Issue by seanmcguire413** [anshooarora/extentreports#418]
Mr. Arora,

Thank you for the awesome product.  I have a question, How do I allow the Extent Report to use UTF-8 characters?  I work on a lot of Japanese Websites and they are all showing up as question marks.  Again thanks for everything!

Sean

**Comment by anshooarora** [comment]
Default is UTF-8, but you can use any encoding by setting it in `extent-config.xml` file (see [here](http://extentreports.relevantcodes.com/java/#configuration) for more info):

```
<!-- document encoding -->
<!-- defaults to UTF-8 -->
<encoding>UTF-8</encoding>
```

You must also make sure your IDE is using the same encoding.
