### ISSUE TITLE
Extent Merge

### ISSUE THREAD

**Issue by mailtokyatham** [anshooarora/extentreports#425]
![individualreport](https://cloud.githubusercontent.com/assets/12842220/14544168/a81ef35a-024c-11e6-9e58-51e3ff1bac03.png)
![issues_in_merge_report](https://cloud.githubusercontent.com/assets/12842220/14544170/a9771606-024c-11e6-89f5-79e1894ea60a.png)
![merge_report](https://cloud.githubusercontent.com/assets/12842220/14544172/aaa95d5e-024c-11e6-82a9-70c956141e60.png)

Hi Anshoo,

I would like to thank you for extent report which makes my life easier .

I have couple of clarifications on extent merge functionality.

Issue1) Attached IndividualReport.png file which is individual report , when I use extent merge for summary , its not showing the data as in individual reports(color, ..ect)

Attached Merge_Report.png for your reference.

Issue2) Issues_in_merge_report.png attached , please open the same and clarify the questions over there.

Issue3) I see ? in merge report , when I give space between words in individual report.

13:09:12	Sheet4� Not Found in 15678_EMIRExtract_0000_20151001_20151031_42545.xls�Hence Skipped for Comparision

Issue4) I am comparing the two excels where excel files contains no.of sheets, in result file sheets shows as test , i dont want to show this as test, (I have added this as child test)

Attached html  file for reference.

Configuration :

extentreports-java-2.40.1-beta5-final.jar
extentmerge.jar

Jdk : 1.7

let me know if you need any information.

**Comment by anshooarora** [comment]
This is a limitation, and there won't any enhancements added as ExtentMerge is deprecated.  You can consider using ExtentX instead, it does everything ExtentMerge does but without any manual effort.
