### ISSUE TITLE
Configure Test Count Setting

### ISSUE THREAD

**Issue by mailtokyatham** [anshooarora/extentreports#426]
Hi,

How to set Test Count Settings parents only  run time? so that my count in merged report will be correct 
When I set to parent only , when closed open its going o default setting, save is not working over here.

![configure_test_count_settings](https://cloud.githubusercontent.com/assets/12842220/14544540/6ce4ea4a-024e-11e6-93cd-b5a033f784e6.png)

Regards
Srinivas

**Comment by anshooarora** [comment]
To select parent-nodes settings by default, simply add this to your extent-config.xml scripts:

```
$('#parentWithoutNodes').click();
$('#test-count-setting .modal-action').click();
```

**Comment by mailtokyatham** [comment]
Thanks Anshooarora , its working , but in my merged report , still it showing child count  also,

I would like to avoid  child count in merged report.

![merge](https://cloud.githubusercontent.com/assets/12842220/14567965/80812238-02eb-11e6-93ca-ab1474e4c7f7.png)

Also I would like to have following things in merged report, pleas suggest how to do

1) % of failure and success( It is ok , when I mouse over on graph, ifit show the %)
2) I would like to remove the duration column(which is no way useful , its not showing any time over there)
