### ISSUE TITLE
installing extentx on ubuntu failed

### ISSUE THREAD

**Issue by Fadih** [anshooarora/extentreports#427]
hi my friend 
im trying to install extentx on ubunto and i get the bellow error can you help please 

oot@QA-Ubuntu-Monitor:/var# cd extentx
root@QA-Ubuntu-Monitor:/var/extentx# ls
api  app.js  assets  config  Gruntfile.js  package.json  README.md  tasks  views

root@QA-Ubuntu-Monitor:/var/extentx# npm install

npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.1.14: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> sails@0.11.5 preinstall /var/extentx/node_modules/sails
> node ./lib/preinstall_npmcheck.js

Sails.js Installation: Checking npm-version successful
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
/
> kerberos@0.0.19 install /var/extentx/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/var/extentx/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
```
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/var/extentx/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error
# gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/extentx/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
grunt-contrib-copy@0.5.0 node_modules/grunt-contrib-copy
```

grunt-sails-linker@0.9.6 node_modules/grunt-sails-linker

grunt-contrib-concat@0.3.0 node_modules/grunt-contrib-concat

grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean
└── rimraf@2.2.8

ejs@0.8.8 node_modules/ejs

rc@0.5.5 node_modules/rc
├── ini@1.3.4
├── strip-json-comments@0.1.3
├── deep-extend@0.2.11
└── minimist@0.0.10

grunt-sync@0.0.8 node_modules/grunt-sync
└── promised-io@0.3.3

grunt-contrib-cssmin@0.9.0 node_modules/grunt-contrib-cssmin
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── clean-css@2.1.8 (commander@2.1.0)
└── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

include-all@0.1.6 node_modules/include-all
└── underscore.string@2.3.1

sails-disk@0.10.9 node_modules/sails-disk
├── waterline-errors@0.10.1
├── waterline-criteria@1.0.0
├── async@0.2.10
├── fs-extra@0.8.1 (jsonfile@1.1.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── waterline-cursor@0.0.6 (async@0.9.2)
└── lodash@2.4.1

grunt-contrib-jst@0.6.0 node_modules/grunt-contrib-jst
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── lodash@2.4.2
└── grunt-lib-contrib@0.7.1 (strip-path@0.1.1, maxmin@0.1.0)

grunt-contrib-uglify@0.4.1 node_modules/grunt-contrib-uglify
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)
└── uglify-js@2.6.2 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.5.3, yargs@3.10.0)

mongodb@2.1.16 node_modules/mongodb
├── es6-promise@3.0.2
├── readable-stream@1.0.31 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.2)
└── mongodb-core@1.3.16 (require_optional@1.0.0, bson@0.4.23)

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── gaze@0.5.2 (globule@0.1.0)
└── lodash@2.4.2

grunt@0.4.2 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── colors@0.6.2
├── hooker@0.2.3
├── async@0.1.22
├── exit@0.1.2
├── rimraf@2.0.3 (graceful-fs@1.1.14)
├── nopt@1.0.10 (abbrev@1.0.7)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)

grunt-contrib-coffee@0.10.1 node_modules/grunt-contrib-coffee
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── coffee-script@1.7.1 (mkdirp@0.3.5)
└── lodash@2.4.2

sails@0.11.5 node_modules/sails
├── sails-build-dictionary@0.10.1
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── mock-res@0.1.0
├── connect-flash@0.1.1
├── mock-req@0.1.0
├── commander@2.1.0
├── sails-stringfile@0.3.2
├── merge-defaults@0.1.4
├── colors@0.6.2
├── pluralize@0.0.12
├── node-uuid@1.4.7
├── async@0.9.2
├── uid-safe@1.1.0 (base64-url@1.2.1, native-or-bluebird@1.1.2)
├── reportback@0.1.9 (switchback@1.1.3)
├── semver@4.3.6
├── ejs-locals@1.0.2
├── fs-extra@0.8.1 (jsonfile@1.1.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── method-override@2.3.5 (methods@1.1.2, vary@1.0.1, parseurl@1.3.1, debug@2.2.0)
├── grunt-cli@0.1.13 (findup-sync@0.1.3, nopt@1.0.10, resolve@0.3.1)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── i18n@0.5.0 (sprintf@0.1.5, mustache@2.2.1, debug@2.2.0)
├── skipper@0.5.9 (string_decoder@0.10.31, dot-access@1.0.0, async@1.4.2, skipper-disk@0.5.4, colors@1.1.2, semver@5.0.3, debug@2.2.0, multiparty@3.2.10)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, utile@0.2.1, winston@0.8.3)
├── captains-log@0.11.11 (rc@0.3.5, lodash@2.4.1)
├── connect@2.30.0 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, fresh@0.3.0, on-headers@1.0.1, pause@0.0.1, parseurl@1.3.1, response-time@2.3.1, vhost@3.0.2, content-type@1.0.1, basic-auth-connect@1.0.0, cookie-parser@1.3.5, depd@1.0.1, qs@2.4.2, http-errors@1.3.1, debug@2.2.0, finalhandler@0.4.0, express-session@1.11.3, morgan@1.6.1, connect-timeout@1.6.2, serve-static@1.10.2, serve-favicon@2.3.0, csurf@1.8.3, multiparty@3.3.2, type-is@1.6.12, body-parser@1.13.3, compression@1.5.2, errorhandler@1.4.3, serve-index@1.7.3)
├── sails-hook-sockets@0.12.3 (machinepack-urls@3.1.1, socket.io@1.4.5, socket.io-client@1.4.5)
├── sails-util@0.10.6 (json-stringify-safe@5.0.1, switchback@1.1.3, optimist@0.6.1, underscore.string@2.3.3)
├── express@3.21.2 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, utils-merge@1.0.0, methods@1.1.2, fresh@0.3.0, range-parser@1.0.3, vary@1.0.1, basic-auth@1.0.3, parseurl@1.3.1, etag@1.7.0, content-type@1.0.1, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.10, send@0.13.0, mkdirp@0.5.1, connect@2.30.2)
├── express-handlebars@2.0.1 (graceful-fs@3.0.8, promise@6.1.0, object.assign@1.1.1, glob@5.0.15, handlebars@3.0.3)
├── lodash@2.4.2
├── waterline@0.10.31 (deep-diff@0.3.3, bluebird@2.9.34, async@1.2.1, switchback@2.0.0, waterline-schema@0.1.20, lodash@3.9.3, anchor@0.11.2, waterline-criteria@0.11.2)
├── anchor@0.10.5
└── sails-generate@0.12.4 (sails-generate-api@0.10.0, sails-generate-gruntfile@0.10.10, async@0.2.10, sails-generate-adapter@0.10.5, sails-generate-generator@0.10.11, sails-generate-views-jade@0.10.4, sails-generate-views@0.10.8, sails-generate-sails.io.js@0.12.5, sails-generate-backend@0.12.6, sails-generate-frontend@0.11.7, sails-generate-controller@0.10.9, sails-generate-model@0.10.12, sails-generate-new@0.10.27)

grunt-contrib-less@0.11.1 node_modules/grunt-contrib-less
├── async@0.2.10
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)
├── lodash@2.4.2
└── less@1.7.5 (graceful-fs@3.0.8, mime@1.2.11, source-map@0.1.43, mkdirp@0.5.1, clean-css@2.2.23, request@2.40.0)

sails-mongo@0.12.0 node_modules/sails-mongo
├── waterline-errors@0.10.1
├── async@1.5.2
├── validator@4.5.1
├── waterline-cursor@0.0.6 (async@0.9.2, lodash@2.4.2)
├── lodash@3.10.1
└── mongodb@2.1.3 (es6-promise@3.0.2, readable-stream@1.0.31, kerberos@0.0.19, mongodb-core@1.2.31)
root@QA-Ubuntu-Monitor:/var/extentx#

**Comment by anshooarora** [comment]
Please open this ticket for extentx, this is the extentreports repo.  https://github.com/anshooarora/extentx
