### ISSUE TITLE
Fail test case is not showing in category filter section.

### ISSUE THREAD

**Issue by ranashahan** [anshooarora/extentreports#428]
Hi,

I am new user in extent report, might I be written wrong code that's why it is happing to me. Anyway I have been facing this problem since day one. I tried to code as you guys has shown in examples (http://extentreports.relevantcodes.com/java/#basic-usage).

1st Issue:
I found one test case has been failed which was covered in dashboard & test sections, but once I tried to search it in a category section, it does not appear and category only shows pass test cases. Kindly view screenshots. 

![1](https://cloud.githubusercontent.com/assets/18508721/14584880/c87589c6-0476-11e6-8342-f76de639c6ef.PNG)

![2](https://cloud.githubusercontent.com/assets/18508721/14584881/d25fadae-0476-11e6-8e7b-8157d81c4640.PNG)

2nd Issue:
Fail test case does not show Test ended time & Time taken to finish (can be seen in attached image). is it default behaviour or bug? as well as my thinking fail/pass should show complete execution time whatever it result shows zero.

**Comment by anshooarora** [comment]
This particular test was not ended safely.  Are you calling `endTest` to end all your tests?

**Comment by ranashahan** [comment]
Yes, but I believe the exception has been raised before it and it goes to after method area, where screenshot has taken. Anyway I put `endTest` on AfterMethod block as well and it fulfil my desire. 

Both Problem solved :+1: 
Thanks.

**Comment by ranashahan** [comment]
@anshooarora Quick question for you refer to above mentioned problems, I have already written `endTest`in AfterClass method, should it not close all open/start test cases instead of last run case? like, I got hundreds of cases and I missed to put `endTest` in so many cases then I would like to have general endTest tag/method for close all open/start cases. I know its consequences that all missed `endTest` time stamp will not be corrected but what I feel that something is better then nothing and it will show in category list too.

**Comment by anshooarora** [comment]
Use `@AfterMethod`, it will run after each test.
