### ISSUE TITLE
LogStatus.INFO overrides LogStatus.SKIP in report

### ISSUE THREAD

**Issue by IvanLitskevich** [anshooarora/extentreports#43]
Hi there! First of all, thank you for the great framework! It's really wonderful!

Probably, I found a bug when LogStatus.INFO overrides LogStatus.SKIP and marks test as Passed:

    @Test(priority = 0,enabled=true, description = "Skip this test")
    public void skipThisTest() throws InterruptedException {

        test = extent
                .startTest("skipThisTest", "skipThisTest");

        test.log(LogStatus.INFO,"SKIP");

        test.log(LogStatus.SKIP,"SKIP");
        skipThisTest("SKIP"); // throw new SkipException(message);
    }

![2015-08-07_9-55-08](https://cloud.githubusercontent.com/assets/13695063/9137190/13117e5e-3cea-11e5-9e3e-d6211447a702.png)

Without test.log(LogStatus.INFO,"SKIP"); test appeared as skipped in the report. Would you please take a look on it.

Now I have to use LogStatus.ERROR instead of LogStatus.SKIP as ERROR status can't be overridden by  INFO.

**Comment by anshooarora** [comment]
Ivan

Please try with the latest jar:  http://relevantcodes.com/Tools/ExtentReports2/extentreports-java-v2.04-beta-2.zip

This will be fixed in the upcoming version (in beta right now).

**Comment by IvanLitskevich** [comment]
Thank you, Anshoo!

**Comment by anshooarora** [comment]
Ivan, please use the download link from here:  http://relevantcodes.com/extentreports-for-selenium/

I have removed the beta from the link above.  The one in the above link is the stable jar.

Cheers.
