### ISSUE TITLE
ExtentCucmberReport- Need to have a filter to display the number for feature status only excluding scenarios

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#431]
I think it would be nice if we have the filter to check the status of feature alone . It should exclude the count of scenarios .

If I have to count the total number of feature failed or pass , then need to count our own , As of now I don't see any option/filter to check the feature status alone.

Can you make this in upcoming release ?

**Comment by anshooarora** [comment]
There are 3 types of settings available:

1. Count parent tests only (this is what applies to you)
2. Count parent tests without children + children (default)
3. Count Children only

This can be selected in the tests view graph.

**Comment by anshooarora** [comment]
Closing as this feature is an existing feature.
