### ISSUE TITLE
Same Test case is showing multiple times in Category section.

### ISSUE THREAD

**Issue by ranashahan** [anshooarora/extentreports#432]
Report V-2.40.2
If I used `endTest` multiple time then duplication appeared in category section. Snapshot is attached for reference. 

![3](https://cloud.githubusercontent.com/assets/18508721/14592670/b028f2d0-053a-11e6-979a-68e680bfa12c.PNG)

Kindly run following code for reproducing it. 

`
public class sample {
	private static WebDriverWait wait = null;
	private static WebDriver driver = null;
	private static ExtentReports report;
	private static ExtentTest logger;

	@BeforeClass
	public void beforeClass() {
		report = new ExtentReports("C:\\Firstautomnation.html", true);

	}

	@BeforeTest()
	public void openBrowser() {
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

	}

	@Test()
	public void searchGmail(Method mtd) throws IOException {

		logger = report.startTest(mtd.getName(), "This testcase searches gmail and go to its sign-in page.");
		logger.assignCategory("Regression");
		logger.assignAuthor("Rana Mansoor Ahmed");

		driver.get("http://www.google.com.pk");
		wait = new WebDriverWait(driver, 10);

		driver.findElement(By.xpath(".//*[@id='lst-ib']")).sendKeys("gmail");

		boolean bool = driver.findElement(By.xpath(".//*[@id='tsf']/div[2]/div[3]/center/input[1]")).isDisplayed();
		logger.log(LogStatus.INFO, "Boolean status = " + bool);
		// Add_Log.info("Boolean status = " + bool);
		if (true == bool) {
			driver.findElement(By.xpath(".//*[@id='tsf']/div[2]/div[3]/center/input[1]")).click();
			logger.log(LogStatus.INFO, "First search button found & clicked");
		} else {
			driver.findElement(By.xpath(".//*[@id='sblsbb']/button")).click();
			logger.log(LogStatus.INFO, "First search button not found, clicked on 2nd search button");

		}

		driver.findElement(By.linkText("Gmail - Google")).click();
		logger.log(LogStatus.PASS, "Gmail link found and clicked");
		report.endTest(logger);
		report.endTest(logger);

	}

	@AfterClass()
	public void afterclass() {
		report.endTest(logger);
		report.flush();
		driver.get("C:\\Firstautomnation.html");
	}
}
`

**Comment by anshooarora** [comment]
This is not the correct usage.  See here for a better design pattern:  http://extentreports.relevantcodes.com/java/#testng-example.  End test only once, in `@AfterMethod`.

**Comment by ranashahan** [comment]
Noted Thanks

**Comment by ranashahan** [comment]
Hi Ansho,

I have used your provided design pattern ([testng-example](http://extentreports.relevantcodes.com/java/#testng-example)) and its run successfully, but once I tried to run on multiple test classes it always fails with null point exception. Kindly note that your `BaseExample Abstract Class`  and  `ExtentManager Class`  has been copied from given link and none has been changed instead of `final String filePath= "Extent.html";` into `	final String filePath = "D:\\Reports\\PageObjectModelSample.html";
`

**First test class:**
`public class SingleLogTest extends BaseExample {

	@Test
	public void passTest() {
		test = extent.startTest("passTest");
		test.log(LogStatus.PASS, "Pass");

		Assert.assertEquals(test.getRunStatus(), LogStatus.PASS);
	}

	@Test
	public void intentionalFailure() throws Exception {
		test = extent.startTest("intentionalFailure");
		throw new Exception("intentional failure");
	}
}`

**Second test class**

`public class DoubleLogTest extends BaseExample {

	@Test
	public void passTest1() {
		test = extent.startTest("passTest");
		test.log(LogStatus.PASS, "Pass");

		Assert.assertEquals(test.getRunStatus(), LogStatus.PASS);
	}

	@Test
	public void intentionalFailure1() throws Exception {
		test = extent.startTest("intentionalFailure");
		throw new Exception("intentional failure");
	}

}`

**testng.xml**
<?xml version="1.0" encoding="UTF-8"?>

suite name= "Sign-in Test" verbose="1" parallel="tests" thread-count="1"

test name="Chrome Sign-in Test"
classes
 class name = "tests.SingleLogTestOne"/
class name = "tests.DoubleLogTest"/
/classes
/test
/suite


**Exception image**

![4](https://cloud.githubusercontent.com/assets/18508721/14595484/081c212e-0559-11e6-8eb7-912c324382f4.PNG)


can you please check and i hope it will be reproducible at your end too.. and sorry for being so dumb!.
