### ISSUE TITLE
UI Bug in reports category view

### ISSUE THREAD

**Issue by ossa619** [anshooarora/extentreports#435]
Getting blank page when viewing specific report categories.

PFA for more details

**Comment by ossa619** [comment]
[Cmplxreportbug.webm.zip](https://github.com/anshooarora/extentreports/files/223844/Cmplxreportbug.webm.zip)

**Comment by anshooarora** [comment]
It would be more helpful if you shared the report file instead.

**Comment by anshooarora** [comment]
PS.  I am deleting the attachment for privacy.  Can you share the report so I can analyze what's happening there?  You can also email me the report directly if you want.

**Comment by ossa619** [comment]
Check this file. It is reproducible in MacOS-X and Chrome browser.
[ComplexReport.html.zip](https://github.com/anshooarora/extentreports/files/224215/ComplexReport.html.zip)

**Comment by anshooarora** [comment]
Unable to repro on Ubuntux64-14.04 FF/Chrome, Win10 FF/Chrome/IE, Win7 Chrome.

**Comment by anshooarora** [comment]
Closing this as I was unable to reproduce on several machines and this seems like a browser issue than the report itself as it works fine on others.
