### ISSUE TITLE
Issue: Test case duplication on Categories views

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#436]
Hi Ansho,

I am seeing test case numbers are not matching vs different views due to duplication of testcases 

So this is screenshot first view ,under that i have total 27 testcases ,which is correct 

[27testcases.pdf](https://github.com/anshooarora/extentreports/files/224260/27testcases.pdf)

now in below screenshot i am seeing 28 test cases with duplicate 

[28testcases.pdf](https://github.com/anshooarora/extentreports/files/224263/28testcases.pdf)

**Comment by anshooarora** [comment]
I am not sure I understand.  If there is a duplicate then, there should be 28 tests cases, right?  Extent doesn't look at duplicates, it simply provides a count of all test cases in the file.

**Comment by jawlitkp** [comment]
yes so issue is why it is not reporting duplicate testcase in first screenshot

**Comment by jawlitkp** [comment]
and my result is not showing same test case numbers across different views of report

**Comment by jawlitkp** [comment]
if you need i can provide report folder

**Comment by anshooarora** [comment]
yes, that would help

**Comment by jawlitkp** [comment]
[160418.zip](https://github.com/anshooarora/extentreports/files/224307/160418.zip)

**Comment by jawlitkp** [comment]
please filter testcases by iteration

**Comment by jawlitkp** [comment]
2.40.1

**Comment by anshooarora** [comment]
I filtered by Iteration1, here is the screenshot:

![iteration1](https://cloud.githubusercontent.com/assets/4107384/14612849/08ab231e-055f-11e6-8a79-d9d55b12116c.png)

**Comment by anshooarora** [comment]
Can you upgrade to 2.40.2, a few bug fixes there:  http://extentreports.relevantcodes.com/changelog/java.html

**Comment by jawlitkp** [comment]
ok so there are total 27 testcases , now swtich to categores view ,you should see 28 testcases

**Comment by jawlitkp** [comment]
Sure i will try with new version

**Comment by anshooarora** [comment]
I see, looks like you've ended this test twice by calling `endTest()`.  Only then you will see a duplicate test here.

**Comment by jawlitkp** [comment]
i am calling endTest() under listeners and assuming it should execute only one time 


	public void onTestFailure(ITestResult tr){

		Long threadID = Thread.currentThread().getId();
		this.deviceBrowserInstance=(String) BBBU_TestConfig.paramMap.get(threadID).get("DEVICEBROWSERINSTANCE");
		this.testcaseName=(String) BBBU_TestConfig.paramMap.get(threadID).get("TESTCASE");
		this.reporter=(BBBU_Reporter) BBBU_TestConfig.paramMap.get(threadID).get("REPORTER");
		this.concept = (String) BBBU_TestConfig.paramMap.get(threadID).get("CONCEPT");



		if (tr.getStatus() == ITestResult.FAILURE) {
			//reporter.log(LogStatus.FATAL, "<pre>" + tr.getThrowable().getMessage() + "</pre>"+ reporter.extentReporter.addScreenCapture(takeScreenShot("failedFromAfterMethod")));
			reporter.log(LogStatus.FATAL, tr.getThrowable());
		}
		BBBU_TestConfig.report.endTest(reporter.extentReporter);

		BBBU_TestConfig.createUpdateOpenDBReportDuringRunTime();

		//		BBBU_TestConfig.report.flush();


		if(BBBU_TestConfig.configProperties.get("CLOSE_BROWSER").toString().equalsIgnoreCase((BBBU_Constants.RUNMODE_YES))){

			WebDriver driver = BBBU_TestConfig.driverFactory.get(deviceBrowserInstance+concept+testcaseName);
			if(driver!=null){
				if(deviceBrowserInstance.contains(BBBU_Constants.DEVICE_PLATFORM_IOS))
				{
					driver.close();
					driver.quit();
				}else
				{
					driver.quit();
				}
			}
		}
		onTestFailure++;
		System.out.println("*********************************************" +  onTestFailure + " : onTestFailure method called for : " + tr.getMethod());

	}

	public static int onTestSkipped=0;
	public void onTestSkipped(ITestResult tr){

		Long threadID = Thread.currentThread().getId();
		this.deviceBrowserInstance=(String) BBBU_TestConfig.paramMap.get(threadID).get("DEVICEBROWSERINSTANCE");
		this.testcaseName=(String) BBBU_TestConfig.paramMap.get(threadID).get("TESTCASE");
		this.reporter=(BBBU_Reporter) BBBU_TestConfig.paramMap.get(threadID).get("REPORTER");
		this.concept = (String) BBBU_TestConfig.paramMap.get(threadID).get("CONCEPT");


		if (tr.getStatus() == ITestResult.SKIP) {
			//reporter.log(LogStatus.FATAL, "<pre>" + tr.getThrowable().getMessage() + "</pre>"+ reporter.extentReporter.addScreenCapture(takeScreenShot("failedFromAfterMethod")));
			reporter.log(LogStatus.FATAL, "Test case skiped due to : " + tr.getThrowable());
		}
		BBBU_TestConfig.report.endTest(reporter.extentReporter);

		BBBU_TestConfig.createUpdateOpenDBReportDuringRunTime();

		//		BBBU_TestConfig.report.flush();


		if(BBBU_TestConfig.configProperties.get("CLOSE_BROWSER").toString().equalsIgnoreCase((BBBU_Constants.RUNMODE_YES))){

			WebDriver driver = BBBU_TestConfig.driverFactory.get(deviceBrowserInstance+concept+testcaseName);
			if(driver!=null){
				if(deviceBrowserInstance.contains(BBBU_Constants.DEVICE_PLATFORM_IOS))
				{
					driver.close();
					driver.quit();
				}else
				{
					driver.quit();
				}
			}
		}

		onTestSkipped++;
		System.out.println("*********************************************" +  onTestSkipped + " : onTestSkipped method called for : " + tr.getMethod());
	}

	public static int onTestSuccess=0;
	public void onTestSuccess(ITestResult tr){

		Long threadID = Thread.currentThread().getId();
		this.deviceBrowserInstance=(String) BBBU_TestConfig.paramMap.get(threadID).get("DEVICEBROWSERINSTANCE");
		this.testcaseName=(String) BBBU_TestConfig.paramMap.get(threadID).get("TESTCASE");
		this.reporter=(BBBU_Reporter) BBBU_TestConfig.paramMap.get(threadID).get("REPORTER");
		this.concept = (String) BBBU_TestConfig.paramMap.get(threadID).get("CONCEPT");


		if (tr.getStatus() == ITestResult.SUCCESS) {
			//reporter.log(LogStatus.FATAL, "<pre>" + tr.getThrowable().getMessage() + "</pre>"+ reporter.extentReporter.addScreenCapture(takeScreenShot("failedFromAfterMethod")));
			reporter.log(LogStatus.PASS, "Test case passed");
		}

		BBBU_TestConfig.report.endTest(reporter.extentReporter);

		BBBU_TestConfig.createUpdateOpenDBReportDuringRunTime();

		//		BBBU_TestConfig.report.flush();



		if(BBBU_TestConfig.configProperties.get("CLOSE_BROWSER").toString().equalsIgnoreCase((BBBU_Constants.RUNMODE_YES))){

			WebDriver driver = BBBU_TestConfig.driverFactory.get(deviceBrowserInstance+concept+testcaseName);
			if(driver!=null){
				if(deviceBrowserInstance.contains(BBBU_Constants.DEVICE_PLATFORM_IOS))
				{
					driver.close();
					driver.quit();
				}else
				{
					driver.quit();
				}
			}
		}

		onTestSuccess++;
		System.out.println("*********************************************" + onTestSuccess + " : onTestSuccess method called for : " + tr.getMethod());
	}

**Comment by anshooarora** [comment]
Looks correct to me, but it would be very hard to tell what's happening.  This issue generally pops up when the test is ended twice.  I will try to see if there is a way to fix this in the next beta, but I can't guarantee..

**Comment by jawlitkp** [comment]
Okay thank you.I will try from side as well

**Comment by anshooarora** [comment]
I found a way to fix this from Extent side, will release in next beta (hopefully by tomorrow):  2.41.0-beta2

**Comment by jawlitkp** [comment]
Awesome , thanks much

**Comment by jawlitkp** [comment]
I am getting compilation errors with 2.41.0-beta2

heres my jar file list ,let me know if i am missing any dependency


[2016-04-20_10-15-33.pdf](https://github.com/anshooarora/extentreports/files/228070/2016-04-20_10-15-33.pdf)

**Comment by anshooarora** [comment]
What is error?  You may have to fix your project after adding the new jar.

**Comment by jawlitkp** [comment]
[2016-04-20_10-35-06.pdf](https://github.com/anshooarora/extentreports/files/228120/2016-04-20_10-35-06.pdf)

**Comment by jawlitkp** [comment]
I did clean  and build project

**Comment by anshooarora** [comment]
See here:  http://stackoverflow.com/questions/15794821/eclipse-error-cannot-be-resolved-to-a-type

**Comment by jawlitkp** [comment]
ok i will try but i have upgraded from 2.40.1 to 2.40.2 and i am not getting any error,only when 2.41.0-beta2

**Comment by jawlitkp** [comment]
i see there are many new jar files under lib folder for 2.41.0-beta2 than 2.40.2, are those dependencies?

**Comment by anshooarora** [comment]
yes, new deps for mongodb etc

**Comment by jawlitkp** [comment]
after adding all deps ,getting below error


[after.pdf](https://github.com/anshooarora/extentreports/files/228304/after.pdf)

**Comment by anshooarora** [comment]
Hmm let me check, are you using the jar from the website or nexus?

**Comment by jawlitkp** [comment]
From website

**Comment by anshooarora** [comment]
Updated the document zip, can you download again and try again after adding the jars?

**Comment by anshooarora** [comment]
Hmm, even the latest jar is not going to work it seems.. something wrong with my environment, checking..

**Comment by anshooarora** [comment]
Please try with the latest.. 

Download extentreports-java-v2.41.0-beta2.zip from:  http://extentreports.relevantcodes.com/

**Comment by jawlitkp** [comment]
worked fine this time ,however i did not add any deps as i am not doing anything for Mongo.db.

Thank you!

Also I tried to configure Extent.x but i am not able to download package using command npm install due to company proxy policies ,let me know if any workaround

**Comment by anshooarora** [comment]
To use ExtentX you will require all dependencies to be added.  For NPM, you will have to work with your networking team and see how npm can use proxy to setup.

**Comment by anshooarora** [comment]
For example, if you have a proxy that you use to connect, you can use:

```
// from: http://jjasonclark.com/how-to-setup-node-behind-web-proxy/
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```

We for example have the same issue and use artifactory to house all our deps, and our proxy points to it instead.

**Comment by Harveer-Singh** [comment]
Hi Anshu,
 i am getting 3 test case under category tab while executing only one,
  please find the screenshot below

![dashboardcount_extentreport](https://cloud.githubusercontent.com/assets/25525179/25097894/0b19d6e8-23c4-11e7-8d08-19137a3c70c9.PNG)


![duplicate_testcase_issue](https://cloud.githubusercontent.com/assets/25525179/25097907/18615a92-23c4-11e7-802c-d2e96b01c85a.PNG)

please help me !! don't know where i am  doing wrong

i am using **2.40.2**
