### ISSUE TITLE
Hide Steps View

### ISSUE THREAD

**Issue by MihailZ** [anshooarora/extentreports#438]
Hi, Anshoo @anshooarora 
is there any easy way to hide/cut whole "Steps View" info from all tabs?
Perhaps using js, or some native configs. 
jar version is 2.40.2.

Thanks in advance!

**Comment by anshooarora** [comment]
remove this dashboard?  use this in extent-config.xml -> scripts tag:

```
$('.charts > div:nth-child(2)').hide();
```

**Comment by MihailZ** [comment]
And one more please, 
how to remove "Total Steps" dashboard?

**Comment by anshooarora** [comment]
Use this in the same location of config.xml:

```
$('.total-steps').parent().hide();
```

**Comment by MihailZ** [comment]
Thanks a lot!
