### ISSUE TITLE
TestRunner logs are not listed in the logs view

### ISSUE THREAD

**Issue by Arunagnz** [anshooarora/extentreports#439]
Hi Anshoo,

Extent reports framework is very useful and great. I am incorporating extent reports in my selenium java project. I am not able to print the logs in the logs view.

Can you please share extent report example that demonstrate all 5 views like [this](http://relevantcodes.com/Tools/ExtentReports2/ExtentJava.html) 

Thanks in advance.

**Comment by anshooarora** [comment]
- The test and dashboard views are default, and will always appear.
- Categories view will be enabled if a category is added.
- Exception view is enabled if an exception is added, using one of the following log sig:

```
log(LogStatus logStatus, Throwable t);
log(LogStatus logStatus, String stepName, Throwable t);
```

- TestRunner logs view will be enabled if you use this method:

```
extent.setTestRunnerOutput(s); 
```
