### ISSUE TITLE
New Feature: Filter by category for ExtentX

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#443]
Hi Anshoo,

I don't see filters for ExtentX , will be coming in next releases ?

Thanks

**Comment by jawlitkp** [comment]
Also when are you planning to release stable release for ExtentX ,I have configured Alpha on my local machine so waiting for stable release to deploy in production

**Comment by anshooarora** [comment]
Filters:  I am not sure if this feature will be available.  Feel free to open an ER and if there is enough support, we can plan on a timeline.  There will be a search category feature available though from which you can do pretty much the same thing.

Stable - when the alphas become stable after the required features, will release stable.

**Comment by jawlitkp** [comment]
Cool, i will explore search feature and if still think category filter require then will open ER.

I haven't tried yet but for ExtentX ,All results are getting written when extent.close() gets called ? like ExtentMerge, will i be able to write results for every test case by calling test.end()?

I am using ExtentMerge to generate live test execution report so trying to figure out if ExtentX can have ability to update mongodb when text.end() getting called

**Comment by anshooarora** [comment]
It will be updated each time `flush()` is called.  All reports will be available there without any manual merge.

**Comment by jawlitkp** [comment]
Got it. thanks.

Can you convert this as ER for extentx ?

**Comment by jawlitkp** [comment]
And would be great if we can apply multiple filters

**Comment by jawlitkp** [comment]
Also let me know if you need help for testing extentx

**Comment by anshooarora** [comment]
Sure thing.  Can you open this on the ExtentX repo?  It will be easier to track and other users may be able to contribute also..  Will close this.
