### ISSUE TITLE
I am unable get the documentTitle,reportName from xml file

### ISSUE THREAD

**Issue by RaviNelluri** [anshooarora/extentreports#444]
Hi, 

here is the my code . when I am running it documentTitle,reportName are nor coming from xml file ? I am doing anything wrong here . 

               inputproperties = new FileInputStream("D:\\extent-config.xml");
		
		properties.load(inputproperties);
		
		report = new ExtentReports("D:\\Result2.html", true);
		
		
		logger_report = report.startTest("HRM : Create User");

		report.addSystemInfo("Selenium Version", "2.46");
		report.addSystemInfo("Environment", "QA");

		WebDriver driver = new FirefoxDriver();
		driver.manage().window().maximize();
		
		logger_report.log(LogStatus.INFO, "Browser Lanuched Sucessfully");
		
		
		driver.navigate().to("http://www.Google.com");
		
		String path = captureScreenshot(driver, "ff");
		String image = logger_report.addScreenCapture(path);
		logger_report.log(LogStatus.PASS, "Login HRM", image);
		
		report.endTest(logger_report);
		report.flush();

**Comment by jawlitkp** [comment]
Below code is working for me.

report.loadConfig(new File("pathforextent-config.xml")));

**Comment by RaviNelluri** [comment]
error is displaying  @ report.loadConfig(new File("D:\\extent-config.xml"));
Saying null pointer

**Comment by anshooarora** [comment]
See if this helps:  http://extentreports.relevantcodes.com/java/#configuration

**Comment by jawlitkp** [comment]
Try this

report.loadConfig(new File("D://extent-config.xml"));

**Comment by RaviNelluri** [comment]
@anshooarora ya copied from there only but no luck .. did not understand what going on :(

**Comment by jawlitkp** [comment]
Are you initialize report before loading xml ? you should do like below 

				report = new ExtentReports();
				report.loadConfig();

**Comment by RaviNelluri** [comment]
report = new ExtentReports("E:\\Result2.html", true);
inputproperties = new FileInputStream(System.getProperty("user.dir") +
"\\Properties\\extent-config.xml");

properties.load(inputproperties);

Still unable to get inputs from xml file :(

**Comment by anshooarora** [comment]
Why are you loading it as a properties file? Please  use the `loadConfig` method.
