### ISSUE TITLE
New graph

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentreports#447]
The percentage of correct bar test occupy too much space and does not give too much information, if you could also include the percentage there in a view history as the following ...

![extentrchange](https://cloud.githubusercontent.com/assets/7159779/14766858/9e857b80-09ee-11e6-9fb6-e4d17e7acf7a.png)

**Comment by anshooarora** [comment]
This will not be possible as there is no db connected and everything is based off the single run session.  I would be happy to provide this information in ExtentX, but won't be possible in this reporting at all..
