### ISSUE TITLE
Attached screen shot override the logged message in extent report , It display only attached screenShot

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#451]
In extent report , when screen shot is not attached and logging some message then the logged message displayed in the extent report correctly .

extent.log(LogStatus.PASS, "Some message");

But When logging the message as well as attaching the screen shot then , the extent report does not display the message . It display only the screen shot . I believe it overrides the message and display only attached image if any .

for Eg:
extent.log(LogStatus.PASS, "Some message",extent.addScreenCapture("path"));

I need to display the logged message as well as Attached screen shot if any next to message . Is

 it supporting now ?

If not please provide some way to make it .

![extent](https://cloud.githubusercontent.com/assets/10355092/14778699/0ce100be-0af2-11e6-9d95-8d5fa346be56.png)

**Comment by perwez123** [comment]
I think its not about the screen shot only . It always display the last logs .

For example 

extent.log(LogStatus.PASS, "Testing report logs","Extent logs");

In this snippet it always display the "Extent logs" only . But i believe it should always display the both if exist .

**Comment by anshooarora** [comment]
I will have to recheck this once, but if you don't add stepName for the 1st step, it won't be possible to include it in the remaining steps to preventing malformed tables.

http://extentreports.relevantcodes.com/java/#create-step-logs

**Comment by perwez123** [comment]
Simple requirement ,I have passed the log message to print in the report and also attach the screenshot in the report if the steps fails . It means it is not necessary that , we will the the screen shot for all steps or first one . It depends up on the failure steps only .

This is very basic requirement . I would like to print the log message as well as the screen shot attached next to the log message and if steps not failed then display only log message.

extent.log(LogStatus.PASS, "Testing report logs","Screen shot");

In the above example all the parameter are passed . But if step is not failed then screen shot will not be attached . So we can not guarantee that the first steps will be having all the logs to print.

extent.log(LogStatus.PASS, "Testing report logs");

Just try it once and see how it goes ?I have a concern for for log message as well as screen shot attachment . Try to make it possible somehow as this is the basic requirement.

**Comment by perwez123** [comment]
Hi Anshoo ,

Have you got the time to go through this issue ? Actually in my current report , if the test is failed and screen shot is attached then the , log message does not display .It display only screen shot . Which is very difficult to understand what went wrong until log message display for failed steps . It would be easy to diagnose if log also display along with screen shot .

Please go through this once , and if it is fixable then please fix it and release in upcoming beta .

**Comment by anshooarora** [comment]
This feature will not be supported, and as I said before, it is to prevent malformed tables.  If you want to report a snapshot, it can be done at the details level also:

```
// with label
test.log(LogStatus.FAIL, "<span class="label label-fail">Error!</span> " +
 test.addScreenCapture("1.png"));

// without label
test.log(LogStatus.FAIL, "Error: " + test.addScreenCapture("1.png"));
```

if you would like to include the step-name, then:

```
test.log(LogStatus.FAIL, "Error", test.addScreenCapture("1.png"));
```

but the above way should be applied to the 1st step otherwise the step-name will not display for the entire table.  This is also what is mentioned in the docs:  http://extentreports.relevantcodes.com/java/#create-step-logs.  So the correct way would be to use only 1 type of log.

> There are 2 ways logs can be created: one that creates 3 columns and other that creates 4. Always use only 1 type of log for the test otherwise the table will become malformed.

**Comment by shalabhdixit** [comment]
Hi Anshoo,

Do we need to create separate classes and method to capture screenshots in extent reports. I mean I used
both the below methods but unable to get screenshots. Please suggest.

// with label
test.log(LogStatus.FAIL, "<span class="label label-fail">Error!</span> " +
 test.addScreenCapture("1.png"));

// without label
test.log(LogStatus.FAIL, "Error: " + test.addScreenCapture("1.png"));

**Comment by anshooarora** [comment]
Is the path correct?

**Comment by KalveeduVijay** [comment]
@perwez123  ...
Extent Report Version :- 2.41.1

I'm having a separate function named "takesScreenshot" which  do the job for me to take the screenprint. Below pasted is the sample code of how we log into system.

*status-> returned by functions as Passed or Failed based on success.
*takesScreenshot-> returns the path of screenshot present.
*HTML are used to high light the passed as Green and Failed as "RED ALERT". 
*Span tag is used to display the complete logs upon mouse hover. IN this case exception.getCause() will return the complete string. It helps user to understand in detail about the root cause. Upon Clicking "Failed" user will get redirected to LOGS file incase of more debugging needed.

  public static void generate(String status){
	    	
	    	if(status.contains("Passed")){
	    		
	    		
	    		logger.debug("Status marked in Pass block : " + status);
	    		constants.extentTest.log(LogStatus.PASS, useCase   , "<font size="+3+" color='#7CFC00'>"+status +"</font>"+ " <br />" +expectedResult);
	    		
	    	}else if(status.contains("Fail"))
	    	{
------->	    		String screenshotPath= reusuableFunctions.takeScreenshot();
	    		String imageOfFailed = constants.extentTest.addScreenCapture(screenshotPath);
	    		logger.debug(imageOfFailed);
	    		logger.debug("Status marked in Fail block : " + status);
	    		constants.extentTest.log(LogStatus.FAIL, 
	    								 useCase, 
	    								 "<span  title='"+constants.status.replaceAll("'", "&#39;")+"'><a href='"+constants.logsPath+"/Framework.log'><font size="+3+" color='#DC143C'>FAILED</font></a></span>"+
	    								  imageOfFailed);
	    		
	    	
	    		
	    	}else{
	    		
	    		logger.debug("skipped" + status); 
	    		constants.extentTest.log(LogStatus.SKIP, useCase, status);
	    	}
	    	
	    }

**Comment by rajeshkumarvalakonda** [comment]
HELLO ALL,

How to print table in extent report

![image](https://cloud.githubusercontent.com/assets/19650957/26537182/c4d402dc-445a-11e7-8da4-1e5a8f6407d4.png)
 

I want print all the values in a table. Could you please anybody on this

**Comment by Shroet** [comment]
Could you please clarify this: test.log(LogStatus.FAIL, "Error! " +
test.addScreenCapture("1.png"));  
How we specify the path to file?
