### ISSUE TITLE
changing environment table rows color 

### ISSUE THREAD

**Issue by Fadih** [anshooarora/extentreports#452]
hi ansho ,

my tests running in parallel on multiple android devices ,in environment table i printed information about each device ,do you have any way to separate each device data??
if not i want to display each data on different color 

see attached image
![kkk](https://cloud.githubusercontent.com/assets/6965157/14782540/a1b380fe-0af2-11e6-99fe-9cf388d6a3ec.PNG)

thanks

**Comment by anshooarora** [comment]
You can do this:

```
extent.addSystemInfo("<span class='label info'>powerControl</span>", "reboot");
```

More types of labels here:  https://github.com/anshooarora/extentreports/blob/master/cdn/extent.css#L777
