### ISSUE TITLE
How to get seprate reporte for each thread while running test cases in parallel

### ISSUE THREAD

**Issue by sanjaybhati87** [anshooarora/extentreports#455]
Hi Anshu,

I am facing an issue, while I am running my test cases in Parallel. I want to run test cases in parallel using testNG on the Test level and want to see the report for each test thread separately like in TestNG report.My objective to run test cases in diffrent browsers and see the result as per browser.

**Comment by anshooarora** [comment]
I would recommend using a single report with categories to distinguish between tests.  If you want multiple reports, you would have to create and manage multiple ExtentReports instances - one for each report.  It will add unnecessary complexity but is completely doable.
