### ISSUE TITLE
How to pass test name into extent.startTest?

### ISSUE THREAD

**Issue by dssauto** [anshooarora/extentreports#456]
Hi,
On your example you have test name hard coded " test = extent.startTest("passTest");"
Is it possiable to make it will grab test name insted of typing it twise? Thank you
    @Test
    public void passTest() {
        test = extent.startTest("passTest");
        test.log(LogStatus.PASS, "Pass");
   }

**Comment by anshooarora** [comment]
If you are using TestNG, you can do:

```
void passTest(Method method) {
    test = extent.startTest(method.getName());
}
```
