### ISSUE TITLE
Total tests count showing incorrect after append tests on dashboard

### ISSUE THREAD

**Issue by rakslalsangi** [anshooarora/extentreports#457]
When I append child test to parent , Total tests count showing double of child tests .

Please find code and screenshots .

**c# code : **
----------------------------------------------------------------------------------------------------------------------------
   ExtentReports extentReport = new ExtentReports("d:/test/newExtentReportDotNet.html");

            ExtentTest parent = extentReport.StartTest("parent");

            ExtentTest child1 = extentReport.StartTest("child1");

            child1.Log(LogStatus.Pass, "step1");

            Thread.Sleep(1000);

            child1.Log(LogStatus.Pass, "step2");

            Thread.Sleep(2000);

            extentReport.EndTest(child1);

            ExtentTest child2 = extentReport.StartTest("child2");

            child2.Log(LogStatus.Pass, "step1");

            Thread.Sleep(2000);

            child2.Log(LogStatus.Pass, "step2");

            Thread.Sleep(3000);

            extentReport.EndTest(child2);

            parent.AppendChild(child1).AppendChild(child2);

            extentReport.EndTest(parent);

            extentReport.Flush();

            Console.WriteLine("Sucess");

            Console.ReadLine();

----------------------------------------------------------------------------------------------------------------------------

![child and parnt test](https://cloud.githubusercontent.com/assets/13434323/14940731/9cc4220e-0f9f-11e6-87d0-25650c82a7a2.png)
![extent report - parnt child](https://cloud.githubusercontent.com/assets/13434323/14940732/9cc5f552-0f9f-11e6-9420-5414516f1716.png)

**Comment by anshooarora** [comment]
Do not call `endTest` on child-tests as `appendChild` does that.  Only call it for parent tests.  Remove these lines:

```
extentReport.EndTest(child1);
extentReport.EndTest(child2);
```

**Comment by rakslalsangi** [comment]
Hi Anshoo ,
I removed 2 line , then also same issue .


Problem solved with Solution -- update jar to extentreports-java-v2.41.0-beta3 if you using JAVA .
For C# , wait till extentreports v2.41.0 available in nuget 

I think this is bug in extentreports-java-v2.40.2 (see screenshot which taken from ------http://extentreports.relevantcodes.com/java/ ) .

![image](https://cloud.githubusercontent.com/assets/13434323/14948003/1259d414-1059-11e6-85aa-0d0df28d98bc.png)
