### ISSUE TITLE
Wrong Screenshots path 

### ISSUE THREAD

**Issue by dssauto** [anshooarora/extentreports#458]
Hi,
I have separate class for taking screenshots with its own folder path  " **/Reports/Screenshots/ **" here all me screenshots will be stored and I have main class to call class to take screenshot and log it to the report and reports goes to this location "** /Reports/** ".
When I run the test screenshots image not showing up on the report when I check the path it is looking for screenshot in the Reports folder, here my actual image is " /Reports/Screenshots/050220161224Screenshot.png " but on the report it is like that " /Reports/050220161224Screenshot.png ". What I am doing wrong? Here is my code:

        private static readonly ExtentReports _instance =
            new ExtentReports(@".\Reports\TestReport.html", DisplayOrder.OldestFirst);

            string screenName = Utility.TakeScreenshot();
            string scrrenShotPath = TestReport.AddScreenCapture(screenName);
            TestReport.Log(LogStatus.Fail, "ScreenshotOfFail", scrrenShotPath);
            extent.EndTest(TestReport);
            extent.Flush();
            Driver.Close();

 When I put my reports and screenshots in the same folder it is working fine but I want to separate both on its own folder.
Thank you.

**Comment by karthikbhatnagar** [comment]
The add screen capture method creates a link to the IMG file.  You can store screenshot path as a properties or global variable and add it with the snapshot name so the link is valid

**Comment by anshooarora** [comment]
In the path you can provide `'/Reports/Screenshots/' + screenShotName` so the folder remains static.
