### ISSUE TITLE
Getting java.sql.SQLException "SQLITE_BUSY" while writing result to DB

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#460]
Hi Anshoo,

I am getting below error,could you please advise,i have also noticed once extra file(extent.db-journal) is getting generated with extent.db file and assuming it is db locking file.

java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:807)
	at org.sqlite.core.DB.executeUpdate(DB.java:847)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:86)
	at com.relevantcodes.extentreports.DBReporter.addTest(DBReporter.java:318)
	at com.relevantcodes.extentreports.Report.finalizeTest(Report.java:370)
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:832)
	at com.bbb.util.BBBU_Listener.onTestSuccess(BBBU_Listener.java:176)

**Comment by jawlitkp** [comment]
I think this is what happening 

*Trying to write to a table while a SELECT is active on that same table. 

while running multiple threads endTest() writes to table and that method is getting multiple times at same times

**Comment by anshooarora** [comment]
Is this intermittent or always happens?  If you are using 1 extent instance, I don't see how this will occur though but I would like to reproduce this as much as possible..

**Comment by jawlitkp** [comment]
This is happens every time after executing large number of test cases(multi threads) ,for me this error comes after 150 -200 test cases.

So here is my observation.

When multiple threads tries to write in to the DB ,it would create extra locking file as below screenshot ,until it finished writing to DB.

![image](https://cloud.githubusercontent.com/assets/9873362/15050122/d3f7daa4-12bf-11e6-93e6-3140f1bd73cc.png)

and what i observed is while this file is there DB is not getting updated right away by calling endTest() method

so far what i tried is made below method to make sure it would not get executed multiple times at same time but didnt work

	public static synchronized void endReporter(ExtentTest rp){
		boolean isTestEnded=false;
		while(!isTestEnded){
			try {
				System.out.println("Started Writing result to DB...");
				BBBU_TestConfig.report.endTest(rp);
				System.out.println("Ended Writing result to DB...");
				isTestEnded=true;
			} catch (Exception e) {
				isTestEnded=false;
				e.printStackTrace();
			}
		}

in below screenshot you can see ,onTestSucess method got called 78 time but my DB report is showing only 59 passed test cases ,so remaining test cases are in pending status to write to DB file even endTest() is already executed

![image](https://cloud.githubusercontent.com/assets/9873362/15050287/cdb0f6a2-12c0-11e6-8f3d-dbfe32ab76fe.png)

you can refer below link for the same issue 

http://stackoverflow.com/questions/10707434/sqlite-in-a-multithreaded-java-application

https://www.sqlite.org/lockingv3.html

**Comment by jawlitkp** [comment]
do you think based on below suggestion ,all methods should be synchronized. I am generating only one DB file during entire execution so there's no multiple multiple instances 

![image](https://cloud.githubusercontent.com/assets/9873362/15050744/84c031f8-12c3-11e6-9192-c4ed6d891267.png)

**Comment by anshooarora** [comment]
Since you are using 1 extent instance, making all [write methods](https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/DBReporter.java) synchronized would fix it.  Although you are using this for ExtentMerge - would recommend using ExtentX as it is the future direction of this feature.

**Comment by jawlitkp** [comment]
Yes i am moving to ExtentX but extent Merge is just to produce live report from DB.my concern is to fix DB issue as i need to keep track all executed test cases.

correct me if i am wrong , DB report is part of extent and will be continuing supporting ?

**Comment by anshooarora** [comment]
yes, the database reporting will remain active

**Comment by jawlitkp** [comment]
Cool!, so I will wait for new version of jar with modified methods and will test against it. hopefully it will resolve this issue

Thanks for helping

**Comment by anshooarora** [comment]
[extentreports-java-2.41.0-beta4-revision.jar.zip](https://github.com/anshooarora/extentreports/files/250864/extentreports-java-2.41.0-beta4-revision.jar.zip)

Can you try with the attached zip?  Same deps as the beta-4.

**Comment by jawlitkp** [comment]
Sure.

**Comment by jawlitkp** [comment]
No luck.

Still getting error

java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:807)
	at org.sqlite.core.DB.executeUpdate(DB.java:847)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:86)
	at com.relevantcodes.extentreports.DBReporter.addLogs(DBReporter.java:449)
	at com.relevantcodes.extentreports.DBReporter.addTest(DBReporter.java:321)
	at com.relevantcodes.extentreports.Report.finalizeTest(Report.java:370)
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:832)
	at com.bbb.util.BBBU_Listener.endReporter(BBBU_Listener.java:501)
	at com.bbb.util.BBBU_Listener.onTestFailure(BBBU_Listener.java:84)

**Comment by jawlitkp** [comment]
so after running first iteration i opening DB connection to same database and closing it in order to check failed test cases and include them in 2nd iteration ,would that be the issue ? but i am seeing same error during first iteration when i am not opening any additional connection to db

**Comment by anshooarora** [comment]
[extentreports-java-2.41.0-beta4-revision2.jar.zip](https://github.com/anshooarora/extentreports/files/251302/extentreports-java-2.41.0-beta4-revision2.jar.zip)

You can try with the attached jar.  If it doesn't work, I will have to see your suite - how you are writing etc.  I tried to reproduce this with many threads but unable to..

**Comment by jawlitkp** [comment]
Sure i will try again and let you know.if not we can do Skype session

**Comment by jawlitkp** [comment]
No luck again:(.I think its SQLite performance issue

here is what happening.

since i have many steps for individual test cases ,even though update query is getting executed anf finished but DB update takes time to update and it is not releasing shared lock for next request and then all requests are goes in pending status hence it is creating extent.db-journal file. while this file is created DB looks blank and it will take time to update with latest results.

this is how db look like with extent.db-journal and without extent.db-journal file 

![image](https://cloud.githubusercontent.com/assets/9873362/15073481/b096ae34-1367-11e6-872c-3133966cfd2a.png)

![image](https://cloud.githubusercontent.com/assets/9873362/15073491/ba3ebf9e-1367-11e6-8ca7-a007f862ad44.png)

![image](https://cloud.githubusercontent.com/assets/9873362/15073525/e5846bb8-1367-11e6-837d-db7720c9517f.png)

![image](https://cloud.githubusercontent.com/assets/9873362/15073520/de2ed6e6-1367-11e6-8729-f01dd235825f.png)

**Comment by jawlitkp** [comment]
We can set up online session whenever you are available

**Comment by anshooarora** [comment]
That won't be possible, but what baffles me is that the DB size that you have shared in the email is only 8MB - not at all large so it shouldn't be this slow.  I can add a check to only write when the journal file is closed, but I am afraid to run into issues where someone manually opens the file and the test pauses until the file gets closed.  Would like to know other possible solutions to this..

**Comment by jawlitkp** [comment]
I can test if you provide me jar to see if opening journal would cause any problem during execution, I got stuck right now and need even temporary solution.and if you think it's coding issue then u can share sample
Code on how I am reporting

**Comment by jawlitkp** [comment]
I am trying this logic but it doesn't recognize file even its there ans always passed condition,do you know is there any other work around i can implement from my side so it wont impact yours.

	     File s1 = new File(DBReportFoldePath.replace("\\", "//")+"//extent.db-journal");

	    System.out.println(DBReportFoldePath.replace("\\", "//")+"//extent.db-journal");
	    
		while(s1.exists()){
			
			System.out.println("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< There's journal db file present so waiting it to disappeared >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				
			}
		}

**Comment by jawlitkp** [comment]
implemented custom dbLogger class with only 5 columns and works perfectly fine ,this is definitely SQLIte performance issue while writing large amount of data in multi threading

**Comment by jawlitkp** [comment]
removed screenshot

**Comment by jawlitkp** [comment]
You might want to put stmt.close under final catch so it will get executed even logic before it failed

**Comment by anshooarora** [comment]
I will do some tests with H2 database - http://www.h2database.com/html/features.html#multiple_connections and replace SQLite if H2 supports concurrency.
