### ISSUE TITLE
The screenshot doesnt show in the report ExtentMerge.html

### ISSUE THREAD

**Issue by azamat163** [anshooarora/extentreports#462]
Hi Anshoo!
There was a problem with merge reports for the next command line: 
java -jar ~/extentmerge.jar -dir /users/azamat/proj_ta/EZD/Selenium_project_EZD/Reports/ -out /users/azamat/proj_ta/EZD/Selenium_project_EZD/Final_Report/ExtentMerge.html
And in the report ExtentMerge.html doesnt showed screenshoots.

**Comment by anshooarora** [comment]
This was one of the ERs for this product.  However, ExtentMerge is deprecated and there will be no future releases as its replaced by ExtentX.  This feature is also an ER for ExtentX, and it will be available soon.  

To use ExtentX, see here:  http://extentreports.relevantcodes.com/extentx/
