### ISSUE TITLE
Issue: Report is taking infinite time to load

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#463]
Hi Anshoo,

Report is taking infinite time to load when huge number of  test cases ,and finally is throws error.

I have sent you an email with report zip folder so you can reproduce.

Thanks

**Comment by anshooarora** [comment]
Jawlit - no issues here, I am able to load the report in all supported browsers..

**Comment by jawlitkp** [comment]
Ok in that case should be issue on my Windows machine. It's working fine on Mac

**Comment by anshooarora** [comment]
Closing issue as this may be related to OS/system-memory
