### ISSUE TITLE
Environment for mobile (Selenium-Appium)

### ISSUE THREAD

**Issue by Grim-persgroep** [anshooarora/extentreports#464]
Hello,

For the moment in my reports under the section Environment for OS it's written Windows 7 since this is my computer OS but I would like to know if it's possible to access the Phone OS instead of the computer one when I'm running test on mobile with Appium

Thank you

**Comment by anshooarora** [comment]
I am not sure how to access, but you can use system info by using:

Java:  http://extentreports.relevantcodes.com/java/#add-system-info
.NET: http://extentreports.relevantcodes.com/net/#add-system-info
