### ISSUE TITLE
Image not getting attached in the reports

### ISSUE THREAD

**Issue by dhirenmudgil** [anshooarora/extentreports#465]
![snip20160507_1](https://cloud.githubusercontent.com/assets/16384125/15093324/0dac6560-14a2-11e6-953e-39d043b350f3.png)
Image is not getting attached. White space is coming in reports while attaching image.

**Comment by jain-pulkit** [comment]
Could you please paste the code base for screen shot and attach statement please?

**Comment by dhirenmudgil** [comment]
I drill down more and found out, i accidentally raised other issue. Please close this.

Reference for other one : https://github.com/anshooarora/extentreports/issues/468
