### ISSUE TITLE
Issue with relative path of screenshot

### ISSUE THREAD

**Issue by dhirenmudgil** [anshooarora/extentreports#468]
Hi,

Problem with relative path when run these test on a Jenkins server.

For Eg : My relative path is "projectname/target/filename.png"

The below condition will be true when i will pass the path as mentioned above.

`  private Boolean isPathRelative(String path) {
        return path.indexOf("http") != 0 && (new File(path)).isAbsolute()?Boolean.valueOf(false):Boolean.valueOf(true);
    }`

`String screenCaptureHtml = this.isPathRelative(imagePath).booleanValue()?ScreenshotHtml.getSource(imagePath).replace("file:///", ""):ScreenshotHtml.getSource(imagePath);`

But when i see the screenCaptureHtml value it takes path as "projectname/target/filename.png" only but browser want path like "/projectname/target/filename.png"

The possible cause which i think is it should replace only ("file://", "") instead of ("file:///", "").

Please review what required.

**Comment by anshooarora** [comment]
I am not sure what the issue is.. if you know the required path, simply pass that instead of "projectname/target/filename.png".

**Comment by dhirenmudgil** [comment]
Issue is with relative path when this report is hosted on some other server other than local host.

**Comment by anshooarora** [comment]
If the relative path changes from one machine to another, then obviously the link would break.  The folders/images should remain in the same path as specified regardless of where they are deployed for them to work correctly.
