### ISSUE TITLE
freemarker/ext/beans/BeansWrapperBuilder Error while intializing the Main Class

### ISSUE THREAD

**Issue by sahiljindal1812** [anshooarora/extentreports#469]
Have updated the jar in my current java project from extent-report 1.4 to 2.40 and suddenly it stopped working by following exception:-
An error occurred while instantiating class com.markit.test.ExecuteReportGenerator: freemarker/ext/beans/BeansWrapperBuilder

Have updated the lib folder with jsoup-1.9.1.jar and extentreports-2.40.2 and freemarker-2.3.20

Can any one help me in the same?

**Comment by anshooarora** [comment]
Please use freemarker version 2.3.23

```
<dependency>
    <groupId>org.freemarker</groupId>
    <artifactId>freemarker</artifactId>
    <version>2.3.23</version>
</dependency>
```

**Comment by sahiljindal1812** [comment]
Thanks Anshu.
You are a genius !

Its working fine now.
