### ISSUE TITLE
Results not displayed in chronological order of execution

### ISSUE THREAD

**Issue by aparnamaturi** [anshooarora/extentreports#473]
This issue is similar to the issue: https://github.com/anshooarora/extentreports/issues/93

I am using TestNG 6.9.9 and I want my emailable-report.html to have tests in the order they were executed. Looks like default behavior is the alphabetical order. Is there a way to order the tests with their end time (without having to generate the whole custom HTML report using IReporter)?

BTW, my testng-results.xml has the correct order (by execution time). Only the report has alphabetical order.
[testng-results.zip](https://github.com/anshooarora/extentreports/files/260616/testng-results.zip)

Thanks
Aparna

**Comment by anshooarora** [comment]
Please open this in the TestNG repo which manages the emailable-report.
