### ISSUE TITLE
Extent report

### ISSUE THREAD

**Issue by akshking** [anshooarora/extentreports#474]
Can we use extent report with Junit framework ?

**Comment by akshking** [comment]
I found this as a alternative for configuring it with JUnit 
http://stackoverflow.com/questions/35000531/one-test-watcher-to-report-results-of-individual-tests-in-junit-suite/37157952#37157952 

I want to know that , Currently I'hv developed unit tests using Junit & building it using maven project to get the results currently i m using surefire reports , Now i want to get the result in extent reports , So in order to configure that i have created above testwatcher class & also formed test suite , & after running it is generating output in extent but it is a aggregate output not showing test scripts level segregation.

Also if i build it through maven it is throwing error of build failure.

Please advise.

**Comment by anshooarora** [comment]
You can use any test framework, including JUnit.  See if [this](http://www.kieftsoft.nl/?p=81) post helps.

**Comment by akshking** [comment]
Hi Anshu,
Have seen this even have implemented this solution , But results are not appropriate.
Can you please tell me where I'm making mistake?

**Comment by akshking** [comment]
Let me know if you want to see my code.

**Comment by akshking** [comment]
Hi Anshoo , Can you please provide me step guide for implementing extent report with - Junit

**Comment by anshooarora** [comment]
You will have to explore the annotations provided by JUnit, for example:

https://github.com/junit-team/junit4/wiki/Rules#testwatchmantestwatcher-rules
https://github.com/junit-team/junit4/wiki/Test-fixtures
