### ISSUE TITLE
Feature Request - ExtentReports Merge Tool

### ISSUE THREAD

**Issue by CharlieThach** [anshooarora/extentreports#48]
I saw in the ExtentReport it has an option to append the later execution:
                  new ExtentReports (reportFile, false)
 
This feature is good for appending the report. I think it will be great if you can provide another feature to merge the reports instead of just appending them.

For Example:
If I execute test Class A and B with test cases A1, A2, B1, B2.  And then both test Classes again but with different test cases A3, A4, B3, B4 but without setting the flag to false for appending.

Is it possible for ExtentReport to provide a feature to merge the reports together by just calling a method like: merge(report1.html, report2.html) or from command line: ExtendReport report1.html report2.html to provide the final report that including all the reports? When we merge the report, we should sort the test cases in the test class.

**Comment by anshooarora** [comment]
Initial commit: 9b073ae.

**Comment by anshooarora** [comment]
Charlie - this is for your other request to neatly arrange tests so they are easy to view.  How does the below template look:

http://relevantcodes.com/Tools/ExtentReports2/ExtentJava210.html

Its for the upcoming version 2.10.

**Comment by anshooarora** [comment]
Charlie,  here is the initial build:  https://github.com/anshooarora/extentreports/tree/master/extentmerge

and a quick sample:  http://relevantcodes.com/Tools/ExtentReports2/ExtentMerge.html#

**Comment by anshooarora** [comment]
Merge tool now available.  

https://github.com/anshooarora/extentreports/tree/master/extentmerge

**Comment by PrasadReddyC** [comment]
i also need the same solution as @CharlieThach the above to merge different extent reports executed in different machines can u please tell me where can i finf merge tool @anshooarora
