### ISSUE TITLE
Format long tables as details

### ISSUE THREAD

**Issue by kodstark** [anshooarora/extentreports#480]
Hi Extentreports,

This library works nice. 

I'm trying to format cucumber tables and I found that HTML can be put only on details column - as effect long tables are taking only 1/3 of the screen and look bad. The same problem is when I publish additional tables with cucumber scenario.write mechanism - I think that having possibility to display details below step row it would give at least 2/3 screen (left sidebar takes already 1/3 of screen). Is any existing solution which I'm missing to format long tables?

**Comment by anshooarora** [comment]
You can use your own CSS styles to customize the layout.  To change placement, you can use custom js.  Both are part of extent-config.xml.

**Comment by anshooarora** [comment]
I am closing this ticket.  Feel free to respond back or open a new one if you continue to have formatting issues.
