### ISSUE TITLE
Report Data 

### ISSUE THREAD

**Issue by Shweta2009** [anshooarora/extentreports#483]
Hi Anshoo

Checked the reporting format and found very nice....I'm planning to implement the same in my project but before implementing this I have some doubts/queries - 
1) By Default report data will be stored locally or on mongodb?
2) In my project I'm using MySQL for reporting purpose so just wanted to confirm that is there any way   
    out that I can use MySQL instead to mongodb?

**Comment by anshooarora** [comment]
I believe you are referring to ExtentX, this is for ExtentReports.  Please raise your query here:  https://github.com/anshooarora/extentx

1.  MongoDB only
2.  No
