### ISSUE TITLE
Make the extent report pop-up after test execution is complete

### ISSUE THREAD

**Issue by mbnrguy** [anshooarora/extentreports#486]
Hi Anshoo,

Please let me know if there is a way so that the extent report html can pop-up using my machine's default browser after execution is complete?

**Comment by ranashahan** [comment]
Hi mbnrguy,

I think if you put following method into your TestNG Aftersuite method that will solve your problem. Make sure that you have closed your all ongoing driver before it through driver.quit();

`@AfterSuite
    protected void afterSuite(){
        //Make sure place correctly your report path.
    	driver.get("D:\\workspace\\\Extent.html");
    	driver.findElement(By.xpath("//a[@class='dashboard-view']/i")).click();
    }`
 

pardon me if i understood wrong your query.

**Comment by mbnrguy** [comment]
Thanks Rana. I was doing something similar already but was wondering if there was any setting within the config file that does this.

**Comment by anshooarora** [comment]
I would recommend using this approach:

http://stackoverflow.com/questions/20517434/how-to-open-html-file-using-java
