### ISSUE TITLE
Difference between Current Run and over all run total times on extend report deshboard panel 

### ISSUE THREAD

**Issue by dachaldas** [anshooarora/extentreports#487]
![currentrun overall](https://cloud.githubusercontent.com/assets/19603401/15598850/db332d9e-23fb-11e6-8085-091d5261a476.jpg)

**Comment by anshooarora** [comment]
This is helpful for those users who run with the `replaceExisting = false` setting to overwrite an existing report with new tests.  Seems you run a single session so both times would be always the same.
