### ISSUE TITLE
Extent Report : Update the english text to spanish

### ISSUE THREAD

**Issue by RaghavendraPrabhu** [anshooarora/extentreports#488]
Hi Anshoo,
I am using extent reports and really the reports generated are awesome. Thanks for creating such nice reports. I have one query. My client needs one update in the reports. He wants to change the english default text to spanish content. Can you please guide can we achieve.

**Comment by lucasribeiro1990** [comment]
Just trying to help, maybe these links can help you:

http://extentreports.relevantcodes.com/java/#localized-versions
http://extentreports.relevantcodes.com/net/#localized-versions

The documentation around can help you better undertand the code you will need to add.

**Comment by anshooarora** [comment]
Closing as @lucasribeiro1990 response shows how to create localized version.
