### ISSUE TITLE
When a testng suite time-out is hit, the report isn't generated and we get the following:

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#49]
[selenium:testng] Total tests run: 0, Failures: 0, Skips: 0
[selenium:testng] ===============================================
[selenium:testng]
[selenium:testng] [TestNG] Reporter ExtentReporterNG@5318a0ac failed
[selenium:testng] java.lang.NullPointerException
[selenium:testng]       at com.relevantcodes.extentreports.ExtentReports.removeChildTests(ExtentReports.java:169)
[selenium:testng]       at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:145)
[selenium:testng]       at ExtentReporterNG.generateReport(ExtentReporterNG.java:58)
[selenium:testng]       at org.testng.TestNG.generateReports(TestNG.java:1115)
[selenium:testng]       at org.testng.TestNG.run(TestNG.java:1074)
[selenium:testng]       at org.testng.TestNG.privateMain(TestNG.java:1364)
[selenium:testng]       at org.testng.TestNG.main(TestNG.java:1333)

**Comment by cktech529** [comment]
Here's the suite header:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<suite allow-return-values="true" configfailurepolicy="skip" data-provider-thread-count="10" group-by-instances="false" guice-stage="DEVELOPMENT" junit="false" name="CemGui" parallel="tests" preserve-order="true" skipfailedinvocationcounts="false" thread-count="10" time-out="10000" verbose="10">
...
..

**Comment by anshooarora** [comment]
Chris, for now, you can remove:

```
extent.close();
```

from the listener and you won't face this issue.  I have fixed the issue with the <code>TestList</code> so this issue won't popup starting next release.

**Comment by cktech529** [comment]
I added close to try and fix it. The issue comes up with flush too.

Chris

**Comment by vishwathma** [comment]
This seems to be a blocker. Am also facing the same issue. Please fix this ASAP.

**Comment by anshooarora** [comment]
Chris,

You can run tests in parallel the same way as methods.  

BTW, what version are you guys using? When does this error occur? - when no tests were run?

**Comment by vishwathma** [comment]
@my end, when I introduced some error in the config file(where everything is set up including driver, in my case I deliberately failed the webdriver initialization, & none of the tests got executed), am seeing this error.

**Comment by anshooarora** [comment]
Vishi - then its probably because there are 0 tests which made Extent close on a few null objects.  I will investigate this.

Can you handle this issue using the code in ExtentReporterNG class only?  So, you can only call flush and close if there are more tests than 0.

**Comment by vishwathma** [comment]
Anshoo, I tried to do that. Fyi, already I have customized the code in ExtentReporterNG. This is somewhat putting me breaks to handle NPE. I will try to handle. But let me know once this gets fixed. Thanks.

**Comment by anshooarora** [comment]
This will be fixed in the upcoming version. No ETA for it though as the next one will be a major upgrade.

**Comment by vishwathma** [comment]
Thanks Anshoo. I did a minor change in the code as below & it seems to work.
@cktech529, please use it. If you come up with something better, please let me know.
for (ISuite suite : suites) {
            Map<String, ISuiteResult> result = suite.getResults();
            for (ISuiteResult r : result.values()) {
                ITestContext context = r.getTestContext();
                int size = context.getSkippedTests().size()+context.getFailedTests().size()+context.getPassedTests().size();
                if(size>0) {
                	try {
		            	buildTestNodes(context.getPassedTests(), LogStatus.PASS);
		            	buildTestNodes(context.getFailedTests(), LogStatus.FAIL);
		            	buildTestNodes(context.getSkippedTests(), LogStatus.SKIP);
					} catch (MalformedURLException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
		        	extent.flush();
		        	extent.close();
                }
            }
        	}
    }

**Comment by vishwathma** [comment]
Fyi, am using the latest version 2.04 .

**Comment by cktech529** [comment]
Hi, sorry for the late reply.

I tested against 2.04. 

A way to duplicate the issue Anshoo is to create a suite with say 10 tests, on the suite put a timeout of say 10000 (10 seconds) put parallel = "tests".

What I noticed is that when there is a timeout, the report will either fail or come back with only a few of the passed tests.

It might be a testng issue?

A workaround that I did (very hacky) was create a suite of SUITE FILES and each of the suites files has a single suite with a single <test> entry :-D

It's messy though because the report is hit for each suite so I have to do more checking.

Will play more when I have time.

Chris

**Comment by virenv** [comment]
So basically the problem here is ->

When testng suite timesout and exception is raised and is handled by TestNG. During this phase your tests stop abruptly and they dont get a chance to call any of your .close or .flush methods.  This should also happen in case of unhandled exceptions in your test.

Solution -> Implement the ISuiteListner interface and make sure that when ever you get a call to ::endSuite method do all your clean up activities like ending test and closing reporter.

Also implement the ITestListener and make sure that in onTestEnd you close the ExtentTest instance.

http://testng.org/javadoc/org/testng/ISuiteListener.html
http://testng.org/javadoc/org/testng/ITestListener.html

Please do let me know if you need more information.

**Comment by anshooarora** [comment]
Closing issue as there was no response.
