### ISSUE TITLE
Reporting server

### ISSUE THREAD

**Issue by akshking** [anshooarora/extentreports#490]
Hi Anshoo,

Do we have any solution such as - we create a database server which will store all the results inside it of every run & we use a web UI to pull the results from the database & show it is extent report also we can have a comparison view to compare results of current run with previous execution runs.

Do we have anything implemented like this?

Do we have plug-in support to Jenkins CI tool ????

Waiting to hear from you.

Thanks!
Akshay

**Comment by akshking** [comment]
Hi Anshoo,

After posting above question was going through the previous history of question & have foud that you have already implemented as solution of reporting API server using mongo db & nodejs server,

Now I'm keen interested to know this - Like server setup requirements then tools required - mongodb + node.js server ..& anythings else?

Can we do this setup on windows OS? Or do we require specific ubantu setup ?

**Comment by akshking** [comment]
Any video tutorial if available for extentX ?

**Comment by ranashahan** [comment]
Hi Akshking, 

I have already raised that request on #482 , can you please like it and so admin/anshoo will be taking seriously our needs. 

https://github.com/anshooarora/extentreports/issues/482

Thanks
Rana

**Comment by anshooarora** [comment]
I would love to create a video tutorial but have very little bandwidth these days to do so.  I can keep this ticket open in case an existing user sees it and decides to fill this gap.

**Comment by anshooarora** [comment]
On a second note, #482 is already open for this purpose, so closing this.
