### ISSUE TITLE
Extent X Dashboard Creation from Executions

### ISSUE THREAD

**Issue by Manjudeepak11** [anshooarora/extentreports#494]
Hi Anshoo,

Thanks for creating wonderfull framework for reporting..

I am trying to Create the dashboard using ExtentX fromthe exetent reports that is generated in my Executions. Please share any documentation if you have for creating the dashboard using ExtentX.

Thanks
Mnajunath B S

**Comment by anshooarora** [comment]
You can find documentation here:  http://extentreports.relevantcodes.com/extentx/

If you are using Java, here is the reference:  http://extentreports.relevantcodes.com/java/#connect-to-extentx
If .NET, see here: http://extentreports.relevantcodes.com/net/#connect-to-extentx
