### ISSUE TITLE
Issue in ExtextX configuration

### ISSUE THREAD

**Issue by Manjudeepak11** [anshooarora/extentreports#498]
Hi Anshoo,

I have done the node js and mongo DB insatllations in my local. Is there any extentX jar that needs to be added to my build path ?? When I use " extent.x();" it is giving me error.. Please let me know on this..

Thanks
MANJUNATH B S

**Comment by anshooarora** [comment]
This is not the correct forum for ExtentX.  You can post your queries here:  https://github.com/anshooarora/extentx

See here for usage instructions: http://extentreports.relevantcodes.com/extentx/
