### ISSUE TITLE
Using ExtentReport Listener for monitoring

### ISSUE THREAD

**Issue by Cooliinnnn** [anshooarora/extentreports#505]
Hi @anshooarora and everyone,

Just a question to anyone here who is using ExtentReport as a listener.

Is it possible to use ExtentReport to generate the HTML Report during the tests being executed?

For example, instead of the report being generated when the tests are finished, the report is generated after the first test, and so on? I want to use ExtentReport to monitor the progress of my tests aswell and showing the results?

I've learnt its possible when using as a logger, as you can do a flush after each tests. However is it possible while using Extent as a Listener?

Thanks in advanced.

Kind regards,
Colin.

**Comment by anshooarora** [comment]
Yes.  What testrunner do you use?  TestNG?  JUnit?

**Comment by Cooliinnnn** [comment]
Hi @anshooarora I'm using TestNG.

Thank you.

**Comment by anshooarora** [comment]
The TestNG listener runs after all the tests have completed running.  If you want to output logs as soon as a test ends, then you would have to use the logger strategy as shown [here](http://extentreports.relevantcodes.com/java/#testng-example) with TestNG `afterMethod`.

**Comment by Cooliinnnn** [comment]
So it is not possible with the Listener?

Thanks @anshooarora

**Comment by anshooarora** [comment]
The listener example uses IReporter which will only run after all the tests have completed running.  TestNG has other listeners that you can use to achieve what you are doing - look at ITestListener interface.  The simplest would be implementing the `AfterMethod` annotation.

**Comment by Cooliinnnn** [comment]
I presume using the ITestListener I wouldn't be able to generate an ExtentReport?

Thanks Anshoo, much appreciated.
