### ISSUE TITLE
Test Steps and Tests

### ISSUE THREAD

**Issue by kandhavellk** [anshooarora/extentreports#506]
Hi Anshoo,

Is it possible to include several test steps within a single test case? I need to automate some 10 test steps and update its result to a single test case.

Thanks in advance.

**Comment by Cooliinnnn** [comment]
Do you mean for example have a test class that contains 10 tests and they are all just declared as one test in your test XML?

**Comment by kandhavellk** [comment]
@Cooliinnnn, I've a test class with 10 test steps. I need to update the status of test steps and test case separately.

Currently, i'm using extent.starttest() and extent.endtest() methods for all the 10 steps. So status of all the test steps are correctly updated in Test Steps and the problem is they are updated as 10 Tests also.

**Comment by Cooliinnnn** [comment]
@kandhavellk Have you tried using ExtentReport as a Listener also? http://www.ontestautomation.com/using-the-extentreports-testng-listener-in-selenium-page-object-tests/ 

You can use this to show all your results in the one test case.

If my understand of your question is correct?

Hope that helps.

**Comment by anshooarora** [comment]
With the listener, I doubt it will be as easy to log all the events that happen.  You would have to use Extent as a logger by putting logging in your classes, and then using the TestNG `afterMethod` to end tests.  [See here](http://extentreports.relevantcodes.com/java/#testng-example) for example.
