### ISSUE TITLE
Does extentreports connect to external server outside my organization?

### ISSUE THREAD

**Issue by Ashish1485** [anshooarora/extentreports#509]
Hi @anshooarora ,

Extentreports looks fantastic and I want to use it in my project. However my project is of a very secured nature, so I wanted to clarify a query. 
Does Extentreports connect to an external server outside my organization while creating report. Will 'NetworkMode' Offline or Online make any difference in this regard?

Thanks,
Ashish

**Comment by anshooarora** [comment]
It only connects to the github cdn to download resources if you are using ONLINE mode.  In OFFLINE mode, it stores everything locally, so nothing is downloaded.  But you have more files/bulk to manage.

**Comment by twarenius** [comment]
But OFFLINE mode is only available in Java version right? Any plans for making OFFLINE mode available in the .NET version?

**Comment by anshooarora** [comment]
v3 pre-release for Java will soon be available to download, which does not have offline mode.  If there is enough support, it will be added to the Java version followed by .NET.

**Comment by kenston** [comment]
@anshooarora I'm hoping to see Offline mode support in v2 being transitioned to v3. :)
