### ISSUE TITLE
How to upload screenshots to ExtentX

### ISSUE THREAD

**Issue by Fasiulla** [anshooarora/extentreports#513]
Hi All, Iam very new to ExtentX and was looking for a way to get the screenshots in ExtentX App. Could someone help on this.

**Comment by RatkoD** [comment]
I'm interested in this as well. I'm using the AppiumTestDistribuiton framework which is ExtentX ready, and generates ExtentReports with screenshots but the screenshots and server logs are not present in ExtentX.

**Comment by saikrishna321** [comment]
https://github.com/anshooarora/extentx/issues/9

@RatkoD @Fasiulla an other way is convert the image to base64 and attach it to the report, but i see there is an issue with base64 size of image.

https://github.com/anshooarora/extentreports/issues/512

**Comment by anshooarora** [comment]
You can also see this for reference:  http://stackoverflow.com/questions/10226046/java-convert-image-to-base64

Note:  the base64 string takes up space and can drastically increase the size of the static HTML file.  You won't notice any difference from ExtentX perspective though.

As Sai pointed out, there is an enhancement open for this already.
