### ISSUE TITLE
Can I use Extentreports with Espresso tool

### ISSUE THREAD

**Issue by nitinEd** [anshooarora/extentreports#515]
I am using extentreports for selenium and appium. I am using espresso for Android UI testing.Is it possible to use Extentreports for espresso as well? If it is possible,that would be great.

**Comment by anshooarora** [comment]
Looking at [this page](https://google.github.io/android-testing-support-library/docs/espresso/index.html), I would say yes.

PS.  Extent is Java/.NET and can be integrated with any tool as long as it uses the 2 programming environments.
