### ISSUE TITLE
Question:Emailable report

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#516]
Hi Anshoo,

Is there any plan to implement mailable report in the near future ?

Thanks

**Comment by email2vimalraj** [comment]
@jawlitkp : We have a feature to generate a single HTML file. Can't be emailed?

**Comment by anshooarora** [comment]
The email-able report addition will be part of version 3 (only java-8), and will be vanilla HTML (no charts etc) as not all clients support them.  

Closing as this is same as #51.
