### ISSUE TITLE
New feature request for Email-able report - User should be able to insert the Description message on the header and footer of the report

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#52]
UAC
--------
1.User should have option to insert the Header message of the report ,By default description message should be displayed . if user want to insert their own message then they should be able to insert and default message should be removed .

2.User should have option to insert the Footer message of the report ,By default footermessage should be displayed . if user want to insert their own message then they should be able to insert and default message should be removed .

**Comment by anshooarora** [comment]
Perwez, 

You can add a header message using:

```
extent.config().reportHeadline("Description message");
```

**Comment by perwez123** [comment]
I tried this and it worked fine , But is it possible to insert the fonts style , size and Color ?

**Comment by anshooarora** [comment]
Closing as duplicate of #51.
