### ISSUE TITLE
Question - Modifying HTML Class On Report Open Via JavaScript?

### ISSUE THREAD

**Issue by dustin-norman** [anshooarora/extentreports#520]
I am wanting to display the time totals at the top of the page when the report opens (Extent Reports 2.41.0). How would I change the class name of time-totals in javascript?

By default it looks like:
```
<div class="container">
   <div id="dashboard-view" class="row">
      <div class="time-totals hide">
```

I want it to look like:
```
<div class="container">
   <div id="dashboard-view" class="row">
      <div class="time-totals">
```

**Comment by dustin-norman** [comment]
I got the class name to change, but it still didn't display the times at the top. It messed up the report and now not everything is visible towards the bottom of the page and you can't scroll to see what's missing. I'm going to leave the code here, but it looks like it may be more trouble than it's worth to make happen.

```
    <!-- custom javascript -->
    <scripts>
      <![CDATA[
        $(document).ready(function() {
          $('#enableDashboard').click();
          document.getElementById(#dashboard-view > div.time-totals.hide).className = "time-totals";
        });
      ]]>
    </scripts>
```

**Comment by anshooarora** [comment]
You can do:

```
$('.time-totals').removeClass('hide');
```
