### ISSUE TITLE
How create link to testRunnerLog

### ISSUE THREAD

**Issue by Ramsescz** [anshooarora/extentreports#522]
Hi anshoo,

can you help me? can i make somehow link to testRunnerLog?
![extents](https://cloud.githubusercontent.com/assets/19989911/16143207/a10a6abc-346b-11e6-9a72-5f430080089a.png)

i  now use external link, but isn't what i need

`report.addSystemInfo("Release notes", "<a href='release_notes.txt'>Here</a>");`

version 2.41.0

**Comment by saikrishna321** [comment]
@Ramsescz yea u can ... 

extent.setTestRunnerOutput("<a href='release_notes.txt'>Here</a>");

**Comment by Ramsescz** [comment]
thx, but i need change link in page on screen. 

i need for word "Here" add hyperlink to testRunnerLog screen. After click on word "Here" there should open testRunnerLog screen

**Comment by anshooarora** [comment]
You can do this:

```
Click <a href='#' class='goto-testrunner-view'>here</a>
```

and in extent-config.xml, scripts:

```
$('.goto-testrunner-view').click(function() { 
    $('.testrunner-logs-view').click();
});
```
