### ISSUE TITLE
How to set the default theme of the report to be dark?

### ISSUE THREAD

**Issue by RatkoD** [anshooarora/extentreports#524]
I want to set the default theme to be dark instead of light. How to do that?

**Comment by Ramsescz** [comment]
@RatkoD hi, u can use extent-config.xml. you found him in *.zip with extentreports. Open him and change theme conf. to dark:
![dark](https://cloud.githubusercontent.com/assets/19989911/16175926/dacfa0f6-35ff-11e6-96ca-7ba538d21e17.png)

after change just use this code in class. this code loading extent-config.xml
`report.loadConfig(new File("path"));`

path = i:\\Automatization\\Config\\extent-config.xml - this is file path for me

**Comment by Novatu** [comment]
i am getting a syntax error in the above line.

I used like the below

  extent.loadConfig(new File("E:\\Project\\jar\\Selenium\\extentreports-java-2.41.2\\extent-config.xml"));

error Message is 

Syntax error on token ".", @ expected after this token
	- Syntax error, insert "SimpleName" to complete 
	 QualifiedName
	- Syntax error, insert "Identifier (" to complete 
	 MethodHeaderName
	- Syntax error, insert ")" to complete MethodDeclaration

i tried with the above suggestions but it  never get resolved ..could you please anyone help me .
