### ISSUE TITLE
Scroll bar is not working for failure test cases 

### ISSUE THREAD

**Issue by amit89** [anshooarora/extentreports#527]
When we put a filter sjows only failure test cases or passed test cases scroll bar is not working in this case we have to zoom out to see the rest of the test cases present at the bottom of the page
![extend_report](https://cloud.githubusercontent.com/assets/8666277/16221879/c6c70824-37b2-11e6-9f05-277a489eb910.jpg)

**Comment by anshooarora** [comment]
Please update to version 2.41.0.  This issue was fixed in the latest.
