### ISSUE TITLE
Not getting + option to expand/collapse while using child parent relationship in extent reports

### ISSUE THREAD

**Issue by GayathriB1010** [anshooarora/extentreports#528]
Hi,

I am using selenium extent reports in my project . I implement child parent concept. I am getting nodes and status as pass/fail. While clicking the pass/ fail its expanding. I want to get + symbol to say its an expand option. How do I do that.
child1 = extent.startTest(strORName);
Parent.appendChild(child1);
This is the code I am using.

**Comment by anshooarora** [comment]
What is the question?  You want a + symbol for?

**Comment by GayathriB1010** [comment]
Hi,

I want a + symbol to show that, there is an expand/ collapse option
available.

Regards,
Gayathri

**Comment by anshooarora** [comment]
Gayathri -  This feature would be a custom implementation and you can do that using JavaScript which can be inserted in the scripts tag of config.xml.  You can see the configuration section for more info.
