### ISSUE TITLE
Getting Unknown in Extent Reports

### ISSUE THREAD

**Issue by puneetbohra** [anshooarora/extentreports#529]
After successfull execution of test scripts Extent report is showing "Unknown" instead of "PASS" or "FAIL".

**Comment by Ashish1485** [comment]
Probably you forgot to end the test.

**Comment by anshooarora** [comment]
This generally happens when you forget to call endTest for each test, or, close after all the tests have executed.

**Comment by SXSAURYA** [comment]
i am calling the end test using @AfterMethod in testng,then also its added it as unknown test case name

**Comment by gunaphysics** [comment]
I face the same issue when I use invocationCount in my @Test annotation. I am calling endTest() in my @AfterMethod annotation. 
![image](https://cloud.githubusercontent.com/assets/19418360/25346678/3ec9238c-28e6-11e7-84c1-51ec3592e19c.png)

**Comment by amolnawale123** [comment]
Hi Anshoo,

I am also facing similar issue where my eclipse shows that the test has passed but the extent report shows the status as Unknown.
I am using endTest and Flush in the @AfterMethod as below:
@AfterClass(alwaysRun=true)
	public void endTest() {
		extent.endTest(test);
		extent.flush();
	}
I am using Extent Report version 2.41.2
Below is the screenshot of the report that I am getting.
![image](https://user-images.githubusercontent.com/30489953/28657107-16803a56-72c3-11e7-927d-40694f9d2490.png)

**Comment by amolnawale123** [comment]
To add to the above details, I am running the below testng.xml file:
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Functional Tests">
<test name="functionalTest1" parallel="classes" thread-count="3" >
  <classes>
   <class name="package.ClassFile1" />
   <class name="package.ClassFile2" />
   <class name="package.ClassFile3" />   
  </classes>
</test>  
<test name="Send Automation Report Email">
  <classes>
   <class name="com.sap.pc365.util.SendEmailReport" />
  </classes>
</test>
</suite>

I am running the classes in parallel with the thread-count as 3.﻿

**Comment by vedika2609** [comment]
I am also facing the same problem, did anyone figure out the problem

**Comment by AliagaMusayev** [comment]
I am also facing with the same problem. Is there any solution for this problem?

**Comment by AliagaMusayev** [comment]
It happens when tests running parallelly(multhithreading). "main" thread also tries to create report, but it creates with unknown status. I think we have to avoid this situation.
