### ISSUE TITLE
[Question]:How to link test case  

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#533]
Hi Anshoo,

I am generating below html email report , is there any way i can display test case as link and it should be linked to test case under extent report?

![image](https://cloud.githubusercontent.com/assets/9873362/16415034/2cdad6f8-3d09-11e6-82a1-ab7f7d7a866e.png)

Thanks

**Comment by anshooarora** [comment]
This will not be possible..

**Comment by jawlitkp** [comment]
Hi Anshoo,

So i was trying to achieve this using js but in order to navigate at specific location on page i need id or name attributes ,in extent report you are using extent-id and using it i am not able to navigate ,could you please help
