### ISSUE TITLE
Extent Report Test Title

### ISSUE THREAD

**Issue by Aswilli4** [anshooarora/extentreports#534]
@anshooarora I want to call my test.Logs at the Page Object class level so I Begin the test instance  in the baseclass at the setup level  (Here is the Setup method in my base class)

    public void Setup()
           {
                CallWebDriver();
                ExtentTestInstance();
               CallURL();

           }

where ExtentTestInstance() contains this 

     public void ExtentTestInstance()
        {
            extent = new ExtentReports(getFPATHRegression(), false);
            test = extent.StartTest("title of test");
        }

This worked but now how can I reference a different test name at the Test Class Level for each .StartTest?

**Comment by anshooarora** [comment]
What test-runner are you using?  NUnit?

**Comment by Aswilli4** [comment]
I was able to resolve thank you!
