### ISSUE TITLE
Issue:Broken report in IE11

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports#535]
Hi Anshoo,

Report is broken in IE11 ,Extent version 2.41.0.

[2016-06-29_14-54-14.pdf](https://github.com/anshooarora/extentreports/files/339970/2016-06-29_14-54-14.pdf)

**Comment by anshooarora** [comment]
This is mostly due to ActiveX settings in IE.  Once you disable them completely or allow the scripts to run on file open, the report should display fine.
