### ISSUE TITLE
New feature request - User should have the option to add the Product Logo into extent report 

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#54]
UAC
------------
1. User should have the option to add the Product Logo into extent report 
2.The product logo should display on left top or right , as already one button exist on the left top .

**Comment by anshooarora** [comment]
To add a report name, you can do this:

```
extent.config().reportName("<img src='pathToImg.png' />");
```

**Comment by perwez123** [comment]
Thanks you so much for replying , I will try this.

**Comment by CharlieThach** [comment]
If that does not work for you use this: 
extend.config().reportHeadline(("<img src='pathToImg.png' />");

**Comment by perwez123** [comment]
What should be the correct Dimension of the image which can fit into correct position ???

**Comment by perwez123** [comment]
Does not display the image into extent report when image url is provided . But it works when the image is available in local system . Off course I have the internet access while viewing the report .

**Comment by perwez123** [comment]
This code does not display the Image in the report 

extent.config().reportName("<img src='pathToImg.png' />");

**Comment by anshooarora** [comment]
Perwez

If you can email me the IMG or link, I can provide you the CSS to align it correctly.  I can provide some sample styles but they may not work 100% without modifications.

**Comment by anshooarora** [comment]
Perwez,  here you go:

```
String css = ".report-name { padding-left: 10px; } .report-name > img { float: left;height: 90%;margin-left: 30px;margin-top: 2px;width: auto; }";

extent.config()
    .reportName("<img src='pathToImg.png' />")
    .insertCustomStyles(css);
```

**Comment by anshooarora** [comment]
Note: if you are using image as a healine as Charlie suggested above, the CSS will change slightly..

**Comment by perwez123** [comment]
Anshoo,

It does not display the image after using above code , It looks like it does not append the image path properly in html file and it is unable to load also it shows some unwanted span tag . 

Also appearing the text as [Report Headline] in the report

I used the following code 
-------------------------------
String css = ".report-name { padding-left: 10px; } .report-name > img { float: left;height: 90%;margin-left: 30px;margin-top: 2px;width: auto; }";

        extent.config()
            .reportName("<img src='http://testiap.globalenglish.com/adminpage/images/iap_logo.png' />")
            .insertCustomStyles(css);

I have copied the code from html and shown below , please have look .
-----------------------------------
<span class="report-name">
<img report-headline'="" src="http://te</span> <span class=">
[Report Headline]
</span>
