### ISSUE TITLE
How to add Link on extent report.

### ISSUE THREAD

**Issue by pavankumar9** [anshooarora/extentreports#540]
Hi Anshoo,

I am trying to link some reports on extent report. Like below using log method:
<a href="http://report.go.com/report" target="_blank" ></a>

However I am not able to attach the link. Its just displaying blue color but on mouse over I am not able to click it. Is there any option please let me know.

**Comment by anshooarora** [comment]
How are you doing it currently?

**Comment by pavankumar9** [comment]
Adding anchor tag as below:

ExtentReportManager.getExtentTestInstance().log(LogStatus.INFO,"API Log Link : <a =\""+jobLink+"/"+String.format(logCatFilePath, tcId)+"\" target=\"_blank\" > API LINK </a>");

**Comment by pavankumar9** [comment]
ExtentReportManager.getExtentTestInstance().log(LogStatus.INFO,"API Log Link : <a =\""+jobLink+"/"+String.format(logCatFilePath, tcId)+"\" target=\"_blank\" > API LINK </a>");

**Comment by pavankumar9** [comment]
ExtentReportManager.getExtentTestInstance().log(LogStatus.INFO,"API Log Link : <a"+""+jobLink+String.format(logCatFilePath, tcId)+"\" target="_blank" > API LINK </a>");

**Comment by anshooarora** [comment]
I don't see a link in your log.  You can do the following:

```
ExtentReportManager.getExtentTestInstance().log(LogStatus.INFO,"API Log Link : <a href='http://github.com'>API LINK</a>");

```

**Comment by pavankumar9** [comment]
yes i am linking the same way but in git I am not able to paste.

**Comment by bala-singamreddy** [comment]
HI.. How can i give the link to the local file path ?
Could you please let me know??
