### ISSUE TITLE
Extent Report HTML: Is there a way to default the report to the Dark Theme Toggle

### ISSUE THREAD

**Issue by Aswilli4** [anshooarora/extentreports#541]
@anshooarora  Thank you for the great report! I love how you can toggle it to a Dark Theme.
Is there a way to Default to Dark without having to select it every time?

Thanks

**Comment by saikrishna321** [comment]
@Aswilli4 create a extent.xml and load that file 

https://github.com/anshooarora/extentreports/blob/7b54b7dc55b2f0ad3b7f3fe2e3e394ab174209da/java/extentreports/src/main/resources/com/relevantcodes/extentreports/resources/extent-config.xml#L6

change this line to dark for loading dark theme by default

**Comment by Aswilli4** [comment]
@saikrishna321    Can you elaborate on loading the xml file. I created the xml file and added the updated code for the dark theme but not sure how to call the xml file, if possible could you show with a code example? Thanks

**Comment by saikrishna321** [comment]
@Aswilli4 https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/report/factory/ExtentTestManager.java#L65

**Comment by anshooarora** [comment]
@Aswilli4 - if I remember correctly, you are using the .NET dll.  See here:  http://extentreports.relevantcodes.com/net/#configuration

```
<?xml version="1.0" encoding="UTF-8"?>
<extentreports>
  <configuration>
    <!-- report theme -->
    <!-- standard, dark -->
    <theme>standard</theme>
```

I just realized that the config section is not updated for .NET.  I will do it tonight, but the above will allow you to default to dark theme on load.
