### ISSUE TITLE
Major considerable issues under log section (ExtentReports Version 2.41.1)

### ISSUE THREAD

**Issue by JaspalAujla** [anshooarora/extentreports#543]
I am writing this description to share that I am facing some major issues under log section (refer below image to see methods under it) while implementing ExtentReports (version 2.41.1) in my test automation framework:
![extentlog](https://cloud.githubusercontent.com/assets/17103120/16705894/e262d214-45ec-11e6-91bc-9ba9965d0f11.png)

Before start explanation of issues, I would like to suggest that if ExtentReports team can manage log section and parameters under it like below that will be awesome:
**log(LogStatus logStatus, String stepDetails): void – ExtentTest
log(LogStatus logStatus, String stepDetails, Throwable t): void – ExtentTest
log(LogStatus logStatus, String stepDetails, String screenCapture): void – ExtentTest
log(LogStatus logStatus, String stepDetails, String screenCapture, Throwable t): void – ExtentTest**

_Explanation of issues_
In first test case I passed only one parameter i.e. String details. The report displayed with DETAILS column, refer below screenshot:
![extentlog1](https://cloud.githubusercontent.com/assets/17103120/16705895/ed1a0d44-45ec-11e6-92ce-79fcc35b776f.png)
Now, in second test case, due to my test case failed, I added a screenshot as well. This time column name has been changed from DETAILS to STEPNAME and added screenshot start displaying under DETAILS column:
![extentlog2](https://cloud.githubusercontent.com/assets/17103120/16705898/ffa9a578-45ec-11e6-9ebc-db284f97bf19.png)

Now, if I added multiple steps under one test case then what happen, check screenshot below:
![extentlog3](https://cloud.githubusercontent.com/assets/17103120/16705900/0b679a50-45ed-11e6-8fc1-0f54997a11c2.png)
The another issue is that if my test step got failed then I need to add screenshot and exception detail at a same time, but in ExtentReports, we can add only screenshot or print only exception in a step.

_How these issues will be resolved_
**log(LogStatus logStatus, String stepDetails): void – ExtentTest
log(LogStatus logStatus, String stepDetails, Throwable t): void – ExtentTest
log(LogStatus logStatus, String stepDetails, String screenCapture): void – ExtentTest
log(LogStatus logStatus, String stepDetails, String screenCapture, Throwable t): void – ExtentTest**

If we manage log related methods and parameters like above then what will happen:
**String stepDetails**: Here user can pass step name or step details whatever he/she wants as per his/her need. (Now, conflicts between stepName and details will no more exist)
**String screenCapture**: Here user can pass “addScreenCapture(imagePath)” or “addScreencast(screencastPath)” or “addBase64ScreenShot(base64)” as per his/her need. (If user does not add any screenshot then the space under screenCapture column will be blank for that particular step).
**Throwable t**: Here user can print exception on the result report (If user does not add any exception then the space under exception column will be blank for that particular step).

(Then, the report will reflect like below)
![extentlog4](https://cloud.githubusercontent.com/assets/17103120/16706046/221ccc34-45f2-11e6-8dc9-a61372150253.png)
Here,
If in a test case only stepDetails exists then ScreenCapture/Screencast and Exception columns will not displayed under that particular test case 
If in a test case only stepDetails and ScreenCapture/Screencast exist then Exception column will not displayed under that particular test case
If in a test case only stepDetails and Exception exist then ScreenCapture/Screencast column will not displayed under that particular test case

**Suggestion regarding print exception:**
Exception details should also reflect same like a ScreenCapture, while clicking on it all exception detail should pop up. Presently, whenever we print exception on result report it takes much space. It seems not good when non-technical person (management, Client, etc.) will see the report, even they don’t like to see exception details like this. (As technical persons (developers) we know that what is the importance of printing exception details on the result report. So, if ExtentReport team can manage it like, while clicking, the exception detail will pop up that will be really awesome).

I hope ExtentReports team will take care of these limitations and update it as soon as possible, and we can continue with this amazing result report solution. 

Thanks
Jaspal Singh Aujla
Email: jsaujla1@gmail.com
Linkedin: https://nz.linkedin.com/in/jaspalsinghaujla

**Comment by anshooarora** [comment]
The existing behavior allows you to add exceptions + screenshots + details in a single log.  Since the result is an HTML file, you can easily distinguish between different items.  Example:

<table>
	<tr>
		<th>Timestamp</th>
		<th>Status</th>
		<th>Details</th>
	</tr>
	<tr>
		<td>nnn</td>
		<td>Info</td>
		<td>
			Expected: Browser should launch
			Actual: Browser launched successfully
		</td>
	</tr>
	<tr>
		<td>nnn</td>
		<td>Info</td>
		<td>
			Expected
<pre>Browser should launch</pre>
			Actual
<pre>Browser launched successfully</pre>
			Screenshot:
			<img src='https://cloud.githubusercontent.com/assets/17103120/16705900/0b679a50-45ed-11e6-8fc1-0f54997a11c2.png'>
		</td>
	</tr>
</table>

In the next version (3.0), the log signatures are going to change:

```
log(Status, details);
log(Status, Throwable);

pass(details);
pass(Throwable);

fail(details);
fail(Throwable);
...
```

The snapshot section will be at the test level instead of log, and all snapshots will be aligned and I will try to make it into a gallery so you can click previous/next to navigate snapshots.
