### ISSUE TITLE
NPE calling ExtentReports.close() where no tests were executed

### ISSUE THREAD

**Issue by elijahkorneckis** [anshooarora/extentreports#554]
Hello!

As the issue title says I'm getting NPEs when trying to close ExtentReports without logging any test cases.

I was able to reproduce this with a simple test:
```groovy
import com.relevantcodes.extentreports.ExtentReports
import spock.lang.Specification

class TmpSpec extends Specification {
    def "throws NPE when no tests ran"() {
        when:
            ExtentReports reports = new ExtentReports("test")
            reports.close()
        then:
            thrown(NullPointerException)
    }
}
```

And the stacktrace is this:
```
java.lang.NullPointerException
	at com.relevantcodes.extentreports.Report.terminate(Report.java:417)
	at com.relevantcodes.extentreports.ExtentReports.close(ExtentReports.java:920)
```
I initially wanted to register ExtentReports as a Spring bean, but that calls .close() when the ApplicationContext is shutting down - causing NPEs from time to time.

Maybe this is a wrong approach I'm taking?  But in any case, thank you for your hard work!

edit: Forgot to add - I'm using version 2.41.1

**Comment by anshooarora** [comment]
This was included in a recent PR:  #537, #538.   

You can either use the latest github build or handle the exception (no report will be created in which case).
