### ISSUE TITLE
How to report passing soft asserts into reports

### ISSUE THREAD

**Issue by ankitvaish04** [anshooarora/extentreports#555]
Hi Anshoo, first of all many thanks for creating such awesome reports,  I have been using them for quite a while. I have a question.
I'm currently using soft asserts in all my test methods, and inside the @AfterMethod I'm doing a softassert.assertAll() which is called every time a testmethod ends. The failed asserts are getting reported into the reports but the passed ones are not. How can I get the passed ones reported as well?

**Comment by anshooarora** [comment]
Ankit,  this is more of a TestNG question which I am not very sure of and I am thinking this may not be possible unless you override the softassert with your own implementation.  You can check stackoverflow or the testng group to know more.
