### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: VERSION_2_3_23 at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:76)

### ISSUE THREAD

**Issue by SHASHIJB** [anshooarora/extentreports#556]
HI Anshoo,

Getting the following NoSuchFieldError for Exception in thread "main" java.lang.NoSuchFieldError: VERSION_2_3_23
        at com.relevantcodes.extentreports.HTMLReporter.start(HTMLReporter.java:76)
        at com.relevantcodes.extentreports.Report.attach(Report.java:314)
        at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:85)
        at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:374)
        at web.mobile.test.DriverScript.start(DriverScript.java:106)
        at main.Intial.main(Intial.java:73)

Currently i m using this project in my gradle project 
compile 'com.relevantcodes:extentreports:2.40.2'.

I am using Gradle as build tool. Please help me to resolve the issue.

Currently i have implemented my project using Hybrid Frawework ( data-driven + keyword driven) .

**Comment by SHASHIJB** [comment]
/*

 

// Apply the java plugin to add support for Java


apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'maven'
apply plugin: 'application'

mainClassName = 'main.Intial'

// In this section you declare where to find the dependencies of your project
repositories {
    // Use 'jcenter' for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    flatDir {
        dirs 'libs'
    }
    //jcenter()
    mavenCentral()
    //mavenLocal()


}

// In this section you declare the dependencies for your production and test code
dependencies {

    // -- Exteranl method to include jar from library path
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.apache.james:apache-mime4j:0.6.1'
    //compile 'bsh:bsh:1.3.0'
    compile 'org.beanshell:bsh:1.3.0'

    // https://mvnrepository.com/artifact/cglib/cglib-nodep
    compile 'cglib:cglib-nodep:2.2'
    // https://mvnrepository.com/artifact/org.apache.commons/commons-exec
    compile 'org.apache.commons:commons-exec:1.3'
    // https://mvnrepository.com/artifact/commons-io/commons-io
    compile 'commons-io:commons-io:2.4'
    // https://mvnrepository.com/artifact/commons-jxpath/commons-jxpath
    compile 'commons-jxpath:commons-jxpath:1.3'
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'commons-logging:commons-logging:1.1.3'
    compile 'dom4j:dom4j:1.5'
    compile 'com.relevantcodes:extentreports:2.10'
    compile 'com.relevantcodes:extentreports:2.41.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.google.guava:guava:18.0'
    compile 'org.hamcrest:hamcrest-core:1.3'
    compile 'org.hamcrest:hamcrest-library:1.3'
    compile 'net.sourceforge.htmlunit:htmlunit:2.15'
    compile 'net.sourceforge.htmlunit:htmlunit-core-js:2.15'
    compile 'org.apache.httpcomponents:httpclient:4.3.6'
    compile 'org.apache.httpcomponents:httpcore:4.3.3'
    compile 'org.apache.httpcomponents:httpmime:4.3.6'
    compile 'org.ini4j:ini4j:0.5.2'
    compile 'io.appium:java-client:2.1.0'
    compile 'io.appium:java-client:3.1.0'
    compile 'com.beust:jcommander:1.29'
    compile 'org.eclipse.jetty:jetty-websocket:8.1.8.v20121106'
    compile 'net.java.dev.jna:jna:3.4.0'
    compile 'net.java.dev.jna:jna-platform:4.2.0'
    //compile 'junit:junit-dep:4.11'
    compile 'log4j:log4j:1.2.17'
    compile 'com.sun.mail:javax.mail:1.5.1'
    compile 'mysql:mysql-connector-java:5.1.20'
    compile 'net.sourceforge.nekohtml:nekohtml:1.9.22'
    compile 'io.netty:netty:3.5.7.Final'
    compile 'com.opera:operadriver:1.5'
    compile 'com.codeborne:phantomjsdriver:1.2.1'
    compile 'org.apache.poi:poi:3.7'
    compile 'org.apache.poi:poi-ooxml:3.7'
    compile 'org.apache.poi:poi-ooxml-schemas:3.7'
    compile 'com.google.protobuf:protobuf-java:2.4.1'
    compile 'com.jayway.android.robotium:robotium-solo:4.3.1'
    compile 'milyn:sac:1.3'
    compile 'org.seleniumhq.selenium:selenium-java:2.45.0'
    compile 'org.seleniumhq.selenium:selenium-java:2.45.0-srcs'
    compile 'org.seleniumhq.selenium:selenium-server:2.48.2'
    compile 'xalan:serializer:2.7.1'
    compile 'org.xerial:sqlite-jdbc:3.8.11.1'
    compile 'org.sikuli:sikuli-api:1.2.0'
    //Added
    compile 'com.sikulix:sikulixapi:1.1.0'
    compile 'org.testng:testng:6.8.5'
    compile 'xalan:xalan:2.7.1'
    compile 'xerces:xercesImpl:2.11.0'
    //Added
    //compile 'xml-apis:xml-apis:1.0.b2'
    compile 'xml-apis:xml-apis:2.0.2'
    compile 'org.apache.xmlbeans:xmlbeans:2.3.0'
    //Flash
    compile 'org.seleniumhq.selenium:selenium:2.0rc2'
    //compile 'com.googlecode.javacpp:javacpp:0.7'
    //compile 'com.google.android:android:4.1.1.4'
    //compile 'com.google.android:support-v4:r7'
    compile 'commons-collections:commons-collections:3.2.1'
   
    compile 'junit:junit:4.10'

}

jar {
    baseName = 'gs-gradle'
    version =  '0.1.0'
}
task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

**Comment by SHASHIJB** [comment]
unable to reproduce it

**Comment by velanbabu** [comment]
Hi Anshoo,

Same issue occurred. Please let me know how to resolve the same.

Regards
Vadivelan
