### ISSUE TITLE
System info view - It does not display the information of all the testing environment in the extent report

### ISSUE THREAD

**Issue by perwez123** [anshooarora/extentreports#56]
All Testing environment detail does not display in the System info view in the report . As of now it display only one environment details .

For example -

My Test script was run in the following environment parallaly .
Win 7- IE 11 , Chrome , FF
MAC_ Chrome , Safari 

But in the system info view display only one environment information .

**Comment by anshooarora** [comment]
Only default system info is provided by the report. For all other info required by your testing env, you can call <code>addSystemInfo</code> to add.

```
extent.addSystemInfo("Selenium Version", "2.46");
```

See here for more info: http://extentreports.relevantcodes.com/2x/docs.html#add-system-info

**Comment by perwez123** [comment]
Thank you so much for reply , I will try this .

**Comment by perwez123** [comment]
Is it possible to insert the image instead of text ?

**Comment by anshooarora** [comment]
Yes.  Just have to insert HTML where required:

```
extent.addSystemInfo("VarName", "<img src='pathToImg.PNG' />");
```
