### ISSUE TITLE
How to add HTML table to report

### ISSUE THREAD

**Issue by ssirekumar** [anshooarora/extentreports#58]
I need to add one table to report. i am using this reports to my device automation so i have a requirement like to add the device information to report with some parameters(deviceName, deviId, deviceVertion ... etc so on). So to do this i want to add this at the place like the present existing one Tests View, Steps View.

**Comment by anshooarora** [comment]
This is certainly possible.  What version aew you using?  .NET or Java?

**Comment by ssirekumar** [comment]
Java 2.0

**Comment by anshooarora** [comment]
Can you add it as System Info?  Example here:  http://extentreports.relevantcodes.com/2x/docs.html#add-system-info

If it is to be added as table, you can add it as a log event:

```
test.log(LogStatus.INFO, "<table><tr><th>DeviceName</th></tr><tr><td>OnePlus</td></tr></table");
```

**Comment by ssirekumar** [comment]
As per my requirement i want to add in a start page(where we have graphs for test case pass of fail list). From your suggestion i can able to add but i try to add this at main window at the time of report generation or in any configuration.

**Comment by anshooarora** [comment]
For such customization, I would recommend downloading and changing the source directly or using js.  It will not be possible by standard extent methods.

**Comment by ssirekumar** [comment]
ok its pretty good but in which file i have to modify for this in source.

**Comment by anshooarora** [comment]
This one: https://github.com/anshooarora/extentreports/blob/master/java/2.x/src/com/relevantcodes/extentreports/source/STANDARD.min.html

But I would recommend doing as much as possible using CSS and js because these files may change quite drastically each release and it would make it very difficult for you to modify them.
