### ISSUE TITLE
New feature Request - Adding expand all and collapse all reports

### ISSUE THREAD

**Issue by ssirekumar** [anshooarora/extentreports#59]
If you add feature like expand all and collapse all in reports would be good one. This is mainly useful for expand all at once or if expanded reports be collapsed.

**Comment by anshooarora** [comment]
What version are you using?  This functionality is available by default in v2.04 Java.

**Comment by ssirekumar** [comment]
I am using 2.0 with java As per your comments i have to check in 2.04 version. Thanks you for updates. I will verify and let know.

**Comment by anshooarora** [comment]
Closing issue as feature was included in v2.04.
