### ISSUE TITLE
ExtentReports using TestNG Listener - Test Status are not logged correctly in Reports/Quick Test Summary. 

### ISSUE THREAD

**Issue by vishwathma** [anshooarora/extentreports#60]
Suddenly the test status are not logged correctly. If there are 3 test cases, once the tests are run & if 2 are fail, 1 is pass & 0 is skipped. In the reports - Quick Test Summary, the status is logged for only  Pass & Fail & not for Skipped. Actually the status goes missing in the header itself. Am using the same code as it is in http://relevantcodes.com/testng-listener-using-extentreports/ . Please rectify.
![issue](https://cloud.githubusercontent.com/assets/13534392/9298322/82f6dae2-44ca-11e5-9e21-26ecfc812eef.jpg)

**Comment by vishwathma** [comment]
This the same with even Pass & Fail status. They are not logged if the results doesn't have tests with results Pass or Fail. Am using version # 2.04.

**Comment by anshooarora** [comment]
Vishi

This is expected in v2.04 in response to #45.  Only the headers with at least 1 log event will show.

**Comment by anshooarora** [comment]
Vishi

The upcoming version will have Pass, Fail and Skip enabled by default.  The other status will be displayed on an as-needed basis automatically.

**Comment by anshooarora** [comment]
Closing this ticket as the quick-summar section has been removed from 2.10.
