### ISSUE TITLE
We need synchronization on methods which modify testList in ExtentReports class

### ISSUE THREAD

**Issue by virenv** [anshooarora/extentreports#61]
Anshoo,

You have mentioned this http://extentreports.relevantcodes.com/2x/docs.html#parallel-classes as a solution for making same extent report instance available for different threads. Basically a singleton pattern for other classes. This is a very good way to generate a single report from multiple threads. 

However as its the same instance of ExtentReports class we will get synchronization issues when we will try to modify/create/alter the testList in ExtentReports class. This is because at the same time multiple thread can fight for access to methods like startTest, endTest, close and flush. All these method alter a simple java.util.list testList which is not thread safe, we will get into unpredicable state at times.

Solution: Either use a thread safe list (java.util.concurrent)
or make these methods synchronized. I am sending a pull request. It gives the idea, I have quickly done it because of lack of time. Feel free to accept or reject.

Thanks
Virender

**Comment by anshooarora** [comment]
Viren,  this is a great catch.  I have merged the pull request.  I like the idea of making the methods synchronized because its easier to handle the methods and not worry about what variables they consume.  

Closing this issue as merge request is complete.
