### ISSUE TITLE
Micro / Minor (spelling) correction

### ISSUE THREAD

**Issue by BeyMelamed** [anshooarora/extentreports#63]
When no images or media has been included and one clicks the view option icon (top left corner of the page) and selects either Images View or Media View, the message is "No media was embed for the tests in this report."
It should be "No media was embedded for the tests in this report." or something of the sort...

Thanks,  This is a gem of a project!

**Comment by anshooarora** [comment]
Bey - thank you.  This will be fixed in the upcoming release.
