### ISSUE TITLE
Test View is showing incorrect result for Parent View 

### ISSUE THREAD

**Issue by AmitRai22** [anshooarora/extentreports#68]
Hi Anshu,

Thanks for providing such a nice reporting framework .

Actually my automation project includes Selenium and JBehave(BDD) and I have implemented 
Extent 2.04   in my automation project (Selenium + Jbehave ).
Will it be  possible for  you add the information(Graph ,status ) for  all  Parent test cases?
Since  I am facing a problem with report .
Eg.There are  4  Parent Test cases  each has 0 or more child

So  I want ,
Total  Test case = {All Parent Test cases That is 4};
eg. 
Test 1- PASS
 Test 2-FAIL
 Test 3-FAIL
 •Child 3.1-PASS
 •Child 3.2-FAIL
Test 4 -PASS
•Child 4.1-PASS

So, the graph should read as:
TEST VIEW: TOTAL: 4(ALL TESTS), PASS=2, FAIL=2

The above equation counts for Jbehave(BDD).

Because in JBehave,
There are Scenarios and each scenarios has step(s).
and I am treating Scenario(Testcase) as Parent  and  Step(Test step) as  Child 
So at the end ,
I want the information (Graph ,status etc)  of all the Scenarios executed(in this case Parent).

Could you please add  the graph and information for Parent test cases or can you change 
the first graph of Dashboardview  to the graph to show  information of all the Parent test cases?(if possible)

Thank you

**Comment by anshooarora** [comment]
Amit, if you use version 2.05, it has the revised way of counting tests.  Here is how the counting will work now:

All tests without child nodes - counted as 1
All child nodes - counted as 1
All top-most parent nodes with child(ren) - counted as 0

So if you have the following structure

```
Test 1
Test 2
Test 3
  - Child 1
  - Child 2
Test 4 
  - Child 3
```

Total Count = 5 tests (Test 1, Test 2, Child 1, Child 2, Child 3)

Example 2:

```
Test 1
  - Child 1
     - Child 1.1
  - Child 2
Test 2
Test 3
Test 4
  - Child 3
```

Total Count = 6 tests (Child 1, Child 1.1, Child 2, Test 2, Test 3, Child 3).

is this the behavior you are expecting?

**Comment by AmitRai22** [comment]
Hi Anshu ,
Thanks for quick reply!
Yes, I  have  already seen extent 2.05 .

I can see there are two information ( count ,status,graph  )section.
So I want the behaviour  like First graph should represent info for Test-Group(Parent Test cases having  0 or more child )only
and Other graph should represent info for total original 'Tests' have been executed(Parent test case having ZERO child + all child nodes)
Example : 


I am refering your example -2 in above comment : 
it should be like 

for Parent view it should be like 
Total count (Parent view )=(Test 1 ,Test2 ,Test3,Test4)=4(Test Groups)
that is it.

and another graph should represent ,
total steps have been perfromed and it will be like below 

Total steps (step view )= (Child1,Child1.1,Child2,Test2,Test3,Child3)=6
So in Step View We will count all the Child tests  as well as the Parent test cases that have ZERO child.


So  in Extent 2.05
STEP View  is ok  
but 
TEST View That should Count  the TEST-Groups(Parent Test cases having ZERO or more Child)only
is not there.
TEST View Should not count Child Test Cases(Test Steps)because Test steps are being counted in 
STEP View already.


So my request if it will be possible to make the Test View Graph to count only Test Groups(Parent Test cases having ZERO or more child).

Am I making any sense? 
If you need more clarification please let me know

**Comment by shabnamsardar** [comment]
Hi Anshoo,

I am also facing the same issue as AmitRai22.

In my current project, we are using BDD(JBehave) and integrating it with ExtentReoprts. But I am facing problem with Parent-Child graph view.

Childs should not be shown/counted under TestView, rather the Testcase(i.e. Parent with 0 child) / Parent(having more than 1 child)  should be counted as result.
Test View : should contain Testcase - that is it can be considered as a Parent (having 0 child or more child)

Step View : No need to change anything, as on version 2.05.

Kindly fix it asap.

Thanks:)
Shabnam Sardar

**Comment by anshooarora** [comment]
Guys, there is nothing to fix because you are asking to count tests as steps. Each node will be counted as a test.  Each log will be counted as a step.  Do not confuse a node as a step.  What you are asking is too specific and the only way you will have this behavior is changing the counting logic to meet your needs, or not using child nodes at all.  If steps are required, just use a log with label:

```
test.log(LogStatus.PASS, "<span class='label pass'>GIVEN</span> Details");
test.log(LogStatus.SKIP, "<span class='label skip'>WHEN</span> Details");
```

Version 2.10 will have support for bdd and for this ticket, have a module to allow selecting what will be counted but there is no ETA for that release.

**Comment by karthikbhatnagar** [comment]
Anshoo, we are also using Cucumber and would like this feature.  It would be nice to have choice tov select the counting logic as you said.  Actually we want to use child tests to count steps in scenario.  Because each node can have more steps but node must be counted as step only. 

This is specifuc for bdd/TDD though as you said by nice to have feature

**Comment by AmitRai22** [comment]
Hi Anshoo,
If there  are 2 views(test view and step view ) already so can we have a view which will provide the info about parent test cases only??

So I am just asking there should be a view which can provide the info about Parent test cases only

Parent test cases can have 0 or more child...

and I am not asking to count step as a test in this view  instead I am asking dont count step as a test 
in this view .

I am asking to count one parent test case as one test case.

ONLY parent test case count/status  I want.
That's it.


Thanks

**Comment by karthikbhatnagar** [comment]
Amit
Some users treat class as parent and all methods as child  test so our req is different.
Currently, a child test that you add using appendchild method counted as test. 
All logs counted as step.
Our req is to count child tests/nodes as 0 tests and only count parent as 1.

In Anshoos example above, child tests are getting count but not parent because methods under class are test. 
 Our case, we ignore child test because bdd everything under scenario is step.  
So the counting logic should support first case as now and also case for bdd users.
So the counting logic can have selection control as Anshoo mentioned. So we can select what meet our needs.

Anshoo- question, how easy is to inpletemt this feature?

**Comment by AmitRai22** [comment]
Yes Karthik , 
I just need Extent to count calling of log() method which is called by Parent  (sort of logic )only in this feature.
I am stuck here rest  all I have integrated  in my BDD project(all scenarios and steps ) with extent 2.05, only  count and status is not correct.

I

**Comment by karthikbhatnagar** [comment]
Why don't you change source now and export jar.  I did this:

Go to src.com.relevantcodes.extentreports.source
Open standard.min.HTML
In testsetchart function
Replace this ".test.displayed .test-node.pass, " with ".test.displayed.pass" 
Do same for all status
It will not count nodes as test

I copied code from older source from when child teats were not introduced.

**Comment by karthikbhatnagar** [comment]
A note to Shabnam:

It is not professional to say "fix it asap" as these are open source projects and developers spend hours of personal time.  Don't return what they do by demandingly them to speed up development.  If you want something sooner, always polite to send a pull request.

**Comment by AmitRai22** [comment]
Hi Karthik  
Your way seems reasonable and I have tried  but initially I am facing problem in unjar and rejar 
the files  .
I have Unjar the jar file and modified  that HTML file  and while doing rejar  it got changed and creating diffrent type of file structure and extent reports classes and packaged are not getting identified by eclipse.
could you please help me to unjar and rejar this so that I can check ahead.
Thanks for the help !

**Comment by AmitRai22** [comment]
Karthik ,
its working .
Thank a lot !!!!

I have applied the changes in HTML as you said above and it is working.
what I wanted is present in Dashboard view.
but there is wrong counting in Run Info view.

Thanks Karthik

**Comment by anshooarora** [comment]
There will be a setting in 2.10 to configure this setting:

![testviewsetting](https://cloud.githubusercontent.com/assets/4107384/9738844/03b2c55c-5613-11e5-9bad-bc2fadb36987.png)

**Comment by anshooarora** [comment]
For RunInfo:

https://github.com/anshooarora/extentreports/blob/master/java/2.x/src/com/relevantcodes/extentreports/source/STANDARD.min.html#L910

```
var totalTests = $('.test').length;
var passedTests = $('.test.pass').length;
```

**Comment by AmitRai22** [comment]
Anshoo ,That's really great! about v2.10.really awesome !
and I have implemented the changes for RunInfo-view as you said above and Its working 
Thank a lot!

Apart from this (regarding v2.05)
(i)I am facing browser compatibility problem also with report file,sometimes it opens with correct layout and sometimes it opens with distorted layout.
(ii)and sometimes report comes with correct execution-time(Total-Time-Taken)and sometimes it comes 
with 00:00:00 execution time.
(iii) Sometimes Fiters work in Detaill option in Dashboard view sometimes not.

(iv)and if we talk about individual test-execution time  it always shows 00:00:00 time with same START TIME and END TIME.

Could you please look into above issues also ??

Thanks Anshoo and Karthik.

**Comment by anshooarora** [comment]
Please try the latest 2.10-beta jar.  It has the feature to configure the types of counts to be selected among many others..

**Comment by AmitRai22** [comment]
thanks Anshu !
I have implemented as you and Karthik suggested and ofcourse this jar that is all I wanted.

Thank you.
