### ISSUE TITLE
Expand/ Collapse issue

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#69]
So when you go to say highlight something on the description, it will trigger the expand/ collapse of the test. 

What if you made the test name clickable and the rest of the test information just text (rather than the entire div clickable)

Any quick workaround off the top of your head :)?

**Comment by anshooarora** [comment]
Chris - are you referencing the auto-toggle control introduced in Java 2.05?

![expand-on-hover](http://extentreports.relevantcodes.com/2x/img/expand-on-hover.png)

**Comment by cktech529** [comment]
Nope (anyway to make that larger/ more visible?)

I am referencing the fact that on a test, if you try to highlight say a "Description" or "Test Name"  to copy for whatever reason, the toggle to Expand/ Collapse is triggered. If instead of having the HAND active for the entire test card we could enable it for just the test name) that would mean we could copy the text of say the description without the report bouncing up and down on the screen :) <-- Feeback from one of the devs here.

**Comment by cktech529** [comment]
![image](https://cloud.githubusercontent.com/assets/6800679/9670397/54200084-525a-11e5-805a-10480241fc43.png)

The above text should be Text only not clickable :)

**Comment by anshooarora** [comment]
Oh I see, surely possible.  I will make it part of the next release.  The only change for this is, before the following line:  https://github.com/anshooarora/extentreports/blob/master/java/2.x/src/com/relevantcodes/extentreports/source/STANDARD.min.html#L973

insert this and rebuild jar: 

```
if (cls == 'test-desc') return;
```

**Comment by cktech529** [comment]
Doesn't seem to work. I'll look further later.

**Comment by anshooarora** [comment]
Chris,  correction:  

```
if (cls == 'test-desc' || evt.target.parentNode.className == 'test-desc') return;
```

**Comment by cktech529** [comment]
Thanks,

Gave it a shot and it still shows:

![image](https://cloud.githubusercontent.com/assets/6800679/9690969/84569872-530d-11e5-870d-ba7e94d7fd06.png)

I'd expect it to show the text selector cursor on the description :).

Like:

![image](https://cloud.githubusercontent.com/assets/6800679/9690986/9ec5c700-530d-11e5-92a4-e4bf60d8487f.png)

**Comment by anshooarora** [comment]
Use the following css with  for this cursor type:

```
.test-desc { cursor: text; }
```

Custom CSS:  http://extentreports.relevantcodes.com/2x/docs.html#using-custom-css

**Comment by anshooarora** [comment]
Closing this issue as the version 2.10 enable copying test from all components without changing their state.
