### ISSUE TITLE
Bug while counting fatal step count in Google pie chart JS Code

### ISSUE THREAD

**Issue by toolsqa** [anshooarora/extentreports#7]
Problem: If a test has failed steps, then while report generation we count the failed steps as fatal steps also. As a result for a test with only two steps (1 fail, 1 Info) we get 3 steps (1 fail, 1 info, 1 fatal).

I debugged the issue and found that its in the JS component of the final report. We have done this there

                var failedSteps = $('td.status.fail').length;
                var fatalSteps = $('td.status.fail').length;

fatalSteps also take value from $(td.status.fail)

It seems like a bug to me. So logging as a bug. Meanwhile sending you a pull request also

**Comment by anshooarora** [comment]
This was indeed a bug, great catch!  I have merged the PR, closing this ticket as your PR fixes this issue.
