### ISSUE TITLE
As a listener only Reporter.log in the test doesn't write to the report

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#71]
import org.testng.Reporter;

ExtentReports is a listener

Shouldn't Report.log() write something to the report (somewhere?)

I remember it did with ReportNG (thoughts?)

**Comment by virenv** [comment]
ExtentReports doesn't extend the Reporter class of TestNG. Hence you will not find the Reporter logs being passed to your ExtentReports report.

**Comment by cktech529** [comment]
That makes sense, was just curious if I was doing something incorrectly. 

Thanks,

Chris

**Comment by anshooarora** [comment]
Chris - if you are using with the listener though: http://relevantcodes.com/testng-listener-using-extentreports/

You can use <code>Reporter.getOutput()</code> and print the logs to the report but you will have to do it as a test as there is no view available to add these logs.
