### ISSUE TITLE
snapshots not visible when opened through appserver

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports#72]
Extentreports: 2.05
On Test execution the extent test report and snapshots get created in appserver folder.
When i open the report file directly (without appserver) then i can see the snapshots inside the report.

But when i open through the app server, the snapshots are coming as empty.

![snapshots_not_visible_when_opened_thru_tomee](https://cloud.githubusercontent.com/assets/8359360/9721384/3376540e-55b7-11e5-8b8f-8277034a7126.jpg
![snapshots_visible_when_opened_directly](https://cloud.githubusercontent.com/assets/8359360/9721390/54a6dd10-55b7-11e5-95ac-d66484a96d3d.jpg)
)

**Comment by gsaimadhu** [comment]
![snapshots_visible_when_opened_directly](https://cloud.githubusercontent.com/assets/8359360/9721453/334d7de4-55b8-11e5-9ae8-c8e820f99aca.jpg)

**Comment by gsaimadhu** [comment]
![snapshots_not_visible_when_opened_thru_tomee](https://cloud.githubusercontent.com/assets/8359360/9721474/83d870f2-55b8-11e5-8cf6-3bb65e3a608e.jpg)

**Comment by gsaimadhu** [comment]
In IE, child links are not getting opened when parent testnames are clicked. This is again when trying to open through app server.
![in_ie_testname_childs_are_not_shown_when_parent_clicked](https://cloud.githubusercontent.com/assets/8359360/9721622/de6b77a0-55bb-11e5-89ec-94428251257e.jpg)

**Comment by gsaimadhu** [comment]
FYI, files location in appserver:
![files_location_in_appserver](https://cloud.githubusercontent.com/assets/8359360/9721632/489b31a6-55bc-11e5-9bff-f2fabca907c6.jpg)

**Comment by virenv** [comment]
While saving a snapshot we usually end up giving absolute path. Can you inspect the snapshot element using regular inspect and let us know the src attribute path?

**Comment by gsaimadhu** [comment]
The path is an absolute path. Afteri changed to relative path w.r.to the extent html report, now the snapshots are properly showing.

But the issue with IE is still present. Unable to click on parent to go to child.

**Comment by anshooarora** [comment]
If its working locally and not via the server, I don't see this as an Extent issue.  You will have to work with the server/network team to figure this out.  You can also check via browser debuggers/console (such as firebug console) what is causing this when you click the links.

**Comment by gsaimadhu** [comment]
OK thanks Anshoo.
Please close the issue.
