### ISSUE TITLE
Feature Request: Store Previous execution Results

### ISSUE THREAD

**Issue by rjmadhu** [anshooarora/extentreports#74]
A easy way to store and retrieve previous execution reports. 
Like storing the data into sql tables and retrieving the reports by build or execution id.

**Comment by anshooarora** [comment]
The merge-tool will release early next month and will allow you to combine your reports into one and also provide trends of how your tests performed over the period of time.  Would that cover this requirement as well?

**Comment by anshooarora** [comment]
This will be a good feature to add: centralizing all runs in a db.  I will add this to version 2.10b and release.  It will also make merging reports much easier and faster.  

Although I am not sure if support would be provided for builds, but execution ID and time ranges would be supported.

**Comment by anshooarora** [comment]
Ability to add DB and centralize all reports into it - added in v2.10.
