### ISSUE TITLE
[Question] Would Extent work with CI tools, e.g. - Jenkins?

### ISSUE THREAD

**Issue by ilyache** [anshooarora/extentreports#75]
Hey, 

First of all I must say that extent looks pretty sweet, you're doing an amazing work here.

I was wondering if the reporting would work with CI tools like Jenkins. Couldn't find any info about it in the F.A.Q.

**Comment by anshooarora** [comment]
Thanks for your feedback.  

To answer your query,  because Extent is agnostic,  you can use it as a normal logger and once session is complete,  publish the results using the HTML publisher plugin for Jenkins.

**Comment by ilyache** [comment]
That's great, thanks a lot for the quick response!
