### ISSUE TITLE
Can i insert a link to a Test?

### ISSUE THREAD

**Issue by udayanem** [anshooarora/extentreports#76]
Hi Anshoo,

ExtentReports is a great API and useful for many users. I recommended this API for many users.

I wanted to have one simple feature, where i want a link associated to a test. When i click on this link I wanted to play a video. How can i do this?

Can you please provide any help on this?

Thanks,
Uday

**Comment by anshooarora** [comment]
Does this answer your query:  http://extentreports.relevantcodes.com/2x/docs.html#insert-custom-html

**Comment by udayanem** [comment]
Anshoo, If i am not wrong, extent.log is at test step level. We can insert custom html like Labels, Spans exc. to test step level.

But i want to have a link at Test Case(TC) level, Basically i am planning to record the entire test execution session of a TC and will save it in a video. So, if i can have a link beside this TC which references to that video link.

**Comment by anshooarora** [comment]
You can insert HTML in the test name:

```
test = extent.startTest("TestName - <a href='http://github.com'>git</a>");
```

**Comment by udayanem** [comment]
Just simply superb Anshoo. It helped me great.
