### ISSUE TITLE
Germanic umlaut display wrong

### ISSUE THREAD

**Issue by dlitmano** [anshooarora/extentreports#77]
Hallo all,
I have since the new update of extentreport a Bug with the display of germanic umlaut. Can you help me with this issue?
![germanic_umlaut](https://cloud.githubusercontent.com/assets/5764388/9936538/ba82717e-5d5c-11e5-84c9-64b028031310.JPG)

**Comment by dlitmano** [comment]
<meta http-equiv='content-type' content='text/html; charset=ISO-8859-1' /> 
is the Solution, how can i implement it?

**Comment by dlitmano** [comment]
"<meta http-equiv='content-type' content='text/html; charset=ISO-8859-1' /> "

**Comment by anshooarora** [comment]
You can add the meta tag above the following lines:

Online report:  https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/source/STANDARD.html#L9

Offline report:  https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/source/STANDARD.offline.html#L9

**Comment by anshooarora** [comment]
This will be fixed in the next version also so you won't have to do it manually.

**Comment by dlitmano** [comment]
Thank you very much. =)

**Comment by anshooarora** [comment]
Version 2.10 is out.  Is this issue still there with the latest?

**Comment by anshooarora** [comment]
Starting version 2.40, you can specify the encoding.
