### ISSUE TITLE
Using Extent Reports with Page Object Framework in Selenium

### ISSUE THREAD

**Issue by amitjaincoer191** [anshooarora/extentreports#78]
Hi,

I want to use this report with Page Object framework. Structure of my project is 

Page Factory Class
Test Page Class 

So here my test page class call Page Class multiple time so I cannot specify start test in Page Factory Class like
ExtentTest test = extent.startTest("FunctionTest()", "Verify Login");

Any way I can capture Info/Pass/Fail logs in Page Class. I dont want to create a separate log file using log4j. I am posting code of Page Factory and Test Page class

Special thanks for creating this wonderful report.

**Comment by amitjaincoer191** [comment]
// Page Factory Class
package com.prj.FactoryPages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;

import com.relevantcodes.extentreports.ExtentTest;
import com.relevantcodes.extentreports.LogStatus;


public class OrderListPage {

	WebDriver driver ;
	String baseURL;
	ExtentTest test;

	public OrderListPage() {
		this.baseURL = getZapporourlConfigHandle().getAsString(
				ZapporoUrlConstants.Zapporo_PEHZUI_SITE);
		driver = getDriver();
		//test.log(LogStatus.INFO, "Initialised Driver and baseURL in PageClass");
	}

	@FindBy(how = How.ID, using = "username")
	public WebElement id_login_username;

	@FindBy(how = How.ID, using = "password")
	public WebElement id_login_password;

	@FindBy(how = How.NAME, using = "submit")
	public WebElement login_submit;
	
	public void OpenListpage(){
		driver.get(this.baseURL);
		//test.log(LogStatus.INFO, "Loading POList Page");
	}
	
	public String getPageTitle(){
	 return driver.getTitle();
	 //test.log(LogStatus.INFO, "Loading POList Page");
	}

	public void Login(){
		id_login_username.sendKeys(LOGIN_USER));
		id_login_password.sendKeys(LOGIN_PASSWORD);
		waitNSeconds(5);
		login_submit.click();
	}

}


// Page Test Class
package com.prj.module;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.relevantcodes.extentreports.LogStatus;

public class OrderListTestPage{

	DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");

	@Test
	public void loginTest() throws InterruptedException {

		test = extent.startTest("logintoZulluTest()", "Verify Zullu Login");
		OrderListPage poListPage = PageFactory.initElements(driver, OrderListPage.class);
		poListPage.OpenPOListpage(); // Method 1 of factory page class is called
		try {
			if (poListPage.getPageTitle().contains("Dashboard"))
				test.log(LogStatus.PASS, poListPage.getPageTitle() + " contains "
						+ "Dashboard");
			else
				test.log(LogStatus.FAIL, poListPage.getPageTitle()
						+ " doesn't contain " + "Dashboard");
		} catch (Exception e) {
			test.log(LogStatus.ERROR, e.getMessage());
		}
		
		poListPage.Login(); // Method 2 of factory page class is called
		extent.endTest(test);

	}


}

**Comment by ilyache** [comment]
Hey amitjaincoer191, 
Why not pass the test-case instance to the page object, and then include the logging in the page object itself? If I understood correctly your question seems like that should do the trick.

**Comment by amitjaincoer191** [comment]
Thanks, it worked. I passed test instance to page object method and it worked

**Comment by mashek347** [comment]
Hi Arora,

Thanks for the extent report. Could you please send me the code for background color black. I like very for black background. I am not a developer I am just a selenium tester. I would like to make background color black. I will be must appreciate if you provide me how to create black color for XSLT report.
Here is my email-masheknyus@gmail.com


Thanks
Alam

**Comment by anshooarora** [comment]
Alam
Please open a new ticket for this as the topic of your query differs.

**Comment by veeramanikandanvv** [comment]
Hi,

I am using a generic automation framework... I am not using testng. Can you please help me in setting up extent reports to my framework...

**Comment by harsha-kumar** [comment]
Hi,

I am using a generic automation framework... I am not using testng. Can you please help me in setting up extent reports to my framework...

and  please guide me setup of extent report for ubuntu os

**Comment by prajwol5667** [comment]
can anyone suggest me solution example for this issue ?
