### ISSUE TITLE
[Improvement] Search tests functionality should also search through child-tests

### ISSUE THREAD

**Issue by ilyache** [anshooarora/extentreports#79]
Hey Anshoo, 

Seems like the search tests option currently searches only parent tests. For example, if I have a parent test, and that ones has two child-tests, when I search the names of the child-tests i'm not getting any results.

If that could be supported as well that'll be great.

Thanks,
Ilya.

**Comment by anshooarora** [comment]
Ilya,  

This will be possible starting 2.10 beta-2.  It is now available for download also.  <a href='http://relevantcodes.com/extentreports-for-selenium/'>Linky</a>.

Disclaimer:  it will create a new database file in the same location as the report.  The stable version will provide the ability to override this setting.

**Comment by ilyache** [comment]
Hey Anshoo, 

Sounds great, i'll give it a go and re-open this issue if needed.

Thanks,
Ilya.
