### ISSUE TITLE
Test vs Step question (2.10 beta 2)

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#80]
Hello,

So I am playing with 2.10 Beta 2 and was wondering why:

[selenium:testng] ===============================================
[selenium:testng] Default Suite
[selenium:testng] Total tests run: 10, Failures: 1, Skips: 0
[selenium:testng] ===============================================

Would result in:

![image](https://cloud.githubusercontent.com/assets/6800679/10065050/06b7b2f2-624e-11e5-992d-e953a93f97b6.png)

Where it shows 9 tests passed, zero tests failed, but 1 step failed.

I'm using this as a Listener...

test.log(fail...,string) is treated as a step failure...

What am I missing here :)?

**Comment by anshooarora** [comment]
Chris,  this was one of the fixed bugs in beta-3.  It is now available for download.
