### ISSUE TITLE
Scrolling issue 2.10 b2

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#81]
When you have say 100 tests and need to scroll on the left side to get to the test result (details view/ test case list)

It requires that you scroll the right side (Details view/ information) to fully see the left scroll bar.

**Comment by anshooarora** [comment]
This is fixed using a pushpin so the details section will remain fixed and you will be able to scroll down to view tests.

**Comment by anshooarora** [comment]
Fixed in 2.10-stable.
