### ISSUE TITLE
2.10 b2 Description alignment issue

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#84]
![image](https://cloud.githubusercontent.com/assets/6800679/10071797/a95474e6-628a-11e5-916c-05471073514d.png)

Would it make sense to put the time data below the test description?

**Comment by anshooarora** [comment]
Chris, this issue has been fixed along with all others you logged (and many more) in beta-3.

Latest sample:  http://relevantcodes.com/Tools/ExtentReports2/ExtentJava210.html
