### ISSUE TITLE
2.10 quesiton (default to details view/ with filtering turned on)

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#85]
If there are failed tests, I'd like to default to the details page (2.10) with the filtering turned on for FAILED tests.

I'm able to get to the page:

String js = "$(document).ready(function() { $('.test-view').click(); })";
		extent.config().documentTitle("Automation Report")
				.reportName("Automation Report").insertJs(js);

**Comment by anshooarora** [comment]
Try with this:

```
$('.tests-toggle li').filter(function() {
  return ($(this).text().toLowerCase() == 'fail');
}).click();
```

Also, v2.10 beta-3 defaults to the test-view so you do not have to explicitly click to navigate there.
