### ISSUE TITLE
Large right panel details on a failed test 2.10 beta 3 - scrolling down fails

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#86]
When you scroll down on a details (right panel) it will pop up to the top.

Did this with 1 test and a huge stack trace.

**Comment by anshooarora** [comment]
Thanks for reporting this. I am able to reproduce.

**Comment by anshooarora** [comment]
This is fixed.  Sample:  http://relevantcodes.com/Tools/ExtentReports2/ExtentJava210.html

The "Uses Media" test has a lot of info and will have a scroll-bar to scroll down.

**Comment by anshooarora** [comment]
Fixed in version 2.10-stable.
