### ISSUE TITLE
2.10 beta 3 (site example) child node, zoom in on screencap

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#87]
Shows a cut off image:

![image](https://cloud.githubusercontent.com/assets/6800679/10120701/e9702d78-6496-11e5-9b8b-67bb9cea3d57.png)

**Comment by anshooarora** [comment]
Chris, this is fixed in beta-4.  Launched today.

**Comment by cktech529** [comment]
Thanks, Just grabbed it.

**Comment by anshooarora** [comment]
Fixed in 2.10/2.40.
