### ISSUE TITLE
Wrong "Time taken to finish" - missing hours  (.Net, ExtentReport 2.0.2)

### ISSUE THREAD

**Issue by mittt** [anshooarora/extentreports#89]
![image](https://cloud.githubusercontent.com/assets/8478583/10139230/93be1ea6-660a-11e5-9bc6-f17601984e01.png)

Time taken to finish is wrong. It shows 31m 58s, but should be 1hour 31m 58s. Inspecting the DOM shows the value is wrong and it's not just covered by samething.

**Comment by anshooarora** [comment]
Thanks for reporting this.  

I will soon release a fix.  Currently working on version 2.10 which has a lot of changes, and would launch .NET 2.10 also once the Java version is launched.

**Comment by mittt** [comment]
+1 for the 2.10 version in .NET. Can't wait. :+1:

**Comment by karthikbhatnagar** [comment]
+1

**Comment by karthikbhatnagar** [comment]
Anshoo
Are we going to see 2.10 for .net anytime soon?

**Comment by anshooarora** [comment]
.NET 2.10 is in alpha-2 now.

**Comment by anshooarora** [comment]
This is fixed in 2.40.
