### ISSUE TITLE
2.10 b4 screenshot zoom in

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#92]
If you have a failure, and on the right side you add a screenshot to say a child node and that child node goes off the screen (requires a bit of vertical scrolling)

When you zoom in the screen goes black and you can't see the image, if you scroll to see it, it zooms back out and your back to the details view.

If you change the screen settings in the browser (zoom out) so that the icon to zoom is ON the screen, then you can see the image.

**Comment by anshooarora** [comment]
Chris,  I had to change the way lightbox was generated..  Can you check with the following sample:

http://relevantcodes.com/Tools/ExtentReports2/ExtentJava210.html

**Comment by cktech529** [comment]
Looks good, how'd you get it to behave this way?

ExtentTest child1 = extent.startTest("RAW Details");

						child1.log(extentStatus,
								"<pre>"
										+ result.getThrowable().getMessage()
												.replaceAll(",", ";")
												.replaceAll("\\|", "\n")
										+ "</pre>");

						child1.log(extentStatus, child1.addScreenCapture(".."
								+ fileSeperator
								+ className.substring(className
										.lastIndexOf(".") + 1) + ".png"));

						test.appendChild(child1);

Resulted in:

![image](https://cloud.githubusercontent.com/assets/6800679/10165718/ac0cd608-668e-11e5-8c57-7143d490c34d.png)

**Comment by anshooarora** [comment]
I added a class to the image which caused it to be displayed like this..  It does save some space in viewing, but may not immediately make sense that its an image you need to click and enlarge. :)

**Comment by cktech529** [comment]
I see, so the sample:

![image](https://cloud.githubusercontent.com/assets/6800679/10170102/a55db5d0-66a1-11e5-9286-86d6d0ef41b1.png)

Is using a custom class to show the above thumbnail? (Just was letting you know it's inconsistent from what I'm seeing using the base 2.10 b4 build)

:-D,

**Comment by anshooarora** [comment]
Yes..  That's right.

Do you prefer the previous thumbnail style or the current one?  The one in beta-4 has a class "chip" which will cause this behavior.

**Comment by cktech529** [comment]
Personally I prefer the thumbnail so it's obvious that there's a screenshot
attached :).

**Comment by anshooarora** [comment]
The stable/next release will have thumbnail enabled by default.  I will release beta-5 tomorrow and if everything is good, will launch the stable version next week.

**Comment by cktech529** [comment]
Thanks,

Just a heads up, the Zoom in functionality is also broken (as in ) it sometimes just goes black, sometimes it'll show a portion of the image. etc.

Chris

**Comment by anshooarora** [comment]
Beta-5 is out.  This issue is finally fixed.  :)
