### ISSUE TITLE
Enhancement: reporter.log

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#94]
Maybe this isn't a good idea, but what are your thoughts?

What if Extent listened on Reporter.log from  org.testng.Reporter and perhaps had a "console log" where we could dump things?

**Comment by anshooarora** [comment]
This feature is available in 2.10 with "setTestRunnerOutput" method.

See <a href='https://github.com/anshooarora/extentreports/blob/master/java/extentreports/src/main/java/com/relevantcodes/extentreports/ExtentReports.java#L198'>here</a>.

**Comment by cktech529** [comment]
Oh great, thanks! Missed it.

**Comment by anshooarora** [comment]
Yes, before you call extent.flush(); just have to set the logs from the output:

```
for (String s : Reporter.getOutput()) {
    extent.setTestRunnerOutput(s);
}
```

**Comment by cktech529** [comment]
Thanks, yup I figured it out. I'll close this!
