### ISSUE TITLE
New feature Request - Video player should show popup

### ISSUE THREAD

**Issue by ssirekumar** [anshooarora/extentreports#95]
HI Extentreports
1). Why don't we add one more feature in here like, when we added any video in the reports that video should be played in new popup window, This should exact like below url
http://demos.jquerymobile.com/1.2.1/docs/pages/popup/popup-iframes.html

2). Just like same thing above if we add any log file attached to reports this file contents should be open in dialog pop up.
https://jqueryui.com/dialog/#default

**Comment by anshooarora** [comment]
Thanks for your feedback.  I will try to include this feature in 2.10-stable.

**Comment by ssirekumar** [comment]
Okay, i want to add some thing like this way of our existing one, For  this we need a overload method from the existing method. the  new one would be when reporter added video to report the video would be thumbnail(This may be hyperlinked image) once click on that thumbnail its should be play as pop up.

Same thing for attached log report also, As of now when we add any .txt file to report as hyperlink then click on this its open into new tab of the browser. To avoid this to add any jquery pop up to display all the content in the popup dialog box.

Thanks for considering this feature.

**Comment by anshooarora** [comment]
Do you know if there is a way to implement this without an external library?  I haven't been able to use regular js/jQuery to show the video inside the new modal..

**Comment by ssirekumar** [comment]
No, Still i am searching for with out this external library to add the video in pop-up mode. But If we add this js/JQuery would give us good look to report.

**Comment by anshooarora** [comment]
I am going to descope this as static html files have several limitations playing video content.  

It can be put in scope for ExtentX as the videos will be hosted on the server.  Please feel free to open this ticket in the ExtentX repo.
