### ISSUE TITLE
Didn't have your email, ETA on 2.10 final build? 

### ISSUE THREAD

**Issue by cktech529** [anshooarora/extentreports#98]
Sorry,

What's the correct way to get these sort of messages to you?

Anyways, any clue when the final build will drop?

Just curious as I plan to migrate our production reports over to it.

Great work!

:-D

**Comment by anshooarora** [comment]
You can email me at anshooarora@gmail.com.

The build should be available very soon, if not by tomorrow then on Monday for sure.

**Comment by anshooarora** [comment]
Final build is now here, both on relevantcodes.com and maven.

**Comment by anshooarora** [comment]
ExtentMerge is also available now:  http://relevantcodes.com/Tools/ExtentReports2/ExtentMerge.html
