### ISSUE TITLE
New Feature Request :: Add a Jenkins Plugin for ExtentReport

### ISSUE THREAD

**Issue by sunnysachdeva** [anshooarora/extentreports#99]
It would be really great if corresponding Jenkins plugin is created for this report.

**Comment by anshooarora** [comment]
I currently do not have this planned but you can use the Jenkins HTML Publisher plugin to post your reports there..

**Comment by VaibhavRepo** [comment]
Used HTML Publisher plugin it works well, but reports openend don't have UI.

**Comment by anshooarora** [comment]
@VaibhavRepo  -  Please do not cross post (#308).
